### ISSUE TITLE
[9.5.5] Collector email

### ISSUE THREAD

**Issue by Wacxiuz** [glpi-project/glpi#9286] opened 2021-07-15 06:51 UTC
**Describe the bug**

I configured the mail collector with a GMAIL mail address. Most of the mails are well retrieved and converted into tickets, however some mails do not pass and are in error.
This problem also arises on an Office 365 mail.
The errors are identical between the 2 mailboxes.

**Page(s) URL**

https://[glpi-host]/front/mailcollector.form.php?

**To reproduce**

1. Send email to mailbox monitored by GLPI
2. Navigate to https: // [glpi-host] /front/mailcollector.form.php?
3. Click "retrieve emails now"

**Expected behavior**

The ticket should be generated based on the email without error.

**Logs**

tail /var/www/glpi/files/_log/mailgate.log
Message invalide : Invalid header value detected<br/>2021-07-15 08:25:29 [1052@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 08:25:29 [1052@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 08:27:52 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 08:27:53 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 08:28:05 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 08:28:05 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 08:29:10 [1052@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 08:29:11 [1052@SRVGLPI01]

**Screenshots**

![image](https://user-images.githubusercontent.com/83710370/125742268-b8d59dfe-9f2a-48fc-9a14-12c454dc535f.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

<html><body>

[code]   GLPI 9.5.5 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 PHP 8.0.8 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, soap, sockets, sodium, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at srvglpi01.adetel.com Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0 Server Software: MySQL Community Server (GPL) 	Server Version: 5.6.19 	Server SQL Mode:  	Parameters: Host info: via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.6.19) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /var/www/glpi/files/_cache has been validated. Write access to /var/www/glpi/config has been validated. Write access to /var/www/glpi/files/_cron has been validated. Write access to /var/www/glpi/files has been validated. Write access to /var/www/glpi/files/_dumps has been validated. Write access to /var/www/glpi/files/_graphs has been validated. Write access to /var/www/glpi/files/_lock has been validated. Write access to /var/www/glpi/files/_pictures has been validated. Write access to /var/www/glpi/files/_plugins has been validated. Write access to /var/www/glpi/files/_rss has been validated. Write access to /var/www/glpi/files/_sessions has been validated. Write access to /var/www/glpi/files/_tmp has been validated. Write access to /var/www/glpi/files/_uploads has been validated. Write access to /var/www/glpi/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/glpi GLPI_CONFIG_DIR: /var/www/glpi/config GLPI_VAR_DIR: /var/www/glpi/files GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/glpi/files GLPI_CACHE_DIR: /var/www/glpi/files/_cache GLPI_CRON_DIR: /var/www/glpi/files/_cron GLPI_DUMP_DIR: /var/www/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales GLPI_LOCK_DIR: /var/www/glpi/files/_lock GLPI_LOG_DIR: /var/www/glpi/files/_log GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins GLPI_RSS_DIR: /var/www/glpi/files/_rss GLPI_SESSION_DIR: /var/www/glpi/files/_sessions GLPI_TMP_DIR: /var/www/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/glpi/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/var/www/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.6 in (/usr/share/php/CAS/source)

Not active

screenshot           Name: Capture d'écran                Version: 1.1.3      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.12.4     State: Enabled 	behaviors            Name: Comportements                  Version: 2.4.1      State: Installed / not activated 	datainjection        Name: Data Injection                 Version: 2.9.0      State: Enabled 	escalade             Name: Escalades                      Version: 2.6.1      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.11.2     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled 	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.4.0      State: Not installed 	metabase             Name: metabase                       Version: 1.2.1      State: Not installed 	moreticket           Name: More ticket                    Version: 1.6.1      State: Not installed 	mreporting           Name: Plus de rapports               Version: 1.7.3      State: Installed / not activated 	reports              Name: Rapports                       Version: 1.14.0     State: Not installed
[/code]

</body>
</html>

**Comment by trasher** [comment] 2021-07-15 07:09
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22))

**Comment by Wacxiuz** [comment] 2021-07-15 07:32
> 
> 
> Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22))

Hello,
The problem is still there.
Thanks

**Comment by cedric-anne** [comment] 2021-07-15 07:47
Hi,

Could you please attach related email into eml format ?

Regards

**Comment by Wacxiuz** [comment] 2021-07-15 08:20
> 
> 
> Hi,
> 
> Could you please attach related email into eml format ?
> 
> Regards

https://fs.centumadetel.com/dl0481731257

**Comment by cedric-anne** [comment] 2021-07-15 09:32
I am able to collect both emails on my local version of GLPI. I guess the malformed header has been fixed during export of your email.

You can try to apply #9288 to be able to get more information about the error.

To be honest, if the source email is malformed, we cannot really fix your issue on GLPI side. You will have to identify the malformed header and fix this issue on the software responsible of this email sending.

**Comment by Wacxiuz** [comment] 2021-07-15 09:41
> 
> 
> I am able to collect both emails on my local version of GLPI. I guess the malformed header has been fixed during export of your email.
> 
> You can try to apply #9288 to be able to get more information about the error.
> 
> To be honest, if the source email is malformed, we cannot really fix your issue on GLPI side. You will have to identify the malformed header and fix this issue on the software responsible of this email sending.

Thanks for your feedback.
On my side, on the php-errors file, here are my errors:

  inc/commondbtm.class.php:4056                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1143                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1353                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1207                      Plugin::doHook()
  inc/mailcollector.class.php:820                    CommonDBTM->add()
  inc/mailcollector.class.php:1742                   MailCollector->collect()
  inc/crontask.class.php:943                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()

**Comment by cedric-anne** [comment] 2021-07-15 09:53
Please provide the complete trace.

**Comment by Wacxiuz** [comment] 2021-07-15 11:11
root@SRVGLPI01:/var/www/glpi# tail /var/www/glpi/files/_log/php-errors.log
  inc/commondbtm.class.php:4056                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1143                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1353                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1207                      Plugin::doHook()
  inc/mailcollector.class.php:820                    CommonDBTM->add()
  inc/mailcollector.class.php:1742                   MailCollector->collect()
  inc/crontask.class.php:943                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()

root@SRVGLPI01:/var/www/glpi# tail /var/www/glpi/files/_log/mailgate.log
Message invalide : Invalid header value detected<br/>2021-07-15 13:07:08 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:09:03 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:09:03 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:09:09 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:09:09 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:11:03 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:11:03 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:11:08 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>2021-07-15 13:11:09 [@SRVGLPI01]
Message invalide : Invalid header value detected<br/>root@SRVGLPI01:/var/www/glpi#

**Comment by cedric-anne** [comment] 2021-07-15 11:12
There are missing line before `inc/commondbtm.class.php:4056 CommonDBTM->getSearchOptionByField()` .

**Comment by Wacxiuz** [comment] 2021-07-15 11:19
Oh yes sorry,
[2021-07-15 08:53:08] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01"} 
[2021-07-15 08:53:08] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01","mem_usage":"0.002\", 7.13Mio)"} 
[2021-07-15 08:53:12] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01"} 
[2021-07-15 08:53:12] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01","mem_usage":"0.036\", 7.53Mio)"} 
[2021-07-15 08:53:29] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01"} 
[2021-07-15 08:53:29] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01","mem_usage":"0.003\", 9.00Mio)"} 
[2021-07-15 08:55:12] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01"} 
[2021-07-15 08:55:12] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01","mem_usage":"0.002\", 7.42Mio)"} 
[2021-07-15 08:56:26] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01"} 
[2021-07-15 08:56:26] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01","mem_usage":"0.003\", 8.55Mio)"} 
[2021-07-15 08:57:09] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01"} 
[2021-07-15 08:57:38] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01"} 
[2021-07-15 08:57:38] glpiphplog.WARNING: CommonDBTM::getFromDBByCrit() in /var/www/glpi/inc/commondbtm.class.php line 351
getFromDBByCrit expects to get one result, 2 found!  {"user":"1311@SRVGLPI01","mem_usage":"0.001\", 7.53Mio)"} 
[2021-07-15 08:58:08] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "glpiactive_entity" in /var/www/glpi/marketplace/formcreator/inc/issue.class.php at line 400
  Backtrace :
  inc/commondbtm.class.php:3677                      PluginFormcreatorIssue->rawSearchOptions()
  inc/commondbtm.class.php:3984                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4056                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1143                      CommonDBTM->filterValues()
  marketplace/formcreator/hook.php:350               CommonDBTM->add()
  inc/plugin.class.php:1353                          plugin_formcreator_hook_add_ticket()
  inc/commondbtm.class.php:1207                      Plugin::doHook()
  inc/mailcollector.class.php:820                    CommonDBTM->add()
  inc/mailcollector.class.php:1742                   MailCollector->collect()
  inc/crontask.class.php:943                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()

**Comment by cedric-anne** [comment] 2021-07-15 11:23
Did you applied #9288 ? There is nothing in your `php-errors.log` related to the mail collector error.

**Comment by Wacxiuz** [comment] 2021-07-15 11:37
[2021-07-15 13:36:46] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Header\Exception\InvalidArgumentException: Invalid header value detected in /var/www/glpi/vendor/laminas/laminas-mail/src/Header/GenericHeader.php at line 64
  Backtrace :
  vendor/laminas/laminas-mail/src/Headers.php:544    Laminas\Mail\Header\GenericHeader::splitHeaderLine()
  vendor/laminas/laminas-mail/src/Headers.php:284    Laminas\Mail\Headers->loadHeader()
  vendor/laminas/laminas-mail/src/Headers.php:105    Laminas\Mail\Headers->addHeaderLine()
  ...r/laminas/laminas-mail/src/Storage/Part.php:113 Laminas\Mail\Headers::fromString()
  ...laminas/laminas-mail/src/Storage/Message.php:53 Laminas\Mail\Storage\Part->__construct()
  ...or/laminas/laminas-mail/src/Storage/Pop3.php:64 Laminas\Mail\Storage\Message->__construct()
  ...aminas-mail/src/Storage/AbstractStorage.php:268 Laminas\Mail\Storage\Pop3->getMessage()
  inc/mailcollector.class.php:721                    Laminas\Mail\Storage\AbstractStorage->current()
  front/mailcollector.form.php:88                    MailCollector->collect()

**Comment by wytchmaster** [comment] 2021-09-14 09:05
I have exactly the same problem. It occures with mail from GMail and Protonmail. When sending Mail from other accounts, it generally works. 
The problem occures always, when sending from the web interface and when sending HTML or HTML/plaintext messages from Thunderbird. It does not occure if sending only plaintext via thunderbird (from the GMail account). I have no problems when sending HTML or HTML/plaintext mails via my own server (using the same mail programm).
Unfortunately some customers of mine use GMail as mail provider ....

**Comment by cedric-anne** [comment] 2021-09-14 09:46
@wytchmaster 

Please attach an export of an email that cause the issue, into eml format.

Regards

**Comment by wytchmaster** [comment] 2021-09-21 17:29
I have isolated the problem. It's caused by a mail header inserted by proxmox mail gateway. If you disabled inserting of the spam score header, GLPI is importing the mail without problem. Maybe the german umlaut is the problem:
`X-SPAM-LEVEL: Spam detection results:  0
	AWL                    -0.150 Adjusted score from AWL reputation of From: address
	DKIM_SIGNED               0.1 Message has a DKIM or DK signature, not necessarily valid
	DKIM_VALID               -0.1 Message has at least one valid DKIM or DK signature
	DKIM_VALID_AU            -0.1 Message has a valid DKIM or DK signature from author's domain
	DKIM_VALID_EF            -0.1 Message has a valid DKIM or DK signature from envelope-from domain
	FREEMAIL_FROM           0.001 Sender email is commonly abused enduser mail provider
	HTML_MESSAGE            0.001 Nachricht enthält HTML
	KAM_NUMSUBJECT            0.5 Subject ends in numbers excluding current years
	RCVD_IN_DNSWL_NONE     -0.0001 Sender listed at https://www.dnswl.org/, no trust
	RCVD_IN_MSPIKE_H2      -0.001 Average reputation (+2)
	SPF_HELO_NONE           0.001 SPF: HELO does not publish an SPF Record
	SPF_PASS               -0.001 SPF: Senderechner entspricht SPF-Datensatz`

I will check that by end of the week.

**Comment by cedric-anne** [comment] 2021-09-23 13:56
As far as I understand, e-mail headers should only contains US-ASCII chars (see https://datatracker.ietf.org/doc/html/rfc2822#section-2.2).

We are using an external lib to fetch emails, and I doubt we would be able to change their policy to accept "invalid" chars (see https://github.com/laminas/laminas-mail/blob/2.16.x/src/Header/HeaderValue.php#L64 ).
You may try to open an issue or a PR on their repository. If a fix is accepted, we would be able to include it in a future version of GLPI.

You may also open an issue on Proxmox forum.

I am closing this issue as we cannot do anything for this on GLPI side.

**Closed by cedric-anne** 2021-09-23 13:56 UTC
Labels: Need feedback

**Comment by troloff** [comment] 2021-11-12 09:38
We (glpi 9.5.6) still are having issues with invalid email headers.

Mostly, they seem to come from empty lines in spam headers (X-Spam_report), which trigger errors in vendor/laminas/laminas-mail/src/Headers.php lines 92 and 98:
`*** Uncaught Exception Laminas\Mail\Exception\RuntimeException: Malformed header detected in /var/www/inventory.net.adk.de/vendor/laminas/laminas-mail/src/Headers.php at line 92`
`*** Uncaught Exception Laminas\Mail\Exception\RuntimeException: Malformed header detected in /var/www/inventory.net.adk.de/vendor/laminas/laminas-mail/src/Headers.php at line 98`

I commented out these lines to see what happens, and ran into the next issue:
`*** Uncaught Exception Laminas\Mail\Header\Exception\InvalidArgumentException: Invalid header value detected in /var/www/inventory.net.adk.de/vendor/laminas/laminas-mail/src/Header/GenericHeader.php at line 64`

As a quick and dirty fix I replaced GenericHeader.php/line 64 with
```
//throw new Exception\InvalidArgumentException('Invalid header value detected');
$parts[1] = 'Invalid header';
```
and now the mails got picked up.

As @cedric-anne pointed out, this may rather be an issue with the receiving server adding these spam headers. But maybe there is a way to sanitize/blacklist/drop these (quite useless in the scope of glpi) headers before fetching the mails.
