### ISSUE TITLE
GLPI 9.3.3 (Since 9.3.2) List Tickets Problem

### ISSUE THREAD

**Issue by guioday83** [glpi-project/glpi#5244] opened 2019-01-12 05:27 UTC
**Describe the bug**

Ticket page does not finish to Load throwing "templateResult is not defined" error. This appears to be related with some Limitation.

---- Error ----
Uncaught ReferenceError: templateResult is not defined
    at HTMLDocument.<anonymous> (ticket.php?is_deleted=0&as_map=0&criteria[0][field]=12&criteria[0][searchtype]=equals&criteria[0][value]=all&criteria[1][link]=AND&criteria[1][field]=15&criteria[1][searchtype]=contains&criteria[1][value]=&search=Search&itemtype=Ticket&start=0&_glpi_csrf_token=0ff3ae8e0af6d0163bc81eee58409f27:232)
    at c (jquery-1.10.2.min.js?v=9.3.3:4)
    at Object.fireWith [as resolveWith] (jquery-1.10.2.min.js?v=9.3.3:4)
    at Function.ready (jquery-1.10.2.min.js?v=9.3.3:4)
    at HTMLDocument.q (jquery-1.10.2.min.js?v=9.3.3:4)
----------------------

**Page(s) URL**

**Search Error:** glpi/front/ticket.php?is_deleted=0&as_map=0&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=all&criteria%5B1%5D%5Blink%5D=AND&criteria%5B1%5D%5Bfield%5D=15&criteria%5B1%5D%5Bsearchtype%5D=contains&criteria%5B1%5D%5Bvalue%5D=2019-01&search=Search&itemtype=Ticket&start=0&_glpi_csrf_token=9da04c805ea933f061c27b6c75419bab
- MySQL Query: select count(*) from glpi_tickets where date_creation like '2019-01%';
- - Result=958

**Search Success**: glpi/front/ticket.php?is_deleted=0&as_map=0&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=all&criteria%5B1%5D%5Blink%5D=AND&criteria%5B1%5D%5Bfield%5D=15&criteria%5B1%5D%5Bsearchtype%5D=contains&criteria%5B1%5D%5Bvalue%5D=2019-01-11&search=Search&itemtype=Ticket&start=0&_glpi_csrf_token=cba90931fc521e14582cb457fd87c551
- MySQL Query: select count(*) from glpi_tickets where date_creation like '2019-01-11%';
- - Result=113

**To reproduce**

**Expected behavior**

Load Tickets page with pagged tickets list no matter what ticket number.

**Logs**

```
No relavant erros. 

```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

Information about system installation & configuration
--
[code]   GLPI 9.3.3 (/glpi => /usr/share/glpi) Installation mode: TARBALL

Operating system: Linux glpi 4.18.16-splDtt-3 #1 SMP Sat Nov 3 06:48:55 -03 2018 x86_64 PHP 7.3.1RC1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, http, iconv, imap, json, ldap, libxml, mbstring, mysql, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, propro, raphf, request, session, sockets, sqlite3, standard, tokenizer, 	wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.3.1RC1 () 	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.1.37-MariaDB 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (10.1.37) - Perfect! /usr/share/glpi/files/_log : OK /usr/share/glpi/config : OK /usr/share/glpi/files : OK /usr/share/glpi/files/_dumps : OK /usr/share/glpi/files/_sessions : OK /usr/share/glpi/files/_cron : OK /usr/share/glpi/files/_graphs : OK /usr/share/glpi/files/_lock : OK /usr/share/glpi/files/_plugins : OK /usr/share/glpi/files/_tmp : OK /usr/share/glpi/files/_cache : OK /usr/share/glpi/files/_rss : OK /usr/share/glpi/files/_uploads : OK /usr/share/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Disabled

htmLawed version 1.2.4.1 in (/usr/share/php/htmLawed) SimplePie version 1.5.2 in (/usr/share/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.25 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) phpCas version 1.3.6 in (/usr/share/pear)

none

Not active

Way of sending emails: SMTP (anonymous@172.16.8.75)


dashboard            Name: Dashboard                      Version: 0.9.4      State: Enabled 	escalade             Name: Escalation                     Version: 2.3.3      State: Enabled 	datainjection        Name: File injection                 Version: 2.6.4      State: Enabled 	mod                  Name: GLPI Modifications             Version: 1.2.2      State: Enabled 	mreporting           Name: More Reporting                 Version: 1.5.3      State: Enabled 	moreticket           Name: More ticket                    Version: 1.4.3      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.6.3      State: Enabled 	surveyticket         Name: Pesquisa                       Version: 9.3+1.0    State: Enabled 	webnotifications     Name: Web Notifications              Version: 1.1.3      State: Enabled
[/code]




```

**Additional context**

**Comment by guioday83** [comment] 2019-01-12 05:32
![ok](https://user-images.githubusercontent.com/22668562/51069655-a08bfb80-161a-11e9-8fa5-cd54453ad775.PNG)
![error](https://user-images.githubusercontent.com/22668562/51069656-a08bfb80-161a-11e9-862e-5cbbf76889f8.PNG)

**Comment by guioday83** [comment] 2019-01-12 05:33
![error](https://user-images.githubusercontent.com/22668562/51069665-c5806e80-161a-11e9-9eb3-aeb233bdac79.PNG)

**Comment by trasher** [comment] 2019-01-12 10:15
Are you sure you do not have a browser cache issue? Alos, please check for your issue on demo; I cannot reproduce.

**Comment by guioday83** [comment] 2019-01-12 15:52
Hello, 
No browser cache issue. Samething happens on many devices even after a full cache flush.

I'll test on a DEMO database, but apparently no issues.

**Comment by guioday83** [comment] 2019-01-12 17:08
Can you send me a DEMO database with something link 10K tickets, so I can do some tests?

**Comment by cedric-anne** [comment] 2019-01-14 10:10
Hi,

Can you try with plugins deactivated ? Maybe one of your plugins is responsible of this error.

Regards

**Comment by guioday83** [comment] 2019-01-17 00:52
Thank you @cedric-anne, but I did every possible test, with modules disabled, removed, etc. It appears to be something related to high ticket volumes being loaded on ticket.php page. When loading ~100 tickets on a query, everything loads fine. But when trying like 500 tickets (a week) it crashes.

**Comment by cedric-anne** [comment] 2019-03-11 15:30
Hi,

The problem you describe is due to performances problems. Even if there is certainly some improvements to do, they requires a lot of technical rework and are done step by step.

Looks like the page is not fully processed due to a timeout or a memory limit error.

If you want to be able to display hundreds of tickets on a single page, you may have to change your apache/PHP/MySQL settings to be sure that memory limits and timeouts are higher than required resources used by this request.
If you need support for this, you can ask on [forum](https://forum.glpi-project.org/) or ask for [professionnal support](https://glpi-project.org/subscriptions/).

I close this issue, as this is not a bug.

Regards

**Comment by guioday83** [comment] 2019-03-15 01:24
Unfortunately I can't agree with you. Trust me, I did so many attempts about performance tuning as:
- Higher memory limits;
- Higher mysql timeouts;
- Higher http timeouts;
- Higher php timeouts;
- Higher APUc Cache memory;
- Activated Apache Cache Module;
- Activated MySQL InnoDB Cache;
- Upgraded to PHP 7.2;

And nothing works. 

We had exactly same business behavior back when using GLPI 9.2x. In that time, no issue at all to load hundreds tickets page (even paged).

We did following trial:
- Restored GLPi server Backup.
- Played around with Ticket List page -> No issue at all.
- Upgraded to 9.3.3, which includes DB conversion from Myisam to Innodb.
- Played around with Ticket List page -> Started to face issues.

DB Size = Around 8K tickets;

**Comment by cedric-anne** [comment] 2019-03-15 08:40
Hi,

> We had exactly same business behavior back when using GLPI 9.2x. In that time, no issue at all to load hundreds tickets page (even paged).

This important information was not clearly mentioned in the description of your issue. If the same search was perfectly working on GLPI 9.2.x, there may be something on which a change must be reviewed.
Not sure to find the solution, but I may try to find the explaination.

To be able to perform a contextual analysis, could you provide list of fields you are displaying ?

Regards

**Comment by guioday83** [comment] 2019-03-20 19:00
Thank you so much for reopening... You can ccheck example bellow.


Search Error: glpi/front/ticket.php?is_deleted=0&as_map=0&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=all&criteria%5B1%5D%5Blink%5D=AND&criteria%5B1%5D%5Bfield%5D=15&criteria%5B1%5D%5Bsearchtype%5D=contains&criteria%5B1%5D%5Bvalue%5D=2019-01&search=Search&itemtype=Ticket&start=0&_glpi_csrf_token=9da04c805ea933f061c27b6c75419bab

MySQL Query: select count(*) from glpi_tickets where date_creation like '2019-01%';
Result=958
Search Success: glpi/front/ticket.php?is_deleted=0&as_map=0&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=all&criteria%5B1%5D%5Blink%5D=AND&criteria%5B1%5D%5Bfield%5D=15&criteria%5B1%5D%5Bsearchtype%5D=contains&criteria%5B1%5D%5Bvalue%5D=2019-01-11&search=Search&itemtype=Ticket&start=0&_glpi_csrf_token=cba90931fc521e14582cb457fd87c551

MySQL Query: select count(*) from glpi_tickets where date_creation like '2019-01-11%';
Result=113

Fields selected are in URL above.

**Comment by cedric-anne** [comment] 2019-03-20 21:41
Hi,

I need to know which fields are displayed (this information is related to your search preferences which are not in URL). For each displayed field, additionnal SQL elements compose the global query, so it is important to know the exact context of your problem.

Regards

**Comment by guioday83** [comment] 2019-03-22 01:15
Hey Cedric, please check....

![image](https://user-images.githubusercontent.com/22668562/54794534-c7703a80-4c26-11e9-9158-73854f88316b.png)

**Comment by cedric-anne** [comment] 2019-03-25 16:11
Hi,

Sorry, I try to reproduce locally, but I have only a small DB and it do not find any slow query.
Could you open the debug panel and try to find which makes this so slow ?

Without plugins, it does not make so many queries and they are quiet simple.

Regards

**Comment by trasher** [comment] 2019-04-16 07:00
No feedback from a while, closing.

**Closed by trasher** 2019-04-16 07:00 UTC
Labels: Need feedback, performance

**Comment by Kapsonfire** [comment] 2019-08-13 13:25
I have a similiar problem. i updated from 9.3.1 to 9.4.3
i get on every page displayResult is not defined error and the execution stops
if i activate the debug mode its working

**Comment by Marisa-Chan** [comment] 2020-04-29 03:42
Same on GLPI 9.4.5 after updating from 9.2.2
All works in debug and get it in normal mode and no drop-down elements:

```
VM441:89 Uncaught ReferenceError: templateResult is not defined
    at HTMLDocument.eval (eval at <anonymous> (jquery.js:349), <anonymous>:89:29)
    at i (jquery.js:3232)
    at Object.add [as done] (jquery.js:3291)
    at n.fn.init.n.fn.ready (jquery.js:3542)
    at new n.fn.init (jquery.js:2967)
    at n (jquery.js:75)
    at eval (eval at <anonymous> (jquery.js:349), <anonymous>:4:1)
    at eval (<anonymous>)
    at jquery.js:349
    at Function.globalEval (jquery.js:349)
```

**Comment by ZwvwZ** [comment] 2021-08-31 09:37
>>Update:
>>Solved by move all old files and place only from fresh version
Что именно сделали? Опишите подробнее.
