### ISSUE TITLE
Display progression in ticket list

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1529] opened 2017-01-05 15:26 UTC
http://forum.glpi-project.org/viewtopic.php?id=156413

**Comment by trasher** [comment] 2017-01-16 13:30
It seems that that progression bar is not displyed when `takeintoaccount_delay_stat` has a value greater than 0; I wonder if the claculation for this field is not in cause here.

**Comment by trasher** [comment] 2017-01-16 13:44
I wonder if the issue is not at https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/ticket.class.php#L1205; I'm not sure in which conditions `takeintoaccount_delay_stat` should be added here (in my tests, `Session::haveRight("task", CommonITILTask::ADDALLITEM) === 4096` so we enter in the condition without any other check).

**Comment by orthagh** [comment] 2017-01-18 15:52
Seems normal for me.
Progress bars need empty xx_delay_stat to be displayed.

for solve delay + progress, it make senses when ticket is not closed (solve_delay_stat = 0).
for takeintoaccount delay + progress, it make sense only when ticket has not been seen by a technician (takeintoaccount_delay_stat = 0).

The misunderstanding come from the fact that takeintoaccount_delay_stat is different than status = new.
We fill this field when an update is done by a technician on the ticket not only when an assignment is done (see https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/ticket.class.php#L1205 like mentionned by trasher).
If a technician changes the category or impact for example, we could consider the ticket read, then taked into account. but still new (not assigned).

I think we can close this issue (and remove milestone), on my side, i don't consider this behavior as a bug.

**Closed** 2017-01-19 13:46 UTC
Labels: bug, invalid
