### ISSUE TITLE
Problem with paste image to tekst in knowladge base

### ISSUE THREAD

**Issue by adamcios** [glpi-project/glpi#12482] opened 2022-08-24 14:53 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When I write an article into the knowledge base and paste pictures into the text, only the picture icon appears as an object, but the picture is not displayed. It is listed in the documents tab as an attached file.There are no entries in the logs for this event, it looks as if the attached image file is not displayed at the place of pasting
![Zaznaczenie_1629](https://user-images.githubusercontent.com/3205775/186450215-89d37a40-e8e8-466a-a52d-dec77d64658b.png)

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.2 ( => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT OPENIT-05 10.0 build 19044 (Windows 10) AMD64
PHP 8.1.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 Server at pomoc.o-it.pl
	Port 443
)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\xampp\htdocs\glpi
GLPI_CONFIG_DIR: C:\xampp\htdocs\glpi/config
GLPI_VAR_DIR: C:\xampp\htdocs\glpi/files
GLPI_MARKETPLACE_DIR: C:\xampp\htdocs\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\xampp\htdocs\glpi/files
GLPI_CACHE_DIR: C:\xampp\htdocs\glpi/files/_cache
GLPI_CRON_DIR: C:\xampp\htdocs\glpi/files/_cron
GLPI_DUMP_DIR: C:\xampp\htdocs\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\xampp\htdocs\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\xampp\htdocs\glpi/files/_locales
GLPI_LOCK_DIR: C:\xampp\htdocs\glpi/files/_lock
GLPI_LOG_DIR: C:\xampp\htdocs\glpi/files/_log
GLPI_PICTURE_DIR: C:\xampp\htdocs\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\xampp\htdocs\glpi/files/_plugins
GLPI_RSS_DIR: C:\xampp\htdocs\glpi/files/_rss
GLPI_SESSION_DIR: C:\xampp\htdocs\glpi/files/_sessions
GLPI_TMP_DIR: C:\xampp\htdocs\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\xampp\htdocs\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\xampp\htdocs\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\xampp\htdocs\glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\xampp\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\xampp\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\glpi\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (pomoc@o-it.pl@o-it.pl)

</details><details><summary>Plugins list</summary><pre> 
	barcode              Name: Barcode                        Version: 2.7.0      State: Not installed                           
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.11.2     State: Installed / not activated               
		Install Method: Marketplace
	domains              Name: Domeny                         Version: 2.2.1      State: Not installed                           
		Install Method: Manual
	pdf                  Name: Drukuj do PDF                  Version: 2.0.0      State: Not installed                           
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.1+1.0 State: Installed / not activated               
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.3      State: Error / to clean                        
		Install Method: Manual
	manufacturersimports Name: Importowani dostawcy           Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	karastock            Name: Karastock                      Version: 1.3        State: Not installed                           
		Install Method: Manual
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Not installed                           
		Install Method: Manual
	dashboard            Name: Pulpit                         Version: 1.0.2      State: Not installed                           
		Install Method: Manual
	scimplementation     Name: ScreenConnect Implementation   Version: 1.5.0      State: Installed / not activated               
		Install Method: Manual
	environment          Name: Środowisko                     Version: 2.4.1      State: Not installed                           
		Install Method: Manual
	order                Name: Zarządzanie zamówieniami       Version: 2.9.0      State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment] 2022-09-01 10:48
Hi,

Maybe a duplicate of #12276.
Can you check if #12281 solves this issue ?

Regards

**Comment by eSkiSo** [comment] 2022-09-01 11:02
A temporary workaround is If you paste the image, then right click it -> **Image...** -> **Save** it will save and display correctly.

**Comment by PandaRoux8** [comment] 2022-09-16 06:31
I looked into it and I think I understand what's going on.

This affect all the Rich text input elements.

## Steps To reproduce

- Copy an image to clipboard that isn't stored on your filesystem, nor from the web (for example an inline text image from an email you recieved on outlook)

If you check the source of the image you will see something like this
`file:///C:/Users/***/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png`

And in your browser console
`Not allowed to load local resource: file:///C:/Users/***/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png`

Basically when you upload an image to rich text GLPI seems to understand he has to send it to the server and link it in the rich text. But when an image is stored in the clipboard it fails to do so. 

Here's the case I noted with results (From what I understand) : 
- [x] Copy from a text on the Web (Link to image is from the web)
- [x] Copy image from filesystem (Link to image is your regular folder)
- [x] Copy text with an image stored in your filesystem (This works since the clipboard holds a reference to the image)
- [ ] Copy an image external to your file system (This doesn't work because the image is stored as is in your clipboard)


I hope it helps, feel free to message me for further investigation

**Comment by cedric-anne** [comment] 2022-09-16 06:40
`Not allowed to load local resource` is related to your browser security configuration, and GLPI cannot change it. I am not even sure it is possible to catch such event to display a warning to user.

**Comment by PandaRoux8** [comment] 2022-09-16 06:43
I know this is related to your chrome settings, but for example when you paste an image from your filesystem inside a rich text.

GLPI takes care of sending it to the server. I would guess by creating an `input` of `type='file'` filling it and sending the form or something alongs those lines.

If you open the network tab while copy pasting an image in the Rich text you'll see that it makes some call to the server.

**Comment by cedric-anne** [comment] 2022-10-27 09:05
I close the issue as it is a duplicate of #12276 + #12849.

**Closed by cedric-anne** 2022-10-27 09:05 UTC
Labels: Need feedback
