### ISSUE TITLE
[GLPI 10] - predefined fields for Title, Description ignored when creating a ticket

### ISSUE THREAD

**Issue by hubMich** [glpi-project/glpi#11579] opened 2022-05-13 10:51 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Having predefined fields in a ticket template for title, description none are applied on the ticket creation form. 
In GLPI 9.5, those fields are populated from the predefined template fields.

### Page URL

front/ticket.form.php

### Steps To reproduce

1. Update the default ticket template; add predefined fields for title and description.
2. create a ticket and observe the form before submitting.

**Comment by cconard96** [comment] 2022-05-13 10:52
Duplicate of #11410.
Already fixed for 10.0.1.

**Comment by cconard96** [comment] 2022-05-13 10:54
A related issue with predefined description always showing after the first fix for missing predefined fields was fixed in #11539.

**Closed** 2022-05-13 10:54 UTC
Labels: duplicate
