### ISSUE TITLE
Not loading CSS after upgrade to 9.4.2 (high css.php loading time)

### ISSUE THREAD

**Issue by llagerlof** [glpi-project/glpi#5919] opened 2019-05-16 15:52 UTC
**Describe the bug**

After update from a fully functional 0.84.3 to 9.4.2 (all dependencies resolved), open any page is extremely slow due to css.php (I think).

**Page(s) URL**

http://myserver/glpi/index.php

**To reproduce**

1. Update from a functional 0.84.3 to 9.4.2
2. Open in the browser http://yourserver/glpi/index.php
3. The page load after a long wait (+30s), but without the css. The problematic script is css.php (screenshot provided).

**Expected behavior**

At least open the login page fast.

**Logs**

No errors are generated in `sql-errors.log` or `php-errors.log` during loading time.

**Screenshots**

[Developer tools, loading time.](https://i.imgur.com/xKnlSO8.jpg)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Can't even access it.

**Additional context**

Running on CentOS 7. Site is served with Apache, running as apache. All directories and files have chmod 755 and it's owned by root:root, except the directories (and all inside) `files` and `config`, that is owned by apache:apache. SELinux is properly configured (as all glpi dependencies). `config` and `files` has set the httpd_sys_rw_content SELinux flag.

Some warning was generated by the update itself:

**Updated to 9.2**
Api users tokens has been reset, if you use REST/XMLRPC api with personal token for authentication, please reset your user's token.

**Updated to 9.3**
New rights has been added for datacenter, you should review ACLs after update.

**Updated to 9.4.0**
New rights has been added for personalization, you should review ACLs after update.

**Comment by llagerlof** [comment] 2019-05-16 16:43
The line that is causing the slow/problem is the `$css = Html::compileScss($_GET);` in `/glpi/front/css.php`.

**Comment by llagerlof** [comment] 2019-05-16 17:05
Debugging a little more:

The `/glpi/inc/html.class.php` contain the method `compileScss()`. In the end this method call `$css = $scss->compile($import);`. It's when it hangs.

So some thoughts. Maybe it tries to compile, but it's so slow to compile that suspasses 30s. Or can be failing to compile the scss at some point inside this `compile()` method.

We need to go deeper.

**Comment by llagerlof** [comment] 2019-05-16 18:22
Tried increase the `max_execution_time` and `max_input_time` in `php.ini` to 300.

It worked in another php scripts (not glpi).

It not worked in this glpi's case. The script continues to die after 30 seconds.

**Comment by llagerlof** [comment] 2019-05-16 19:24
Strange. After many page refresh the GLPI compiled the scss sucefully, and now is opening fast due the not execution of `$css = $scss->compile($import);`

**Comment by cedric-anne** [comment] 2019-05-17 08:05
Hi,

It is weird that it takes this amount of time.

First, which palette do you use ? And are you using the "high contrast" mode ?

Second, which version of PHP do you use, and which extensions are enabled ?

Regards

**Comment by llagerlof** [comment] 2019-05-17 12:58
The palette is Auror. High contrast disabled.

PHP 7.3.5

All requirements set:
![All required extensions enabled](https://i.imgur.com/vLPrk3k.png)

**Comment by cedric-anne** [comment] 2019-05-21 09:13
Hi,

I have a similar configuration and it takes no more than 3 or 4 seconds for the first compilation on my development machine in debug mode, so I close this as this is not a bug in GLPI.

This looks like a performances issue on your server and can be related to many elements (hardware, system configuration, ...). If you need help to fix this, [please use forum](https://forum.glpi-project.org/).

Regards

**Closed by cedric-anne** 2019-05-21 09:13 UTC

**Comment by llagerlof** [comment] 2019-05-21 13:54
:´(

**Comment by rajven** [comment] 2019-06-03 13:44
Same problem. In apache error.log:

[Mon Jun 03 16:37:45.407925 2019] [php7:error] [pid 8430] [client 192.168.253.10:60178] PHP Fatal error:  Uncaught Error: Class 'Leafo\\ScssPhp\\Compiler' not found in /usr/share/glpi/inc/html.class.php:6668\nStack trace:\n#0 /usr/share/
glpi/front/css.php(45): Html::compileScss(Array)\n#1 {main}\n  thrown in /usr/share/glpi/inc/html.class.php on line 6668, referer: http://glpi.jmtc.local/front/plugin.php

**Comment by cedric-anne** [comment] 2019-06-03 13:52
> Same problem. In apache error.log:
> 
> [Mon Jun 03 16:37:45.407925 2019] [php7:error] [pid 8430] [client 192.168.253.10:60178] PHP Fatal error: Uncaught Error: Class 'Leafo\ScssPhp\Compiler' not found in /usr/share/glpi/inc/html.class.php:6668\nStack trace:\n#0 /usr/share/
> glpi/front/css.php(45): Html::compileScss(Array)\n#1 {main}\n thrown in /usr/share/glpi/inc/html.class.php on line 6668, referer: http://glpi.jmtc.local/front/plugin.php

This is not the same problem. Please open another issue and fill requested informations.

**Comment by rajven** [comment] 2019-06-03 14:19
> 
> 
> > Same problem. In apache error.log:
> > [Mon Jun 03 16:37:45.407925 2019] [php7:error] [pid 8430] [client 192.168.253.10:60178] PHP Fatal error: Uncaught Error: Class 'Leafo\ScssPhp\Compiler' not found in /usr/share/glpi/inc/html.class.php:6668\nStack trace:\n#0 /usr/share/
> > glpi/front/css.php(45): Html::compileScss(Array)\n#1 {main}\n thrown in /usr/share/glpi/inc/html.class.php on line 6668, referer: http://glpi.jmtc.local/front/plugin.php
> 
> This is not the same problem. Please open another issue and fill requested informations.

The problem occurs only when the update from the previous version.

Solution:
Replace /usr/share/glpi/vendor/autoload.php to file from source tarball.

**Comment by BuDOOM3uR** [comment] 2020-03-02 16:37
I had a similar problem after an update from 9.3.3 to 9.4.5 : `css.php` loaded in about 12 seconds each time.
While I am sure that I finished the update with a `chown -R www-data[...]` on the glpi directory, I finaly realised (after having debugged `/inc/html.class.php` thanks to you @llagerlof and a `grep` on the generated `$ckey = md5($ckey);` in glpi directory)  that some files in /files/_cache/ and in /files/_cache/cache_db had root as owner...
A new "chown" fixed it.
