### ISSUE TITLE
Connection Closed in Receivers / Conexão fechada em Destinatários

### ISSUE THREAD

**Issue by ricarte-carlos** [glpi-project/glpi#17118] opened 2024-05-14 16:54 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

**Português Brasil**
Conexão fechada em Destinatários

Eu estava configurando o Destinatários para possibilitar a abertura de chamados por e-mail, porém todas as vezes em que eu dou um click em "Obter e-mails agora" ele me entrega o erro:
![image](https://github.com/glpi-project/glpi/assets/59579529/6d38a36f-0fcf-4039-bad4-7e7e2aca97c8)

Analisando logs como a php-errors.log na pasta glpi/flies/_log/php-errors.php eu encontro isso:

`[2024-05-11 01:43:15] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Protocol\Exception\RuntimeException: cannot read - connection closed? in C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol\Imap.php at line 110
  Backtrace :
  ...\laminas\laminas-mail\src\Protocol\Imap.php:125 Laminas\Mail\Protocol\Imap->nextLine()
  ...r\laminas\laminas-mail\src\Protocol\Imap.php:87 Laminas\Mail\Protocol\Imap->assumedNextLine()
  ...r\laminas\laminas-mail\src\Storage\Imap.php:223 Laminas\Mail\Protocol\Imap->connect()
  src\Toolbox.php:2235                               Laminas\Mail\Storage\Imap->__construct()
  src\MailCollector.php:1434                         Toolbox::getMailServerStorageInstance()
  src\MailCollector.php:708                          MailCollector->connect()
  front\mailcollector.form.php:106                   MailCollector->collect()`
![image](https://github.com/glpi-project/glpi/assets/59579529/46d165fb-1f00-4584-a965-9e0b08775fdb)

Alguém pode me ajudar? Não consigo chegar em canto algum.

**English**
Connection closed on Receivers

I was configuring the Recipients to allow opening calls by email, but every time I clicked on "Get emails now" it gave me the error:
![image](https://github.com/glpi-project/glpi/assets/59579529/6d38a36f-0fcf-4039-bad4-7e7e2aca97c8)

Analyzing logs like php-errors.log in the glpi/flies/_log/php-errors.php folder I find this:

`[2024-05-11 01:43:15] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Protocol\Exception\RuntimeException: cannot read - connection closed? in C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol\Imap.php at line 110
  Backtrace :
  ...\laminas\laminas-mail\src\Protocol\Imap.php:125 Laminas\Mail\Protocol\Imap->nextLine()
  ...r\laminas\laminas-mail\src\Protocol\Imap.php:87 Laminas\Mail\Protocol\Imap->assumedNextLine()
  ...r\laminas\laminas-mail\src\Storage\Imap.php:223 Laminas\Mail\Protocol\Imap->connect()
  src\Toolbox.php:2235                               Laminas\Mail\Storage\Imap->__construct()
  src\MailCollector.php:1434                         Toolbox::getMailServerStorageInstance()
  src\MailCollector.php:708                          MailCollector->connect()
  front\mailcollector.form.php:106                   MailCollector->collect()`
![image](https://github.com/glpi-project/glpi/assets/59579529/e61b11c8-bca4-44eb-bf11-8f4498b8a4dd)

Can someone help me? I can't get anywhere.

### Relevant log output

```shell
[2024-05-10 01:20:59] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\glpi\src\DBmysql.php at line 250
  Backtrace :
  src\DBmysql.php:250                                mysqli->real_connect()
  src\DBmysql.php:209                                DBmysql->connect()
  src\DBConnection.php:416                           DBmysql->__construct()
  src\DBConnection.php:510                           DBConnection::switchToMaster()
  inc\config.php:127                                 DBConnection::establishDBConnection()
  inc\includes.php:58                                include_once()
  ajax\dashboard.php:38                              include()
  
[2024-05-10 01:21:02] glpiphplog.WARNING: Test logger  
[2024-05-11 01:43:15] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Protocol\Exception\RuntimeException: cannot read - connection closed? in C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol\Imap.php at line 110
  Backtrace :
  ...\laminas\laminas-mail\src\Protocol\Imap.php:125 Laminas\Mail\Protocol\Imap->nextLine()
  ...r\laminas\laminas-mail\src\Protocol\Imap.php:87 Laminas\Mail\Protocol\Imap->assumedNextLine()
  ...r\laminas\laminas-mail\src\Storage\Imap.php:223 Laminas\Mail\Protocol\Imap->connect()
  src\Toolbox.php:2235                               Laminas\Mail\Storage\Imap->__construct()
  src\MailCollector.php:1434                         Toolbox::getMailServerStorageInstance()
  src\MailCollector.php:708                          MailCollector->connect()
  front\mailcollector.form.php:106                   MailCollector->collect()
```

### Steps To reproduce

**Português**

1- Vá em Configurar - Destinatários - Adicionar
![image](https://github.com/glpi-project/glpi/assets/59579529/e6c41509-e478-49ba-8525-615f0f0223ba)

2- Preencha a ficha
![image](https://github.com/glpi-project/glpi/assets/59579529/1abdfccf-5cc6-4755-ae93-775e8a65f253)

3- Abra a configuração e clique em Ações e depois em Obter Emails Agora
![image](https://github.com/glpi-project/glpi/assets/59579529/e16f3907-6779-421b-a85b-4dcd4957f658)

4- Aguarde o erro
![image](https://github.com/glpi-project/glpi/assets/59579529/5c4d2938-ef28-42f7-8a45-b73bb0051008)

**English**

1- Go to Configure - Recipients - Add
[image](https://github.com/glpi-project/glpi/assets/59579529/e6c41509-e478-49ba-8525-615f0f0223ba)

2- Fill out the form
![image](https://github.com/glpi-project/glpi/assets/59579529/1abdfccf-5cc6-4755-ae93-775e8a65f253)

3- Open the configuration and click on Actions and then on Get Emails Now
![image](https://github.com/glpi-project/glpi/assets/59579529/e16f3907-6779-421b-a85b-4dcd4957f658)

4- Wait for the error
![image](https://github.com/glpi-project/glpi/assets/59579529/5c4d2938-ef28-42f7-8a45-b73bb0051008)

### Your GLPI setup information

Operating system: Linux glpisvr 5.15.0-106-generic #​116-Ubuntu SMP Wed Apr 17 09:17:56 UTC 2024 x86_64
PHP 8.1.27 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at 192.168.1.220 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.16-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiadm@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (8.1.27) is supported.PHP version (8.1.27) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.16) is supported.Database engine version (10.6.16) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi_unifaat/glpi/../files/_cache has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_cron has been validated. Write access to /var/www/glpi_unifaat/glpi/../files has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_dumps has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_graphs has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_lock has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_pictures has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_plugins has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_rss has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_sessions has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_tmp has been validated. Write access to /var/www/glpi_unifaat/glpi/../files/_uploads has been validated.Write access to /var/www/glpi_unifaat/glpi/../files/_cache has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_cron has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_dumps has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_graphs has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_lock has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_pictures has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_plugins has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_rss has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_sessions has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_tmp has been validated.
Write access to /var/www/glpi_unifaat/glpi/../files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
GLPI data directories are located in a secured path.GLPI data directories are located in a secured path.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is not present.ldap extension is not present.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi_unifaat/glpi/marketplace has been validated.Write access to /var/www/glpi_unifaat/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cedric-anne** [comment] 2024-05-15 06:05
Hi,

It seems to be a configuration issue, not a bug. I close this issue as we only track bugs here.

**Closed** 2024-05-15 06:05 UTC
Labels: support
