### ISSUE TITLE
Satisfaction survey for post only

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1619] opened 2017-01-16 14:10 UTC
http://forum.glpi-project.org/viewtopic.php?id=156302

Specific right was requested for technician and doesn't exist in simplified interface.

adding this new value in both interfaces

**Comment by tomolimo** [comment] 2017-01-16 15:43
linked to #1371?

**Comment by trasher** [comment] 2017-01-16 15:45
This is a duplicate of #1371 that has been fixed in the bugfixes branch alreay. Will be fixed in 9.1.2 :)

**Closed by trasher** 2017-01-16 15:45 UTC
Labels: bug
