### ISSUE TITLE
TTR ticket list view not highlighted when expired

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#14544] opened 2023-04-18 10:19 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

After upgrade from GLPI 10.0.6 to 10.0.7 time to resolve column (in ticket list view) are not highlighted anymore when date and time is expired.

Before update, the cell become red once expired.

### Your GLPI setup information

Operating system: Linux SRVSIMS04 5.15.0-5.76.5.1.el9uek.x86_64 #2 SMP Fri Dec 9 18:37:36 PST 2022 x86_64
PHP 8.1.13 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, apcu, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysql, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Oracle Linux Server) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Server Software: MariaDB Server
	Server Version: 10.5.16-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpidbusr@localhost/glpi_prod
	Host info: Localhost via UNIX socket
	
PHP version (8.1.13) is supported.PHP version (8.1.13) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.16) is supported.Database engine version (10.5.16) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
SELinux configuration is OK.SELinux configuration is OK.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/html/glpi": ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is not present.Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cedric-anne** [comment] 2023-05-22 10:54
My bad, it works when status is not `Pending`.

![image](https://github.com/glpi-project/glpi/assets/33253653/cf5ff4d4-3a18-4883-a9d8-afce3d0c326c)

What was the status of related elements?

**Comment by ArriMa** [comment] 2023-05-23 07:58
In our case the status is "Processing (planned)" and this is the service level:
![immagine](https://github.com/glpi-project/glpi/assets/16684500/65b8bad2-c711-4bf6-8a17-7f17608c3d2a)

This is the view in the list
![immagine](https://github.com/glpi-project/glpi/assets/16684500/aef1b429-532e-48a0-b023-3309d3cfd015)

**Comment by cedric-anne** [comment] 2023-06-19 14:05
I just made some tests and I am still not able to reproduce.

Unless I missi somthing, it should not be related to a timezone offset between PHP and MySQL server, but you can still check if both are configured correctly.

Regarding the code, the red background will not be present if there is a `solvedate` value (in the `glpi_tickets` table) that is present and correspond to a date lower than the TTR target date. Is there a value in this field?

**Comment by trasher** [comment] 2023-06-28 05:21
No feedback from a while, closing.

**Closed by trasher** 2023-06-28 05:21 UTC
Labels: Need feedback
