### ISSUE TITLE
[9.2.1] User title is wrong

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3429] opened 2018-01-15 09:15 UTC
Hi, user titles are wrong in difenent pages.

GLPI 9.2.1
In 9.1.4 is all right.

Examples:
..../glpi-test2/front/user.php
Rus
![glpi - -](https://user-images.githubusercontent.com/17082164/34934947-4351f036-f9ed-11e7-8ea5-851131d562ca.png)
Eng
![glpi - users -](https://user-images.githubusercontent.com/17082164/34934952-46ef1c0a-f9ed-11e7-9960-0300e7be6ddb.png)

..../glpi/front/user.form.php?id=1
Rus
![glpi - - 1](https://user-images.githubusercontent.com/17082164/34935000-7167fc54-f9ed-11e7-8750-fa609325733c.png)
Eng
![glpi - users - 1](https://user-images.githubusercontent.com/17082164/34935015-77aaa5da-f9ed-11e7-9e69-e8dce5b73688.png)

**Comment by trasher** [comment] 2018-02-05 12:55
Just tested with current 9.2/bugfixes branch, I cannot reproduce.
Please test with that branch if the issue is present.

**Comment by trasher** [comment] 2018-02-21 13:23
Seems to be fixed; closing

**Closed by trasher** 2018-02-21 13:23 UTC
Labels: Need feedback
