### ISSUE TITLE
Unable to select requester items in standard interface 

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi#11977] opened 2022-06-22 12:50 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Unable to select requester items in standard interface.
In simplified interface, the requester can select his items to link with the ticket.
When IT Technician, open the ticket for the requester, he can't select requester item directlly from standard interface.
He need to create the ticket and then add requester item.

**Comment by cconard96** [comment] 2022-06-22 22:46
Duplicate of #11646

**Closed by cconard96** 2022-06-22 22:46 UTC
Labels: duplicate
