### ISSUE TITLE
[GLPI 9.3.2] Mail receiver refuse all my emails 

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#4856] opened 2018-11-01 08:26 UTC
Hi !

Since 9.2.3, all my e-mails are refused by receiver. I try multiple options but nothing change. Always the same result. Any idea ? Do you ecounter the same problem ? 

Thanks for your help.

**Comment by ciadch** [comment] 2018-11-01 08:35
This issue seems to be related by profile. 

I don't know why but now I need to check "Create ticket" in profile : 

![image](https://user-images.githubusercontent.com/12936546/47841267-57693100-ddb9-11e8-840b-c914985af214.png)

**Comment by pedroluisvsousa** [comment] 2018-11-05 12:33
Likewise for me.
But I discovered that this problem is bypassed by enabling the ticket create option in the user profile.

![profile_create](https://user-images.githubusercontent.com/26510405/47998343-babad200-e0dd-11e8-99f9-0bb0e8b120a3.png)

**Comment by ciadch** [comment] 2018-11-05 14:55
Yes, it works with this optoin checked. But why we have to check it now and not in previous version ? It's my question. This behaviour is a bit annyoing because now all my users can create a tiket directly trough the GLPI web interface, and it's not what I want...

**Comment by pedroluisvsousa** [comment] 2018-11-05 15:40
It's a bug, I belive.

**Comment by cedric-anne** [comment] 2018-11-06 14:39
Hi,

When you say that all your emails are refused, are you talking about mails that should create tickets or abour mails that should create followups ?

On GLPI 9.3.2, we fixed how rights are checked. Now users have to be able to create tickets or followups in order to create the via the mail receiver.

Regards

**Comment by mrspam** [comment] 2018-11-07 12:00
I confirmed this problem.
Check create ticket for the profil solved this problem.

**Comment by pedroluisvsousa** [comment] 2018-11-07 13:37
> 
> On GLPI 9.3.2, we fixed how rights are checked. Now users have to be able to create tickets or followups in order to create them via the mail receiver.
> 
> Regards

You can limit email opening by profile using "Rules for assigning a ticket created through a mails receiver" So, I do not see convenience in doing this check in profile.

**Comment by trasher** [comment] 2018-11-08 09:55
See https://github.com/glpi-project/glpi/issues/2722

Sound like you were relying on a bug to do something that does not seems logic to us. Currently, you user porfile ACLs concerns the whole application, there is no distinction beetween UI, Mails or API.

If you really need such a distinction, this is a new feature.

**Comment by cedric-anne** [comment] 2018-11-20 10:48
@ciadch @pedroluisvsousa @mrspam ,

What was done in 9.3.2 was intentional. Indeed, I considered that the fact that a user does not have rights on the interface should result in the refusal of his email.
Since this choice is not understood by the users and does not reflect our expectations, we have chosen to review what has been done.
We continue to add rights checking on user profiles, but only if the corresponding `Allow anonymous ...` option is not enabled.

PR #4904 should fix this.
Could you test this change on your side and give us a feedback ?

Regards

**Comment by trasher** [comment] 2018-11-22 08:12
Closing, please continue discussion on duplicate #4889

**Closed by trasher** 2018-11-22 08:12 UTC
Labels: Need feedback, question
