### ISSUE TITLE
SNMP Connections 10.0.6-dev

### ISSUE THREAD

**Issue by periodistacg** [glpi-project/glpi#13523] opened 2022-12-05 11:08 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6-dev

### Bug description

Hi,
SNMP inventory makes a connection between a switch and printer port.
You can see this connection in switch network port tab, but in printer network port tab does not appear connected.

Network Equipment has a printer connected on Port43 (networkport 229, mac 00:12:a9...)
`    <DEVICE>
      <INFO>
        <TYPE>NETWORKING</TYPE>
		...
      </INFO>
      <PORTS>
        <PORT>
          <CONNECTIONS>
            <CONNECTION>
              <MAC>00:26:73:...</MAC>
            </CONNECTION>
          </CONNECTIONS>
          <IFNUMBER>43</IFNUMBER>
          <MAC>00:12:a9:...</MAC>
`
![image](https://user-images.githubusercontent.com/119592157/205620403-5aac26e3-812d-4f41-a056-406a6829aa17.png)

Networkport 229 shows correctly the connected printer (printer 1, networkport 11, mac 00:26:73...)
`    <DEVICE>
      <TYPE>PRINTER</TYPE>
      <MAC>00:26:73:...</MAC>
`
![image](https://user-images.githubusercontent.com/119592157/205620420-65bc6b89-2c34-454b-97ce-abdc01ab27a7.png)

Networkport 11 does not shows the connected Network Equipment port

![image](https://user-images.githubusercontent.com/119592157/205620461-8ae6234a-8072-4c21-a855-eff40534405a.png)

**Comment by trasher** [comment] 2022-12-07 05:11
Pleas emake sure you can reproduce on curren tnightly build, severakl fixes has already been merged.

If you can reproduce on nightly, you have to provide inventory files that will permit us to reproduce the issue.

**Comment by periodistacg** [comment] 2022-12-07 10:40
The same error is happengin
Nightly version
![image](https://user-images.githubusercontent.com/119592157/206157572-d109144b-cc92-4873-9181-c7a791c94a5d.png)

The result
![image](https://user-images.githubusercontent.com/119592157/206157628-43d8ce3a-35b0-4c36-8d9e-5844ee372eb2.png)

**Comment by stonebuzz** [comment] 2022-12-07 11:06
Hi @periodistacg 
without inventory file it will be complicated to reproduce and propose a fix.

Possible to send it to my mail address ?

Best regards

**Comment by periodistacg** [comment] 2022-12-07 11:17
Hi @stonebuzz 
I will send you those files

The next inventory: the port43 is now disconnected ¿?
![image](https://user-images.githubusercontent.com/119592157/206165567-fdb71ad1-7c5c-40f2-96e0-28ee0170f663.png)

**Comment by stonebuzz** [comment] 2022-12-07 13:40
Thanks for inventory file.
Can you export glpi rules and post generated file here 

![image](https://user-images.githubusercontent.com/7335054/206194227-de448ab1-1344-47c0-9f64-8cb76e0f3713.png)

Best regards

**Comment by stonebuzz** [comment] 2022-12-07 14:01
Hi  @periodistacg 

i find the rule to allow mac connection between asset.

Can you try this : 

1 - Reset all rules 
2 - Disable ```No creation on partial import``` (```global``` tab)

![image](https://user-images.githubusercontent.com/7335054/206197978-bd0fd737-9533-406d-9f82-cb2607d645e7.png)
 
Then : 

1 - import ```Printer``` (need to be created before network equipement so that GLPI can find it and connect it to the Network Equipement NetworkPort )
2 - import ```NetworkEquipement```

With this, connection is made and stable

**Comment by periodistacg** [comment] 2022-12-07 16:18
Thanks @stonebuzz 
I have disabled "No creation on partial import" rule Is it enough to import printer inventory before the network equipment inventory to put this order in the task?
![image](https://user-images.githubusercontent.com/119592157/206232655-3f063e32-fb70-4f0d-b0fd-50171e477e72.png)

**Comment by stonebuzz** [comment] 2022-12-08 06:35
To be sure, you could dedicate one task for ```Printer``` inventory and another for ```NetworkEquipement``` inventory.

Or run the task twice, the first time to bring up all the assets and the second time so that GLPI can make the link

Best regards

**Comment by periodistacg** [comment] 2022-12-09 07:58
I have created two tasks, with one job each.
Is it run in creation time order?

![image](https://user-images.githubusercontent.com/119592157/206651472-9ec25d8f-dbdc-4954-9bd6-fefcc273dc07.png)

**Comment by stonebuzz** [comment] 2022-12-09 09:07
If you re-run task, printer is connected ?

**Comment by periodistacg** [comment] 2022-12-09 10:11
I have tried to re-run both tasks, and separately but the result is the same: Network Equipment ok, Printer not connected.

**Comment by stonebuzz** [comment] 2022-12-09 12:52
Natively GLPI blacklist ```0.0.0.0``` IP

![image](https://user-images.githubusercontent.com/7335054/206706508-6b7b2d38-ba49-466e-baf0-b919117c2dff.png)

If this entry does not exist, it has been deleted at some point, just add it.

Best regards

**Comment by periodistacg** [comment] 2022-12-09 12:55
As you can see, this entry exists

**Comment by stonebuzz** [comment] 2022-12-09 13:52
have you ```reset``` all of your rules ?

**Comment by periodistacg** [comment] 2022-12-09 14:54
I have done this actions:
Reset all of rules
Force start of Printer Task
Make an inventory
(The networkport of printer port had changed)
Force start of Network Equipment Task
Make an inventory
The result is: Network Equipment connected, Printer port disconnected.
I have made two invetories again: the same result.

**Comment by stonebuzz** [comment] 2022-12-09 15:00
Do you see the same thing?

**Comment by periodistacg** [comment] 2022-12-09 15:15
Some times works fine, as you are sent, but is not usually.
The most of times appear this in printer port (network equipment as yours)
![image](https://user-images.githubusercontent.com/119592157/206732854-d20ae6c1-cc74-4c47-a501-a5e65ad1aed4.png)

![image](https://user-images.githubusercontent.com/119592157/206733249-91659a8b-bdff-4857-950d-3e88679adc4e.png)

**Comment by stonebuzz** [comment] 2022-12-09 15:18
Maybe printer is not always connected to this port ?

Have you some lock on ```Printer``` or ```NetworkEquipement```  (```Lock``` tab)

```Printer``` ```NetworkPort``` still has the same ID (see in URL) at each inventory ?

**Comment by stonebuzz** [comment] 2022-12-09 15:20
> The result is: Network Equipment connected, Printer port disconnected.

When ```NetworkEquipment``` ```NetworkPort``` is connected, can you check related connected ```NetworkPort``` and linked asset (to see if it's always the ```Printer```)

**Comment by periodistacg** [comment] 2022-12-09 15:26
`Maybe printer is not always connected to this port ?`
The printer are always connected to this port.

The printer NetworkPort ID always is different at each inventory. Previus ID is deleted

When NetworkEquipment NetworkPort is connected, the connected printer is the same always (with different ID in url)

**Comment by periodistacg** [comment] 2022-12-09 15:38
NetworkEquipment Locks? Why?
![image](https://user-images.githubusercontent.com/119592157/206737975-183f042c-8743-48ff-9469-8f2fb5d95ea0.png)

Printer locks -> none

**Comment by periodistacg** [comment] 2022-12-12 10:25
I have installed glpi again.
Discovery (Network Equipments and Printers)
ip 0.0.0.0 imported -> deleted manually
Inventory 1
Network Equipment disconnected, no locks, Printer disconnected (ID np 20)
no ip 0.0.0.0 imported any more by inventory
Inventory 2
Network Equipment connected, locks, Printer disconnected (id np 296, id 20 does not exists in bbdd)
Inventory 3
Network Equipment disconnected, locks, Printer disconnected (id np 413, id 296 does not exists in bbdd)
Inventory 4
Network Equipment disconnected, locks, Printer disconnected (id np 422, id 413 does not exists in bbdd)

**Comment by stonebuzz** [comment] 2022-12-12 11:07
On my side

1. Network discovery for  ```Printer```
Printer have one management Port

2. Network inventroy Printer
GLPI remove  management Port in favor of ```NetworkPort``` ```Ethernet```

3. Network discovery then network inventory for ```Switch```
Switch ```NetworkPort``` is correctly conencted to ```Printer``` ```NetworkPort```

Can you try this : 
- Network discovery then inventory  for  ```Printer```
- Network discovery then inventory  for  ```Switch```

Check connected ```NetworkPort```


For ```0.0.0.0``` ```IP``` I do not reproduce on my side
```NetworkPort``` is created without this IP.

Can you post here related XML tag ?


We are certainly on a special case in your architecture / configuration.
Hard to reproduce on my side
Maybe you can consider [taking a subscription](https://glpi-project.org/subscriptions/) to get professional support 
to resolved your issue.

Best regards

**Comment by periodistacg** [comment] 2022-12-12 15:00
I have installed glpi again.

1. Network discovery for printer:
NP 11 management Port
0.0.0.0 imported -> I have deleted in bbdd

2. Network inventory for printer:
NP 17 Ethernet Port

3. Network discovery for network equipment:
Network Equipment: (Only) NP 20 Management Port

5. Network inventory for network equipment:
Network Equipment: Port43 NP 241 Connected
Printer: Port 17, disconnected

6. Network inventory for printer:
Network Equipment: Port43 NP 241 Disconnected
Printer: Port 316, disconnected

7. Network inventory for network equipment:
Network Equipment: Port43 NP 241 Connected
Printer: Port 316 Disconnected

You have this 0.0.0.0 ip in printer xml file. You can see this ip in 3er picture on up (in my firts post).
This 0.0.0.0 appears in glpi_ipaddresses table after printer discovery

I still trying more things...

**Comment by periodistacg** [comment] 2022-12-13 08:05
One question:
When you inject the printer xml file, the ip 0.0.0.0 included in xml file are imported?
![image](https://user-images.githubusercontent.com/119592157/207259959-7481a2ce-62e3-4700-b1f6-f83243037e3c.png)
![image](https://user-images.githubusercontent.com/119592157/207259204-efb651ab-58bb-401f-84cb-0840d59db5d2.png)

**Comment by stonebuzz** [comment] 2022-12-13 08:41
Hi @periodistacg 
can you retry with this pull request -> https://github.com/glpi-project/glpi/pull/13591

(```0.0.0.0``` will be ignored from inventory process but added too)

**Comment by stonebuzz** [comment] 2022-12-13 14:05
@periodistacg 

can you undo this -> https://github.com/glpi-project/glpi/pull/13591
and retry with this -> https://github.com/glpi-project/glpi/pull/13594

**Comment by periodistacg** [comment] 2022-12-13 16:23
After change both files (backlist and networkequipment) all is work fine now
I tried separated inventory (printer and network equipment) -> works fine. ID printer networkport do not change
I tried both inventories (printer and network equipment at the same time) -> works fine. ID printer networkport do not change

**Comment by periodistacg** [comment] 2022-12-13 16:58
How can I do the printer inventory first and next the network inventory automatically?
I have two diferents tasks for each job

**Comment by stonebuzz** [comment] 2022-12-13 17:06
You need to try

**Comment by periodistacg** [comment] 2022-12-14 10:43
I have made more test.
Inventory only with that printer and that network equipment: result ok with several inventories
Each discovery remove and create a new printer network port.
Inventory with more printers: result ok with several inventories
Discovery to find more network equipment remove the printer network port
Inventory with printers and network equipments: result ok with several inventories

Why discovery change the printer network port?

**Comment by stonebuzz** [comment] 2022-12-14 11:40
I don't Know why, seems to be another problem.

Can you open New issue ?

Best regards

**Comment by periodistacg** [comment] 2022-12-14 12:41
I have opened the issue #13609

**Comment by stonebuzz** [comment] 2022-12-14 13:06
I close this one 
best regards

**Closed by stonebuzz** 2022-12-14 13:06 UTC
Labels: Need feedback

**Comment by periodistacg** [comment] 2022-12-15 14:47
I think the snmp inventory should not change the id printer port each time. Is it not wrong?
