### ISSUE TITLE
[9.2.2] Regression : too many line breaks in followups and tasks

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#3737] opened 2018-03-20 10:57 UTC
Hello,

After an upgrade from GLPI 9.2.1 to GLPI 9.2.2, I notice too many line breaks in followups and tasks on Timeline tab. 

* Steps to reproduce (which actions have you made) :
  * Create a followup with following content : 
```
Hello,
One line break

One line break + one line feed.
```
* Actual result :
![line_break](https://user-images.githubusercontent.com/10830260/37649705-e9fc8abe-2c32-11e8-951c-18502cd5126e.png)

* Expected result :
![no_br](https://user-images.githubusercontent.com/10830260/37650655-dcfff0e6-2c35-11e8-9446-7e65c1ba2e39.png)

Important : issue doesn't affect description display in Timeline tab.

I tested with PR #3687 related to issue #3712, issue still presents. As said in https://github.com/glpi-project/glpi/pull/3687#issuecomment-372659363 , I suspect this commit : https://github.com/glpi-project/glpi/commit/591217f13552a7409a957e8f9d5396ed40b41f3f#diff-bb7c2f434e967018d0af7b0789728933

**Comment by nqb** [comment] 2018-03-21 07:40
@edgardmessias, 

Do you reproduce this issue ?
Do you think this issue related to #3712 ?

Thanks.

**Comment by edgardmessias** [comment] 2018-03-21 11:24
@nqb, the #3712 is oposite of this

**Comment by nqb** [comment] 2018-03-21 13:38
@edgardmessias,

Sorry but I don't understand #3712.
Could you provide screenshots for (Actual/Expected results) ?
Could you explain more why my issue is oposite of #3712 ?

**Comment by edgardmessias** [comment] 2018-03-21 13:47
Single: the #3712 remove linebreaks for users without permission to edit.

The problem is after this: https://github.com/glpi-project/glpi/commit/591217f13552a7409a957e8f9d5396ed40b41f3f#diff-007edb12589cf3c8df3121cd7b19028aL7013

**Comment by edgardmessias** [comment] 2018-03-22 13:13
@nqb, check the `css/styles.css` and `css/styles.min.css`, find the `.timeline_history .h_content` and remove `white-space:pre-wrap;`

Or: Open Developer Tools in browser and find it and disable

**Comment by nqb** [comment] 2018-03-22 13:36
@edgardmessias : thanks for workarounds but I open this issue to have an upstream patch.

@trasher or @orthagh, could you fix it ?

9.2.1 :
![reg_9 2 1](https://user-images.githubusercontent.com/10830260/37773254-69370146-2ddd-11e8-9ce2-df3c45a35169.png)
9.2.2 :
![reg_9 2 2](https://user-images.githubusercontent.com/10830260/37773280-79a11e22-2ddd-11e8-90cc-8936c76d8f03.png)
9.2.2 bugfix : 
![reg_9 2 2bf](https://user-images.githubusercontent.com/10830260/37773290-7fdfc108-2ddd-11e8-9afd-d94fff7feae7.png)

**Comment by edgardmessias** [comment] 2018-03-22 13:39
@nqb, show the screenshot of result

**Comment by nqb** [comment] 2018-03-22 13:51
9.2.1 :
![s_reg_9 2 1](https://user-images.githubusercontent.com/10830260/37773962-42adb00e-2ddf-11e8-8a8c-cabe4591e79f.png)
9.2.2 :
![s_reg_9 2 2](https://user-images.githubusercontent.com/10830260/37774344-3dac6a22-2de0-11e8-81fb-dfa12064d96a.png)
9.2.2 bugfix : 
![s_reg_9 2 2bf](https://user-images.githubusercontent.com/10830260/37774352-43f435ea-2de0-11e8-8343-40c5882614ee.png)

I just take screenshots of my **own** followups.

**Comment by trasher** [comment] 2018-04-04 14:10
OK, there are no extra line breaks; this is just a display issue

**Comment by nqb** [comment] 2018-04-10 10:43
My feedback : 
* if I comment `white-space:pre-wrap;` in `css/styles.css` : no effect
* if I comment `white-space:pre-wrap;` in `css/styles.min.css` : I get expected result for tasks and followups but ticket description lost its line feeds and line breaks.

Ticket description has no `<br>` to represents line feeds or line breaks : 
![ticket_desc](https://user-images.githubusercontent.com/10830260/38552561-c250c418-3cbc-11e8-80e1-ea42bcee84f5.PNG)
![ticket_desc_inspect](https://user-images.githubusercontent.com/10830260/38552560-c22c0e34-3cbc-11e8-9bdf-c3fb94a9d7bd.PNG)

@trasher : could you fix it ?

**Comment by nqb** [comment] 2018-04-12 09:02
@trasher : could you reopen issue and provide me a patch ?

**Comment by trasher** [comment] 2018-04-12 09:39
On current 9.2/bugfixes branch
Input:
![screenshot-2018-4-12 glpi - tickets - 6](https://user-images.githubusercontent.com/224733/38669231-1946258a-3e46-11e8-8ef0-619bb5948da1.png)

Result:
![screenshot-2018-4-12 glpi - tickets - 6 1](https://user-images.githubusercontent.com/224733/38669233-1b360dce-3e46-11e8-9eeb-bafb50159795.png)

**Comment by nqb** [comment] 2018-04-12 10:09
@trasher : try same test on followup or task.

**Comment by trasher** [comment] 2018-04-12 10:40
OK, I was sur fix has been commited in 9.2/bugfixes; but it was not. See #3854

**Closed** 2018-04-12 13:35 UTC
Labels: bug

**Comment by nqb** [comment] 2018-05-09 06:45
It works.
