### ISSUE TITLE
V10 RC3 : inventory Import JSON file

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi#11183] opened 2022-04-05 09:29 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

V10 RC3

### Bug description

Hello
when importing a json file (issue from GLPI agent on phone)

![image](https://user-images.githubusercontent.com/42341169/161723142-54b7334d-b002-4b53-a341-e55d16de0cf5.png)

Json not valid, but it contains 'content' data...

+ problem on $deviceid not defined ?

**Comment by trasher** [comment] 2022-04-05 09:32
Please provide json and xml file. I wonder if the json provided from agent is correct.

**Comment by EC2311** [comment] 2022-04-05 09:37
here are json and xml files generated on phone (glpi agent)
[Inventory.zip](https://github.com/glpi-project/glpi/files/8416876/Inventory.zip)

**Comment by stonebuzz** [comment] 2022-04-05 10:24
Hi @EC2311 
Do you get the same error when it's the agent that sends the XML to GLPI ?

**Comment by EC2311** [comment] 2022-04-05 11:15
when it's XML : 
![image](https://user-images.githubusercontent.com/42341169/161742127-c9915e56-013c-437c-992d-50ca9f19d0e2.png)

**Comment by stonebuzz** [comment] 2022-04-05 12:17
And when it's the agent that sends the XML inventory ?

**Comment by EC2311** [comment] 2022-04-05 12:19
It's the report from my phone, and I can't connect it to the WIFI of my GLPI server.
That's why I use the 'import' option...

**Comment by trasher** [comment] 2022-04-05 13:29
OK, problem is the data provided are all incorrect. 
First; there are HTML entities in the XML file, It's required to convert them to regular characters in order to import the file. Also, there is an unknown status value of `dormant` on a network port (I've replaced with valid `down`).
The JSON file is also incorrect, the `request` level should not be present.

If I fix the XML and then use GLPI to convert it to JSON, the result is ok.

This may be an agent issue, we will investigate.

**Comment by stonebuzz** [comment] 2022-04-06 07:03
Hi @EC2311 , after test

inventory send by agetnthe ```Agent``` works fine

![image](https://user-images.githubusercontent.com/7335054/161914385-04de3d54-2986-4236-9aa4-5b0485f48ba0.png)

If I get the XML file generated by the agent (in the Download folder) is well formatted 

![image](https://user-images.githubusercontent.com/7335054/161914705-54bf6fe2-770a-4b88-8468-da33c0bfa6ce.png)

compared to your file 

![image](https://user-images.githubusercontent.com/7335054/161914831-4aefe44c-2cc1-4153-b4c4-7cfa1df97a59.png)


where ```<![CDATA]]>``` are encoded to ```&lt;![CDATA]]&gt;```

how do you get the XML file generated by the agent?

Best regards

**Comment by EC2311** [comment] 2022-04-06 07:58
Hello

I shared it from my phone using bluetooth 

I checked in the download folder and indeed, the xml doesn't content 'lt' but < 
So it should be the 'transfer' module of bluetooth (either on the phone or computer)

**Comment by stonebuzz** [comment] 2022-04-06 10:41
Downloaded like you (with USB cable) and from ```VSCode``` / ```AndroidStudio``` / ```bluetooth```

Original file have a good encoding each time.

Have you update inventory.xml file with ```NotePad++``` when you send it here ?

**Comment by EC2311** [comment] 2022-04-06 12:09
Phone connected with USB
-> using Explorer on my PC -> I go to download file on the phone
Have a look on the screen I see below
![image](https://user-images.githubusercontent.com/42341169/161971354-73a9ae67-ac9f-478f-9a14-9eca6b7fba6f.png)

**Comment by stonebuzz** [comment] 2022-04-06 12:13
I don't know if Explorer decode file before display it.
Can you send inventory.xml (not altered) at skita@teclib.com

Best regards

**Comment by EC2311** [comment] 2022-04-06 12:34
here is the original xml document generated by the phone
[Inventory.zip](https://github.com/glpi-project/glpi/files/8426872/Inventory.zip)
Best regards

**Comment by stonebuzz** [comment] 2022-04-06 13:14
The format is good

![image](https://user-images.githubusercontent.com/7335054/161982807-711f42dc-3d7f-45a6-b4d9-b42b253b5a39.png)

You can use this file to manually import device into GLPI

**Comment by EC2311** [comment] 2022-04-06 15:40
I just uploaded the last version, : same error :(

to confirm : 
- I use this link to upload the file : ....glpi/front/inventory.conf.php 
- I use Chrome (or Edge)

**Comment by stonebuzz** [comment] 2022-04-07 06:37
Because XML file is converted as JSON from GLPI native inventory to validate data and format 
with this https://github.com/glpi-project/inventory_format/blob/master/inventory.schema.json

A CDATA section is "[a section of element content that is marked for the parser to interpret as only character data, not markup.](http://en.wikipedia.org/wiki/CDATA)"

The problem here is that the ```<![CDATA[ ]]>``` is converted to  ```&lt;![CDATA[]]&gt;``` between the moment you retrieve the file from the phone (where fiel encoding is fine)  and the moment you import the file into GLPI

Did you update (with notepad++ ) file before import ?

**Comment by EC2311** [comment] 2022-04-07 06:47
Hello

I rerun at the moment a new inventory on my phone.
I transfer the file (xml) with bluetooth to my computer
I upload it without updating it

always Same error.

Can we imagine a problem with php version ? I use 7.4.9 version. and you ?

**Comment by stonebuzz** [comment] 2022-04-07 06:51
PHP 7.4.3 but I don't think the problem is PHP

can you test by using the Agent to send XML inventory to GLPI (and not share and manually import) ?

**Comment by stonebuzz** [comment] 2022-04-07 06:53
Where GLIP is hosted ? Linux, IIS, Windows ?

Are you using apache2 / Nginx  other ?

**Comment by EC2311** [comment] 2022-04-07 06:56
I can't connect my phone to the wifi network :(
I cant' share the connection of my Pc computer (forbidden by admin) : that's why I used the bluetooth (or mail from phone to computer)

I use Windows 10 and a wamp installation with apache

One more information : 
As i Have 9.5.5 glpi with fusioninveotyr : There is a option to load the xml file
here is the result of the import (no error when importing, but strange result)
![image](https://user-images.githubusercontent.com/42341169/162138410-8f88d696-db3a-4891-8673-82594b812e4b.png)

**Comment by EC2311** [comment] 2022-04-07 09:08
Pour info : 
j'ai supprimé tous les lt; les gt; ainsi que les !Cdata[ et ]] 
l'import (hormis le status dormant -> up) passe et fonctionne.

je peux comprendre que le cdata peut faire partie du xml, mais en l'occurence l'import manuel ne le permet pas àl'heure actuelle

**Comment by stonebuzz** [comment] 2022-04-07 10:03
Pour information la prochaine version de l'agent inclura une option permettant de choisir la destination ```Computer``` ou ```Phone```

Cette nouvelle option n'est valable que pour l'inventaire natif de GLPI (FusionInventory ne gère pas ce noeud)

Vous pouvez tester en ajoutant le noeud suivant dans le fichier XML 

```<ITEMTYPE>Phone</ITEMTYPE>```

juste après la balise ```<REQUEST>``` en haut du fichier XML.


Concernant le ```CDATA``` ne reproduisant pas localement (même sur nos tests interne) il est difficile pour moi de comprendre ce qu'il se passe.

Bien cordialement

**Comment by EC2311** [comment] 2022-04-07 11:08
En effet, itemtype : c'est ok : le telephone est bien créé correctement.

dommage pour xml et l'import json egalement n'est pas ok (propriété requise manquante... + erreur avec deviceid (abstractrequest.php)

**Comment by stonebuzz** [comment] 2022-04-07 11:15
La priorité manquante à déjà fait l'objet d'un fix ici
https://github.com/glpi-project/inventory_format/pull/69

Il sera intégrer prochainement dans GLPI

**Comment by EC2311** [comment] 2022-04-07 11:28
ok pour "dormant" 

mais pour 
![image](https://user-images.githubusercontent.com/42341169/162188743-3e09a315-82dc-4ce6-9716-77db10a45ceb.png)

![image](https://user-images.githubusercontent.com/42341169/162188653-8eaed6e3-e588-44ba-87be-18c2d1963360.png)

**Comment by trasher** [comment] 2022-04-07 11:28
Could you please use english?

**Comment by EC2311** [comment] 2022-04-07 11:32
Sorry
in summury
when removing cdata, lt; and gt; from the initial xml file -> ok to import (as computer, but as said by stonebuzz, the itemtype could be use in the file to split in the right item : ok

but I have still problem if I import using json (it's the screen shots of my last message)
thanks

**Comment by stonebuzz** [comment] 2022-04-08 08:17
Please only use the XML (agent work with it)

**Comment by stonebuzz** [comment] 2022-04-08 13:21
Hi @EC2311 
can you try with this version (futur latest of android-inventory-agent)

[android-inventory-agent.tar.gz](https://github.com/glpi-project/glpi/files/8452083/android-inventory-agent.tar.gz)

This version remove all ```CDATA``` from XML file

Reminder: only work with the XML file on GLPI !

You need to update your GLPI to the latest nightly build  tomorrow 

or apply manually apply this fix -> https://github.com/glpi-project/glpi/pull/11212

**Comment by EC2311** [comment] 2022-04-11 09:19
Hello

I removed the previous version of android
I installed the new one
I run it on the phone
I transfered the filte using bluetooth to the computer

1- i remark the itemtype line but it contains 'computer' rather 'phone' -> i Updated it to upload as phone
2- when uploading : an error linked to camera
![image](https://user-images.githubusercontent.com/42341169/162706936-ec3600e2-542c-4de7-bf58-318c30f08a73.png)

nevertheless but the phone is created

**Comment by EC2311** [comment] 2022-04-11 09:39
perhaps still a mismatch in the volumes (drives)
![image](https://user-images.githubusercontent.com/42341169/162711052-6906e271-5274-4604-aa78-f69ff8ff0e86.png)
-> no name on the volumes (drives) ? (empty in the xml file)

**Comment by trasher** [comment] 2022-04-19 06:39
Seems this is now fixed, I close this one.

**Closed by trasher** 2022-04-19 06:39 UTC
Labels: Need feedback
