### ISSUE TITLE
 financial and administrative information gone

### ISSUE THREAD

**Issue by tomSDL** [glpi-project/glpi#5690] opened 2019-03-27 08:29 UTC
Hi,

The financial and management info for my assets is gone. I can see in the historical information where I set it. I cant see it being unset?

Any idea's?

Thanks,

Tom

**Comment by tomSDL** [comment] 2019-03-27 08:32
I see what the issue is if I transfer a computer from an entity to another the supplier, warranty etc is gone.

**Comment by trasher** [comment] 2019-03-27 08:35
Requested information from issue template are missing.

**Comment by tomSDL** [comment] 2019-03-27 08:49
**Describe the bug**

Financial and administrative information is being cleared from Assets. This is occurring shortly after entering the information. I did believe it was from transferring but I now see it is 

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

Enter financial and administrative information, wait a few minutes. Its gone.

**Expected behavior**

A clear and concise description of what you expected to happen.

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

If applicable, add screenshots to help explain your problem.

Assets have to have the financial and administrative information button pressed again.

![image](https://user-images.githubusercontent.com/32687810/55062007-f9d9c780-506c-11e9-89c1-fcde4b3c8133.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

GLPI 9.4.1.1 (/glpi => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux helpdesk 4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 PHP 7.0.33-0ubuntu0.16.04.2 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, 	apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, 	json, ldap, libxml, mbstring, mcrypt, memcache, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, 	readline, recode, session, shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="3000" memory_limit="2048M" post_max_size="300M" safe_mode="" session.save_handler="files" 	upload_max_filesize="300M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at  Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.25-0ubuntu0.16.04.2 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (5.7.25) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

Server: '192.168.100.246', Port: '389', BaseDN: 'DC=, DC=CO, DC=UK', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=ldap-glpi,ou=ldap 		accounts,ou=nologonscript,DC=DC=co,DC=uk', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@mail.l.co.uk)

Name: '' Active: Yes 	Server: '{}' Login: 'st' Password: Yes

fields               Name: Additionnal fields             Version: 1.9.1      State: Enabled 	appliances           Name: Appliances                     Version: 2.4.1      State: To be cleaned 	behaviors            Name: Behaviours                     Version: 2.2.0      State: Enabled 	browsernotification  Name: Browser Notification           Version: 1.1.9      State: To be cleaned 	certificates         Name: Certificates                   Version: 2.3.0      State: To be cleaned 	dashboard            Name: Dashboard                      Version: 0.9.0      State: To be cleaned 	databases            Name: Databases                      Version: 2.1.1      State: To be cleaned 	archimap             Name: Diagrams                       Version: 2.0.15     State: To be cleaned 	domains              Name: Domains                        Version: 2.1.0      State: To be cleaned 	environment          Name: Environment                    Version: 2.3.0      State: To be cleaned 	datainjection        Name: File injection                 Version: 2.7.0      State: Enabled 	formcreator          Name: Forms                          Version: 2.7.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled 	glpi2mdt             Name: GLPI 2 MDT                     Version: 0.2.1      State: To be cleaned 	mod                  Name: GLPI Modifications             Version: 1.3.0      State: Enabled 	openvas              Name: GLPi openvas Connector         Version: 1.2.0      State: Enabled 	geninventorynumber   Name: Inventory number generation    Version: 2.4.0      State: Enabled 	metabase             Name: metabase                       Version: 0.9.0      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.7.0      State: To be cleaned 	genericobject        Name: Objects management             Version: 2.7.0      State: Enabled 	order                Name: Orders management              Version: 2.4.0      State: To be cleaned 	reports              Name: Reports                        Version: 1.13.0     State: Not installed 	manufacturersimports Name: Suppliers imports              Version: 2.1.2      State: To be cleaned 	taskdrop             Name: TaskDrop                       Version: 1.1.0      State: Not installed 	tasklists            Name: Tasks list                     Version: 1.5.0      State: Not installed


```

**Additional context**

Add any other context about the problem here.

**Comment by trasher** [comment] 2019-03-27 08:57
"wait a few minutes. Its gone." => looks like a cron issue.

You should try disabling plugins first; and see if you still reproduce. You should also try with latest 9.4/bugfixes nightly build, some things may have been fixed yet.

**Comment by tomSDL** [comment] 2019-03-27 09:00
Thanks trasher<https://github.com/trasher>

**Comment by tomSDL** [comment] 2019-03-27 11:43
planningrecall



Planning reminders

Send planning recalls

Scheduled

27-03-2019 11:38

mailgate

Receivers

Retrieve email (Mails receivers)

Scheduled

27-03-2019 11:35

slaticket

SLA level for Ticket

Automatic actions of SLA

Scheduled

27-03-2019 11:33

reservation

Reservable items

Alerts on reservations

Scheduled

27-03-2019 11:31

queuednotification

Notification queue

Send mails in queue

Scheduled

27-03-2019 11:27

ticketrecurrent

Recurrent tickets

Recurrent tickets

Scheduled

27-03-2019 11:00

graph<https://helpdesk.shearwell.co.uk/glpi/front/crontask.form.php?id=13>

Automatic actions

Clean generated graphics

Scheduled

27-03-2019 11:00

temp

Automatic actions

Clean temporary files

Scheduled

27-03-2019 10:49

alertnotclosed

Tickets

Not solved tickets

Scheduled

27-03-2019 08:57

closeticket

Tickets

Automatic tickets closing

Scheduled

27-03-2019 08:49


Hi,

These are the jobs run today. I added some test info earlier – All gone

**Comment by tomSDL** [comment] 2019-03-27 14:59
I have disabled all plugins and the bug still exists. I will try the nightly.

**Comment by trasher** [comment] 2019-03-27 15:04
OK, keep us in touch. Plus, did you setup any crontab for GLPI on your system?

**Comment by TomEvin** [comment] 2019-03-29 16:24
My issue is connecting to this.
I used 9.4.0 before, and after the update to 9.4.1.1, all financial information gone from the webpage, and there is just a button "Enable financial and administrative information".
Even in the General setting I choose "Enable the financial and administrative information by default" to YES.
But the Financial data are in the database!

**Comment by rollandpf** [comment] 2019-03-29 19:45
I have the same issue. I reverted to 9.4.0. Nothing strange in th logs for me.

**Comment by trasher** [comment] 2019-03-30 06:31
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/)); as I do not reproduce with it on my side.

**Comment by TomEvin** [comment] 2019-03-30 08:33
I downloaded the latest nightly (9.4-bugfixes.tar.gz 	30-03-19) from your link, no change. :(
What do you need to you can identify the problem?

**Comment by TomEvin** [comment] 2019-03-30 10:00
OK, I found my problem.
I have checked the infocoms table in the database, and because I saw some data (probably the users made between 9.4.1.1 update and recognize the problem), and I thought the Financial data are there. But no!
Somehow the financial data was deleted during the 9.4.0->9.4.1.1 update. All of them!
I restored this table from previous backup, and now Managemant page is OK at the devices.

I'm not sure what really happened with these data.

**Comment by cedric-anne** [comment] 2019-04-01 07:12
Hi,

Have you use the transfer feature recently (in 9.4.1.1) ? This issue may explain your problem: https://github.com/glpi-project/glpi/pull/5703.

Regards

**Comment by ladenree76000** [comment] 2019-04-02 12:11
https://forum.glpi-project.org/viewtopic.php?pid=360509#p360509

I also lost  Financial infos by transfering an asset from an entity to another.

**Comment by ladenree76000** [comment] 2019-04-02 12:12
glpi 9.4.2    (1/04/2019 tarball)

**Comment by cedric-anne** [comment] 2019-04-02 12:21
Hi,

It has been merged yesterday, so fix is only available since today's nightly build (`Tue, 02 Apr 2019 02:49:09 +0200`).

Regards

**Comment by ladenree76000** [comment] 2019-04-02 12:35
glpi_infocoms is now empty !

**Comment by ladenree76000** [comment] 2019-04-03 07:53
version :  glpi 9.4.2 (tarball 3/4/2019) 
actions : 
dump glpi_infocoms
select count(*) from glpi_infocoms =>14430
in glpi GUI : 1 computer (with infocom) Added to transfert list, mode complete-> transfert to sub entity 

results :
after about 20 seconds :  
Fatal error: Uncaught RuntimeException: Empty IN are not allowed in /var/www/html/glpi942/inc/dbmysqliterator.class.php:546 Stack trace: #0 /var/www/html/glpi942/inc/dbmysqliterator.class.php(516): DBmysqlIterator->analyzeCriterion(Array) #1 /var/www/html/glpi942/inc/dbmysqliterator.class.php(506): DBmysqlIterator->analyseCrit(Array) #2 /var/www/html/glpi942/inc/dbmysqliterator.class.php(288): DBmysqlIterator->analyseCrit(Array) #3 /var/www/html/glpi942/inc/dbmysqliterator.class.php(94): DBmysqlIterator->buildQuery('`glpi_contracts...', Array, false) #4 /var/www/html/glpi942/inc/dbmysql.class.php(569): DBmysqlIterator->execute(Array, '', false) #5 /var/www/html/glpi942/inc/transfer.class.php(2781): DBmysql->request(Array) #6 /var/www/html/glpi942/inc/transfer.class.php(2719): Transfer->transferSingleSupplier('152') #7 /var/www/html/glpi942/inc/transfer.class.php(1077): Transfer->transferInfocoms('Computer', '3467', '3467') #8 /var/www/html/glpi942/inc/transfer.class.php(203): Transfer->transferItem('Computer', '3467', '34 in /var/www/html/glpi942/inc/dbmysqliterator.class.php on line 546

and 
select count(*) from glpi_infocoms =>9726    (should be 14430 !)

**Comment by TomEvin** [comment] 2019-04-03 09:55
With 9.4.2 (tarball 3/4/2019) so far I do not have issue.
Financial data are intact after device moved.

**Comment by cedric-anne** [comment] 2019-04-04 09:13
@ladenree76000 

The code related to the transfer is really complex and I do not really know how to fix this error. Indeed, logic is not the same for all items to transfer so I do not really know which logic should be use in the case you had the error.

Regards

**Comment by msource** [comment] 2019-04-22 14:19
Any news about this? I've upgraded to version 9.4.2 last stable that is in the Github and all my Financal and Administrative information are gone. What can I do to solve it?

**Comment by trasher** [comment] 2019-04-23 04:10
Looks like everybody is not talking about the same issues. Some problems are related to transfer, for other I do not know.

Please keep discussion focused; it's difficult to understand this thread now.

**Comment by msource** [comment] 2019-04-26 13:55
Hi Guys, I'm having the same problem, when update to version 9.4.2 (stable version) all my Financial and Administrative information is gone 👎 any news about this?

**Comment by trasher** [comment] 2019-04-26 13:59
Since anyone has been able yet to provide any cause and we cannot reproduce, nothing new. 

Also; as I've already said:

> You should try disabling plugins first; and see if you still reproduce. You should also try with latest 9.4/bugfixes nightly build, some things may have been fixed yet.

**Comment by cedric-anne** [comment] 2019-04-26 14:02
Hi,

Can you confirm that if, on a test server that does not have any GLPI plugin, you restore your SQL dump backup and just launch migrations your informations are gone ?

By the way, when you are talking about updating, from which version ?

Regards

**Comment by msource** [comment] 2019-04-26 14:13
Hi,

I update from version 9.4.1 to 9.4.2 and was when all Financial and Administrative information simply gone. 

Sincerely,
Marcos Fernandes

**Comment by jessgoodwin** [comment] 2019-05-17 19:00
We are having the same issue and can recreate it. If I move one computer from our root entity to another entity....no issue. But if I move more than one computer (in a single batch) from the root to another entity the entire glpi_infocoms table gets wiped clean.

**Comment by trasher** [comment] 2019-05-20 06:33
You're talking about an transfer issue, this is not the original subject of current tissue.
All known transfer issues has been fixed, try nightly.

**Comment by msource** [comment] 2019-05-20 08:04
Were can we download the nightly/last release?

**Comment by trasher** [comment] 2019-05-20 08:08
see https://forge.glpi-project.org/tarballs/

**Closed** 2019-06-05 10:48 UTC
Labels: Need feedback, help wanted
