### ISSUE TITLE
 Error Notification Templates 

### ISSUE THREAD

**Issue by dmmario** [glpi-project/glpi#9649] opened 2021-10-01 14:54 UTC
Hello

I have an Ubuntu Server with version 9.5.6 every time I go to Notification Templates an error appears:

PHP User Error (256): Trying to load a forbidden class name "0" in /var/www/html/glpi/inc/autoload.function.php at line 280

What can it depend on?

Thanks

**Comment by cedric-anne** [comment] 2021-10-04 06:21
Hi,

Please provide the full stack trace of this error, and please provide your GLPI system informations.

Regards

**Comment by dmmario** [comment] 2021-10-04 06:58
sorry I'm not practical, how do I find this full stack of the error?
Thanks



<html>
<body>


Server
--
Operating system: Linux glpi 5.11.0-36-generic #40~20.04.1-Ubuntu SMP Sat Sep 18 02:14:19 UTC 2021 x86_64 PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, 	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, soap, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 192.168.1.101 Port 88) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36 Server Software: Ubuntu 20.04 	Server Version: 10.3.31-MariaDB-0ubuntu0.20.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpidb 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.31) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.6 GLPI_SCHEMA_VERSION: 9.5.6 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Not active

Way of sending emails: SMTP xxxxxxxxx)

Name: 'ccxxxxxx' Active: No 	Server: '{xxxxxxxxxxx}' Login: 'xxxxxxxx' Password: Yes

actualtime           Name: ActualTime                     Version: 1.5.0      State: Installed / not activated 	autologin            Name: Auto Login                     Version: 2.1.1      State: Installed / not activated 	news                 Name: Avvisi                         Version: 1.9.0      State: Enabled 	fields               Name: Campi aggiuntivi               Version: 1.12.4     State: Installed / not activated 	behaviors            Name: Comportamenti                  Version: 2.5.0      State: Installed / not activated 	dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.12.2     State: Enabled 	formvalidation       Name: Form Validation                Version: 0.6.8      State: Not installed 	genericobject        Name: Gestione degli Oggetti         Version: 2.9.2      State: Installed / not activated 	order                Name: Gestione ordini                Version: 2.6.0      State: Installed / not activated 	mreporting           Name: More Reporting                 Version: 1.7.2      State: Installed / not activated 	browsernotification  Name: Notifiche del browser          Version: 1.1.9      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.1      State: Installed / not activated 	reports              Name: Report                         Version: 1.14.1     State: Installed / not activated 	simcard              Name: Sim cards management           Version: 1.4.2      State: Not installed 	pdf                  Name: Stampa in PDF                  Version: 2.0.0      State: Installed / not activated 	useditemsexport      Name: Used items export              Version: 2.4.0      State: Not installed 	webresources         Name: Web Resources                  Version: 1.3.2      State: Not installed


</body>
</html>

**Comment by cedric-anne** [comment] 2021-10-04 07:01
![image](https://user-images.githubusercontent.com/33253653/135807329-206a623d-cd81-4468-a3ec-f00ea0a20539.png)

**Comment by dmmario** [comment] 2021-10-04 07:11
OK which log file should I attach? cron.log, php-error.log, event.log

**Comment by cedric-anne** [comment] 2021-10-04 07:15
`php-error.log`

**Comment by dmmario** [comment] 2021-10-04 07:19
the code is long but I don't see on the forum how to attach files

**Comment by dmmario** [comment] 2021-10-04 07:25
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_cb5jcbcs34qr9kuuaglnmjf4d8): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_9lmplpsvva528jt88ohaqh8vqt): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_ce02eoju794sb6dp86oetd9ol5): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_9mvnl5eo76tur3jqeo4rdtgv73): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_e37avd9ad7aufkeko9hdg33iaf): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_q4g6bgiivej45rd7kgqgqcnclh): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_q1e0ppfn24e5pvloh07t5rbtjt): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_lk3ct554tec0vch9bou1bkqnnm): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_ccob55q50uqtf8od3v7grh83t4): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_cpbq3im8u8lf8k64rcudala7am): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.WARNING:   *** PHP Warning (2): file_get_contents(/var/www/html/glpi/files/_sessions/sess_ckiim44uvdsg9jlfe9m8vkeh6u): failed to open stream: Permission denied in /var/www/html/glpi/plugins/dashboard/front/main.php at line 841
  Backtrace :
  plugins/dashboard/front/main.php:841               file_get_contents()
  
[2021-10-01 17:17:27] glpiphplog.NOTICE:   *** PHP User deprecated function (16384): Use DBmysql::fetchAssoc() in /var/www/html/glpi/inc/toolbox.class.php at line 653
  Backtrace :
  inc/toolbox.class.php:653                          trigger_error()
  inc/dbmysql.class.php:488                          Toolbox::deprecated()
  plugins/dashboard/front/main.php:880               DBmysql->fetch_assoc()
  
[2021-10-01 17:18:46] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Glpi\Dashboard\Provider::formatMonthyearDates() must be of the type string, null given, called in /var/www/html/glpi/inc/dashboard/provider.class.php on line 950 in /var/www/html/glpi/inc/dashboard/provider.class.php at line 1269
  Backtrace :
  inc/dashboard/provider.class.php:950               Glpi\Dashboard\Provider::formatMonthyearDates()
  :                                                  Glpi\Dashboard\Provider::getTicketsStatus()
  inc/dashboard/grid.class.php:1002                  call_user_func_array()
  ajax/dashboard.php:122                             Glpi\Dashboard\Grid->getCardHtml()
  
[2021-10-02 15:49:20] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7520
css/dashboard.scss is new, loading  {"user":"197@glpi"} 
[2021-10-02 15:49:21] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7520
css/palettes/flood.scss is new, loading  {"user":"197@glpi"} 
[2021-10-02 15:49:21] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7520
css/styles.scss is new, loading  {"user":"197@glpi"} 
[2021-10-02 15:49:25] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Glpi\Dashboard\Provider::formatMonthyearDates() must be of the type string, null given, called in /var/www/html/glpi/inc/dashboard/provider.class.php on line 950 in /var/www/html/glpi/inc/dashboard/provider.class.php at line 1269
  Backtrace :
  inc/dashboard/provider.class.php:950               Glpi\Dashboard\Provider::formatMonthyearDates()
  :                                                  Glpi\Dashboard\Provider::getTicketsStatus()
  inc/dashboard/grid.class.php:1002                  call_user_func_array()
  ajax/dashboard.php:122                             Glpi\Dashboard\Grid->getCardHtml()
  
[2021-10-04 08:55:19] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7520
css/dashboard.scss is new, loading  {"user":"197@glpi"} 
[2021-10-04 08:55:19] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7520
css/palettes/flood.scss is new, loading  {"user":"197@glpi"} 
[2021-10-04 08:55:20] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/inc/html.class.php line 7520
css/styles.scss is new, loading  {"user":"197@glpi"} 
[2021-10-04 08:55:23] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Glpi\Dashboard\Provider::formatMonthyearDates() must be of the type string, null given, called in /var/www/html/glpi/inc/dashboard/provider.class.php on line 950 in /var/www/html/glpi/inc/dashboard/provider.class.php at line 1269
  Backtrace :
  inc/dashboard/provider.class.php:950               Glpi\Dashboard\Provider::formatMonthyearDates()
  :                                                  Glpi\Dashboard\Provider::getTicketsStatus()
  inc/dashboard/grid.class.php:1002                  call_user_func_array()
  ajax/dashboard.php:122                             Glpi\Dashboard\Grid->getCardHtml()
  
[2021-10-04 08:55:33] glpiphplog.WARNING: Test logger

**Comment by dmmario** [comment] 2021-10-04 07:26
this is a part of the file

**Comment by cedric-anne** [comment] 2021-10-04 07:29
This has nothing to do with you initial error.

Please provide the log corresponding to your initial error, i.e, try to reproduce and catch the log at this exact moment.

**Comment by dmmario** [comment] 2021-10-04 07:32
[2021-10-04 09:30:27] glpiphplog.ERROR:   *** PHP User Error (256): Trying to load a forbidden class name "0" in /var/www/html/glpi/inc/autoload.function.php at line 280
  Backtrace :
  inc/autoload.function.php:280                      trigger_error()
  :                                                  glpi_autoload()
  :                                                  spl_autoload_call()
  inc/dbutils.class.php:309                          is_subclass_of()
  inc/db.function.php:138                            DbUtils->getItemForItemtype()
  inc/search.class.php:6508                          getItemForItemtype()
  inc/search.class.php:1446                          Search::giveItem()
  inc/search.class.php:320                           Search::constructData()
  inc/search.class.php:95                            Search::getDatas()
  inc/search.class.php:80                            Search::showList()
  front/notificationtemplate.php:40                  Search::show()

**Comment by cedric-anne** [comment] 2021-10-04 07:42
I guess you have some invalid data in some of your `glpi_notification*` tables data. Some rows may have an invalid value `0` in `itemtype` column. This data should not exist, and you have to fix it manually.

This is not a bug, but certainly a corrupted data generated by a plugin, so I close this issue. To get support from community, please ope a thread on [community forum](https://forum.glpi-project.org/). You may also considere subscribing for [professionnal support](https://services.glpi-network.com/).

**Closed by cedric-anne** 2021-10-04 07:42 UTC
Labels: invalid

**Comment by dmmario** [comment] 2021-10-04 10:02
Thank you, I found the error. There was a value 0 in the db under glpi_notificationtemplates, putting the right value has disappeared error.

A thousand thanks





> Immagino che tu abbia alcuni dati non validi in alcuni dei `glpi_notification*`dati delle tue tabelle. Alcune righe potrebbero avere un valore non valido `0`nella `itemtype`colonna. Questi dati non dovrebbero esistere e devi correggerli manualmente.
> 
> Questo non è un bug, ma sicuramente un dato danneggiato generato da un plugin, quindi chiudo questo problema. Per ottenere supporto dalla community, apri un thread sul [forum della community](https://forum.glpi-project.org/) . Puoi anche prendere in considerazione la sottoscrizione di [un supporto professionale](https://services.glpi-network.com/) .
