### ISSUE TITLE
RAM is not accurate between OCS and GLPI 

### ISSUE THREAD

**Issue by fabien4455** [glpi-project/glpi#5676] opened 2019-03-25 15:12 UTC
Hello,

- The version of the plugin : 1.5.6 ( for GLPI 9.3.X ) 1.6.0 ( for GLPI 9.4.0 ) ( Tried 2 versions ) 

- The version of GLPI : 9.3.1 & 9.3.2 & 9.3.3 & 9.4.0 ( I tried 4 versions ) 

- The steps to reproduce my issue : 

1- Have a OCS 2.5 server with GLPI 9.3.X. 
2- Install 1.5.6 plugin
3- Import a computer in GLPI from OCS. The RAM will not be accurate. 

My real exemple with screenshots. 

I have a computer imported on OCS with 2.4.2 UNIX AGENT,
here is RAM info from OCS : 

![image](https://user-images.githubusercontent.com/22091839/51972521-d8e56380-247b-11e9-8159-5b4a7e414083.png)

See, i have 2 * 8 Go RAM sticks in the computer so 16 Go of RAM. 

![image](https://user-images.githubusercontent.com/22091839/51972601-0df1b600-247c-11e9-83ec-b79c2ecf6585.png)

If I go to GLPI and import my computer.. I have problems with RAM import. 

![image](https://user-images.githubusercontent.com/22091839/51972650-38437380-247c-11e9-84a7-91a7be608fda.png)

GLPI only report : one stick of RAM : 8 Go.

![image](https://user-images.githubusercontent.com/22091839/51972834-a0925500-247c-11e9-9668-a2ec25e0801f.png)

Also I have a computer that got 32 Go of RAM ( 4 * 8 Go sticks ) correctly showed in OCS, but in GLPI only 1 of them ( 1 * 8 Go ) is showed.. 

I've tried to downgrade to Glpi 9.2.2 and OCS plugin 1.4.4 with the same OCS server ( 2.5 ) and it's working perfectly fine...

**Comment by cedric-anne** [comment] 2019-03-25 15:27
Hi,

I am not sure, but it looks like the problem is that OCS plugin does not create a memory component having the good total size.
Please open a ticket on OCS plugin repository.

Regards

**Comment by fabien4455** [comment] 2019-03-25 16:58
Opened but they don't care....

1 month without any reply. 

Sorry about that

**Comment by trasher** [comment] 2019-03-25 17:00
If this is a plugin issue, we cannot fix anything, closing this one.

**Closed by trasher** 2019-03-25 17:00 UTC
