### ISSUE TITLE
GLPI 9.1.1 Can't change settings in network port

### ISSUE THREAD

**Issue by sebfun** [glpi-project/glpi#1349] opened 2016-11-25 14:56 UTC
Hi 
In GLPI 9.1.1 when I go in a network port associated to a computer or printer, I'm unable to change settings such as network outlet, Ethernet port type, speed, etc...
In the right corner of the page near "childs entities" words you hover with the mouse on the "i" and get "Can"t change this attribute. It's inherited from its parent".
Well I see that we can"t when it's on an automatic discover but I recreated it manually and it's same result even if I click on Save.

Any idea ?

thanks

**Comment by trasher** [comment] 2016-11-30 15:14
I think this is a duplicate of #1334 

Please try the proposed fix, and feel free to reopen if that does not solve your issue.

**Closed by trasher** 2016-11-30 15:14 UTC

**Comment by sebfun** [comment] 2016-11-30 15:23
Ok it's the same issue but I didn't see any proposed fix

**Comment by trasher** [comment] 2016-12-01 06:55
@sebfun see commit 7958557cc53208eb75f3f287f69da068676d6d66 ;)

**Comment by sebfun** [comment] 2016-12-01 07:03
thanks. Done and it works !
