### ISSUE TITLE
Problem with dashboard- Does not stretch cards

### ISSUE THREAD

**Issue by adrianonleitemao** [glpi-project/glpi#12777] opened 2022-09-27 10:48 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.3

### Bug description

Cards do not stretch vertically.
Version 10.0.0.2 did not have the problem.
See the reproduction of the error:
https://vimeo.com/754007800

### Page URL

/front/central.php

### Steps To reproduce

Install clean glpi;
login as glpi:glpi you will be at /front/central.php page;
open all dashboard;
observe broken dashboard.

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.3 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux coari-new 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at 172.17.131.135 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protected
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: '172.22.0.11', Port: '389', BaseDN: 'ou=SEMINF,ou=USERS,ou=DOMAIN,dc=manaus,dc=am,dc=gov,dc=br', Connection filter:
		none, RootDN: 'uid=adm_seminf,ou=PEOPLES,ou=SEMINF,ou=USERS,ou=DOMAIN,dc=manaus,dc=am,dc=gov,dc=br', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (seminf.ti@pmm.am.gov.br@172.17.100.5)

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.0     State: To update                               
		Install Method: Manual
	gappessentials       Name: Gapp Essentials                Version: 2.0.1      State: Not installed                           
		Install Method: Manual
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.10.0     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Manual
	satisfaction         Name: Mais satisfação                Version: 1.6.0      State: Installed / not activated               
		Install Method: Manual
	mydashboard          Name: Meu Painel                     Version: 2.0.4      State: Installed / not activated               
		Install Method: Manual
	dashboard            Name: Painel                         Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment] 2022-10-01 11:06
I'm not able to recreate the issue.
Can you check the browser console (F12 key > Console tab) for warnings/errors when you try to resize a dashboard card?

**Comment by redddcyclone** [comment] 2022-10-04 11:33
I have the same problem. No errors or warnings on the console. It happens to me when I select the Computers by Model card. Card does not stretch more than 3 squares vertically.

**Comment by adrianonleitemao** [comment] 2022-10-04 14:25
JQMIGRATE: Migrate is installed with logging active, version 3.4.0
rightclick.js:25 allow right click processing http://172.17.131.135/glpi/front/central.php
central.php:1          GET http://172.17.131.135/glpi/front/Roboto-Regular.ttf net::ERR_ABORTED 404 (Not Found)

This is the console error.

**Comment by adrianonleitemao** [comment] 2022-10-09 01:03
> Não consigo recriar o problema. Você pode verificar se há avisos/erros no console do navegador (tecla F12 > guia Console) ao tentar redimensionar um cartão do painel?

Ok??

**Comment by trasher** [comment] 2022-10-10 06:24
I've removes the comment that was not written in english.

**Comment by adrianonleitemao** [comment] 2022-10-10 10:17
> I'm not able to recreate the issue. Can you check the browser console (F12 key > Console tab) for warnings/errors when you try to resize a dashboard card?

good morning, so any new?

**Comment by FelipeBendetto** [comment] 2022-10-25 16:23
We have the same problem, do we have a solution for the same?

**Comment by Tartiflette-glpi** [comment] 2022-10-28 10:17
Hi,
I have the same problem, is a patch planned?

**Comment by cedric-anne** [comment] 2022-10-28 10:36
We are not able to reproduce, so it is quiet hard to provide a patch.

What browser are you using ?

**Comment by Tartiflette-glpi** [comment] 2022-10-28 12:22
Firefox up to date & Google Chrome, I have the same issue with Brave too
I had a GLPI 9.5.5 & migrated to 10.0.3, maybe the problem does appear when we upgrade GLPI

**Comment by redddcyclone** [comment] 2022-11-03 13:13
As of 10.0.4, the problem is solved for me. Thanks for the attention.

**Comment by cedric-anne** [comment] 2022-11-03 13:33
@adrianonleitemao @FelipeBendetto @Tartiflette-glpi 

Could you confirm that problem is solved in GLPI 10.0.4 ?

**Comment by Tartiflette-glpi** [comment] 2022-11-03 13:50
Fixed for the main admin Dashboard, but still broken for the user interface
Here is the view: https://ibb.co/xzBdnxx
It happen with Chrome, Firefox & Brave, even after refresh

**Comment by cedric-anne** [comment] 2022-11-03 13:59
Is this a view from the Formcreator plugin ?

**Comment by Tartiflette-glpi** [comment] 2022-11-03 14:07
> Is this a view from the Formcreator plugin ?

Ho, yes. my bad ! nvm
I'll check formcreator's git

Thanks

**Comment by cedric-anne** [comment] 2022-11-03 15:14
This is probably another issue.

**Comment by cedric-anne** [comment] 2022-11-03 15:15
I close this issue. Please create another issue.

**Closed by cedric-anne** 2022-11-03 15:15 UTC
Labels: Need feedback
