### ISSUE TITLE
Adding ticket not working everytime

### ISSUE THREAD

**Issue by JackBauer78** [glpi-project/glpi#10230] opened 2021-12-27 10:12 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Hello,

some of my team experience this annoying problem for a few months now :

1. We click on the "+" to add a ticket on the top left hand corner.
2. After we finished fill out the ticket, we click on the "add" button at the bottom and...
3. Nothing happen !

One of my colleagues who creates the most tickets can only create a few normally. The other times are exactly as I describ.
We didn't noticed a pattern in the apparition of the problem and why especially one of my colleagues has more than the others.

I migrated the server from Ubuntu 14.04 LTS to Debian 11 in September and I noticed myself the problem too.
I upgraded to the last version of GLPI 9.5.6 in October and I didn't notice it myself but I don't create ticket everyday, not like my colleague.

I thank you in advance for your help.

### Page URL

front/ticket.form.php

### Your GLPI setup information

GLPI 9.5.6 ( => /var/www/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux  5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64
PHP 7.4.21 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="15M" safe_mode="" session.save_handler="files"
	upload_max_filesize="15M" 
Software: Apache/2.4.51 (Debian) (Apache/2.4.51 (Debian) Server at glpi Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
Server Software: Debian 11
	Server Version: 10.5.12-MariaDB-0+deb11u1
	Server SQL Mode: 
	Parameters: 
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.5.12) - Perfect!Database version seems correct (10.5.12) - Perfect!

The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.Write access to /var/www/glpi/files/_uploads has been validated.
Write access to /var/www/glpi/marketplace has been validated.Write access to /var/www/glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

GLPI constants
 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /var/www/glpi/config
GLPI_VAR_DIR: /var/www/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/glpi/files
GLPI_CACHE_DIR: /var/www/glpi/files/_cache
GLPI_CRON_DIR: /var/www/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/glpi/files/_lock
GLPI_LOG_DIR: /var/www/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 9.5.6
GLPI_SCHEMA_VERSION: 9.5.6
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2021

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/marketplace/metabase/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/marketplace/metabase/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

LDAP directories
 
Server: '', Port: '389', BaseDN: '', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: '', Use TLS:
		none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP 

Plugins list
 
	fields               Name: Champs supplémentaires         Version: 1.12.8     State: Installed / not activated
	behaviors            Name: Comportements                  Version: 2.5.0      State: Installed / not activated
	mydashboard          Name: Dashboard                      Version: 1.8.2      State: Installed / not activated
	datainjection        Name: Data Injection                 Version: 2.9.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.12.3     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled
	manufacturersimports Name: Imports fabricants             Version: 2.3.1      State: Enabled
	pdf                  Name: Impression pdf                 Version: 2.0.0      State: Enabled
	metabase             Name: metabase                       Version: 1.2.3      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.7.3      State: Enabled
	reports              Name: Rapports                       Version: 1.14.1     State: Enabled
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Installed / not activated
	vip                  Name: VIP                            Version: 1.7.2      State: Enabled

**Comment by cconard96** [comment] 2021-12-27 14:28
Please include any entries from the `files/_log/php-errors.log` and `files/_log/sql-errors.log` files from the time you couldn't create the ticket(s).

**Comment by CorentinS6** [comment] 2022-01-04 10:07
Hello,
You're using behaviors, linked to https://github.com/yllen/behaviors/issues/4 ?
Regards

**Comment by trasher** [comment] 2022-01-31 13:47
No feedback, closing.

**Comment by JackBauer78** [comment] 2022-02-03 10:41
I'm sorry for the delay.

I did some tests in real time and nothing was writing in `files/_log/php-errors.log`, `files/_log/sql-errors.log` and the apache error file.
When I launched the Chrome dev tools, I saw this error each time I click and the + button : **An invalid form control with name='content' is not focusable.**
I deleted the `é` and `è` from the ticket content and I could create the ticket, maybe it's a lead.
I didn't make any upgrade of GLPI and its plugins since I first posted.

**Comment by cedric-anne** [comment] 2022-02-14 07:45
This error is related to the `description` field validation, and may be due to an edge case. Your browser triggers an error because it considers that the field that should be validated (i.e. the `description` field) cannot be focused. As this field is replaced by a tinyMCE instance, I guess we have some code dedicated to this validation that is not working in your specific case.
Maybe it depends on the hidden/mandatory/hidden fields of the ticket template used.

**Comment by JackBauer78** [comment] 2022-04-22 13:11
> This error is related to the `description` field validation, and may be due to an edge case. Your browser triggers an error because it considers that the field that should be validated (i.e. the `description` field) cannot be focused. As this field is replaced by a tinyMCE instance, I guess we have some code dedicated to this validation that is not working in your specific case. Maybe it depends on the hidden/mandatory/hidden fields of the ticket template used.

The description field is a indeed a mandatory field but it has been for years now.
And we only have a problem for a few months.
Maybe the code validating the field has a problem for our case because of some characters.
How can we debug this problem ?

**Comment by cedric-anne** [comment] 2022-04-22 13:17
> How can we debug this problem ?

I do not know.

Can you try to reproduce on GLPI 10.0 ?

**Comment by cedric-anne** [comment] 2022-05-30 06:54
Hi,

I close this issue as I consider it has been solved in GLPI 10.0.

**Closed by cedric-anne** 2022-05-30 06:54 UTC
