### ISSUE TITLE
List of items in a  supplier

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1522] opened 2017-01-05 13:48 UTC
*** MySQL query error:
  SQL: SELECT `glpi_infocoms`.`entities_id`, `name`, `glpi_items_devicecontrols`.*
                      FROM `glpi_infocoms`
                      INNER JOIN `glpi_items_devicecontrols` ON (`glpi_items_devicecontrols`.`id` = `glpi_infocoms`.`items_id`) WHERE `glpi_infocoms`.`itemtype` = \'Item_DeviceControl\'
                             AND `glpi_infocoms`.`suppliers_id` = \'693\' AND ( `glpi_items_devicecontrols`.`entities_id` IN (\'1\', \'332\')  ) 
                       ORDER BY `glpi_infocoms`.`entities_id`,
                                `glpi_items_devicecontrols`.`name`
  Error: Unknown column 'name' in 'field list'

Item_device* have no name in database

And possibility to distinct template from object (different color) or only list object
http://forum.glpi-project.org/viewtopic.php?id=156331

**Comment by trasher** [comment] 2017-01-12 13:07
I cannot reproduce; maybe this has been fixed from another bug. If this is not fixed in the current 9.1/bugfixes, feel free to reopen and indicate how to reproduce.

Another ticket has been opened for the feature (#1602).

**Comment by yllen** [comment] 2017-01-25 15:52
Test done today in 9.1.2 and still present.
You have this error if you list items from a supplier recursive from root entity and you are in a sub-entity

**Comment by trasher** [comment] 2017-01-25 15:56
OK thanks for the details; I'll try again

**Comment by trasher** [comment] 2017-04-19 13:21
Still cannot reproduce :/

I've created a supplier in root entiy, with child entities set to yes.

I have 3 computers, all linked to the supplier. One is in the root entitiy, second is in _test_root_entity and third is _test_child_1 (under _test_root_entity).

Then, if i switch to _test_root_entity without children; items in supplier gives me one result; that is ok.
If I switch to same entity with children, I get 2 results, and nothing in logs.

**Comment by trasher** [comment] 2017-04-19 14:14
Ok found it... The error in the logs appears when you activate infocom on a device component (at last).

**Closed** 2017-04-20 13:45 UTC
Labels: bug
