### ISSUE TITLE
One satisfaction survey by user

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#570] opened 2016-04-06 06:31 UTC
The satisfaction survey must be generated for each user of the ticket who answers because currently they update the same record
![image](https://cloud.githubusercontent.com/assets/15769828/14307533/140e5b1a-fbd0-11e5-92bc-33b168cd9373.png)

**Comment by yllen** [comment] 2016-04-06 13:37
Who are User 2 and User 1? requester of the ticket? member of a requester group? author of the ticket?

**Comment by jsamaniegog** [comment] 2016-04-07 06:09
User 1 open the ticket. The requester is User 2.
User 1 assigns the task to himself.
User 1 solve the ticket.
User 1 close the ticket.
User 1 answer the satisfaction survey (Change by 5).
User 2 answer the satisfaction survey (Change comments and change 5 by 4).

**Comment by yllen** [comment] 2016-04-07 11:31
If a user is the author or the requester of a ticket he can reply to survey.
But if a reply is already done, you can change the survey only during 12 hours (for mistake).
On next version you have a new parameter in profil to allow or not the author of the ticket to reply to survey.

**Comment by jsamaniegog** [comment] 2016-04-07 12:15
Ok but, in this case, the requester and the author is editing the same record in database, i thik that each user must be fill his own survey.

**Comment by yllen** [comment] 2016-04-07 13:22
For a ticket you only have 1 survey generated

**Comment by jsamaniegog** [comment] 2016-04-08 06:03
Yes, for that reason I'm asking one per user.

**Comment by yllen** [comment] 2016-04-08 12:08
You can't have several survey for one ticket. The survey is generated only one time

**Comment by jsamaniegog** [comment] 2016-04-08 12:22
Why not?, if the program send the survey to several users is logical that each user complete their own survey.

**Comment by yllen** [comment] 2016-04-08 15:35
The problem is that the survey is generated only one time, when the ticket is closed.
If you want several answers you must generate several surveys (like for validation). And for who do you generated these surveys? Author + requester + all member of group requester?

**Comment by jsamaniegog** [comment] 2016-04-11 07:31
All the people that you are currently sending surveys, author and requesters if I'm not mistaken.

**Comment by tomolimo** [comment] 2016-04-12 07:26
Hello,
If you have several surveys per ticket, how do you manage the results?
Which mark will really represents the ticket resolution quality?
Thank you
Regards,
Tomolimo

**Comment by jsamaniegog** [comment] 2016-04-12 12:46
Hello tomolimo,

> If you have several surveys per ticket, how do you manage the results?

Each user only can to complete their survey. Everyone should be able to see all surveys, but only edit their own survey.

> Which mark will really represents the ticket resolution quality?

It will be the average of the ratings.

---

However, if you want to make it simple it would be enough send the survey to a single user, for example the author or the first requester (if isn't technician like i said in this issue: https://github.com/glpi-project/glpi/issues/474).

Regards!

**Comment by tomolimo** [comment] 2016-04-12 13:03
> It will be the average of the ratings.

This needs to be discussed as I'm sure that it will not fit all needs :smile:

**Comment by orthagh** [comment] 2016-04-20 13:46
Hello @jsamaniegog 

Thank you for your proposal.

As described by @tomolimo, it may not fit all organization if we do only an average grouping.
You can add an entry in [suggest site](https://suggest.glpi-project.org) to open discussion.

Also, code in PR for this need should be accepted if enough flexible.
I close this issue.

**Closed by orthagh** 2016-04-20 13:46 UTC
