### ISSUE TITLE
[9.4.5] Cannot add a followup via REST API

### ISSUE THREAD

**Issue by Aleksiv95** [glpi-project/glpi#6965] opened 2020-02-23 15:50 UTC
**Describe the bug**

Trying to add any followups via REST API results in "You don't have permission to perform this action". Adding a new followup using the web interface works as expected.

**Page(s) URL**

`/apirest.php/Ticket/:id:/ITILFollowup`

**To reproduce**

Ensure that the active profile is `Super-Admin` (or any profile with permissions to add followups):

```
GET /apirest.php/getActiveProfile HTTP/1.1
Host: glpi.********.com
Session-Token: ********
App-Token: ********
```

Response:

```
{
    "active_profile": {
        "id": 4,
        "name": "Super-Admin",
...
```

Ensure that the ticket exists with given ID and it has followups:

```
GET /apirest.php/Ticket/1466/ITILFollowup HTTP/1.1
Host: glpi.********.com
Session-Token: ********
App-Token: ********
```

Response:

```
[
    {
        "id": 7638,
        "itemtype": "Ticket",
        "items_id": 1466,
...
```

Create a followup:

```
POST /apirest.php/Ticket/1466/ITILFollowup HTTP/1.1
Host: glpi.********.com
Session-Token: ********
App-Token: ********
Content-Type: application/json

{"input":{"tickets_id": "1466", "is_private": "0", "requesttypes_id": "1", "content": "Followup contents"}}
```

Response:

```
[
    "ERROR_GLPI_ADD",
    "You don't have permission to perform this action."
]
```

**Expected behavior**

A new followup is added and a response with HTTP status code 200 is returned.

**Logs**

No related logs in `event.log` or `php-errors.log`, except for:

```
2020-02-23 12:34:19 [@********]
[login] 3: ******** login from IP ***.***.***.***
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.5-git-********-9.4.5-e1f1e431c ( => ********)
Installation mode: GIT

Server
 
Operating system: Linux ******** 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64
PHP 7.2.24-0ubuntu0.18.04.3 apache2handler (Core, PDO, PDO_Firebird, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, bcmath, bz2, calendar, ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp,
	hash, iconv, imap, interbase, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_dblib, pdo_mysql,
	pdo_pgsql, pdo_sqlite, pgsql, posix, pspell, readline, recode, session, shmop, snmp, soap, sockets, sodium, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at glpi.********.com Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.29-0ubuntu0.16.04.1-log
	Server SQL Mode: 
	Parameters: ********
	Host info: ******** via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
exif extension is installed
APCu extension is not present
CAS extension is not present
Database version seems correct (5.7.29) - Perfect!Database version seems correct (5.7.29) - Perfect!
OK/********/files/_log : OK
OK/********/config : OK
OK/********/files : OK
OK/********/files/_dumps : OK
OK/********/files/_sessions : OK
OK/********/files/_cron : OK
OK/********/files/_graphs : OK
OK/********/files/_lock : OK
OK/********/files/_plugins : OK
OK/********/files/_tmp : OK
OK/********/files/_cache : OK
OK/********/files/_rss : OK
OK/********/files/_uploads : OK
OK/********/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.2.4 in (/********/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/********/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/********/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/********/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/********/vendor/michelf/php-markdown/Michelf)
true/punycode in (/********/vendor/true/punycode/src)
iamcal/lib_autolink in (/********/vendor/iamcal/lib_autolink)
sabre/vobject in (/********/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/********/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/********/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/********/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/********/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/********/vendor/sebastian/diff/src)
elvanto/litemoji in (/********/vendor/elvanto/litemoji/src)
symfony/console in (/********/vendor/symfony/console)
leafo/scssphp in (/********/vendor/leafo/scssphp/src)

LDAP directories
 
Server: '********', Port: '389', BaseDN: '********', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(memberof=CN=********))', RootDN:
		'CN=********', Use TLS: '1'

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+TLS (********)

Mails receivers
 
Name: '********' Active: Yes
	Server: '{********}Inbox' Login: '********'
		Password: Yes

Plugins list
 
	fields               Name: Additional Fields              Version: 1.10.0     State: Enabled
```

**Comment by cconard96** [comment] 2020-02-23 20:34
Instead of "tickets_id" in the ITILFollowup input, try using:
"itemtype": "Ticket"
"items_id": "1466"

Since 9.4.0 the followup class is shared between Tickets, Changes, and Problems so you need to specify the type of item you are making the followup for.

**Comment by trasher** [comment] 2020-02-24 07:10
This is not a bug, closing

**Closed by trasher** 2020-02-24 07:10 UTC
