### ISSUE TITLE
[0.90.3] Can't check for update

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#693] opened 2016-05-31 08:10 UTC
Renew the issue: [#656](https://github.com/glpi-project/glpi/issues/656)

Can't check for update on server

![glpi - maintenance - google chrome 2016-05-17 15 14 27](https://cloud.githubusercontent.com/assets/17082164/15321908/30c7de56-1c42-11e6-99ef-96dd6334778c.png)

I tested to check for update of GLPI:

By [fix check of new releases](https://github.com/glpi-project/glpi/commit/a4177b933233185526a4766df86fae52a15ebe4c)

So  works:
`toolbox.class.php:1375` set:

`$latest_version = self::getURLContent("http://glpi-project.org/latest_version", $error);`

Error 501 of the proxy Squid3 - it's error of a server failure

**Comment by orthagh** [comment] 2016-06-03 15:21
Hello @AircraftRu 

Could you precise your issue.

In fact, githhub url is the best way to check new version as we release here.
http://glpi-project.org/latest_version is manually updated and can be forgotten.

The code you mention should use the proxy configuration set up in setup > general, system tab

**Comment by AircraftRu** [comment] 2016-06-06 07:07
When the code of check on GitHub, then displays this error.

**Comment by AircraftRu** [comment] 2016-09-15 12:58
Squid 3.5.12 logs write a message when cheking updates:
`1473943959.453      0 192.168.40.68 TAG_NONE/501 4069 GET https://api.github.com/repos/glpi-project/glpi/releases - HIER_NONE/- text/html`

**Comment by AnaelMobilia** [comment] 2017-01-03 18:01
@AircraftRu 
Hello,

Does the issue still occurs ?

If yes, could you, please, give me a little detail on your proxy configuration in order to trying to reproduce the bug ?

Regards,
Anael

**Comment by AircraftRu** [comment] 2017-01-03 22:53
Yes, everything else is going on.
Unfortunately no longer I can send you a proxy configuration. But settings were almost by default.

**Comment by trasher** [comment] 2017-01-19 13:33
See proposed solution in #1660.

Closing as duplicate of #1335

**Closed by trasher** 2017-01-19 13:33 UTC
