### ISSUE TITLE
Users sync constantly

### ISSUE THREAD

**Issue by emaw705** [glpi-project/glpi#6914] opened 2020-02-06 14:17 UTC
Hi!

I have detected a problem with users sync with AD.

All users active in AD are sync each minute.

For test, I renamed the script ldap_mass_sync.php to ldap_mass_sync2.php and the sync stop.

In the cron config I don't have anything to tell GLPI that this script runs each minute.

I'm using GLPI 9.4.3 with Debian 9 and PHP 7.3.

Best regards!

**Comment by cedric-anne** [comment] 2020-02-06 14:27
Hi,

Nothing in GLPI tells this script to run each minute. So if it runs, then you may have something in your system that is responsible of it.

As this is not a bug, I close this issue. Feel free to ask for community support on [forums](https://forum.glpi-project.org/).

Regards

**Closed by cedric-anne** 2020-02-06 14:27 UTC
