### ISSUE TITLE
Associated items in new ticket 

### ISSUE THREAD

**Issue by pamescan** [glpi-project/glpi#1286] opened 2016-11-11 10:08 UTC
Hello:

No items shows in associated items dropdown at the first time load ticket template.
![image](https://cloud.githubusercontent.com/assets/6113771/20211311/2c21653c-a7fe-11e6-99a6-eb735b10c13f.png)
![image](https://cloud.githubusercontent.com/assets/6113771/20211371/8083554a-a7fe-11e6-8584-07cd7ad78d6b.png)
When I click on Categories dropdown (1) and change the template then the items dropdown appears

![image](https://cloud.githubusercontent.com/assets/6113771/20211429/c8851ef0-a7fe-11e6-814e-a24250bbe0cc.png)

If in the default template I hide too many items then I must change Categories two times until the items dropdown appears

**Comment by orthagh** [comment] 2016-11-14 10:24
Hello @pamescan 

Could you provide the following information:
- glpi version
- In Administration > Profiles, displays the used profile and return me the configuration set in the Assistance tab, part Association

Thank you

**Comment by pamescan** [comment] 2016-11-15 14:48
Hello @orthagh 

Version  is 9.1

![image](https://cloud.githubusercontent.com/assets/6113771/20310022/9f6be2e8-ab4a-11e6-8fc2-0df2d22e107a.png)
![image](https://cloud.githubusercontent.com/assets/6113771/20310067/cca0de44-ab4a-11e6-845f-7c41dcbdfed1.png)


Thank you

**Comment by trasher** [comment] 2017-04-24 10:42
Hello,

I've just tested with current 9.1/bugfixes; and I'm not able to reproduce.

I guess this is fixed in 9.1.3; feel free to reopen if not.

**Closed by trasher** 2017-04-24 10:42 UTC
