### ISSUE TITLE
Last Update show 5 hours more - GLPI v0.90.3 

### ISSUE THREAD

**Issue by gituncar** [glpi-project/glpi#614] opened 2016-04-19 19:32 UTC
Hi, with last version, when update some items, show 5 hours more on column last update.
![image 4](https://cloud.githubusercontent.com/assets/7705197/14652775/7af7f136-063b-11e6-9915-c5038c2ee08e.png)

**Comment by orthagh** [comment] 2016-04-20 13:07
I do not reproduce your issue (in documents list like your screenshot).

Did you only updated the version of your glpi, no system or server updates ?

Can, you check the date/time on your system (server) ?
Also, did your php config contains the right timezone ?

**Comment by orthagh** [comment] 2016-05-27 09:34
No answer since days, i close this issue.
Feels free to reopen and comment.

**Closed by orthagh** 2016-05-27 09:34 UTC
