### ISSUE TITLE
Very large table glpi_ipaddresses_ipnetworks

### ISSUE THREAD

**Issue by Spleeff** [glpi-project/glpi#16534] opened 2024-02-08 16:33 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.12

### Bug description

The glpi_ipaddresses_ipnetworks table is larger than 35 GB. Is there anything to do to reduce the size of this table ?

### Relevant log output

```shell
No errors are available in the different logs
```

**Comment by trasher** [comment] 2024-02-08 17:55
We need more information.

**Comment by Spleeff** [comment] 2024-02-08 18:45
Of course, what information do you need ?

**Comment by cconard96** [comment] 2024-02-08 20:38
On its own, the question of how to reduce the size of the table, is more of a support question rather than a report of an issue with GLPI. For that, the question would usually be redirected to the community forum as it would be a question of general database maintenance and how InnoDB stores the data for tables (it doesn't automatically shrink the data files when rows are deleted).

However, unless you have a very large environment and/or have been using GLPI for many years it seems odd that this table would have gotten to this point and it may indicate a bug. Under the assumption GLPI is creating far more records in this table than necessary, some information about your environment would be needed. I'm not sure of the full list since I don't usually work on this part of GLPI, but I think this is a good start:

- What is your GLPI setup information (Setup > General > System tab)? This would give us some details about your PHP version/config, database server, installed plugins, and some other general information. We ask for this for all issues reported on GitHub.
- Are there any entries in the GLPI server logs that seem relevant (files/_log folder)? Again, this is asked for all issue reports. Even if it may not seem relevant in this case, if there is indeed something relevant in those logs it could save us a lot of time.
- How many rows are actually in the database table currently?
```sql
SELECT COUNT(`id`) FROM `glpi_ipaddresses_ipnetworks`
```
- Are you using the GLPI agent or some other solution to perform automatic inventory?
- Approximately how many assets do you have (does the number of current rows in that table make sense)?
- Do you notice any signs of IP addresses, network ports, or other related items being deleted and recreated or duplicated unnecessarily (check historical tabs)?
- Do you have any idea if this suddenly became an issue recently or was a progressive issue over a long period of time? Or was the size growing a lot in the past but seems like it isn't growing much anymore?

**Comment by Spleeff** [comment] 2024-02-14 19:36
**GLPI Setup Information :** 
<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.12 ( => E:\Site\glpi-prod)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Windows NT GLPIServer 10.0 build 20348 (Windows Server 2022) AMD64
PHP 8.2.15 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	random, readline, session, soap, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.36
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost:3306/glpi-prod
	Host info: localhost via TCP/IP
	
PHP version (8.2.15) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.36) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to E:\Site\glpi-prod/files/_cache has been validated.
Write access to E:\Site\glpi-prod/files/_cron has been validated.
Write access to E:\Site\glpi-prod/files has been validated.
Write access to E:\Site\glpi-prod/files/_dumps has been validated.
Write access to E:\Site\glpi-prod/files/_graphs has been validated.
Write access to E:\Site\glpi-prod/files/_lock has been validated.
Write access to E:\Site\glpi-prod/files/_pictures has been validated.
Write access to E:\Site\glpi-prod/files/_plugins has been validated.
Write access to E:\Site\glpi-prod/files/_rss has been validated.
Write access to E:\Site\glpi-prod/files/_sessions has been validated.
Write access to E:\Site\glpi-prod/files/_tmp has been validated.
Write access to E:\Site\glpi-prod/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to E:\Site\glpi-prod/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "E:\\Site\\glpi-prod"
GLPI_CONFIG_DIR: "E:\\Site\\glpi-prod/config"
GLPI_VAR_DIR: "E:\\Site\\glpi-prod/files"
GLPI_MARKETPLACE_DIR: "E:\\Site\\glpi-prod/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "E:\\Site\\glpi-prod/files"
GLPI_CACHE_DIR: "E:\\Site\\glpi-prod/files/_cache"
GLPI_CRON_DIR: "E:\\Site\\glpi-prod/files/_cron"
GLPI_DUMP_DIR: "E:\\Site\\glpi-prod/files/_dumps"
GLPI_GRAPH_DIR: "E:\\Site\\glpi-prod/files/_graphs"
GLPI_LOCAL_I18N_DIR: "E:\\Site\\glpi-prod/files/_locales"
GLPI_LOCK_DIR: "E:\\Site\\glpi-prod/files/_lock"
GLPI_LOG_DIR: "E:\\Site\\glpi-prod/files/_log"
GLPI_PICTURE_DIR: "E:\\Site\\glpi-prod/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "E:\\Site\\glpi-prod/files/_plugins"
GLPI_RSS_DIR: "E:\\Site\\glpi-prod/files/_rss"
GLPI_SESSION_DIR: "E:\\Site\\glpi-prod/files/_sessions"
GLPI_TMP_DIR: "E:\\Site\\glpi-prod/files/_tmp"
GLPI_UPLOAD_DIR: "E:\\Site\\glpi-prod/files/_uploads"
GLPI_INVENTORY_DIR: "E:\\Site\\glpi-prod/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "E:\\Site\\glpi-prod/locales"
GLPI_VERSION: "10.0.12"
GLPI_SCHEMA_VERSION: "10.0.12@b902ef5f5da967c1a9d0826ee8a7dce07d57cf3d"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (E:\Site\glpi-prod\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.8.0 in (E:\Site\glpi-prod\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (E:\Site\glpi-prod\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.6.2 in (E:\Site\glpi-prod\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (E:\Site\glpi-prod\vendor\michelf\php-markdown\Michelf)
true/punycode in (E:\Site\glpi-prod\vendor\true\punycode\src)
iamcal/lib_autolink in (E:\Site\glpi-prod\vendor\iamcal\lib_autolink)
sabre/dav in (E:\Site\glpi-prod\vendor\sabre\dav\lib\DAV)
sabre/http in (E:\Site\glpi-prod\vendor\sabre\http\lib)
sabre/uri in (E:\Site\glpi-prod\vendor\sabre\uri\lib)
sabre/vobject in (E:\Site\glpi-prod\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (E:\Site\glpi-prod\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (E:\Site\glpi-prod\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (E:\Site\glpi-prod\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (E:\Site\glpi-prod\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (E:\Site\glpi-prod\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (E:\Site\glpi-prod\vendor\elvanto\litemoji\src)
symfony/console in (E:\Site\glpi-prod\vendor\symfony\console)
scssphp/scssphp in (E:\Site\glpi-prod\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (E:\Site\glpi-prod\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (E:\Site\glpi-prod\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (E:\Site\glpi-prod\vendor\rlanvin\php-rrule\src)
ramsey/uuid in (E:\Site\glpi-prod\vendor\ramsey\uuid\src)
psr/log in (E:\Site\glpi-prod\vendor\psr\log\Psr\Log)
psr/simple-cache in (E:\Site\glpi-prod\vendor\psr\simple-cache\src)
psr/cache in (E:\Site\glpi-prod\vendor\psr\cache\src)
league/csv in (E:\Site\glpi-prod\vendor\league\csv\src)
mexitek/phpcolors in (E:\Site\glpi-prod\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (E:\Site\glpi-prod\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (E:\Site\glpi-prod\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (E:\Site\glpi-prod\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (E:\Site\glpi-prod\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (E:\Site\glpi-prod\vendor\paragonie\sodium_compat\src)
symfony/cache in (E:\Site\glpi-prod\vendor\symfony\cache)
html2text/html2text in (E:\Site\glpi-prod\vendor\html2text\html2text\src)
symfony/css-selector in (E:\Site\glpi-prod\vendor\symfony\css-selector)
symfony/dom-crawler in (E:\Site\glpi-prod\vendor\symfony\dom-crawler)
twig/twig in (E:\Site\glpi-prod\vendor\twig\twig\src)
twig/string-extra in (E:\Site\glpi-prod\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (E:\Site\glpi-prod\vendor\symfony\polyfill-php82)
league/oauth2-client in (E:\Site\glpi-prod\vendor\league\oauth2-client\src\Provider)
league/oauth2-google in (E:\Site\glpi-prod\vendor\league\oauth2-google\src\Provider)
thenetworg/oauth2-azure in (E:\Site\glpi-prod\vendor\thenetworg\oauth2-azure\src\Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'LDAP-Srv.domain.local', Port: '389', BaseDN: 'OU=User Accounts,OU=Paris,OU=FR,OU=Country,DC=dom,DC=domain,DC=local',
		Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'dom\GLPILookup', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@)

</pre></details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alerts                         Version: 1.12.1     State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.13.4     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Installed / not activated               
		Install Method: Manual
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: More Reporting                 Version: 1.8.6      State: Enabled                                 
		Install Method: Manual
	mydashboard          Name: My Dashboard                   Version: 2.1.5      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Manual
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Enabled                                 
		Install Method: Manual

</pre></details>
**GLPI server logs** : A lot of "glpiphplog.WARNING: Test logger" message

**Rows count :** 385405648

**Use of GLPI Agent** : Not GLPI agent (it is planned) it was FusionInventory in the past

**Number of assets :** 6807 Computers /  10248 Monitors / 64913 Software / 17037 Devices / 1088 Printers / 765 Phones 

**Duplicate IP addresses** : By going to "Assets" > "Network Names" I can see a significant number of duplicate addresses. Does this answer the question ?

**Start of the issue**: I think that this is a table that has grown gradually and that my predecessors did not investigate


Many thanks for your support/help

**Comment by trasher** [comment] 2024-02-15 06:39
OK; there is indeed something that's not working well, but it's clearly due to fusion inventory plugin; maybe something that's already been fixed on their side; that's very hard to say. GLPI itself did not seems to do anything wrong (it does not creates IP on the fly :))

Until native inventory still grows your IP addresses table; there is not much we can fix.

About cleaning existing data; that's far out of the scope of a community support; there are too many data. 
Maybe a way would be to remove all IPs/NetworkNames/... and let your inventory recover proper data? Maybe could you try that on a test instance to inspect.
If you do not rely on IPs, that may not be a problem at all.

Note if you use fusioninventory plugin to do that and see issues; that's something to report on their side. Open an issue here only if you can reproduce with GLPI >10 native inventory along with glpiinventory plugin.

**Comment by trasher** [comment] 2024-02-15 08:14
I'll close this one since there is no bug core side here. Feel free to open a new one if you have the same issue using native inventory.

**Closed** 2024-02-15 08:14 UTC
Labels: support
