### ISSUE TITLE
Empty solution description

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#2378] opened 2017-06-28 16:56 UTC
Dear All,
I recently upgraded to glpi 9.14. I have a question. If I click on save without any input in solution description field. It creates a new update instead of solving the ticket and sends notification regarding update of ticket. Has anyone come across such issue or am I the only one

**Comment by roshanroche** [comment] 2017-06-30 19:59
Anyone please?

**Comment by trasher** [comment] 2017-07-03 08:01
I cannot reproduce. Saving a solution empty does nothing. If I leave description empty and select a type, ticket is closed as expected.

**Comment by trasher** [comment] 2017-07-03 08:03
Also, check in you log files for any interesting extra info.

**Comment by roshanroche** [comment] 2017-07-03 14:35
Dear trasher,
Yes in 9.1.2 version I had no issues. But I feel since update to 9.1.4 I noticed it. When u just click on save button below description field without entering anything it refreshes the page and a ticket update notification is sent. I checked all the logs but didn't find anything conclusive. Fresh install of glpi also I tried. Same behaviour.

**Comment by roshanroche** [comment] 2017-07-18 16:27
Dear @trasher  I installed 9.1.5 version but still the issue remains. With an empty solution description if I click save , page refreshed and an update ticket notification is sent. How to avoid this false update ticket notification? And this is a fresh install of  glpi on Centos.

**Comment by trasher** [comment] 2017-09-15 12:10
Indeed... A notification is sent; I was focusing on the initial issue description, and not on your last comments :)

**Closed** 2017-09-15 14:08 UTC
Labels: bug

**Comment by roshanroche** [comment] 2017-09-15 14:11
Dear @trasher ,
Thanks for the reply. I will check this commit and update you.
