### ISSUE TITLE
[10.0.7] empty list templates solution and no html in traking

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#14774] opened 2023-05-24 13:19 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Good morning,
since the migration in 10.0.7
-  I don’t have the empty list templates anymore do you have any idea? 
- I no longer have the possibility to put html in the tracking? Thanks to you

**Comment by cedric-anne** [comment] 2023-05-24 13:25
Hi,

I do not even understand what can be your issue. Can you please give more information about it? At least, put some screenshots and provide your GLPI system information.

**Comment by cedric-anne** [comment] 2023-05-24 13:32
Could you check your browser console to see if there is a javascript error? In such case, could you try to empty your browser cache to see if problem persist? Also, could you try to reproduce with no active plugins?

**Comment by falco2001** [comment] 2023-05-24 13:40
same in private navigation: without cache ...

**Comment by cedric-anne** [comment] 2023-05-24 14:39
Do you have a javascript error ?

**Comment by falco2001** [comment] 2023-05-24 15:04
nothing in the logs. No javascript errors.
When I click on the template information I have "No items found"?
How to restore them?

**Comment by cedric-anne** [comment] 2023-05-24 16:12
It seems that you have no followup templates. Is there something in the `glpi_itilfollowuptemplates` database table?

**Comment by cedric-anne** [comment] 2023-05-25 07:12
I cannot reproduce your issue.

If there is no javascript error, no PHP error, no SQL error, ... We will never be able to investigate. Also, you tend to provide sparse information or make ambiguous/inaccurate sentences, which really does not help.

Unless you provide some information that can really help to reproduce, I will not go to spend more time there.

**Comment by falco2001** [comment] 2023-05-25 07:19
Il s'agit bien su gabarit de solution qui d'affiche dans le menu à droite mais rien dans le cadre de gauche .
Comment résoudre ceci ? Merci
![image](https://github.com/glpi-project/glpi/assets/31952346/397359bd-1869-46a1-881c-ef4da9e316ea)

**Comment by falco2001** [comment] 2023-05-25 07:37
Do you have an idea to display the html response bar in the follow-ups?

**Comment by falco2001** [comment] 2023-05-31 07:27
Good morning,
Do you have an idea for the htm code in the tracking?
do you have an idea for bug templates in solutions? Do I have to look in javascript, php or sql?
MErci

**Comment by falco2001** [comment] 2023-05-31 13:22
When I click on the templates nothing happens, however there are many templates in base ...
For html I don’t have the html banner in the tracking? 
Merci

**Comment by cedric-anne** [comment] 2023-05-31 13:32
Still not able to reproduce.

This feature is used by many people and no one complained about a bug on it.

IMHO, you have an javascript error somewhere. Could you check again your browser console to see if there is any error? Last time you gave a screenshot of the network panel, but JS errors are usually located on `Console` panel of browser developer tools.

**Comment by falco2001** [comment] 2023-06-02 09:43
Failed to initialize the editor as the document is not in standards mode. TinyMCE requires standards mode. [tinymce.js:19028](webpack://glpi/glpi/node_modules/tinymce/tinymce.js)
    initError tinymce.js:19028
    findTargets tinymce.js:29722
    initEditors tinymce.js:29752
    executeHandlers tinymce.js:4017
    defaultNativeHandler tinymce.js:3839
    readyHandler tinymce.js:3812
    bindOnReady tinymce.js:3817
    bind tinymce.js:3886
    bind tinymce.js:4672
    init tinymce.js:29771
    <anonyme> ticket.form.php:9
    jQuery 2
        mightThrow
        process
and
jQuery.Deferred exception: this.editor is null register@https://assistance.ens-lyon.fr/js/RichText/UserMention.js?v=7c637cabf5ecb12e09ea2d4f74b85c8d03c53406:66:9
@https://assistance.ens-lyon.fr/front/ticket.form.php?id=134102 line 21410 > injectedScript:9:29
mightThrow@https://assistance.ens-lyon.fr/public/lib/base.js?v=7c637cabf5ecb12e09ea2d4f74b85c8d03c53406:25043:29
480/</Deferred/then/resolve/</process<@https://assistance.ens-lyon.fr/public/lib/base.js?v=7c637cabf5ecb12e09ea2d4f74b85c8d03c53406:25111:12
 undefined

**Comment by cedric-anne** [comment] 2023-06-02 11:45
What browser are you using ?

Can you take a screenshot of the first lines of the source code of the page on which you have this bug ?
E.g.
![image](https://github.com/glpi-project/glpi/assets/33253653/41fec69f-31c1-4a17-a0b6-9f55e70701ca)

**Comment by falco2001** [comment] 2023-06-02 11:56
here is : 
`<script type="text/javascript" src="[/../../../lib/extjs/adapter/ext/ext-base.js?v=7c637cabf5ecb12e09ea2d4f74b85c8d03c53406](view-source:https://assistance.ens-lyon.fr/lib/extjs/adapter/ext/ext-base.js?v=7c637cabf5ecb12e09ea2d4f74b85c8d03c53406)"></script><script type="text/javascript" src="[/../../../lib/extjs/ext-all-debug.js?v=7c637cabf5ecb12e09ea2d4f74b85c8d03c53406](view-source:https://assistance.ens-lyon.fr/lib/extjs/ext-all-debug.js?v=7c637cabf5ecb12e09ea2d4f74b85c8d03c53406)"></script>
<!DOCTYPE html>
<html lang="fr" >
<head>
   <title>Ticket (# 134102) - Utilisateur local GLPI pour usage API - GLPI</title>

   <meta charset="utf-8" />

      <meta http-equiv="X-UA-Compatible" content="IE=edge" />`

**Comment by cedric-anne** [comment] 2023-06-02 12:02
It seems that you have patched tour GLPI, or that you are using plugins that are altering HTML source of generated page without respecting HTML standards.

I close this issue as it is not a GLPI bug.

**Comment by falco2001** [comment] 2023-06-02 12:03
![image](https://github.com/glpi-project/glpi/assets/31952346/37d83980-5bd5-4e19-a8eb-cc28aa61ef1a)

**Closed** 2023-06-02 12:04 UTC
Labels: support
