### ISSUE TITLE
Observer vs Watcher

### ISSUE THREAD

**Issue by J-C-P** [glpi-project/glpi#12603] opened 2022-09-07 10:33 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Hi,

"Observer" and "watcher" are mixed up in the GUI.
Creating a ticket user "observer"
Business rules use "watcher"
Notification recipient use "watcher"
Receivers config use "observer" (Add CC users as observer)

This is not easy to explain to a new customer :-/

Have a good day,
JC

**Comment by trasher** [comment] 2022-09-07 11:05
10.0.1 is not the latest stable release, you shoul dreally consider upgrading. Maybe the issue is fixed as of 10.0.2, anyways, it is certainly for the 10.0.3 to come, try with last nightly build.

Feel free to reopen if the issue is really still present.

**Comment by cedric-anne** [comment] 2022-09-07 11:08
It is indeed a known thing, but I am not sure that labels have been harmonized recently.
Anyway, feel free to propose a pull request to do it.

**Comment by J-C-P** [comment] 2022-09-07 12:01
>feel free to propose a pull request to do it.

Honestly, this is beyond my skills.
I would be glad to search for the occurrences and fix them but GIT is a complete mystery to me :-/
For the time being, I support the project by bringing new subscription customers ;-)

**Comment by cedric-anne** [comment] 2022-09-13 09:04
@cconard96 What would be the most appropriate word, is it watcher or observer ?

**Comment by cconard96** [comment] 2022-09-13 16:00
I am not aware of any difference between these words.

**Comment by J-C-P** [comment] 2022-09-13 16:33
Historically, "watcher" was used.
I (as a french/dutch/english speaker) find "observer" easier to understand and explain.
In my mind, "watcher" has a sense of "observer, waiting for something to happen". "Observer" is more neutral.
Again, I'm not native speaker. I may be completely wrong, but that's how I feel it :-/

I know I am NOT helping but I'm willing to participate as I opened the issue :-)

**Comment by dxdemetriou** [comment] 2022-09-14 03:07
Observer sounds better, but I found some times that when you have to make a presentation of the GLPI that watcher is more understandable as the watcher (user in notifications) is watching everything. Eitherway, it's just a word, but I think it's better to be the same word everywhere or both of them with the one as definition.

**Comment by trasher** [comment] 2022-09-14 06:10
> I am not aware of any difference between these words.

Looking quickly at google results on a vs, it seems differences can be found; but I can't say if those sources can be trusted at all

**Comment by cconard96** [comment] 2022-09-19 23:33
Completed by #12649

**Closed by cconard96** 2022-09-19 23:33 UTC
