### ISSUE TITLE
dropdown for software install is confusing

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#14593] opened 2023-04-26 09:40 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When selecting a computer and going to "Software", you can get a dropdown of software "to install". However, in a company it is very common that different servers have different versions of software installed. This dropdown currently shows a name only, but results in double lines resulting in unsure outcome:
![image](https://user-images.githubusercontent.com/75667/234535474-8d0b1f00-5b3a-49d4-82da-ce10d450a043.png)
==> so either this is a unique thing (which then installs the latest version available on that server), or it mentions relevant info (version + OS release, since you can have a mix of linux flavours as well). It would even be better that the list is limited to the relevant OS and OS release (in which case the OS info is not needed).

**Comment by cedric-anne** [comment] 2023-05-03 07:37
Hi,

This list could probably be enhanced, but, as some GLPI instances may have a really huge amount of softwares versions in their database, it may be technically tricky to do something that has acceptable performances.

However, this is not a bug, so I will close this issue.

**Closed** 2023-05-03 07:37 UTC
Labels: feature suggestion
