### ISSUE TITLE
PHP Notice (8): Undefined index

### ISSUE THREAD

**Issue by zaraiab** [glpi-project/glpi#11239] opened 2022-04-11 00:03 UTC
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

GLPI SETUP

Upgrade
Database connection successful
Database version seems correct (8.0.28) - Perfect!Database version seems correct (8.0.28) - Perfect!

PHP Notice (8): Undefined index: version in /var/www/html/glpi10/src/Update.php at line 134
PHP Notice (8): Undefined index: version in /var/www/html/glpi10/src/Update.php at line 138
PHP Notice (8): Undefined index: language in /var/www/html/glpi10/src/Update.php at line 140
PHP Notice (8): Undefined index: version in /var/www/html/glpi10/src/Update.php at line 335
Uncaught Exception TypeError: Argument 1 passed to GLPIKey::getExpectedKeyPath() must be of the type string, null given, called in /var/www/html/glpi10/src/Update.php on line 335 in /var/www/html/glpi10/src/GLPIKey.php at line 94
![up glpi 10](https://user-images.githubusercontent.com/6960780/162645684-eaadd635-787a-4c80-b23b-5dc820f3d750.PNG)

**Comment by cedric-anne** [comment] 2022-04-11 06:33
Hi,

Could youplease describe the exact steps to reproduce, and provide the full stack trace of the errors, that you could find in `files/_log/php-errors.log` ?

**Comment by zaraiab** [comment] 2022-04-13 08:36
[2022-04-13 09:43:06] glpiphplog.WARNING: Test logger  
[2022-04-13 09:43:07] glpiphplog.WARNING: Test logger  
[2022-04-13 09:43:11] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: version in /var/www/html/glpi10/src/Update.php at line 134
  Backtrace :
  src/Update.php:335                                 Update->getCurrents()
  src/Update.php:317                                 Update->getExpectedSecurityKeyFilePath()
  install/update.php:236                             Update->isExpectedSecurityKeyFileMissing()
  
[2022-04-13 09:43:11] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: version in /var/www/html/glpi10/src/Update.php at line 138
  Backtrace :
  src/Update.php:335                                 Update->getCurrents()
  src/Update.php:317                                 Update->getExpectedSecurityKeyFilePath()
  install/update.php:236                             Update->isExpectedSecurityKeyFileMissing()
  
[2022-04-13 09:43:11] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: language in /var/www/html/glpi10/src/Update.php at line 140
  Backtrace :
  src/Update.php:335                                 Update->getCurrents()
  src/Update.php:317                                 Update->getExpectedSecurityKeyFilePath()
  install/update.php:236                             Update->isExpectedSecurityKeyFileMissing()
  
[2022-04-13 09:43:11] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: version in /var/www/html/glpi10/src/Update.php at line 335
  Backtrace :
  src/Update.php:317                                 Update->getExpectedSecurityKeyFilePath()
  install/update.php:236                             Update->isExpectedSecurityKeyFileMissing()
  
[2022-04-13 09:43:11] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to GLPIKey::getExpectedKeyPath() must be of the type string, null given, called in /var/www/html/glpi10/src/Update.php on line 335 in /var/www/html/glpi10/src/GLPIKey.php at line 94
  Backtrace :
  src/Update.php:335                                 GLPIKey->getExpectedKeyPath()
  src/Update.php:317                                 Update->getExpectedSecurityKeyFilePath()
  install/update.php:236                             Update->isExpectedSecurityKeyFileMissing()

**Comment by zaraiab** [comment] 2022-04-13 08:37
![log](https://user-images.githubusercontent.com/6960780/163135780-0702861b-d772-4e2a-a6c4-e8617273631c.png)

**Comment by cconard96** [comment] 2022-04-13 11:25
Which version of GLPI are you trying to upgrade from?

**Comment by zaraiab** [comment] 2022-04-14 06:45
I want to upgrade GLPI 9.5 to 10

![Capture d’écran 2022-04-14 074315](https://user-images.githubusercontent.com/6960780/163329114-24ff1258-9f50-491b-9aa4-c4e0bb30c780.png)

**Comment by cedric-anne** [comment] 2022-04-14 09:26
How was created the target database ? I cannot reproduce the issue without manually altering the database contents.

**Comment by trasher** [comment] 2022-05-06 05:53
No feedback from a while, closing.

**Closed by trasher** 2022-05-06 05:53 UTC
Labels: Need feedback
