### ISSUE TITLE
[glpi 10.0 beta] External events not added to planning from time to time

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#10365] opened 2022-01-18 17:26 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 beta

### Bug description

When adding event to planning, sometimes it gets added, sometimes not,and the dialog window closes without the confirmation dialog saying the item was created.

I tried on another server with same browser and it works properly; I must say that on the server where I have the issue there is opcache disabled(sorry but I cannot enable it for the moment and I do not know the config of the other server which is a demo site)
![js](https://user-images.githubusercontent.com/63743077/149987396-5d3c00f3-b79e-424f-8cf3-1a2128989257.png)

### Relevant log output

```shell
[2022-01-18 17:28:42] glpiphplog.DEBUG: Html::compileScss() in /usr/www/users/mysite/site/src/Html.php line 6626
Compile css/palettes/auror.scss  {"user":"myuser"} 
[2022-01-18 17:28:42] glpiphplog.CRITICAL:   *** Uncaught Exception ScssPhp\ScssPhp\Exception\CompilerException: It's not clear which file to import. Found:
  /usr/www/users/mysite/site/css/palettes/_auror.scss
  /usr/www/users/mysite/site/css/palettes/auror.scss: /usr/www/users/mysuser/site/css/palettes on line 1, at column 0 in /usr/www/users/mysite/site/vendor/scssphp/scssphp/src/Compiler.php at line 6032
  Backtrace :
  vendor/scssphp/scssphp/src/Compiler.php:5850       ScssPhp\ScssPhp\Compiler->error()
  vendor/scssphp/scssphp/src/Compiler.php:5817       ScssPhp\ScssPhp\Compiler->checkImportPathConflicts()
  vendor/scssphp/scssphp/src/Compiler.php:5792       ScssPhp\ScssPhp\Compiler->resolveImportPath()
  vendor/scssphp/scssphp/src/Compiler.php:2648       ScssPhp\ScssPhp\Compiler->findImport()
  vendor/scssphp/scssphp/src/Compiler.php:2864       ScssPhp\ScssPhp\Compiler->compileImport()
  vendor/scssphp/scssphp/src/Compiler.php:2327       ScssPhp\ScssPhp\Compiler->compileChild()
  vendor/scssphp/scssphp/src/Compiler.php:724        ScssPhp\ScssPhp\Compiler->compileChildrenNoReturn()
  vendor/scssphp/scssphp/src/Compiler.php:504        ScssPhp\ScssPhp\Compiler->compileRoot()
  src/Html.php:6627                                  ScssPhp\ScssPhp\Compiler->compileString()
  front/css.php:51                                   Html::compileScss()
```

### Your GLPI setup information

GLPI 10 beta
Debian 4.19.208-1 (2021-09-29) x86_64
PHP version (7.4.27)
Opcache disabled

**Comment by cconard96** [comment] 2022-01-19 00:20
Do you have duplicate palette stylesheets in your `css/palettes` folder? The valid ones should be prefixed with an underscore. In older GLPI versions, these files didn't have the prefix. If so, it seems like the v10 files were copied over the existing files of an older instance.

In general, you should only need to keep the `files` folder of the old GLPI version (but I still recommend backing up the full directory just in case).

**Comment by cedric-anne** [comment] 2022-01-19 07:36
Indeed, the issue is due to mix between older GLPI files and current master branch files.

Solution:
 - backup your `/usr/www/users/mysite/site` GLPI directory,
 - drop all content from your `/usr/www/users/mysite/site` directory,
 - extract the GLPI archive inside your empty `/usr/www/users/mysite/site` directory,
 - restore `config` and `files` directory (and ensure it is own by your webserver user).

I close this as it is not a bug.

**Closed by cedric-anne** 2022-01-19 07:36 UTC
Labels: beta, Need feedback

**Comment by joomlafun** [comment] 2022-01-19 09:05
Hi, 

Thanks for the help, I deleted the css files which do not have an underscore and I do not get the palette error in the php log.

However, the original issue is still present with the following in JS console 
![image](https://user-images.githubusercontent.com/63743077/150098294-55feaeaa-708b-46b4-b8c5-7b2158369180.png)

Something might have been wrong through the installation, so I will probably reinstall with your instructions
