### ISSUE TITLE
Add second rack - Error "Position is not available"

### ISSUE THREAD

**Issue by rybinpv** [glpi-project/glpi#4037] opened 2018-05-22 05:25 UTC
Hello!
If i add second rack with any name - error "Position is not available".
First rack added is ok.

**Comment by rybinpv** [comment] 2018-05-22 08:57
GLPI 9.3-dev (beta with DCIM)

**Comment by trasher** [comment] 2018-05-22 09:21
Just tested with current 9.3/bf branch, I cannot reproduce.

**Comment by trasher** [comment] 2018-05-23 06:27
You **have to** give us as many details as possible so we can reproduce the issue. 
Also, since the beta has been released a quite long time ago, many things has been fixed; so you should tests latests nigthly build of the 9.3/bugfixes branch.

**Comment by orthagh** [comment] 2018-05-25 12:32
Hello @rybinpv 

"Position is not available" message may triggers in some cases:
- Your equipment has a model with number of units > 1 and the position where you try to insert is not sufficiant to accept the full height
- Your equipment has a full width and on the other side of the rack, there are already some other items.

**Comment by trasher** [comment] 2018-05-29 12:40
Does not seems to be a bug, closing.

**Closed by trasher** 2018-05-29 12:40 UTC
