### ISSUE TITLE
GLPI 10.0.0 Requester does not add himself automatically to the ticket

### ISSUE THREAD

**Issue by szymik1029** [glpi-project/glpi#11499] opened 2022-05-05 13:16 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

The problem occurs when adding a ticket in the simplified interface. When I add a ticket via helpdesk.public.php the Requester field is not filled in the ticket list.

**Comment by cconard96** [comment] 2022-05-05 21:28
Duplicate of #11334, #11377, #11418.

Fixed by #11328 for 10.0.1

**Closed by cconard96** 2022-05-05 21:28 UTC
Labels: duplicate
