### ISSUE TITLE
Native Inventory: Software Asset uses direct SQL queries to add / update, circumventing hooks

### ISSUE THREAD

**Issue by pftpz** [glpi-project/glpi#14228] opened 2023-03-01 17:03 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.*

### Bug description

The Software class of the native inventory (src/Inventory/Asset/Software.php) directly executes queries on the database in order to add or update the items (both Software and SoftwareVersion).
This is a problem, because this circumvents the entry points for all hook functions related to the item inventory (pre_item_add, pre_item_update, item_add,...). So, the items are added to GLPI without the hooks ever being called, breaking the "promise" that the hooks provide.

Instead, the usual functions of CommonDBTM (add, update,...) should be used that also call the hooks. In fact, these are used for all other inventory asset types that I have looked at, not a single one except Software uses SQL queries directly.

Therefore, I believe that this is a bug or might have been forgotten.

**Comment by cedric-anne** [comment] 2023-03-01 17:38
Hi,

This has been done like this due to performances issues. Many changes were done since this choice has been made and I would be interested to have a new benchmark done on this, but I guess we would still have performances issues here.

Could you please explain your need? We could maybe help to find an alternative.

**Comment by pftpz** [comment] 2023-03-02 08:52
Hi,

thank you for your answer.
At the moment, I am using the hooks to populate some data of the fields plugin automatically when an item is added or updated, especially from the native json import.

**Comment by trasher** [comment] 2023-03-02 09:21
Using GLPI framework while importing software is not possible; all hooks will slower the proceess, and inventory is using prepared queries that reallly have an impact.

The only possibility I see would be to  add some kind of hooks on inventory, or something like that, or populating from soft rules maybe.

That's not a bug, but rather a feature request.

**Comment by pftpz** [comment] 2023-03-02 10:51
I understand. At the time of reporting, I flagged it as a bug as the underlying performance reasons were not known to me and it was a clear deviation from the expected behavior (whenever an item is added, the hook is called).

**Comment by trasher** [comment] 2023-03-02 12:56
In facts, Software is no t the only part of inventory that does not uses the standard framework; but that's certainly the more visible one.
We'll close this issue since we only track bugs here, feel free to open a demand on the suggestion website, or contact our services.

**Closed** 2023-03-02 12:57 UTC
Labels: feature suggestion
