### ISSUE TITLE
[GLPI 9.1.6] SLA Time to own execution bug

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#2828] opened 2017-09-25 13:01 UTC
Dear All ,
please refer to the pics below regarding this issue. i tried even on 9.2 RC 1 the issue still persists there.
I create SLA , and under the SLA , SLT like below. and SLT is for Time to own.

![image](https://user-images.githubusercontent.com/22425503/30809469-dee5fbba-a212-11e7-83ff-bc996915015c.png)

now for this SLT i create escalation like below
![image](https://user-images.githubusercontent.com/22425503/30809511-07b1d5d2-a213-11e7-8d4a-765d8c71c2a8.png)

now under escalation i chose execution as time to own.

![image](https://user-images.githubusercontent.com/22425503/30809528-1625d37a-a213-11e7-9067-377d8bd4ce8c.png)

everything is fine untill i click on save. once i click add this is what happens like below
![image](https://user-images.githubusercontent.com/22425503/30809544-254d2b64-a213-11e7-9f58-a4ab45754c83.png)

now the execution is time to resolve instead of time to own.

**Comment by trasher** [comment] 2017-09-25 13:10
This is a complete duplicate of https://github.com/glpi-project/glpi/issues/2765; where some of the issues listed here have been fixed

**Closed by trasher** 2017-09-25 13:10 UTC
Labels: duplicate

**Comment by trasher** [comment] 2017-09-25 13:11
I don't think we're going to fix on the 9.1; there were too much changes on 9.2 SLA's to be backported

**Comment by roshanroche** [comment] 2017-09-25 13:12
@trasher ,
thanks for the reply. 
even on 9.2 the email notifications are not sent. neither for time to own nor time to solve.

**Comment by trasher** [comment] 2017-09-25 13:13
@roshanroche ok; I do not have time to take a look at this right now, please open a specific issue only on notifications (will make things more clear)

**Comment by roshanroche** [comment] 2017-09-25 13:16
@trasher ,
thank you. when you have time i will open this notification issue.
as @orthagh had asked for a test regarding sla reminders and i have already posted my comments on the previous post.
Thanks again.
