### ISSUE TITLE
Images dont dysplay in ticket

### ISSUE THREAD

**Issue by orom3ro** [glpi-project/glpi#7964] opened 2020-09-16 13:16 UTC
**Describe the bug**

Hello,

I'm new ussing GLPI and I did the update from 9.4.2 to 9.5.1 and now the images of the ticket dont appear in the ticket.

I already check and give the right permision on the directory and the problem persist.

**Page(s) URL**

/glpi/front/ticket.form

**Screenshots**

![Screen Shot 2020-09-16 at 9 05 31 AM](https://user-images.githubusercontent.com/71388071/93341248-db850000-f7fb-11ea-9ce3-76a2e94b18b4.png)

![Screen Shot 2020-09-16 at 9 04 39 AM](https://user-images.githubusercontent.com/71388071/93341072-ad9fbb80-f7fb-11ea-9ac9-80ea1637610c.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

`

[code]       GLPI   9.5.1 (/glpi => /var/www/html/glpi)   Installation   mode: TARBALL
--
Server
Operating   system: Linux glpi 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC   2019 x86_64   PHP   7.2.24-0ubuntu0.18.04.6 apache2handler (Core, PDO, Phar, Reflection, SPL,   SimpleXML, Zend OPcache, apache2handler, apc,   apcu,   bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd,   gettext, hash, iconv, imap, intl, json, ldap,   libxml,   mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline,   session, shmop, snmp, sockets, sodium, standard,   sysvmsg,   sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl,   zip, zlib)   Setup:   max_execution_time="30" memory_limit="128M"   post_max_size="8M" safe_mode=""   session.save_handler="files"   upload_max_filesize="20M"   Software:   Apache/2.4.34 (Ubuntu) (Apache/2.4.34 (Ubuntu) Server at glpi.dumit.local   Port 80)   Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0)   Gecko/20100101 Firefox/80.0   Server   Software: (Ubuntu)   Server   Version: 5.7.31-0ubuntu0.18.04.1   Server   SQL Mode:   Parameters:   root@localhost/glpi   Host   info: Localhost via UNIX socket       PHP   version is at least 7.2.0 - Perfect!   Sessions   support is available - Perfect!   Allocated   memory > 64 Mio - Perfect!   mysqli   extension is installed   ctype   extension is installed   fileinfo   extension is installed   json   extension is installed   mbstring   extension is installed   iconv   extension is installed   zlib   extension is installed   curl   extension is installed   gd   extension is installed   simplexml   extension is installed   intl   extension is installed   ldap   extension is installed   apcu   extension is installed   Zend   OPcache extension is installed   xmlrpc   extension is installed   CAS   extension is not present   exif   extension is installed   zip   extension is installed   bz2   extension is installed   sodium   extension is installed   Database   version seems correct (5.7.31) - Perfect!   Timezones seems not loaded, see   https://glpi-install.readthedocs.io/en/latest/timezones.html.   The   log file has been created successfully.   Write access to   /var/www/html/glpi/config has been validated.   Write access to   /var/www/html/glpi/files has been validated.   Write access to   /var/www/html/glpi/files/_dumps has been validated.   Write access to   /var/www/html/glpi/files/_sessions has been validated.   Write access to   /var/www/html/glpi/files/_cron has been validated.   Write access to   /var/www/html/glpi/files/_graphs has been validated.   Write access to   /var/www/html/glpi/files/_lock has been validated.   Write access to   /var/www/html/glpi/files/_plugins has been validated.   Write access to   /var/www/html/glpi/files/_tmp has been validated.   Write access to   /var/www/html/glpi/files/_cache has been validated.   Write access to   /var/www/html/glpi/files/_rss has been validated.   Write access to   /var/www/html/glpi/files/_uploads has been validated.   Write access to   /var/www/html/glpi/files/_pictures has been validated.   Write access to   /var/www/html/glpi/marketplace has been validated.   Web   access to files directory is protected
GLPI   constants
GLPI_ROOT:   /var/www/html/glpi   GLPI_CONFIG_DIR:   /var/www/html/glpi/config   GLPI_VAR_DIR:   /var/www/html/glpi/files   GLPI_MARKETPLACE_DIR:   /var/www/html/glpi/marketplace   GLPI_USE_CSRF_CHECK:   1   GLPI_CSRF_EXPIRES:   7200   GLPI_CSRF_MAX_TOKENS:   100   GLPI_TELEMETRY_URI:   https://telemetry.glpi-project.org   GLPI_INSTALL_MODE:   TARBALL   GLPI_NETWORK_MAIL:   glpi@teclib.com   GLPI_NETWORK_SERVICES:   https://services.glpi-network.com   GLPI_MARKETPLACE_PRERELEASES:   GLPI_USER_AGENT_EXTRA_COMMENTS:   GLPI_AJAX_DASHBOARD:   1   GLPI_CALDAV_IMPORT_STATE:   0   GLPI_DEMO_MODE:   0   GLPI_FORCE_EMPTY_SQL_MODE:   1   GLPI_DOC_DIR:   /var/www/html/glpi/files   GLPI_CACHE_DIR:   /var/www/html/glpi/files/_cache   GLPI_CRON_DIR:   /var/www/html/glpi/files/_cron   GLPI_DUMP_DIR:   /var/www/html/glpi/files/_dumps   GLPI_GRAPH_DIR:   /var/www/html/glpi/files/_graphs   GLPI_LOCAL_I18N_DIR:   /var/www/html/glpi/files/_locales   GLPI_LOCK_DIR:   /var/www/html/glpi/files/_lock   GLPI_LOG_DIR:   /var/www/html/glpi/files/_log   GLPI_PICTURE_DIR:   /var/www/html/glpi/files/_pictures   GLPI_PLUGIN_DOC_DIR:   /var/www/html/glpi/files/_plugins   GLPI_RSS_DIR:   /var/www/html/glpi/files/_rss   GLPI_SESSION_DIR:   /var/www/html/glpi/files/_sessions   GLPI_TMP_DIR:   /var/www/html/glpi/files/_tmp   GLPI_UPLOAD_DIR:   /var/www/html/glpi/files/_uploads   GLPI_NETWORK_REGISTRATION_API_URL:   https://services.glpi-network.com/api/registration/   GLPI_MARKETPLACE_PLUGINS_API_URI:   https://services.glpi-network.com/api/glpi-plugins/   GLPI_I18N_DIR:   /var/www/html/glpi/locales   GLPI_VERSION:   9.5.1   GLPI_SCHEMA_VERSION:   9.5.0   GLPI_MIN_PHP:   7.2.0   GLPI_YEAR:   2020
Libraries
htmlawed/htmlawed   version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)   phpmailer/phpmailer   version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)   simplepie/simplepie   version 1.5.5 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)   tecnickcom/tcpdf   version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)   michelf/php-markdown   in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)   true/punycode   in (/var/www/html/glpi/vendor/true/punycode/src)   iamcal/lib_autolink   in (/var/www/html/glpi/vendor/iamcal/lib_autolink)   sabre/dav   in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)   sabre/http   in (/var/www/html/glpi/vendor/sabre/http/lib)   sabre/uri   in (/var/www/html/glpi/vendor/sabre/uri/lib)   sabre/vobject   in (/var/www/html/glpi/vendor/sabre/vobject/lib)   laminas/laminas-cache   in (/var/www/html/glpi/vendor/laminas/laminas-cache/src)   laminas/laminas-i18n   in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)   laminas/laminas-serializer   in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src)   monolog/monolog   in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)   sebastian/diff   in (/var/www/html/glpi/vendor/sebastian/diff/src)   elvanto/litemoji   in (/var/www/html/glpi/vendor/elvanto/litemoji/src)   symfony/console   in (/var/www/html/glpi/vendor/symfony/console)   scssphp/scssphp   in (/var/www/html/glpi/vendor/scssphp/scssphp/src)   laminas/laminas-mail   in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)   laminas/laminas-mime   in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)   rlanvin/php-rrule   in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)   blueimp/jquery-file-upload   in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)   ramsey/uuid   in (/var/www/html/glpi/vendor/ramsey/uuid/src)   psr/log   in (/var/www/html/glpi/vendor/psr/log/Psr/Log)   psr/simple-cache   in (/var/www/html/glpi/vendor/psr/simple-cache/src)   mexitek/phpcolors   in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)   guzzlehttp/guzzle   in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)   wapmorgan/unified-archive   in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)   paragonie/sodium_compat   in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)`
```

**Comment by cedric-anne** [comment] 2020-09-16 13:25
Hi,

Can you give us the content of the `glpi_tickets.content` database field for corresponding ticket ?

Can you also looks at your GLPI logs to see if anything is logged when displaying this ticket ?

Then, can you export the corresponding email into eml format and attach it to current issue ?

Regards

**Comment by orom3ro** [comment] 2020-09-16 14:31
Hello,

Thanks in advance for any help:

`

N° | Queries | Time | Errors
-- | -- | -- | --
1 | SELECT *    FROM `glpi_plugins`    WHERE `state` = '1' | 0.000 |  
2 | SELECT `id`    FROM `glpi_plugins`    WHERE `directory` = 'fusioninventory' | 0.000 |  
3 | SELECT *    FROM `glpi_plugins`    WHERE `glpi_plugins`.`id` = '14' LIMIT 1 | 0.000 |  
4 | SELECT `id`    FROM `glpi_plugins`    WHERE `directory` = 'dashboard' | 0.000 |  
5 | SELECT *    FROM `glpi_plugins`    WHERE `glpi_plugins`.`id` = '15' LIMIT 1 | 0.000 |  
6 | SELECT `id`    FROM `glpi_plugins`    WHERE `directory` = 'treeview' | 0.000 |  
7 | SELECT *    FROM `glpi_plugins`    WHERE `glpi_plugins`.`id` = '16' LIMIT 1 | 0.000 |  
8 | SELECT `id`    FROM `glpi_plugins`    WHERE `directory` = 'moreticket' | 0.000 |  
9 | SELECT *    FROM `glpi_plugins`    WHERE `glpi_plugins`.`id` = '17' LIMIT 1 | 0.000 |  
10 | SELECT *    FROM `glpi_plugins`    WHERE `state` IN ('1', '3') | 0.000 |  
11 | SELECT `id`    FROM `glpi_plugins`    WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
12 | SELECT *    FROM `glpi_plugins`    WHERE `glpi_plugins`.`id` = '14' LIMIT 1 | 0.000 |  
13 | SELECT `id`    FROM `glpi_plugins`    WHERE `glpi_plugins`.`directory` = 'fusioninventory' | 0.000 |  
14 | SELECT *    FROM `glpi_plugins`    WHERE `glpi_plugins`.`id` = '14' LIMIT 1 | 0.000 |  
15 | SELECT *    FROM `glpi_plugin_fusioninventory_configs` | 0.000 |  
16 | SELECT `table_name` AS   `TABLE_NAME`    FROM `information_schema`.`tables`    WHERE `table_schema` = 'glpi' AND `table_type` = 'BASE TABLE' AND   `table_name` LIKE 'glpi_plugin_moreticket_configs' | 0.001 |  
17 | SELECT *    FROM `glpi_entities`    WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
18 | SELECT *    FROM `glpi_entities`    WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
19 | SHOW COLUMNS    FROM `glpi_computers` | 0.000 |  
20 | SHOW COLUMNS    FROM `glpi_monitors` | 0.000 |  
21 | SHOW COLUMNS    FROM `glpi_softwares` | 0.000 |  
22 | SHOW COLUMNS    FROM `glpi_networkequipments` | 0.001 |  
23 | SHOW COLUMNS    FROM `glpi_peripherals` | 0.000 |  
24 | SHOW COLUMNS    FROM `glpi_printers` | 0.000 |  
25 | SHOW COLUMNS    FROM `glpi_cartridgeitems` | 0.000 |  
26 | SELECT *    FROM `glpi_entities`    WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
27 | SHOW COLUMNS    FROM `glpi_consumableitems` | 0.000 |  
28 | SELECT *    FROM `glpi_entities`    WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
29 | SHOW COLUMNS    FROM `glpi_phones` | 0.000 |  
30 | SHOW COLUMNS    FROM `glpi_racks` | 0.000 |  
31 | SHOW COLUMNS    FROM `glpi_enclosures` | 0.000 |  
32 | SHOW COLUMNS    FROM `glpi_pdus` | 0.000 |  
33 | SHOW COLUMNS    FROM `glpi_passivedcequipments` | 0.000 |  
34 | SHOW COLUMNS    FROM `glpi_items_devicesimcards` | 0.000 |  
35 | SHOW COLUMNS    FROM `glpi_tickets` | 0.000 |  
36 | SHOW COLUMNS    FROM `glpi_problems` | 0.000 |  
37 | SHOW COLUMNS    FROM `glpi_changes` | 0.000 |  
38 | SHOW COLUMNS    FROM `glpi_ticketrecurrents` | 0.000 |  
39 | SHOW COLUMNS    FROM `glpi_softwarelicenses` | 0.000 |  
40 | SHOW COLUMNS    FROM `glpi_budgets` | 0.000 |  
41 | SHOW COLUMNS    FROM `glpi_suppliers` | 0.000 |  
42 | SHOW COLUMNS    FROM `glpi_contacts` | 0.000 |  
43 | SHOW COLUMNS    FROM `glpi_contracts` | 0.000 |  
44 | SELECT *    FROM `glpi_entities`    WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
45 | SHOW COLUMNS    FROM `glpi_documents` | 0.000 |  
46 | SHOW COLUMNS    FROM `glpi_lines` | 0.000 |  
47 | SHOW COLUMNS    FROM `glpi_certificates` | 0.000 |  
48 | SHOW COLUMNS    FROM `glpi_datacenters` | 0.000 |  
49 | SHOW COLUMNS    FROM `glpi_clusters` | 0.000 |  
50 | SHOW COLUMNS    FROM `glpi_domains` | 0.000 |  
51 | SHOW COLUMNS    FROM `glpi_appliances` | 0.000 |  
52 | SHOW COLUMNS    FROM `glpi_projects` | 0.000 |  
53 | SHOW COLUMNS    FROM `glpi_reminders` | 0.000 |  
54 | SHOW COLUMNS    FROM `glpi_rssfeeds` | 0.000 |  
55 | SHOW COLUMNS    FROM `glpi_knowbaseitems` | 0.000 |  
56 | SHOW COLUMNS    FROM `glpi_users` | 0.001 |  
57 | SHOW COLUMNS    FROM `glpi_groups` | 0.000 |  
58 | SHOW COLUMNS    FROM `glpi_entities` | 0.001 |  
59 | SELECT COUNT(*) AS cpt    FROM `glpi_mailcollectors` | 0.000 |  
60 | SHOW COLUMNS    FROM `glpi_profiles` | 0.000 |  
61 | SELECT DISTINCT `name`    FROM `glpi_profilerights` | 0.002 |  
62 | SHOW COLUMNS    FROM `glpi_fieldunicities` | 0.000 |  
63 | SHOW COLUMNS    FROM `glpi_mailcollectors` | 0.000 |  
64 | SHOW COLUMNS    FROM `glpi_links` | 0.000 |  
65 | SHOW COLUMNS    FROM `glpi_plugins` | 0.000 |  
66 | SELECT *    FROM `glpi_configs`    WHERE `context` = 'core' AND `name` IN ('marketplace_replace_plugins') | 0.000 |  
67 | SELECT *    FROM `glpi_tickets`    WHERE `glpi_tickets`.`id` = '2281' LIMIT 1 | 0.000 |  
68 | SELECT *    FROM `glpi_groups_tickets`    WHERE `tickets_id` = '2281'    ORDER BY `id` ASC | 0.000 |  
69 | SELECT *    FROM `glpi_tickets_users`    WHERE `tickets_id` = '2281'    ORDER BY `id` ASC | 0.000 |  
70 | SELECT *    FROM `glpi_suppliers_tickets`    WHERE `tickets_id` = '2281'    ORDER BY `id` ASC | 0.000 |  
71 | SELECT *    FROM `glpi_tickets`    WHERE `glpi_tickets`.`id` = '2281' LIMIT 1 | 0.000 |  
72 | SELECT *    FROM `glpi_groups_tickets`    WHERE `tickets_id` = '2281'    ORDER BY `id` ASC | 0.000 |  
73 | SELECT *    FROM `glpi_tickets_users`    WHERE `tickets_id` = '2281'    ORDER BY `id` ASC | 0.000 |  
74 | SELECT *    FROM `glpi_suppliers_tickets`    WHERE `tickets_id` = '2281'    ORDER BY `id` ASC | 0.000 |  
75 | SELECT COUNT(*) AS cpt    FROM `glpi_items_tickets`    INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` =   `glpi_tickets`.`id`)    WHERE `itemtype` = 'Ticket' AND `items_id` = '2281' AND `is_deleted` = '0' | 0.000 |  
76 | SELECT `id`, `itemtype`,   `items_id`    FROM `glpi_items_tickets`    WHERE `tickets_id` = '2281' | 0.000 |  
77 | SHOW COLUMNS    FROM `glpi_tickettasks` | 0.000 |  
78 | SELECT *    FROM `glpi_itilfollowups`    WHERE `items_id` = '2281' AND `itemtype` = 'Ticket'    ORDER BY `date` DESC, `id` DESC | 0.000 |  
79 | SELECT *    FROM `glpi_tickettasks`    WHERE `tickets_id` = '2281'    ORDER BY `date` DESC | 0.000 |  
80 | SELECT *    FROM `glpi_documents_items`    WHERE (((`glpi_documents_items`.`itemtype` = 'Ticket' AND   `glpi_documents_items`.`items_id` = '2281') OR   (`glpi_documents_items`.`itemtype` = 'ITILFollowup' AND   `glpi_documents_items`.`items_id` IN (SELECT `id`    FROM `glpi_itilfollowups`    WHERE `glpi_itilfollowups`.`itemtype` = 'Ticket' AND   `glpi_itilfollowups`.`items_id` = '2281')) OR   (`glpi_documents_items`.`itemtype` = 'ITILSolution' AND   `glpi_documents_items`.`items_id` IN (SELECT `id`    FROM `glpi_itilsolutions`    WHERE `glpi_itilsolutions`.`itemtype` = 'Ticket' AND   `glpi_itilsolutions`.`items_id` = '2281')) OR   (`glpi_documents_items`.`itemtype` = 'TicketTask' AND   `glpi_documents_items`.`items_id` IN (SELECT `id`    FROM `glpi_tickettasks`    WHERE `tickets_id` = '2281')))) AND `timeline_position` > '-1' | 0.001 |  
81 | SELECT *    FROM `glpi_documents`    WHERE `glpi_documents`.`id` = '1007' LIMIT 1 | 0.000 |  
82 | SELECT *    FROM `glpi_itilsolutions`    WHERE `itemtype` = 'Ticket' AND `items_id` = '2281' | 0.000 |  
83 | SELECT *    FROM `glpi_ticketvalidations`    WHERE `tickets_id` = '2281' | 0.000 |  
84 | SELECT *    FROM `glpi_ticketsatisfactions`    WHERE `glpi_ticketsatisfactions`.`tickets_id` = '2281' LIMIT 1 | 0.000 |  
85 | SELECT COUNT(*) AS cpt    FROM `glpi_ticketvalidations`    WHERE `tickets_id` = '2281' | 0.000 |  
86 | SELECT COUNT(*) AS cpt    FROM `glpi_knowbaseitems_items`    WHERE `itemtype` = 'Ticket' AND `items_id` = '2281' | 0.000 |  
87 | SELECT COUNT(*) AS cpt    FROM `glpi_items_tickets`    WHERE `tickets_id` = '2281' AND `itemtype` IN ('Computer', 'Monitor',   'NetworkEquipment', 'Peripheral', 'Phone', 'Printer', 'Software', 'DCRoom',   'Rack', 'Enclosure') | 0.000 |  
88 | SELECT `id`, `itemtype`,   `items_id`    FROM `glpi_items_tickets`    WHERE `tickets_id` = '2281' | 0.000 |  
89 | SELECT COUNT(*) AS cpt    FROM `glpi_ticketcosts`    WHERE `tickets_id` = '2281' | 0.000 |  
90 | SELECT COUNT(*) AS cpt    FROM `glpi_itils_projects`    WHERE `itemtype` = 'Ticket' AND `items_id` = '2281' | 0.000 |  
91 | SHOW COLUMNS    FROM `glpi_projecttasks_tickets` | 0.000 |  
92 | SHOW COLUMNS    FROM `glpi_projecttasks` | 0.000 |  
93 | SELECT COUNT(*) AS cpt    FROM `glpi_projecttasks_tickets`    LEFT JOIN `glpi_projecttasks` ON   (`glpi_projecttasks_tickets`.`projecttasks_id` = `glpi_projecttasks`.`id`)    INNER JOIN `glpi_entities` ON (`glpi_projecttasks`.`entities_id` =   `glpi_entities`.`id`)    WHERE `glpi_projecttasks_tickets`.`tickets_id` = '2281'    ORDER BY `glpi_entities`.`completename`, `glpi_projecttasks`.`name` | 0.000 |  
94 | SHOW COLUMNS    FROM `glpi_problems_tickets` | 0.000 |  
95 | SELECT   `glpi_problems_tickets`.`id` AS `linkid`, `glpi_problems`.*,   `glpi_entities`.`id` AS `entity`    FROM `glpi_problems_tickets`    LEFT JOIN `glpi_problems` ON (`glpi_problems_tickets`.`problems_id` =   `glpi_problems`.`id`)    INNER JOIN `glpi_entities` ON (`glpi_problems`.`entities_id` =   `glpi_entities`.`id`)    WHERE `glpi_problems_tickets`.`tickets_id` = '2281'    ORDER BY `glpi_entities`.`completename`, `glpi_problems`.`name` | 0.000 |  
96 | SELECT COUNT(*) AS cpt    FROM `glpi_changes_tickets`    WHERE `tickets_id` = '2281' | 0.000 |  
97 | SELECT *    FROM `glpi_entities`    WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
98 | SELECT COUNT(*) AS cpt    FROM `glpi_logs`    WHERE `itemtype` = 'Ticket' AND `items_id` = '2281' | 0.000 |  
99 | SELECT `table_name` AS   `TABLE_NAME`    FROM `information_schema`.`tables`    WHERE `table_schema` = 'glpi' AND `table_type` = 'BASE TABLE' AND   `table_name` LIKE 'glpi_plugin_moreticket_configs' | 0.001 |  
100 | SELECT `table_name` AS   `TABLE_NAME`    FROM `information_schema`.`tables`    WHERE `table_schema` = 'glpi' AND `table_type` = 'BASE TABLE' AND   `table_name` LIKE 'glpi_plugin_moreticket_configs' | 0.001 |  
101 | SELECT *    FROM `glpi_configs`    WHERE `context` = 'core' AND `name` IN ('cache_db') | 0.000 |  

`

I do not know if that is the info:

I attach the email in compress format.

[FRONT.eml.zip](https://github.com/glpi-project/glpi/files/5232785/FRONT.eml.zip)

**Comment by cedric-anne** [comment] 2020-09-17 06:55
Hi,

I reimport your message into my testing mailbox and was able to reproduce your issue.
I will try to find a fix for this.

Regards

**Comment by cedric-anne** [comment] 2020-09-17 09:25
Hi,

Can you test #7968 ?

Regards

**Comment by orom3ro** [comment] 2020-09-17 13:22
Hi @cedric-anne 

I already did the first change in the class named "ticket.class.php "

![Screen Shot 2020-09-17 at 9 17 40 AM](https://user-images.githubusercontent.com/71388071/93475485-a85b7300-f8c6-11ea-8b9e-6814ef34dbef.png)

But the second change in the " tests/imap/MailCollector.php" I don't know where to find it.

Regards,

**Comment by trasher** [comment] 2020-09-17 13:24
Hi,
Tests are not provided in tarball, you can just ignore that part

**Comment by orom3ro** [comment] 2020-09-17 13:27
hit @trasher, 

Thank you for the information. 

The first change didnt work. 

Regards,

**Comment by orom3ro** [comment] 2020-09-17 13:28
Sorry I closed by error..

**Comment by cedric-anne** [comment] 2020-09-17 13:30
For information, this change will not fix existing tickets, as it cannot be done, but it should fix this bug for emails that will be collected in the future.

I checked with your email and it was creating a ticket with the correct image.

**Comment by orom3ro** [comment] 2020-09-17 13:42
@cedric-anne 

I did a new ticket from the same source and doesnt work.

![Screen Shot 2020-09-17 at 9 37 35 AM](https://user-images.githubusercontent.com/71388071/93477834-7ac3f900-f8c9-11ea-94a1-af1a4dde3cf1.png)

<p class="MsoNormal"><img id="Imagen_x0020_1" src="denied:cid:image001.jpg@01D68B65.C580F910" alt="image" data-mce-src="denied:cid:image001.jpg@01D68B65.C580F910" data-mce-selected="1" width="1028" height="578"></p>

![Screen Shot 2020-09-17 at 9 40 55 AM](https://user-images.githubusercontent.com/71388071/93479227-10f81f00-f8ca-11ea-9e83-ef72cc2aafc8.png)
![Screen Shot 2020-09-17 at 9 41 02 AM](https://user-images.githubusercontent.com/71388071/93479254-181f2d00-f8ca-11ea-8e12-b7f1228aebed.png)

**Comment by cedric-anne** [comment] 2020-09-18 08:09
Hi,

I made a new check and gub is fixed on my side (and was reproduceable).

![image](https://user-images.githubusercontent.com/33253653/93572679-774a7380-f996-11ea-9db1-ab9cd152e8d1.png)

So either their is a slight different in mail contents du to usage of different mailservers and/or due to the fact that the mail was altered during export/import operations, either other bugfixes made recently on mail receivers feature are also required.

You can try to get [latest nightly build](https://github.com/glpi-project/glpi/suites/1203993613/artifacts/17842752), apply the patch and see if your bug is fixed.

Regards

**Closed** 2020-09-23 09:01 UTC
Labels: bug

**Comment by dronces** [comment] 2022-10-07 15:22
Hello friend, would you be very kind to share with us how you solved the problem, the same thing happens to me, I can see the attached files in a ticket
