### ISSUE TITLE
Collector bug

### ISSUE THREAD

**Issue by MOUSTACHEBIKES** [glpi-project/glpi#8052] opened 2020-10-02 13:48 UTC
Hello,

After just change our mail collector address, this last don't ready.

The bug message : 
Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name message_id or message_id not found in /usr/share/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307

What ?

Regards

**Comment by cedric-anne** [comment] 2020-10-02 13:50
Hi,

Multiple mail collector issues has been fixed recently. Please try with [latest nightly build](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22) to see if problem persist.

Regards

**Comment by MOUSTACHEBIKES** [comment] 2020-10-02 14:00
Hi Cédric-Anne,

Thanks for your answer.
Please just confirm me the method for the fix.
We have a 9.5.1 version.
Just download 118 GLPI nightly build, unzip en copy past to glpi folder ?
For any information : Recently, I modified our GLPI with your return : laminas/laminas-mail#111 ticket #8005, don't risk ?

Best

**Comment by cedric-anne** [comment] 2020-10-02 14:03
> Just download 118 GLPI nightly build, unzip en copy past to glpi folder ?

Yes

> For any information : Recently, I modified our GLPI with your return : [laminas/laminas-mail#111](https://github.com/laminas/laminas-mail/pull/111) ticket #8005, don't risk ?

This patch will have to be applied afet replacement of GLPI by the nightly release.

**Comment by MOUSTACHEBIKES** [comment] 2020-10-02 15:06
I  upgrade GLPI with 9.5.2 118
It's OK for collector but one message don't up to the ticket.
Screenshot attached
Error message : Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name message_id or message_id not found in /usr/share/glpi/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307

![Capture d’écran 2020-10-02 à 17 02 47](https://user-images.githubusercontent.com/72015078/94938809-a0f4b600-04d1-11eb-9080-3ab6b5954f24.png)
![Capture d’écran 2020-10-02 à 17 03 00](https://user-images.githubusercontent.com/72015078/94938812-a225e300-04d1-11eb-965a-941d11bd1bfe.png)

**Comment by cedric-anne** [comment] 2020-10-02 17:16
Can you attach here the errored into eml format?

**Comment by cedric-anne** [comment] 2020-10-08 06:40
Hi,

I close this issue as we will not investigate without the mail source. Feel free to reopen if you can reproduce and provide the source of e problematic mail.

Regards

**Closed by cedric-anne** 2020-10-08 06:40 UTC
Labels: Need feedback

**Comment by Gaesi-JP** [comment] 2020-10-08 08:09
Hello,

Since the update to version GLPI 9.5.1, the recovery of my emails via collector no longer works.

The automatic actions of the "Mailgate" work without problem.

No problem BEFORE migration.

--------------------------------------

When I go to the mail collector options "Configuration \ Collectors \ (the collector) \ Action \ Retrieve emails now", this is what is displayed:

Error
Number of messages: available = 3, retrieved = 3, refused = 0, errors = 3, blacklisted = 0

--------------------------------------

I have been checking the logs, the only logs that return some interesting stuff and the "mailgate.log" log which is in the "/ var / www / glpi / files / _log /" directory.

I have no error in the "php-errors.log" and "sql-errors.log" logs which concern the collector.

Here is what the log says:
Invalid message: Malformed header detected <br/> 2020-10-01 15:10:06 [@SERVER]
Invalid message: Malformed header detected <br/> 2020-10-01 15:10:06 [@SERVER]
Invalid message: Malformed header detected <br/> 2020-10-01 15:10:06 [@SERVER]

Obviously the mailgate tells me that the mail header is badly formatted (this only since the migration to 9.5.1).

--------------------------------------

Regarding the configuration of the collector:
Server type: onpremise (internal) "Kerio Connect"
Connection type: POP
TLS: NO-TLS
Authentication: YES

--------------------------------------

WORKAROUND :

I changed the configuration of the collector, I replaced "POP" with "IMAP" and since the collector is working.

I can no longer use my "POP" collector.

If this can give a clue to solving the problem or troubleshooting someone else with the same problem

**Comment by trasher** [comment] 2020-10-08 08:42
> Since the update to version GLPI 9.5.1, the recovery of my emails via collector no longer works.

Try 9.5.2.

**Comment by Gaesi-JP** [comment] 2020-10-09 07:16
> 
> 
> > Since the update to version GLPI 9.5.1, the recovery of my emails via collector no longer works.
> 
> Try 9.5.2.

As I said in my post:

> 
> I updated to 9.5.2, but this does not solve my problem
> 

Thank you anyway for your return

**Comment by cedric-anne** [comment] 2020-10-09 07:21
> > > Since the update to version GLPI 9.5.1, the recovery of my emails via collector no longer works.
> > 
> > 
> > Try 9.5.2.
> 
> As I said in my post:
> 
> > I updated to 9.5.2, but this does not solve my problem
> 
> Thank you anyway for your return

Hi,

Please open another issue, this one is closed, with all requested informations. This bug is closed and, as you says that there is nothing in your error logs, your issue is a different one.

Regards
