### ISSUE TITLE
Trashed projects are displayed in the Global Kanban

### ISSUE THREAD

**Issue by MrYsson** [glpi-project/glpi#13651] opened 2022-12-19 15:44 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

The Global Kanban displays the projects that are in the trash bin (🗑️ ; French : "Corbeille")

### Page URL

https://interventiontest.sieeen.fr/glpi/front/project.form.php?showglobalkanban=1

### Steps To reproduce

1. Create a Project
2. Move it to trash
3. Go to Global Kanban
4. You should see the project

### Your GLPI setup information

For security reasons, we'd like to limit the informations we share about the config. Plus, the issue seems to be on the client side. So here is a short version :

Linux : 3.10
PHP : 8.1.11
Webserver : Apache2
Plugins : all disabled
If you need more specific infos, just ask 😉

**Comment by cconard96** [comment] 2022-12-19 15:54
Deleted items showing in the global Project Kanban is not a bug. It was intended that you should trash an item directly from the Kanban, and also purge trashed items from there as well. Although, the red background of the cards seems to no longer show to indicate they were deleted. Some improvements could be made around this functionality.

**Comment by MrYsson** [comment] 2022-12-20 10:15
Thank you for this information. And the commit #13654 should be a great addition.

**Comment by cedric-anne** [comment] 2023-01-03 07:44
I close this issue as #13653, #13654 and #13655 fixed handling of deleted items.

**Closed by cedric-anne** 2023-01-03 07:44 UTC
