### ISSUE TITLE
Attachment missing on ticket timeline

### ISSUE THREAD

**Issue by marlonvalim** [glpi-project/glpi#10961] opened 2022-03-11 15:25 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc2

### Bug description

I noticed that when I create a ticket and attach a file, the file won't show in the ticket timeline.
It uploads normally in the server path.
I've also noticed that the date and time of this field in the ticket timeline is wrong (ex: i opened the ticket today and the date of where the attachment was supposed to be shows 6 days past).
![glpi](https://user-images.githubusercontent.com/11953146/157895230-ea626369-2515-499f-b49c-877b45affe55.png)

This problem does not occur in 10.0.0-rc1 version.

I've tested clean install of both versions with nothing configured, rc1 works normally and rc2 behaves like reported. 

**The problem does not occur when I add an attachment in a followup on the ticket.**

### Relevant log output

```shell
I don't know if this error logs are useful for this but here it goes.

php-errors
[2022-03-10 20:34:25] glpiphplog.WARNING: Test logger  
[2022-03-10 20:36:22] glpiphplog.DEBUG: Html::compileScss() in C:\xampp\htdocs\glpi\src\Html.php line 6771
Compile css/palettes/auror.scss  {"user":"@4130-TI"} 
[2022-03-11 15:35:05] glpiphplog.WARNING: Test logger  

sql-errors
[2022-03-11 15:29:01] glpisqllog.ERROR: DBmysql::query() in C:\xampp\htdocs\glpi\src\DBmysql.php line 367
  *** MySQL query error:
  SQL: INSERT INTO `glpi_logs` (`items_id`, `itemtype`, `itemtype_link`, `linked_action`, `user_name`, `date_mod`, `id_search_option`, `old_value`, `new_value`) VALUES ('1', 'Config', '', '0', 'glpi (2)', '2022-03-11 15:29:01', '1', 'priority_matrix {\"1\":{\"1\":\"1\",\"2\":\"1\",\"3\":\"2\",\"4\":\"2\",\"5\":\"2\"},\"2\":{\"1\":\"1\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"3\"},\"3\":{\"1\":\"2\",\"2\":\"2\",\"3\":\"3\",\"4\":\"4\",\"5\":\"4\"},\"4\":{\"1\":\"2\",\"2\":\"3\', '{\"1\":{\"1\":\"1\",\"2\":\"1\",\"3\":\"2\",\"4\":\"2\",\"5\":\"2\"},\"2\":{\"1\":\"1\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"3\"},\"3\":{\"1\":\"2\",\"2\":\"2\",\"3\":\"3\",\"4\":\"4\",\"5\":\"4\"},\"4\":{\"1\":\"2\",\"2\":\"3\",\"3\":\"4\",\"')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '{\"1\":{\"1\":\"1\",\"2\":\"1\",\"3\":\"2\",\"4\":\"2\",\"5\":\"2\"},\"2\":{\...' at line 1
  Backtrace :
  src\DBmysql.php:1295                               
  src\Log.php:261                                    DBmysql->insert()
  src\Log.php:188                                    Log::history()
  src\Config.php:3717                                Log::constructHistory()
  src\Config.php:3690                                Config->logConfigChange()
  src\CommonDBTM.php:1642                            Config->post_updateItem()
  src\Config.php:3048                                CommonDBTM->update()
  src\Config.php:280                                 Config::setConfigurationValues()
  src\CommonDBTM.php:1512                            Config->prepareInputForUpdate()
  front\config.form.php:63                           CommonDBTM->update()
  {"user":"2@4130-TI"}
```

### Steps To reproduce

Open a ticket and insert an attachment with it.

### Your GLPI setup information

GLPI 10.0.0-rc2 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:pt_BR

Operating system: Windows NT 4130-TI 10.0 build 19044 (Windows 10) AMD64
PHP 8.1.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2 (Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2 Server at 127.0.0.1
	Port 8081
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.22-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.1.2) is supported.PHP version (8.1.2) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.22) is supported.Database engine version (10.4.22) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated. Write access to C:\xampp\htdocs\glpi/config has been validated. Write access to C:\xampp\htdocs\glpi/files/_cron has been validated. Write access to C:\xampp\htdocs\glpi/files has been validated. Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated. Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated. Write access to C:\xampp\htdocs\glpi/files/_lock has been validated. Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated. Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated. Write access to C:\xampp\htdocs\glpi/files/_rss has been validated. Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated. Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated. Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

**Comment by cconard96** [comment] 2022-03-11 15:57
Possible duplicate of #10839 which was already fixed. Please test on the latest nightly "master" release.
https://nightly.glpi-project.org/glpi/

**Comment by marlonvalim** [comment] 2022-03-14 12:04
Tried the latest nightly master release.
It fixed the issue when opening a ticket, but when you close a ticket and add an attachment, the issue appears again and the attachment that was added in the ticket opening disappears from the timeline too. 

Also "Requirer" info on this latest nightly master version is gone too.

**Comment by SteadEXE** [comment] 2022-03-14 13:09
I noticed this issue too, but I was not sure of the exact order of event to reproduce it. I guess you found it.

**Comment by marlonvalim** [comment] 2022-03-23 12:46
I've tried to mix the archives of working versions that affetcs this issue but had no success...

**Comment by cedric-anne** [comment] 2022-03-31 07:18
Hi,

I confirm the bug.

To reproduce:
 - open a ticket with an attached document,
 - close the ticket.

There is an entry related to the document, but no preview/link to the document itself.

**Comment by marlonvalim** [comment] 2022-04-01 12:34
I've tested the CommonITILObject.php you modified.
It fixed the issue for the attachment that was added in the ticket opening. 

But if you add an attachment to to ticket solution, it won't appear yet in the ticket timeline. 

![anexo teste](https://user-images.githubusercontent.com/11953146/161264188-3fd8f4e0-dbe0-49f3-98f3-138abe4fd77e.png)

**Closed** 2022-04-19 07:57 UTC
Labels: bug, beta

**Comment by marlonvalim** [comment] 2022-04-19 11:17
Tested now and it's working!
Thank you!!
