### ISSUE TITLE
How to synchronise GLPI planning with outlook ?

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1214] opened 2016-10-24 13:44 UTC
Please, do you have a procedure to do that ?

Thank you for your help

GLPI 9.1

**Comment by tomolimo** [comment] 2016-10-24 13:47
Go to the 'PLanning' view, and 
![image](https://cloud.githubusercontent.com/assets/7569958/19648040/11af4170-9a01-11e6-975f-e30909ee0baa.png)
Export in webcal and open the exported file with Outlook

**Comment by satyan01** [comment] 2016-10-24 13:49
![image](https://cloud.githubusercontent.com/assets/15144026/19648138/76597514-9a01-11e6-81f7-8cb0658c6811.png)

**Comment by tomolimo** [comment] 2016-10-24 13:50
which version of Outlook do you use?

**Comment by satyan01** [comment] 2016-10-24 13:50
2010

**Comment by tomolimo** [comment] 2016-10-24 13:51
Did you export ical or webcal?

**Comment by satyan01** [comment] 2016-10-24 13:51
webcal

**Comment by tomolimo** [comment] 2016-10-24 13:51
try ical!

**Comment by satyan01** [comment] 2016-10-24 13:52
it works with ICAL but how to synchronize ?

**Comment by tomolimo** [comment] 2016-10-24 13:53
is done by outlook

**Comment by satyan01** [comment] 2016-10-24 13:53
ok I will see

**Comment by satyan01** [comment] 2016-10-24 13:54
So If I delete in GLPI or Add something it will be synchronised in outlook ?

**Comment by tomolimo** [comment] 2016-10-24 13:56
See outlook doc to refresh calendar periodically

**Comment by satyan01** [comment] 2016-10-24 14:01
Thank you so much !

**Comment by tomolimo** [comment] 2016-10-24 14:03
you're welcome

**Comment by satyan01** [comment] 2016-10-25 14:20
Hello, Unfortunately the synchronization does not work, If I modify something on each side, other side is not updated

**Comment by halouc** [comment] 2016-10-26 23:39
I have the same problem !
Tested with:
Zimbra  ( Glpi 0.90.4 = OK, GLPI 9.1 = KO )
Outlook 2010 and 2014 ( Glpi 0.90.4 = OK, GLPI 9.1 = KO )

**Comment by denzoil2** [comment] 2016-10-30 08:03
Hi. 
@Satyan01: Please note that the synchronisation way is only GLPI => outlook.
@admins: There is a bug with GLPI 0.91: webcal doesn't work anymore. 
If I test with Evolution Mail the error message is that the file format is wrong. It is ok with 0.90.

**Comment by denzoil** [comment] 2016-10-31 11:38
Sorry I wrote 0.91 but i meant GLPI 9.1 of course.
Doesn't work anymore with Outlook 2010

**Comment by orthagh** [comment] 2016-11-09 15:07
Duplicate of #1257

**Closed by orthagh** 2016-11-09 15:07 UTC
Labels: help wanted

**Comment by aze789** [comment] 2018-06-13 10:09
Hello,
Do you know if it's possible to synchronize automatically outlook with glpi ? ( add an appointment on outlook and can be see on glpi )

**Comment by aze789** [comment] 2018-06-14 07:17
up

**Comment by orthagh** [comment] 2018-06-14 10:11
@aze789 cf https://glpi.userecho.com/communities/1/topics/699-import-and-sync-planning-glpi-side
It's an evolution.

**Comment by aze789** [comment] 2018-06-14 10:28
@orthagh What am I suppose to do with that lmao

**Comment by orthagh** [comment] 2018-06-14 10:39
Waiting for someone to develop it (or not).
The feature doesn't exists in GLPI.

On your side, you can vote for the feature to improve it's visibility

**Comment by Eisbaeeer** [comment] 2019-03-15 05:58
Actually don´t know how it is exactly to do, but all enterprise API´s using the EWS to exchange that. Perhaps there is a programmer who can realize that?
In other systems, they using the autodiscover dns feature to get connected. Second is to use a managed service account with full access rights to the mailboxes and to connect to exchange and the API using the mail-address to synchronize the calendar informations.

**Comment by dxdemetriou** [comment] 2022-09-22 12:14
Tried this:
https://github.com/aluxnimm/outlookcaldavsynchronizer/

and seems to be the only alternative for Outlook.
