### ISSUE TITLE
Sending responses to the email address from which the request was made (a comment was written).

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#7398] opened 2020-06-10 16:40 UTC
Hello. Are there any plans to implement such a function: The user has two emails in their profile one@email.com and two@email.com. First (one@email.com) selected by the checkbox. The user creates a request from email two@email.com. The request is successfully created under this user, but notifications are sent to one@email.com. Is it possible to make them come to the email address from which the request was made, or both at once?

**Comment by cedric-anne** [comment] 2020-06-18 07:06
Hi,

With actual state of GLPI notification system, doing this is not so easy. If you want to sponsor this feature, feel free to contact us at contact@teclib.com.

I close this issue as it is not a bug. You can open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).

Regards

**Closed by cedric-anne** 2020-06-18 07:06 UTC
