### ISSUE TITLE
When updating a task, the system is not respecting the private task flag.

### ISSUE THREAD

**Issue by Gambware** [glpi-project/glpi#15539] opened 2023-09-05 19:12 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.9

### Bug description

When I edit any task within a ticket that contains multiple tasks, both public and private, the email sent to the requester includes all tasks in the body, including the private ones. This should not happen, as the requester should not have access to them.

### Page URL

N/A

### Steps To reproduce

1. Create a Ticket with requester 
2. Add a private Task in this ticket
3. Add a public task in this ticket
4. Check that the email its ok
5. Edit any task and update it 
6. Check that the requester will receive all tasks, including the private ones.

### Your GLPI setup information

Operating system: Linux XXX-CLD1-Cliente-FRONTEND-001 5.15.0-1042-azure #49-Ubuntu SMP Tue Jul 11 17:28:46 UTC 2023 x86_64 PHP 8.1.2-1ubuntu2.14 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, 	cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, imap, intl, json, 	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, redis, session, shmop, soap, sockets, 	sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="1024M" post_max_size="50M" safe_mode="" session.save_handler="files" 	upload_max_filesize="50M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0 Server Software: Ubuntu 20.04 	Server Version: 10.3.38-MariaDB-0ubuntu0.20.04.1 	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: teste@192.168.1.4/db_prod 	Host info: 192.168.1.4 via TCP/IP 	 PHP version (8.1.2-1ubuntu2.14) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter. curl extension is installed. gd extension is installed. intl extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (10.3.38) is supported. No files from previous Cliente version detected. The log file has been created successfully. Write access to /www/Cliente_downstream/Cliente/files/_cache has been validated. Write access to /dados/Cliente_downstream/Cliente/etc has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_cron has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_documents has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_dumps has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_graphs has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_lock has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_pictures has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_plugins has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_rss has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_sessions has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_tmp has been validated. Write access to /dados/Cliente_downstream/Cliente/files/_uploads has been validated.  Web server root directory configuration seems safe. Sessions configuration is secured. OS and PHP are relying on 64 bits integers. exif extension is installed. ldap extension is installed. openssl extension is installed. Following extensions are installed: bz2, Phar, zip. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /dados/www/Cliente/marketplace has been validated. Timezones seems loaded in database.
--

Cliente_ROOT: "/dados/www/Cliente" Cliente_CONFIG_DIR: "/dados/Cliente_downstream/Cliente/etc" Cliente_MARKETPLACE_ALLOW_OVERRIDE: false Cliente_VAR_DIR: "/dados/Cliente_downstream/Cliente/files" Cliente_DOC_DIR: "/dados/Cliente_downstream/Cliente/files/_documents" Cliente_CRON_DIR: "/dados/Cliente_downstream/Cliente/files/_cron" Cliente_DUMP_DIR: "/dados/Cliente_downstream/Cliente/files/_dumps" Cliente_GRAPH_DIR: "/dados/Cliente_downstream/Cliente/files/_graphs" Cliente_LOCK_DIR: "/dados/Cliente_downstream/Cliente/files/_lock" Cliente_PICTURE_DIR: "/dados/Cliente_downstream/Cliente/files/_pictures" Cliente_PLUGIN_DOC_DIR: "/dados/Cliente_downstream/Cliente/files/_plugins" Cliente_RSS_DIR: "/dados/Cliente_downstream/Cliente/files/_rss" Cliente_SESSION_DIR: "/dados/Cliente_downstream/Cliente/files/_sessions" Cliente_TMP_DIR: "/dados/Cliente_downstream/Cliente/files/_tmp" Cliente_UPLOAD_DIR: "/dados/Cliente_downstream/Cliente/files/_uploads" Cliente_CACHE_DIR: "/dados/Cliente_downstream/Cliente/files/_cache" Cliente_LOG_DIR: "/var/log/Cliente" Cliente_SYSTEM_CRON: true Cliente_MARKETPLACE_DIR: "/dados/www/Cliente/marketplace" Cliente_USE_CSRF_CHECK: "1" Cliente_CSRF_EXPIRES: "7200" Cliente_CSRF_MAX_TOKENS: "100" Cliente_USE_IDOR_CHECK: "1" Cliente_IDOR_EXPIRES: "7200" Cliente_ALLOW_IFRAME_IN_RICH_TEXT: false Cliente_SERVERSIDE_URL_ALLOWLIST: ["/^(https?\|feed):\\/\\/[^@:]+(\\/.*)?$/"] Cliente_TELEMETRY_URI: "https://telemetry.Cliente-project.org" Cliente_INSTALL_MODE: "TARBALL" Cliente_NETWORK_MAIL: "Cliente@teclib.com" Cliente_NETWORK_SERVICES: "https://services.Cliente-network.com" Cliente_MARKETPLACE_MANUAL_DOWNLOADS: true Cliente_USER_AGENT_EXTRA_COMMENTS: "" Cliente_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1" Cliente_AJAX_DASHBOARD: "1" Cliente_CALDAV_IMPORT_STATE: 0 Cliente_DEMO_MODE: "0" Cliente_CENTRAL_WARNINGS: "1" Cliente_LOCAL_I18N_DIR: "/dados/Cliente_downstream/Cliente/files/_locales" Cliente_INVENTORY_DIR: "/dados/Cliente_downstream/Cliente/files/_inventories" Cliente_NETWORK_REGISTRATION_API_URL: "https://services.Cliente-network.com/api/registration/" Cliente_MARKETPLACE_PLUGINS_API_URI: "https://services.Cliente-network.com/api/marketplace/" Cliente_I18N_DIR: "/dados/www/Cliente/locales" Cliente_VERSION: "10.0.9" Cliente_SCHEMA_VERSION: "10.0.9@77fc44668eaae89b61d95fe606d20d93d66110cd" Cliente_MARKETPLACE_PRERELEASES: false Cliente_MIN_PHP: "7.4.0" Cliente_MAX_PHP: "8.3.0" Cliente_YEAR: "2023"

htmlawed/htmlawed version 1.2.14 in (/dados/www/Cliente/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.8.0 in (/dados/www/Cliente/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/dados/www/Cliente/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.4.4 in (/dados/www/Cliente/marketplace/pdf/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/dados/www/Cliente/vendor/michelf/php-markdown/Michelf) true/punycode in (/dados/www/Cliente/vendor/true/punycode/src) iamcal/lib_autolink in (/dados/www/Cliente/vendor/iamcal/lib_autolink) sabre/dav in (/dados/www/Cliente/vendor/sabre/dav/lib/DAV) sabre/http in (/dados/www/Cliente/vendor/sabre/http/lib) sabre/uri in (/dados/www/Cliente/vendor/sabre/uri/lib) sabre/vobject in (/dados/www/Cliente/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/dados/www/Cliente/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/dados/www/Cliente/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/dados/www/Cliente/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/dados/www/Cliente/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/dados/www/Cliente/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/dados/www/Cliente/vendor/elvanto/litemoji/src) symfony/console in (/dados/www/Cliente/vendor/symfony/console) scssphp/scssphp in (/dados/www/Cliente/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/dados/www/Cliente/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/dados/www/Cliente/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/dados/www/Cliente/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/dados/www/Cliente/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/dados/www/Cliente/vendor/ramsey/uuid/src) psr/log in (/dados/www/Cliente/vendor/psr/log/Psr/Log) psr/simple-cache in (/dados/www/Cliente/vendor/psr/simple-cache/src) psr/cache in (/dados/www/Cliente/vendor/psr/cache/src) league/csv in (/dados/www/Cliente/vendor/league/csv/src) mexitek/phpcolors in (/dados/www/Cliente/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/dados/www/Cliente/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/dados/www/Cliente/vendor/guzzlehttp/psr7/src) Cliente-project/inventory_format in (/dados/www/Cliente/vendor/Cliente-project/inventory_format/lib/php) wapmorgan/unified-archive in (/dados/www/Cliente/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/dados/www/Cliente/vendor/paragonie/sodium_compat/src) symfony/cache in (/dados/www/Cliente/vendor/symfony/cache) html2text/html2text in (/dados/www/Cliente/vendor/html2text/html2text/src) symfony/css-selector in (/dados/www/Cliente/vendor/symfony/css-selector) symfony/dom-crawler in (/dados/www/Cliente/vendor/symfony/dom-crawler) twig/twig in (/dados/www/Cliente/vendor/twig/twig/src) twig/string-extra in (/dados/www/Cliente/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 not found symfony/polyfill-php82 in (/dados/www/Cliente/vendor/symfony/polyfill-php82) league/oauth2-client in (/dados/www/Cliente/vendor/league/oauth2-client/src/Provider) league/oauth2-google in (/dados/www/Cliente/vendor/league/oauth2-google/src/Provider) thenetworg/oauth2-azure in (/dados/www/Cliente/vendor/thenetworg/oauth2-azure/src/Provider) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Server: 'ldaps://4.228.89.125', Port: '636', BaseDN: 'OU=AADDC Users,DC=teste,DC=com,DC=br', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'Cliente123.ad@teste.com.br', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@127.0.0.1)

Name: 'Chamados TESTE' Active: Yes 	Server: '{outlook.office365.com:993/imap-oauth-1/ssl}' Login: 'chamado@testes.com.br' Password: Yes

actualtime           Name: ActualTime                     Version: 2.1.0      State: Enabled                                  		Install Method: Marketplace 	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Installed / not activated                		Install Method: Marketplace 	news                 Name: Alertas                        Version: 1.12.1     State: Not installed                            		Install Method: Marketplace 	chatcorp             Name: API Chat Corp                  Version: 1.5.6      State: Enabled                                  		Install Method: Manual 	barcode              Name: Barcode                        Version: 2.7.1      State: Not installed                            		Install Method: Marketplace 	fields               Name: Campos adicionais              Version: 1.20.6     State: Enabled                                  		Install Method: Marketplace 	screenshot           Name: Captura de tela                Version: 2.0.2      State: Not installed                            		Install Method: Marketplace 	credit               Name: Cargas de crédito              Version: 1.11.3     State: Not installed                            		Install Method: Marketplace 	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated                		Install Method: Marketplace 	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                  		Install Method: Manual 	accounts             Name: Contas                         Version: 3.0.3      State: Not installed                            		Install Method: Marketplace 	dividirdropdown      Name: Dividir Dropdown               Version: 1.0.0      State: Installed / not activated                		Install Method: Manual 	escalade             Name: Escalonamento                  Version: 2.9.2      State: Enabled                                  		Install Method: Marketplace 	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                  		Install Method: Marketplace 	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                  		Install Method: Marketplace 	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                  		Install Method: Marketplace 	genericobject        Name: Gerenciamento de objetos       Version: 2.14.1     State: Installed / not activated                		Install Method: Marketplace 	datainjection        Name: Importação de dados            Version: 2.13.2     State: Enabled                                  		Install Method: Marketplace 	jsaddons             Name: JS Addons                      Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace 	releases             Name: Liberações                     Version: 2.0.3      State: Not installed                            		Install Method: Marketplace 	timelineticket       Name: Linha do tempo dos chamados    Version: 10.0+1.1   State: Enabled                                  		Install Method: Marketplace 	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                  		Install Method: Manual 	mailbehaviours       Name: Mail Behaviours                Version: 2.0.0      State: Enabled                                  		Install Method: Manual 	moreticket           Name: Mais Chamados                  Version: 1.7.1      State: Not installed                            		Install Method: Marketplace 	mreporting           Name: Mais Relatórios                Version: 1.8.2      State: Installed / not activated                		Install Method: Marketplace 	satisfaction         Name: Mais satisfação                Version: 1.6.1      State: Installed / not activated                		Install Method: Marketplace 	metabase             Name: Metabase                       Version: 1.3.2      State: Installed / not activated                		Install Method: Marketplace 	mydashboard          Name: Meu Painel                     Version: 2.1.4      State: Installed / not activated                		Install Method: Manual 	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                  		Install Method: Manual 	dashboard            Name: Painel                         Version: 1.0.3      State: Enabled                                  		Install Method: Manual 	phpsaml              Name: PHP SAML                       Version: 1.2.1      State: Installed / not activated                		Install Method: Manual 	ticketfilter         Name: Plugin TICKETFILTER            Version: 1.0.0      State: Enabled                                  		Install Method: Marketplace 	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Enabled                                  		Install Method: Marketplace 	reports              Name: Relatórios                     Version: 1.16.0     State: Installed / not activated                		Install Method: Manual 	singlesignon         Name: Single Sign-on                 Version: 1.3.3      State: Enabled                                  		Install Method: Manual 	splitdropdown        Name: Split dropdown                 Version: 1.0.0      State: Not installed                            		Install Method: Manual 	tag                  Name: Tag Management                 Version: 2.11.1     State: Not installed                            		Install Method: Marketplace 	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Not installed                            		Install Method: Marketplace 	tasklists            Name: Tasks list                     Version: 2.0.3      State: Not installed                            		Install Method: Marketplace 	vip                  Name: VIP                            Version: 1.8.2      State: Installed / not activated                		Install Method: Marketplace 	webhook              Name: Webhooks                       Version: 1.0.12     State: Enabled                                  		Install Method: Marketplace 	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                  		Install Method: Marketplace

**Comment by cedric-anne** [comment] 2023-10-03 11:34
Hi @Gambware ,

I am not able to reproduce on GLPI 10.0.10. I guess it has been fixed by #15297. Could you confirm?

**Comment by trasher** [comment] 2023-10-13 06:18
Ne feedback from a while, closing

**Closed by trasher** 2023-10-13 06:18 UTC
Labels: Need feedback
