### ISSUE TITLE
[9.3.0] No closed nor resolved tickets on schedule

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#4433] opened 2018-08-03 12:46 UTC
* Steps to reproduce (which actions have you made) :
Look at the schedule

* Expected result :
See the closed and resolved tickets (all tickets indeed)

* Actual result :
Blank schedule, not any closed and resolved tickets

* URL of the page :
/front/planning.php

* Links of reported issue on the forum
[Resolved or closed tickets are no longer visible in the schedule](https://forum.glpi-project.org/viewtopic.php?id=162419)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
GLPI 9.3.0 - PHP 7.2.8 - Zend OPcache v7.2.8 - APCu 5.1.12
```

**Comment by naisspas** [comment] 2018-08-06 14:51
Exactly the same problem here.
GLPI 9.3.0 - PHP 7.1.20 - Zend OPcache v7.1.20 - APCu 5.1.12

**Comment by M-Falken** [comment] 2018-08-07 23:10
Related to this: https://github.com/orthagh/glpi/commit/99f23f8e7c83c4f5954b563f3544f59606b1ad73

**Comment by orthagh** [comment] 2018-08-08 13:49
Duplicate of #4313

In planning view (not list) done events will still be displayed.

The above commit (https://github.com/glpi-project/glpi/issues/4433#issuecomment-411231352) is actually to fix this issue (and #4313 )

**Closed by orthagh** 2018-08-08 13:49 UTC
