### ISSUE TITLE
[glpi 9.5.6]  mail collector error link url not accessible

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#10933] opened 2022-03-09 14:37 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.6

### Bug description

Good morning,
When I receive a request in a function box and I move this email to the mailbox of the mail collector, the links in the tracking are in error:
By email I get: imap://ydao@imap.toto-lyon.fr:993/fetch%3EUID%3E/INBOX%3E130813
By webmail I get: https://webmail.toto-lyon.fr/#NOP
So the two links don’t work.
If I receive the mail in the collector’s direct inbox everything works!

**Comment by cedric-anne** [comment] 2022-03-10 07:01
Hi,

Could you attach here the email that causes this issue, in eml format ?

Regards

**Comment by falco2001** [comment] 2022-03-10 08:27
Good morning,
this is a standard email sent, but an email sent to a function box
It’s copying it into the mail collector’s box and then writing a follow-up that makes the links in the original function box unreadable!
In fact the problem comes from the follow-up that is not adapted to a function box. I have not yet looked at the code, but if you have an idea? 
Thank you

**Comment by cedric-anne** [comment] 2022-03-10 08:38
I do not understand what you are trying to explain.

What is a `function box` ? What kind of link are you talking about ?

Really, having the source of the email that cause your issue can really help to investigate.

**Comment by falco2001** [comment] 2022-03-10 09:19
a function box is a mailbox shared by several people

**Comment by cedric-anne** [comment] 2022-03-10 09:43
Unless you provide us the source of the email, I guess noone will investigate on this.

**Comment by falco2001** [comment] 2022-03-11 08:24
Good morning,
here is the mail copied in the collector’s box that poses a problem in the processing since in the mail tool (thunderbird) and in the webmail url to access the ticket is wrong.
Thank you
[test yves 11 03 2022 912 - Yves Da (Yves.Dao - 2022-03-11 0913.eml.zip](https://github.com/glpi-project/glpi/files/8230285/test.yves.11.03.2022.912.-.Yves.Da.Yves.Dao.-.2022-03-11.0913.eml.zip)

**Comment by cedric-anne** [comment] 2022-03-11 10:48
I still not understand what is the issue. Which URL are you talking about ?

Here is the generated notification based on your mail:
![image](https://user-images.githubusercontent.com/33253653/157852898-36cd241d-b97c-4d70-9f57-3a8d5036681e.png)

**Comment by falco2001** [comment] 2022-03-11 13:13
url in mail in writing a follow-up
By email I get: imap://ydao@imap.toto-lyon.fr:993/fetch%3EUID%3E/INBOX%3E130813
By webmail I get: https://webmail.toto-lyon.fr/#NOP
So the two links don’t work.

**Comment by cedric-anne** [comment] 2022-03-11 13:27
But, again, what is this URL you are talking about ? Which value is expected ? Should this be the URL of the ticket ? Or should it be a custom URL added in your notification template ?

Maybe a screenshot could help.

**Comment by falco2001** [comment] 2022-03-11 13:50
hello,

01.jpg with  url  = By email I get: [imap://ydao@imap.toto-lyon.fr:993/fetch%3EUID%3E/INBOX%3E130813](mailto:imap://ydao@imap.toto-lyon.fr:993/fetch%3EUID%3E/INBOX%3E130813)

02.jpg  with url By webmail I get: https://webmail.toto-lyon.fr/#NOP
![Clipboard02](https://user-images.githubusercontent.com/31952346/157880323-77634a43-7c8c-43a2-8839-3c34efc91f4e.jpg)
![Clipboard01](https://user-images.githubusercontent.com/31952346/157880326-61c6c70d-8a44-423e-8c62-261ef6705487.jpg)

**Comment by cedric-anne** [comment] 2022-03-11 13:52
You still not answer my precise questions, I'm giving up.

**Comment by falco2001** [comment] 2022-03-11 13:54
![InkedClipboard02_LI](https://user-images.githubusercontent.com/31952346/157880926-2bc6d589-2df4-413d-b3e4-4c6f8e725cc6.jpg)
![InkedClipboard01_LI](https://user-images.githubusercontent.com/31952346/157880934-fd76975a-d316-4717-946e-407206525fc9.jpg)

**Comment by cedric-anne** [comment] 2022-03-11 14:10
I guess it is due to the fact that notification is sent to an anonymous user (from the GLPI point of view), and therefore there is no link generated. 
https://github.com/glpi-project/glpi/blob/c8dc120695213ca80d67cf88e556bd185fc30583/src/NotificationTarget.php#L637-L639
This is an intended behaviour as anonymous users should not receive links to GLPI. They may be, for instance, external suppliers.

So, basically, the generated html code looks like `<a href="">Nouveau Ticket : test yves</a>`, which means that link points to current URL of the email.

Default notifications code is `<a href="##ticket.url##">##ticket.url##</a>`, so, if URL is empty, there is nothing shown as link test is empty. You can prevent generating this kind of links by using `##IFticket.url##<a href="##ticket.url##">##ENDIFticket.url## ... ##IFticket.url##</a>##ENDIFticket.url##` in your notification template.

I close this as it is not an issue.

**Closed by cedric-anne** 2022-03-11 14:10 UTC
Labels: Need feedback

**Comment by falco2001** [comment] 2022-03-11 14:17
Thank you very much. I’ll see if it’s possible to create a URL? Is it possible.
Thank you for your speed and professionalism
