### ISSUE TITLE
Software installation count on software list differ count inside the software

### ISSUE THREAD

**Issue by fgendorf** [glpi-project/glpi#6340] opened 2019-09-20 14:32 UTC
**Describe the bug**

when I see the column Number of installations in software list show a number that differ when I see inside the software on Installation TAB

**Page(s) URL**

/front/software.php - software list
/front/software.form.php?id=198 - inside the software 

**Expected behavior**

show the same number of installed software in list and in tab installations

**Screenshots**

![screen2](https://user-images.githubusercontent.com/15034336/65334937-d023d800-db99-11e9-8c8e-98013b07bd2d.png)
![screen1](https://user-images.githubusercontent.com/15034336/65334938-d023d800-db99-11e9-8a2f-eb6adc998d09.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
{
    "glpi": {
        "uuid": "0VCdUigR9KxVvVLrgYvz31lF9VZPdFAdaur4fQZ0",
        "version": "9.4.3",
        "plugins": [
            {
                "key": "fields",
                "version": "1.10.0"
            },
            {
                "key": "addressing",
                "version": "2.8.0"
            },
            {
                "key": "datainjection",
                "version": "2.7.0"
            },
            {
                "key": "formcreator",
                "version": "2.8.4"
            },
            {
                "key": "fusioninventory",
                "version": "9.4+1.1"
            },
            {
                "key": "order",
                "version": "2.5.1"
            },
            {
                "key": "pdf",
                "version": "1.5.0"
            },
            {
                "key": "mailanalyzer",
                "version": "1.6.0"
            },
            {
                "key": "mreporting",
                "version": "1.6.1"
            },
            {
                "key": "ocsinventoryng",
                "version": "1.6.0"
            },
            {
                "key": "reports",
                "version": "1.13.1"
            },
            {
                "key": "simcard",
                "version": "1.4.2"
            }
        ],
        "default_language": "pt_BR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "500-1000",
            "avg_networkequipments": "0-500",
            "avg_tickets": "10000-50000",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "500-1000",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": true,
            "notifications_modes": [],
            "notifications": [
                "mailing",
                "ajax"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "MySQL Community Server (GPL)",
            "version": "5.7.25",
            "size": "1611.9",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "",
            "version": ""
        },
        "php": {
            "version": "7.2.19",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "sodium",
                "session",
                "standard",
                "apache2handler",
                "mysqlnd",
                "PDO",
                "xml",
                "apcu",
                "apc",
                "bcmath",
                "bz2",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "imap",
                "intl",
                "json",
                "ldap",
                "exif",
                "mysqli",
                "pdo_mysql",
                "Phar",
                "posix",
                "readline",
                "shmop",
                "SimpleXML",
                "soap",
                "sockets",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "xmlwriter",
                "xsl",
                "zip",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "128M",
                "post_max_size": "25M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "20M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "",
            "version": "4.15.0-60-generic"
        }
    }
}
```

**Comment by trasher** [comment] 2019-09-27 07:58
I cannot reproduce with latest release; either this has been fixed since or we miss informations to reproduce.

**Comment by yllen** [comment] 2019-10-09 10:28
I can reproduce this.
In search engine list you have all versions of software (filter is on software item)
In installation tab of a software you have a filter on computer.
So difference between list are installation in a computer not in current entity, computer deleted.

**Comment by fgendorf** [comment] 2019-10-09 10:54
Hi @yllen , I'm not sure about you talking about same thing, the images I sent are just about software, on Assets -> Software (2nd image) list all offices and show the number of installations column, I choose Office 2010 (1st image) and information in tab Installations are different. According my inventory the number of Offices 2010 installed are the number in TAB Installations, less the number of license (2nd image).
I always remove all installed software of computers when I delete computers, I think there a problem in SQL query to show information um software list.

**Comment by cconard96** [comment] 2020-06-15 01:17
Hi @fgendorf with 9.5.0, there was a fairly substantial rework on how Software works in order to allow it to work with more than just Computers. I just ran a few tests with multiple computers and software/software versions in different entities and wasn't able tor recreate the issue. The installation count seems correct and consistent between the Installations tab and search field. Both are only showing installations on computers in the current entity. Could you try and recreate the issue on the 9.5.0-RC1 release and let me know if the issue is resolved?

If it is still an issue, could you share how you were able to recreate it?

**Comment by trasher** [comment] 2020-07-15 08:02
No feedback from a while, closing.

**Closed by trasher** 2020-07-15 08:02 UTC
Labels: Need feedback
