### ISSUE TITLE
[9.3] mail import not adding inline image as attachment

### ISSUE THREAD

**Issue by cyril2018** [glpi-project/glpi#4615] opened 2018-09-11 10:13 UTC
When receiving an email into GLPI to be converted into a ticket, all images inside the email are shown as numbers with # in front and end.
example: #78764fb3-d9d62df8-5b978c6e018259.62890971#

When going to that ticket --> processing ticket-->associate an existing document. I am able to select that specific image and add it.

So it's actually converting the inline image to a file inside the images/JPG/<folder>. But it does not add it to the ticket automatically.

There's no difference if I use the automatic mailgate action or if I click on the receiver "get email tickets now".

At General --> Assistance --> "Use rich text for helpdesk" is set to no. We do not want to use rich text.

**Comment by cedric-anne** [comment] 2018-09-11 10:17
Hi,

It seems like a duplicate of https://github.com/glpi-project/glpi/issues/4396.
Can you try using this fix: https://github.com/glpi-project/glpi/pull/4472.

Regards

**Comment by cyril2018** [comment] 2018-09-11 10:40
Wow, I have been searching for this but could not find anything.
That fix did the trick. Thank you for your quick response!

**Closed** 2018-09-11 10:40 UTC
Labels: Need feedback, bug, duplicate
