### ISSUE TITLE
Ticket created by mailgate doesn't have description

### ISSUE THREAD

**Issue by pzbdkp** [glpi-project/glpi#10622] opened 2022-02-14 09:35 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

We've updated from GLPI 9.4.5 to GLPI 9.5.7. Config of "receivers" hasn't changed.

When a ticket is created by mailgate, GLPI retrieves sender as requester and title from subject. But we've noticed the body of e-mail isn't available in the description of the ticket.

### Relevant log output

```shell
none
```

### Your GLPI setup information

[code]
GLPI 9.5.7 ( => /var/www/glpi) 
Installation mode: TARBALL 
Current language:en_GB
--
Operating system: Linux xxxxxx 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, 	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
 	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) 
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
 	upload_max_filesize="2M"  
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.xxx.xxx.xx Port 443)
 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 
Server Software: (Ubuntu)
 	Server Version: 8.0.26-0ubuntu0.20.04.3
 	Server SQL Mode:  	Parameters: glpi@localhost/glpi
 	Host info: Localhost via UNIX socket

 PHP version is at least 7.2.0 - Perfect!
 Sessions support is available - Perfect!
 Allocated memory > 64 Mio - Perfect!
 mysqli extension is installed ctype extension is installed
 fileinfo extension is installed
 json extension is installed
 mbstring extension is installed
 iconv extension is installed
 zlib extension is installed
 curl extension is installed
 gd extension is installed
 simplexml extension is installed
 intl extension is installed
 ldap extension is installed
 apcu extension is installed
 Zend OPcache extension is installed
 xmlrpc extension is installed
 exif extension is installed
 zip extension is installed
 bz2 extension is installed
 sodium extension is installed
 Database version seems correct (8.0.26) - Perfect!
 Timezones seems loaded in database
 The log file has been created successfully.
 Write access to /var/www/glpi/files/_cache has been validated.
 Write access to /var/www/glpi/config has been validated.
 Write access to /var/www/glpi/files/_cron has been validated.
 Write access to /var/www/glpi/files has been validated.
 Write access to /var/www/glpi/files/_dumps has been validated.
 Write access to /var/www/glpi/files/_graphs has been validated.
 Write access to /var/www/glpi/files/_lock has been validated.
 Write access to /var/www/glpi/files/_pictures has been validated.
 Write access to /var/www/glpi/files/_plugins has been validated.
 Write access to /var/www/glpi/files/_rss has been validated.
 Write access to /var/www/glpi/files/_sessions has been validated.
 Write access to /var/www/glpi/files/_tmp has been validated.
 Write access to /var/www/glpi/files/_uploads has been validated.
 Write access to /var/www/glpi/marketplace has been validated.
 Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
 Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

 GLPI_ROOT: /var/www/glpi
 GLPI_CONFIG_DIR: /var/www/glpi/config
 GLPI_VAR_DIR: /var/www/glpi/files
 GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
 GLPI_USE_CSRF_CHECK: 1
 GLPI_CSRF_EXPIRES: 7200
 GLPI_CSRF_MAX_TOKENS: 100
 GLPI_USE_IDOR_CHECK: 1
 GLPI_IDOR_EXPIRES: 7200
 GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
 GLPI_INSTALL_MODE: TARBALL
 GLPI_NETWORK_MAIL: glpi@teclib.com
 GLPI_NETWORK_SERVICES: https://services.glpi-network.com
 GLPI_MARKETPLACE_PRERELEASES: 
 GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
 GLPI_USER_AGENT_EXTRA_COMMENTS: 
 GLPI_AJAX_DASHBOARD: 1
 GLPI_CALDAV_IMPORT_STATE: 0
 GLPI_DEMO_MODE: 0
 GLPI_FORCE_EMPTY_SQL_MODE: 1
 GLPI_DOC_DIR: /var/www/glpi/files
 GLPI_CACHE_DIR: /var/www/glpi/files/_cache
 GLPI_CRON_DIR: /var/www/glpi/files/_cron
 GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
 GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
 GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
 GLPI_LOCK_DIR: /var/www/glpi/files/_lock
 GLPI_LOG_DIR: /var/www/glpi/files/_log
 GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
 GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
 GLPI_RSS_DIR: /var/www/glpi/files/_rss
 GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
 GLPI_TMP_DIR: /var/www/glpi/files/_tmp
 GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
 GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ 
 GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
 GLPI_I18N_DIR: /var/www/glpi/locales
 GLPI_VERSION: 9.5.7
 GLPI_SCHEMA_VERSION: 9.5.7
 GLPI_MIN_PHP: 7.2.0
 GLPI_YEAR: 2022

 htmlawed/htmlawed version 1.2.5 in (/var/www/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
 simplepie/simplepie version 1.5.6 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
 michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src)
 iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
 sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
 sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
 sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
 sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
 laminas/laminas-cache in (/var/www/glpi/vendor/laminas/laminas-cache/src)
 laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
 laminas/laminas-serializer in (/var/www/glpi/vendor/laminas/laminas-serializer/src)
 monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
 sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
 elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
 symfony/console in (/var/www/glpi/vendor/symfony/console)
 scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
 laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
 laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
 rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
 blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
 ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
 psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
 mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
 guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
 guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
 wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
 paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
 phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Server: 'w.x.y.z', Port: '389', BaseDN: 'OU=XXX,OU=XXX,OU=User Accounts,DC=XXX,DC=XX', Connection filter: 		'(&(objectClass=user)(objectCategory=person))', RootDN: 'XXX', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@w.x.y.z)

Name: 'xxx@yyy.com' Active: Yes 	Server: '{w.x.y.z:1143/imap/ssl/novalidate-cert/notls}Support ICT' Login: 'xxx@yyy.com' Password: 		Yes

behaviors            Name: Behaviours                     Version: 2.2.1      State: Error / to clean
[/code]

**Comment by pzbdkp** [comment] 2022-02-15 09:17
After long search I've found a closed issue with a simular problem. It never received a solution, but was closed because of inactivity; see #8333.

**Comment by cedric-anne** [comment] 2022-02-15 16:46
Hi,

Please attach email that causes this issue in eml format, so we could investigate.

Regards

**Comment by pzbdkp** [comment] 2022-02-16 06:58
Hi,

An example in attachement.
[GLPI.zip](https://github.com/glpi-project/glpi/files/8077463/GLPI.zip)

Problem exists for all e-mails retrieved by mail receiver.

**Comment by cedric-anne** [comment] 2022-02-16 12:20
Attached file does not seems to be a valid email source. Headers are translated, they should not.

**Comment by pzbdkp** [comment] 2022-02-16 12:34
@cedric-anne : that's probably because I used this how-to to save to .eml from outlook: https://www.extendoffice.com/documents/outlook/5235-outlook-convert-message-to-eml.html
My outlook client is in Dutch.

There isn't a direct "save-to-eml" option in Outlook...

**Comment by cedric-anne** [comment] 2022-02-16 12:35
You may do it using Thunderbird.

**Comment by pzbdkp** [comment] 2022-02-16 12:42
Found another way to export to eml from Outlook (Web Access): https://www.codetwo.com/kb/export-email-to-file/#outlook-on-the-web

New attachement
[GLPI.zip](https://github.com/glpi-project/glpi/files/8079923/GLPI.zip)

**Comment by cedric-anne** [comment] 2022-02-16 13:24
It works on my side.

![image](https://user-images.githubusercontent.com/33253653/154273336-6bbd1ceb-2577-4448-b76b-5185086073a1.png)

**Comment by husisusi** [comment] 2022-02-22 11:16
It works on my side too.
![grafik](https://user-images.githubusercontent.com/8606735/155121647-031f09ee-c30f-4182-99c1-ed3e2b5d3ace.png)

**Comment by cedric-anne** [comment] 2022-03-18 12:47
@pzbdkp 

Is your issue still present ? Is it on all tickets ?

**Comment by pzbdkp** [comment] 2022-03-18 13:00
The problem still exists and has an effect on every ticket by e-mail.

As a workaround, I've installed form creator and created a simple ticket creation form so most of my users can create a ticket that way. It only helps the internal users, because GLPI installation isn't available for users on other locations.

**Comment by cedric-anne** [comment] 2022-03-18 13:13
> The problem still exists and has an effect on every ticket by e-mail.

This is really weird. Many people are using the mail collector feature. We should have many feedbacks about this issue.

Can you try to reproduce on the latest [GLPI 9.5 nightly build](https://nightly.glpi-project.org/glpi/) ?

**Comment by trasher** [comment] 2022-04-19 06:44
No feedback from a while, closing.

**Closed by trasher** 2022-04-19 06:44 UTC
Labels: Need feedback
