### ISSUE TITLE
Software inventory problem : PHP Warning (2): Undefined property: stdClass::$manufacturers_id

### ISSUE THREAD

**Issue by stephaneJA** [glpi-project/glpi#15632] opened 2023-09-26 09:34 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

- When I deactivate "Software" in Administration/Inventory/Import Options, GLPI-Agent (1.5) pulls up the inventory  and the link is made with an existing item in the inventory.
- When I activate "Software" in Administration/Inventory/Import Options, GLPI-Agent indicates an error "The number of elements in the type definition string must match the number of bind variables",  a new agent is created, but the link is not made with an existing item in the inventory (Element = 0)

### Relevant log output

```shell
log GLPI-agent 1.5 :

[Tue Sep 26 11:05:38 2023][error] [http client] communication error: 500 Internal Server Error, The number of elements in the type definition string must match the number of bind variables
[Tue Sep 26 11:05:38 2023][debug2] [http client] E8DEF30E: received message:
{"status":"error","message":"The number of elements in the type definition string must match the number of bind variables","expiration":24}
[Tue Sep 26 11:05:38 2023][error] [http client] E8DEF30E: server error: The number of elements in the type definition string must match the number of bind variables

/var/www/glpi/files/_log/php-errors.log :

[2023-09-26 09:42:10] glpiphplog.WARNING:   *** PHP Warning (2): Undefined property: stdClass::$manufacturers_id in /var/www/glpi/src/Inventory/Asset/Software.php at line 717 597 605
  Backtrace :
  src/Inventory/Asset/Software.php:462               Glpi\Inventory\Asset\Software->storeSoftware()
  src/Inventory/Asset/MainAsset.php:933              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:848              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1640                        Rule->process()
  src/Inventory/Asset/MainAsset.php:573              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:709                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:340                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  index.php:93                                       include_once()
```

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.9 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux vm-bioweb 4.19.0-24-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64
PHP 8.1.18 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Server Software: Debian 10
	Server Version: 10.3.39-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiadmin@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (8.1.18) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.39) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/glpi":
‣ "/var/www/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/glpi/public".
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpi/files"
GLPI_CACHE_DIR: "/var/www/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.9"
GLPI_SCHEMA_VERSION: "10.0.9@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@xyz.fr)

</pre></details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Adressage IP                   Version: 3.0.1      State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.20.5     State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.2      State: Installed / not activated               
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

The problem is the same with GLPI 10.0.7 and GLPI-agent 1.4

**Comment by stonebuzz** [comment] 2023-09-26 10:07
Hi @stephaneJA 
can you post here related inventory file ?

Best regards

**Comment by stephaneJA** [comment] 2023-09-26 13:56
Hi !

Here is the json file.

[rochefaurio-2023-09-21-17-42-18.zip](https://github.com/glpi-project/glpi/files/12728418/rochefaurio-2023-09-21-17-42-18.zip)

Thanks !

**Comment by trasher** [comment] 2023-09-26 13:58
Provided file is invalid: 

```
File has not been imported: `JSON does not validate. Violations: Invalid ipv4 at #->properties:content->properties:networks->items[2]:2->properties:ipaddress `.
```

**Comment by stonebuzz** [comment] 2023-09-26 14:00
IPs have been obfuscated

**Comment by trasher** [comment] 2023-09-26 14:02
I did not check what's wrong; it's quite easy to check it using simple file upload in GLPI test instance.

Or you can also use command line tool:
```
cd glpi/vendor/glpi-project/inventory_format
./bin/validate /path/to/file.json
```

**Comment by stonebuzz** [comment] 2023-09-26 14:03
Can you retry with this

[rochefaurio_V2.zip](https://github.com/glpi-project/glpi/files/12728502/rochefaurio_V2.zip)

I have removed software with non-breaking spaces To see if that's what's causing the problem

**Comment by stephaneJA** [comment] 2023-09-26 14:34
Sorry for the the Ips, that wasn't a good idea... :-(  Here is a new file.
 

@trasher  I've tried with command line tool, but nothing occurs.
@stonebuzz  I've tried with GUI and with command line, but nothing occurs
There is no new agent in the two cases.

[rochefaurio-2023-09-21-17-42-18-ip.zip](https://github.com/glpi-project/glpi/files/12728812/rochefaurio-2023-09-21-17-42-18-ip.zip)

Thanks for your help !

**Comment by stonebuzz** [comment] 2023-09-26 14:36
do you have software/manufacturer dictionaries?

**Comment by stephaneJA** [comment] 2023-09-27 06:07
@stonebuzz : yes, I had some dictionaries from old inventories under Fusion Inventory  !  I have disabled them, and it seems to work now !
The agent correctly uploads a new element in GLPI, which is linked to an existing computer.

I've been looking for several days !

Sorry for the inconvenience and thanks a lot!

**Comment by stonebuzz** [comment] 2023-09-27 06:07
No problem =)

Now you need to clean up your dictionaries 

Best regards

**Comment by stonebuzz** [comment] 2023-09-27 06:43
Can you export your dictionaries and upload them here?

**Comment by stephaneJA** [comment] 2023-09-27 07:04
Here it is :
[rules.zip](https://github.com/glpi-project/glpi/files/12735474/rules.zip)

These are old rules implemented a long time ago with the FusionInventory agent, which I no longer used.

**Comment by trasher** [comment] 2023-09-27 07:06
Thank you. We will try to reproduce and investigate to be sure this cannot be reproduced nowadays with GLPI rules.

**Comment by stonebuzz** [comment] 2023-09-27 07:29
I was unable to reproduce

test with or without the rules when creating/updating the computer, with or without agent, php 7.4 and php8.1

I'm closing this issue. Feel free to reopen if you need to.

Best regards

**Closed by stonebuzz** 2023-09-27 07:29 UTC
Labels: Need feedback
