### ISSUE TITLE
Incorrect "Pending validation" message shown on adding ticket solution

### ISSUE THREAD

**Issue by lfardin** [glpi-project/glpi#11666] opened 2022-05-23 18:12 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

When a solution is included to a ticket, if the ticket has validation requests sent, even though they are all approved, the system displays an alert message informing there are pending validations

### Steps To reproduce

Create a ticket
Send and approval request
Validate the approval request
Add a Solution to the ticket

**Comment by cconard96** [comment] 2022-05-24 15:25
I cannot recreate the issue on the latest 10.0 bug fix commit. It looks like the issue may be triggered if the global approval status is set to Waiting still, but in my case, the global approval status was updated properly when I approved the approval request.

**Comment by lfardin** [comment] 2022-05-24 17:35
This is the current approval tab status:

![image](https://user-images.githubusercontent.com/56692658/170096655-1962f93f-4389-4778-a44a-851447481d17.png)

This happens on adding a solution:

![image](https://user-images.githubusercontent.com/56692658/170097625-e0c6bdf3-d8c4-45d1-bc21-ac75463d87bb.png)

**Comment by lfardin** [comment] 2022-06-06 11:13
The issue still exists at 10.0.1

**Comment by paulopera** [comment] 2022-06-08 11:53
Running the 10.0.1 and I have the same issue where the approval was granted but when adding a solution to the ticket, it show a warning information that the ticket isn't approval granted.
![Clipboard - 8 de Junho de 2022 08_40](https://user-images.githubusercontent.com/7115215/172609936-8d61ef09-3711-4f35-9afe-005ddebd25e2.png)

**Comment by guinfox** [comment] 2022-06-15 18:44
Hi guys, any solution to the problem?

**Comment by LuizRicarte** [comment] 2022-08-09 15:51
Hi guys,

I have the same problem, did you find a solution?

**Comment by cconard96** [comment] 2022-08-11 11:43
This may be fixed by:
https://github.com/glpi-project/glpi/pull/12162
This patch would be included in 10.0.3.

**Comment by sandroalvesbrasil** [comment] 2022-08-20 05:50
Hello. I didn't understand what I need to do to fix it. Sorry, I don't know much about github.

**Comment by sandroalvesbrasil** [comment] 2022-08-20 05:50
> This may be fixed by: #12162 This patch would be included in 10.0.3.

Hello. I didn't understand what I need to do to fix it. Sorry, I don't know much about github.

**Comment by cedric-anne** [comment] 2022-12-07 17:24
@lfardin 

Is this issue still present in GLPI 10.0.5?

**Comment by paulopera** [comment] 2022-12-07 17:26
@cedric-anne the issue is fixed.

**Comment by lfardin** [comment] 2022-12-07 17:28
@cedric-anne Fixed: global aproval status is changing, and the message is not being shown.

**Closed** 2022-12-08 07:20 UTC
Labels: bug
