### ISSUE TITLE
Extra <br>

### ISSUE THREAD

**Issue by gqueirolo** [glpi-project/glpi#11370] opened 2022-04-24 13:40 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

An extra br in code

![imagen](https://user-images.githubusercontent.com/104309475/164979246-2a2f8f09-c7ff-40e6-a12e-6f281b90008a.png)

![imagen](https://user-images.githubusercontent.com/104309475/164979273-6eacd6cf-3a64-48e9-91b3-0d0c31a3c65d.png)

### Page URL

.glpi/front/problem.form.php

### Your GLPI setup information

A fresh installation

**Comment by cconard96** [comment] 2022-04-24 21:34
Please elaborate on the issue this is causing. Is it causing an issue with the UI? It isn't very clear from the screenshot and description.

**Comment by gqueirolo** [comment] 2022-04-25 12:06
Hi Curtis, sorry for the little information, I opened the case with little time.
The report is purely aesthetic, but the "Opening date" field is misaligned with the rest of the fields in the ticket, problems & changes forms.
There is only one extra br that does this, removing it sets it accordingly. (attached the screenshots)
Many successes, GLPI is fantastic.
Thank you

![imagen](https://user-images.githubusercontent.com/104309475/165085348-ebe44463-8ba1-4ca2-8e36-73ec7998302d.png)
![imagen](https://user-images.githubusercontent.com/104309475/165085584-ae8b7528-97d9-4b36-b850-93b1024c1c13.png)

![imagen](https://user-images.githubusercontent.com/104309475/165085717-5ea49c95-798c-4269-ab1e-be9f506419fb.png)
![imagen](https://user-images.githubusercontent.com/104309475/165085649-0c479850-c45c-4214-ab3a-a02f798bdc04.png)

**Comment by orthagh** [comment] 2022-04-28 13:47
The problem is triggered by the plugin news.
I'll do a fix in the incoming day.

But i close this issue as it's not related to glpi itself.

**Closed by orthagh** 2022-04-28 13:47 UTC
Labels: Need feedback
