### ISSUE TITLE
10.0.3 anonymous replyer/sender name not visible in ticket when replying

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#13240] opened 2022-11-08 13:00 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

1° Create a ticket and add an external email in the observer
2° Reply by email as the observer
3° See in the ticket that the reply from the external email does only contain the body of the message : not the email from the sender

**Comment by cedric-anne** [comment] 2022-11-30 17:46
Hi,

Can you give an export of the email into eml format and give some screenshots ?

**Comment by joomlafun** [comment] 2022-12-05 14:39
Hi Cédric,

-Could you not reproduce the issue, as I tried with different providers(gmail, mailbox.org), using different clients(thunderbird, gmail etc.)

-There could be an Avatar that says that it is a reply from an unregistred user, then the name and email of the external user.

![051215322022](https://user-images.githubusercontent.com/63743077/205662802-db882d32-2e32-49e1-8d5b-09d25cb9a3dd.jpeg)

**Comment by cedric-anne** [comment] 2022-12-05 14:49
If I understand right, the issue here is that there is no name/avatar beside the followup. Could you confirm ?

**Comment by joomlafun** [comment] 2022-12-05 14:53
That is right, but only for anonymous users which are replying.

**Comment by joomlafun** [comment] 2022-12-05 15:03
I also realise that that when GLPI notifies from a new followup from an anonymous user, it does not use its name but uses the term "myself" in the mail notfication send to other actor  of the ticket

![051215582022-1](https://user-images.githubusercontent.com/63743077/205669460-6db24114-e3f8-4c99-863b-0210c973e1bf.jpeg)

**Comment by cedric-anne** [comment] 2023-01-23 13:47
Hi,

I take a look on the code. There is no change on this part between GLPI 9.5.x and GLPI 10.0, except that the generic term `Requester` was present on GLPI 9.5 (see image below).

Here we show the name of author of the ticket/followup, but in case of anonymous ticket/followup creation via a mail collector, stored information is `0`, so we do not have anything to display. Being able to display the email address of the author is not so easy and requires some work, and would probably not be done in a bugfixes version due to impacts on database.

I close this issue as it is not a bug, just a missing feature.

![image](https://user-images.githubusercontent.com/33253653/214053132-881ef5e5-4e17-40cd-a0ac-28abb9843deb.png)

**Closed** 2023-01-23 13:48 UTC
Labels: feature suggestion

**Comment by joomlafun** [comment] 2023-01-23 15:28
Ok, thank you for checking anyway.

@Antoine2tt please upvote here : https://glpi.userecho.com/communities/1/topics/2081-include-the-name-field-from-the-received-emails-of-non-existent-users-on-glpi

**Comment by joomlafun** [comment] 2023-01-26 22:20
@Antoine2tt 
Solution : 

in mailcollector.php, line 1210 right after" // Clean mail content" ; add
       
     ```
  if($tkt['_users_id_requester'] == 0)
       {
       $tkt['content'] = $requester . ':' . '<br>' . $tkt['content'];
       }
```

**Comment by joomlafun** [comment] 2023-01-27 15:06
> @joomlafun
> 
> Hi ! Thanks, unfortunalty it just writes the email of the requester into the ticket, that's not really what i wanted, and you too i guess !
> 
> But as you said, it could be good to set the requester's name as the name from the sender of the email

No, it works fine : it does write the name of any unregistered user above their answer in the ticket
$requester in the mailcollector.php is just a name for anyone sending an email to the collectors adress, I understand that you got confused though :)

**Comment by joomlafun** [comment] 2023-01-27 15:58
@Antoine2tt "this thread is for 'replies' and it works fine for replies ; 
On ticket creation, it must not be too difficult to solve adding a similar condition

**Comment by joomlafun** [comment] 2023-01-27 16:22
> @joomlafun Oh sorry !! Didn't notice it ! ^^'

No worries ^^
