### ISSUE TITLE
[9.5.0]  Error registering a ticket with image

### ISSUE THREAD

**Issue by alyssonalvesdev** [glpi-project/glpi#7987] opened 2020-09-21 21:06 UTC
Error when registering a ticket with image in the simplified interface.
The same image appears much smaller and with strokes on top of it.

Follow print
![660081f3-0a94-400d-a6b0-9db1bbb16c6a](https://user-images.githubusercontent.com/65170332/93821552-18eef080-fc35-11ea-9671-b7f3e36da3ec.jpg)

**Comment by cedric-anne** [comment] 2020-09-22 06:38
Hi,

I cannot reproduce.

First, can you try to reproduce with no active plugin ?

Second, if the problem persist, can you try to inspect these elements to tell us which HTML tag is corresponding to this ?

Regards

**Comment by AdrienClairembault** [comment] 2020-09-22 06:45
This is already fixed by #7829.

**Closed by AdrienClairembault** 2020-09-22 06:45 UTC
Labels: Need feedback
