### ISSUE TITLE
Font color matches background on Projects "Description" and "Comments" textboxes

### ISSUE THREAD

**Issue by natedawg20** [glpi-project/glpi#15824] opened 2023-10-18 17:39 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

On the Projects _Description_ and _Comment_ sections, the text font is the same color as the textbox. The issue only appears when using any dark mode theme but isn't existant when a light theme is used (as the font color doesn't change). All other font colors are correct on the "Projects" form

- Boxes w/ hidden text
![image](https://github.com/glpi-project/glpi/assets/99000334/2a360291-a013-4363-a956-5a6018ac9dd9)
- Description with cursor inside
![image](https://github.com/glpi-project/glpi/assets/99000334/b923e1ec-7465-4d72-add7-126b98cd2e24)
- Comments with cursor inside
![image](https://github.com/glpi-project/glpi/assets/99000334/30a33af8-1e6d-4a39-9a9e-fedf265c3ccf)

### Page URL

hxxps://*domain*/glpi/front/project.form.php?id=2

### Steps To reproduce

1. Open GLPI instance
2. Navigate to Projects
     a. Tools > Projects > New Project (or open existing Project)
3. On the "Main" Projects page, scroll down to _Description_ and _Comments_ sections

### Your GLPI setup information

```
Operating system: Linux $HOSTNAME 5.4.0-162-generic #​179-Ubuntu SMP Mon Aug 14 08:51:31 UTC 2023 x86_64
PHP 8.2.10 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.34-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.2.10) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.34) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.
```

**Comment by cconard96** [comment] 2023-10-19 10:32
Duplicate of #15645

**Closed** 2023-10-19 10:32 UTC
Labels: duplicate
