### ISSUE TITLE
[9.5.2] Public & private note overview won't show on personnal page for superadmin but for technician yes

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7627] opened 2020-07-08 17:37 UTC
//PHP 7.3.16 ; Centos 8.1 stable
//sql/php log checked and nothing in it

Unwanted current behavior:
-On the personal page you cannot see an overview of the note for a superadmin but for a regular technician, you can.
The note is targeting recursively all entities(no profile was selected)

Wanted proper behavior :
Note overview to be visible on personal page for superadmin

![image](https://user-images.githubusercontent.com/63743077/86950835-fb8ba980-c150-11ea-9600-940f3c4a10fa.png)

**Comment by joomlafun** [comment] 2020-11-07 15:44
Hi, can anybody review this issue please.

**Comment by joomlafun** [comment] 2020-11-10 20:04
Those logs may be connected to the issue : 

[2020-11-10 14:00:14] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /home/newsurf9/glpidemo1/inc/dashboard/dashboard.class.php at line 444
  Backtrace :
  inc/dashboard/dashboard.class.php:444              count()
  inc/dashboard/dashboard.class.php:359              Glpi\Dashboard\Dashboard::checkRights()
  inc/dashboard/grid.class.php:104                   Glpi\Dashboard\Dashboard::getAll()
  inc/dashboard/grid.class.php:187                   Glpi\Dashboard\Grid::loadAllDashboards()
  inc/central.class.php:72                           Glpi\Dashboard\Grid::canViewOneDashboard()
  inc/commonglpi.class.php:339                       Central->getTabNameForItem()
  inc/central.class.php:55                           CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:294                       Central->defineTabs()
  ajax/updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()

**Comment by cedric-anne** [comment] 2020-11-12 07:40
Hi,

I cannot reproduce this issue.

First, please provide all requested informations (logs, GLPI setup informations, plugins list, ...).

Second, can you try to reproduce with no active plugins ?

Third, can you give more details about your reminders ?

Regards

**Comment by joomlafun** [comment] 2020-11-12 18:57
Hi,

Thank you for your time.


There was no log and it seems to be working fine now somehow after I created another superadmin to make new notes.

By the way, what do you think of adding a "target" column on the note page so that we know which group does the note apply to on the note view page?

Kind regards,

**Comment by cedric-anne** [comment] 2020-11-13 07:53
Hi,

Adding target informations in notes list may be interresting, but is not in our roadmap for now. If you want to sponsor this feature, feel free to contact your partner manager, or submit this form: https://portal.glpi-network.com/contact-us

I close this issue as initial bug is not reproducible.

Regards

**Closed by cedric-anne** 2020-11-13 07:53 UTC
Labels: Need feedback

**Comment by felag** [comment] 2021-09-27 10:09
@cedric-anne Hello, I can reproduce this bug with GLPi 9.5.5. Here is how to reproduce:
1. Note setup
* create a note
* add a visibility start date (this makes the note public)
* add target (tested with technician profile _or_ a group of users _or_ both)

2. Note access
Login with an account with super-admin profile and (technician profile and/or member of targetted group of users). Go to personnal page: note is not visible.
When account has not super-admin profile (but only technician profile and/or member of targetted group of users), then note is visible in personnal page.

We have also seen that when specific user account is targetted, even if account has super-admin profile, then personal page of this account shows the note.


Can somebody else reproduce this bug with super-admin profile ?
