### ISSUE TITLE
[9.2] Tickets to be processed

### ISSUE THREAD

**Issue by alias59** [glpi-project/glpi#2891] opened 2017-10-03 13:53 UTC
Hello,
![image](https://user-images.githubusercontent.com/24585721/31128644-b24599f8-a852-11e7-8034-a50e37a1662f.png)
The tickets closed are consideration in the tickets to be processed

Thanks
Regards.

**Comment by trasher** [comment] 2017-10-06 06:33
Simple test: login using superadmin profile, creating a ticket (it appears in list), than closing it (changing state manually to cloed or add a solution) and it no longer appears in list.

Please provide additional details to reproduce this.

**Comment by alias59** [comment] 2017-10-06 06:41
![image](https://user-images.githubusercontent.com/24585721/31265895-884fb126-aa71-11e7-8347-7595f8bfda7f.png)
I do not find it normal that tasks appear while the ticket is closed
![image](https://user-images.githubusercontent.com/24585721/31265939-b9797980-aa71-11e7-975e-42051b613e82.png)
![image](https://user-images.githubusercontent.com/24585721/31265943-c18ec3e6-aa71-11e7-9a36-144e6a7c1a9f.png)
Certainly the tasks are not checked but the ticket remains closed

**Comment by trasher** [comment] 2017-10-06 06:48
OK, you're talking about tasks... But your title and description was about tickets. This is confusing.

So, it's a duplicate of https://github.com/glpi-project/glpi/issues/2902

**Closed by trasher** 2017-10-06 06:48 UTC
Labels: duplicate

**Comment by trasher** [comment] 2017-10-06 06:49
This is the inverse in facts; but no need for two opened issues anyways ;)

**Comment by alias59** [comment] 2017-10-06 06:51
Oh sorry, I misspoke
