### ISSUE TITLE
page "Assets/Global : model and type absent and bookmark creation impossible

### ISSUE THREAD

**Issue by johannsan** [glpi-project/glpi#1546] opened 2017-01-06 15:43 UTC
Hello.
Own version is 0.90.5.
On the list page "Assets/Global" (front/allassets.php), it's impossible to select "Model" and "Type". : 
![image](https://cloud.githubusercontent.com/assets/6028912/21722965/0b8dae86-d42f-11e6-9c1e-efe3c341cde2.png)

It's also impossible to create a bookmark (save as bookmark) on this page. It's possible on the others pages.
![2017-01-06_16h41_11](https://cloud.githubusercontent.com/assets/6028912/21722946/efd57cfa-d42e-11e6-96de-f4fd22815362.png)

A patch is it available?

**Comment by johannsan** [comment] 2017-01-09 11:13
With debug mode, the error message is : 
"Fatal error: Uncaught exception 'RuntimeException' with message 'Invalid name provided!' in /applis/www/helpdesk/front/bookmark.php:55 Stack trace: #0 {main} thrown in /applis/www/helpdesk/front/bookmark.php on line 55
"
![2017-01-09_12h13_31](https://cloud.githubusercontent.com/assets/6028912/21764773/0f13735a-d665-11e6-9d9a-29b347f21455.png)

**Comment by trasher** [comment] 2017-01-09 13:14
Looks like a duplicate of #1340

**Comment by johannsan** [comment] 2017-01-09 13:18
Thanks,
Ok for the bookmark, but not for the selection of  "Model" and "Type" columns.

**Comment by trasher** [comment] 2017-01-09 13:18
The patch is: e80c33fbbc8a8d9937ef258a2f78d78cf8c14b3b

**Comment by trasher** [comment] 2017-01-09 13:20
Oh, maybe I have closed this ticket a bit quickly... Not sure this is really a bug; I do not know this part enough.

**Comment by johannsan** [comment] 2017-01-09 13:59
In fact, in inc/search.class.php, It is necessary to add in
static function &getOptions($itemtype, $withplugins=true) {
...
 case 'AllAssets' : 
...

               $search[$itemtype][4]['table']           = 'glpi_computertypes';
               $search[$itemtype][4]['field']           = 'name';
               $search[$itemtype][4]['name']            = __('Type');
               
               
               $search[$itemtype][40]['table']          = 'glpi_computermodels';
               $search[$itemtype][40]['field']          = 'name';
               $search[$itemtype][40]['name']           = __('Model');
  but    'table'  depends of "asset_types" array('Computer', 'Monitor', 'NetworkEquipment',  'Peripheral', 'Phone', 'Printer', 'SoftwareLicense');

if asset_types = Computer
glpi_computertypes and glpi_computermodels
if asset_types = Monitor
glpi_monitortypes and glpi_monitormodels
if asset_types = NetworkEquipment
glpi_networkequipmenttypes and glpi_networkequipmentmodels
...

**Comment by johannsan** [comment] 2017-01-09 14:15
I think the correction https://github.com/glpi-project/glpi/commit/e80c33fbbc8a8d9937ef258a2f78d78cf8c14b3b is wrong because 'N/A' : 
![image](https://cloud.githubusercontent.com/assets/6028912/21769176/aad5bce0-d67d-11e6-9f6a-99d40134c2cd.png)

The correction to do is : 

> if (!isset($_GET["itemtype"])) {
   $_GET["itemtype"] = -1;
} else if($_GET['itemtype'] != 'AllAssets'){
   if (!is_subclass_of($_GET['itemtype'], 'CommonDBTM')) {
       throw new \RuntimeException('Invalid name provided!');
   }
}
--> 
![image](https://cloud.githubusercontent.com/assets/6028912/21769300/4e6ed9ae-d67e-11e6-9411-92ab650f2262.png)

**Comment by trasher** [comment] 2017-04-24 13:10
> I think the correction e80c33f is wrong because 'N/A'

Indeed, well catched! I've fixed the fix with your proposal; thank you.

As for adding model and type, this is more a feature than a bug.

**Comment by cedric-anne** [comment] 2019-03-15 11:51
Hi,

This mentionned bug has been fixed.

For the enhancement, even if it could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards

**Closed by cedric-anne** 2019-03-15 11:51 UTC
Labels: enhancement
