### ISSUE TITLE
[9.5.3] - Missing type for Ticket template!

### ISSUE THREAD

**Issue by andrepetinga** [glpi-project/glpi#8418] opened 2020-12-16 13:55 UTC
Hello.
After upgrading (today) to 9.5.3, we are getting lots of errors in php-errors.log saying Missing type for Ticket template!
What is it?

**Logs**

[php-errors.log](https://github.com/glpi-project/glpi/files/5703118/php-errors.log)

**Screenshots**

![image](https://user-images.githubusercontent.com/43515938/102357161-f6574400-3fa5-11eb-87e8-7c7689c4ac80.png)

**Comment by andrepetinga** [comment] 2021-01-14 15:52
This problem seems to occur when we make a solution!
Anyone??

**Comment by vemi2709** [comment] 2021-01-19 11:25
Same problem here. Also, if you try to assign the requester as technician, the same error occurs.

**Comment by vemi2709** [comment] 2021-01-21 10:56
I had to clear the 'Ticket template' from Entity and put it in the users profile to get rid of the error message. In the settings of the user I cannot choose 'Default entity' (it's empty, it's cleared everytime I try to change it).

**Comment by andrepetinga** [comment] 2021-01-26 11:08
> I had to clear the 'Ticket template' from Entity and put it in the users profile to get rid of the error message. In the settings of the user I cannot choose 'Default entity' (it's empty, it's cleared everytime I try to change it).

Confirmed!

I had to remove the template from each entity and apply it to the Profiles.
Regarding "Default entity" for each user, yes I can change it as I want and it stays.

**Comment by OscarBeiro** [comment] 2021-01-27 15:48
Hi,
We were debugging another issue and found this one.
Same errors on our 9.5.3.
Your workaround also works @vemi2709. Thanks
Cheers,

**Comment by ZeikoFr** [comment] 2021-02-09 12:15
Can confirm the issue is present.

I don't think the workaround is a good idea if you have a lot of people in one entity.

**Comment by phamorais** [comment] 2021-02-10 00:12
HELLO!
I also confirm the error when migrating from 9.4.6 to 9.5.3 in my environment.

**Comment by phamorais** [comment] 2021-04-13 21:51
@trasher and Teclib Groups!

just to inform them.

I upgraded to version 9.5.5 and the error reported on that issue in 2020 still persists.
Before, the message did not appear in an evident way.
Now, when opening a ticket, the message is displayed and immediately afterwards the user is redirected. See gif below.

![error](https://user-images.githubusercontent.com/35368369/114625411-97ba8200-9c88-11eb-9e39-b0598be465ce.gif)

The gif is fast. But follow the printout of the error message

![image](https://user-images.githubusercontent.com/35368369/114625577-d6e8d300-9c88-11eb-9e7d-0984a94ee191.png)

log in php-erros.log

![image](https://user-images.githubusercontent.com/35368369/114625660-f7b12880-9c88-11eb-87d8-3628a3f4f83a.png)

log in sql-erros.log

**Comment by cedric-anne** [comment] 2021-04-14 07:37
Hi,

So it seems to be a problem that have to be fixed in FormCreator plugin. Please open an issue on [plugin repository](https://github.com/pluginsGLPI/formcreator).

Regards

**Closed by cedric-anne** 2021-04-14 07:37 UTC

**Comment by btry** [comment] 2021-04-14 09:43
Hi @phamorais I opened an issue in Formcreator, linked to this one.

Could you share in the Formcreator's issue the complete backtrace. Your tail command returned too  few lines and the beginning of the backtrace seems missiing.

Also, please confirm that the ticket being created has a group in the actors. It seems this is important to reproduce.
