### ISSUE TITLE
"all" grid appears broken on first load

### ISSUE THREAD

**Issue by asabatep** [glpi-project/glpi#13393] opened 2022-11-23 14:46 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

The "home -> all" grid appears broken on first load. Columns do not reposition themselves as content is being loaded from the ajax requests.

This only happens in the "all" view. All others ("personal view", "group view"...) are unaffected.

Resizing the window (such as clicking restore->maximize on the browser) makes the columns appear correctly.

This site was updated from 9.5.5 to 10.0.5 (following documented procedure). The issue happens too with 10.0.3 and the current git trunk.

![imatge](https://user-images.githubusercontent.com/101092983/203575734-0332467d-a9ee-4a5e-aea5-d24c932cfc02.png)

### Page URL

/front/central.php

### Steps To reproduce

- Login to glpi as technician or super-admin profile
- Click "all" tab in home view
- Columns load broken
- Resize browser
- Columns load correctly

### Your GLPI setup information

```
Operating system: Linux hestiatest.example.com 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64
PHP 8.1.12 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, oci8, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, soap, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="128M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.54 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1n ()
	Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0
Server Software: MariaDB Server
	Server Version: 10.6.11-MariaDB-log
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@172.30.128.105/glpi10
	Host info: 172.30.128.105 via TCP/IP
	
PHP version (8.1.12) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.11) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_cache has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/config has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_cron has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_dumps has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_graphs has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_lock has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_pictures has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_plugins has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_rss has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_sessions has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_tmp has been validated.
Write access to /home/pi10test/web/pi10test.example.com/public_html/files/_uploads has been validated.
The following directories should be placed outside "/home/pi10test/web/pi10test.example.com/public_html":
‣ "/home/pi10test/web/pi10test.example.com/public_html/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/pi10test/web/pi10test.example.com/public_html/marketplace has been validated.
Timezones seems loaded in database.
```

**Comment by cconard96** [comment] 2022-11-23 16:47
Duplicate of #13009

**Closed by cconard96** 2022-11-23 16:47 UTC
Labels: duplicate
