### ISSUE TITLE
Create ticket and automatically add requester

### ISSUE THREAD

**Issue by TheRiddlePT** [glpi-project/glpi#11418] opened 2022-04-28 13:19 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Before the upgrade from 9.5.6 to 10.0.0, every time that our users created a ticket they are automatically added as requester.
Well, after the upgrade to version 10, the users can create the tickets but they are not automatically assigned as requesters.

I search a while here about this problem, but I'm sorry I did not find any entry about this problem.
I think probably, something in the structure of the new glpi have changed (entities or something else).

Even when I create the ticket and on the right side in the "Actors section" I click put "Associate myself", GLPI don't add me as requester on ticket (this option is not available to ours users, because they use the simplified template of ticket).

### Relevant log output

```shell
There is no error log for this.
```

### Steps To reproduce

1. Create a ticket with a simplified version of template
2. Go to the tickets list as admin mode.
3. Check if you have the name of requester in the ticket list.

____Another Way____

1. Create a ticket with a standard version of template, to have the right sidebar and click associate myself in the Actors section).
2. Go to the tickets list as admin mode.
3. Check if you have the name of requester in the ticket list.

### Your GLPI setup information

GLPI 10.0.0 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language: en_US

**Comment by orthagh** [comment] 2022-04-28 13:23
see fix already done : #11328 (or take current nightly : https://nightly.glpi-project.org/glpi/)

duplicate of #11334, and #11377

**Closed by orthagh** 2022-04-28 13:23 UTC
