### ISSUE TITLE
[API][HATEOAS] Log sub item not available

### ISSUE THREAD

**Issue by MartialSeron** [glpi-project/glpi#3736] opened 2018-03-19 13:25 UTC
When you request a ticket, there is no link for `Log` sub item.
But `http://.../apirest.php/Ticket/<ticketId>/Log` URL is available and it will show the logs.
So it makes sense to me that the `Log` should be in the links.

**Comment by msizec** [comment] 2019-06-05 16:33
also with getItem and "with_logs=true" parameter, logs aren't retrieved with a 401 error 

![image](https://user-images.githubusercontent.com/29256398/58973476-5c171d00-87c0-11e9-8415-03e3002cae72.png)

**Comment by msizec** [comment] 2021-09-17 08:20
I think the issue is still here if no one resolved it ...
I dont have the last version so can't reproduce it now

**Comment by Sicoval31** [comment] 2022-02-21 10:32
Hi, this bug is not resolved ! Why close it automatically ?????

**Comment by cconard96** [comment] 2022-02-21 10:45
Unable to recreate issue.

Request:
GET /apirest.php/Computer/59?with_logs=1&app_token=MY_APP_TOKEN&session_token=MY_SESSION_TOKEN HTTP/1.1

Response included "_logs" property with all historical data.

Please test with 9.5.7 and ensure the user you are authenticating with has access to view historical data (Administration > Historical in profile).

If it is still an issue you can reopen this.

**Comment by Sicoval31** [comment] 2022-02-21 10:54
Not work in both version 9.5.6 or 9.5.7.
The user is super_admin :)

---
je n'ai pes les droits pour rouvrir un incident sur Github ;)

**Comment by Sicoval31** [comment] 2022-02-21 12:37
Thank you for the reopening.

I tried your solution and it's working with computer but not with ticket :

With ticket : 
URL : /apirest.php/ticket/110305?with_logs=true
Part of the answer :
"validation_percent": 0,
    "date_creation": "2021-08-13 09:07:11",
    "_logs": {
        "error": 401,
        "message": "Vous n'avez pas les droits requis pour réaliser cette action."
    },


With computer :
URL : /apirest.php/computer/4054?with_logs=true

Part of the answer :
 "date_creation": "2022-01-18 10:27:49",
    "is_recursive": 0,
    "_logs": {
        "44814574": {
            "id": 44814574,
            "itemtype": "Computer",
            "items_id": 4054,
            "itemtype_link": "0",
            "linked_action": 20,

I am logged as Super admin and I specified my profile with changeActiveProfile.

**Comment by cconard96** [comment] 2022-03-06 14:24
Fixed via #10856.

**Closed by cconard96** 2022-03-06 14:24 UTC
Labels: bug, api
