### ISSUE TITLE
Can't See Private follow up after upgrade to 10.0.8 version

### ISSUE THREAD

**Issue by espacitto** [glpi-project/glpi#15186] opened 2023-07-10 22:54 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

Hello,

Technician, admin and super-admin can't see Private follow-ups after upgrade even if the ticket was created by them.

Regards.

**Comment by cconard96** [comment] 2023-07-10 23:16
Duplicate of #15128

**Closed** 2023-07-10 23:19 UTC
Labels: duplicate
