### ISSUE TITLE
Error accessing config table

### ISSUE THREAD

**Issue by Roddg** [glpi-project/glpi#6297] opened 2019-09-12 09:13 UTC
**Describe the bug**

Error accessing config table

**Page(s) URL**

https://glzayavki.000webhostapp.com

**To reproduce**

The error appears after changing any equipment, let's say I add the inventory number to the monitor, save it, and this error appears Error accessing config table and the site does not work

**Expected behavior**

expected opening page

**Logs**

```
https://drive.google.com/drive/folders/1iIn20E9g5iXBWtyehX_681BjePmm9fSh?usp=sharing
```

**Screenshots**

http://joxi.ru/ZrJQOa7hwRllDA

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
http://joxi.ru/L219pKDTRnjyl2
```

**Additional context**

roddg86@gmail.com 
my email

**Comment by Roddg** [comment] 2019-09-16 03:28
updated

**Comment by cedric-anne** [comment] 2019-09-16 07:24
Hi,

SQL logs shown you have a communication problem between GLPI and your DB. 
```
  *** MySQL query error:
  SQL: SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'id10782991_glpi' AND `TABLE_TYPE` = 'BASE TABLE' AND `TABLE_NAME` LIKE 'glpi_config%'
  Error: Max connect timeout reached while reaching hostgroup 1028 after 10049ms
```
As this is not a bug, I close the issue.

Please use [forums](https://forum.glpi-project.org/) to get community support or consider [taking a subscription](https://glpi-project.org/subscriptions/) to get professional support.

Regards

**Closed by cedric-anne** 2019-09-16 07:24 UTC
Labels: invalid
