### ISSUE TITLE
Tremendous Email Notification Lag running version GLPI ver 10.0

### ISSUE THREAD

**Issue by rudolcas** [glpi-project/glpi#11695] opened 2022-05-25 19:48 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Version 10.0

### Bug description

Tremendous Email Notification Lag running version GLPI ver 10.0

Please help!

RC

**Comment by rudolcas** [comment] 2022-05-25 20:07
Every time I reply on the ticket as super-user/or tech/or anybody its taking a long time to email reply to be sent-out/received.

**Comment by cconard96** [comment] 2022-05-25 20:16
Please provide the requested GLPI setup information from Setup > General > System tab.
Please also include if the "queuednotification" and "mailgate" Automatic Actions are set for GLPI mode or CLI mode (Setup > Automatic Actions).

**Comment by rudolcas** [comment] 2022-05-25 20:27
queuednotification setup

###

![image](https://user-images.githubusercontent.com/42798291/170361291-2c7b5af5-dec1-46c8-96d2-47f6839dbe7b.png)

**Comment by cconard96** [comment] 2022-05-26 00:30
In GLPI mode, the actions are started occasionally when users navigate GLPI.
If you do not have a lot of users navigating pages, then the actions would not be run consistently. Also, when a specific user's navigation triggers an automatic action run, that user cannot trigger another run for another 5 minutes. This was to avoid having a consistently slower experience. Finally, in GLPI mode, only one action can be triggered at a time.

If you have the ability to add a cron job (Linux/MacOS) or Scheduled Task (Windows) it is preferred to use CLI mode for at least time-sensitive actions. GLPI mode is the default because it works even if not the most performant on all systems even one that are hosted that don't give access to these scheduler systems.

Here is a link to the user documentation for configuring automatic actions in CLI mode:
https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/crontasks.html

I would suggest trying to switch at least those two actions I mentioned before to CLI mode and setting up a cron/Scheduled Task to run every minute (make sure it runs under the web server user account to avoid issues with permissions).

**Comment by rudolcas** [comment] 2022-05-26 19:31
Yeah what I see is that queuenotifications* is the problem.  

There was no automatic actions before it and I have it on one-minute frequency.  Just waiting there for a few minutes - It seems like it doesn't even trigger unless going into there and manually pressing "Execute."

Then the email is sent out... sigh

**Comment by rudolcas** [comment] 2022-05-26 22:08
**1. I have updated my crontab**

<img width="575" alt="image" src="https://user-images.githubusercontent.com/42798291/170587383-e2be86dd-affe-454e-8b44-fd25904a599e.png">

Everything is looking good there..

**2. Checked Administration/Entities/Root Entity**

- Delay to send email notifications = 1 minute
- Enable Notifications by default = Yes

<img width="715" alt="image" src="https://user-images.githubusercontent.com/42798291/170587829-5a68cfed-85d3-4be0-90c5-4312adf64e7d.png">


**3. Switched from **GLPI --- to ---> CLI on the Setup/Automatic Actions/queuednotification****

<img width="1909" alt="image" src="https://user-images.githubusercontent.com/42798291/170587502-18cece47-eaf8-451a-bfd7-e5c8f4971898.png">

Still after much testing - nothing is happening with the Notification Update.
I always have to press down **Execute** to send out email updates.

**Comment by cedric-anne** [comment] 2022-05-30 06:46
Hi,

1. The script to call is `php /var/www/glpi/front/cron.php`.
2. This script should not be called using root user. Indeed, it should be called using same user as your web server uses (e.g. `www-data`), as crontask may create files that HAVE to be read later by the web server user.
3. Until GLPI 9.5, notifications related to tickets were not using the notification queue, and that was sometime causing issues. Now they are put in notification queue like all other notifications. It can explain the small "lag" you are experiencing.

**Comment by cedric-anne** [comment] 2022-05-30 06:47
I closed this issue as it is a configuration issue, not a GLPI bug.

**Closed by cedric-anne** 2022-05-30 06:46 UTC
Labels: Need feedback

**Comment by rudolcas** [comment] 2022-05-31 23:00
I have changed it to user "apache" on the cronjob, but it still DOESN'T work.  I am not sure why this case is closed it should still be opened until this is solved.

![image](https://user-images.githubusercontent.com/42798291/171297636-4ac85169-ff1d-451e-b3b9-03a9e8dbafe5.png)

**Comment by rudolcas** [comment] 2022-05-31 23:02
![image](https://user-images.githubusercontent.com/42798291/171297724-7208a4ca-954f-4d24-b33c-5dd1666559dd.png)

**Comment by rudolcas** [comment] 2022-05-31 23:29
![image](https://user-images.githubusercontent.com/42798291/171300040-6544a0ee-83ce-443c-90ac-c1c85aba6947.png)

**Comment by cconard96** [comment] 2022-05-31 23:32
The called script in the crontab needs to be `/var/www/html/glpi/front/cron.php` not `/var/www/html/glpi/front/queuednotification.php`.

The issue was closed because it seems like a configuration issue and not a bug in GLPI.
If you need additional help with the configuration of CLI mode or something else, you can open a topic on the forum.
https://forum.glpi-project.org/

**Comment by rudolcas** [comment] 2022-06-02 00:41
Thank you, here always thinking it was the action "/queuenotification.php" job that was always stuck.  Now working by modifying to /cron.php !

<img width="374" alt="image" src="https://user-images.githubusercontent.com/42798291/171523919-83b7afc4-1fe7-4205-9f7c-918e307edabb.png">
