### ISSUE TITLE
After creating a ticket without an assigned technician, the ticket status changes to In progress (assigned).

### ISSUE THREAD

**Issue by hubMich** [glpi-project/glpi#11705] opened 2022-05-27 07:54 UTC
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

After creating a ticket without an assigned technician, the ticket status changes to "In progress (assigned)".

**Comment by cconard96** [comment] 2022-05-27 09:32
Duplicate of #11384.
Fixed by #11392.
Will be fixed in 10.0.1.

**Closed by cconard96** 2022-05-27 09:32 UTC
Labels: duplicate
