### ISSUE TITLE
[GLPI 9.5.0] Child projects are not sortable by name in the left sidemenu of the parent project

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7705] opened 2020-07-16 13:37 UTC
//PHP 7.3.16 ; Centos 8.1 stable

Unwanted current behavior
Child project are not sortable in the sidemenu tab of the parent project.
It gets only sorted by ID

![image](https://user-images.githubusercontent.com/63743077/87851172-8f4e3a00-c8f6-11ea-81f8-abdccf678f45.png)

Wanted behavior
Child projects sortable

**Comment by cedric-anne** [comment] 2020-07-21 11:58
Hi,

Although it may be interesting to be able to sort child projects list, such an improvement is not in our roadmap for now. If you want to sponsor this feature, feel free to contact us at contact@teclib.com.

I close this issue as it is not a bug. You can open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).

Regards

**Closed by cedric-anne** 2020-07-21 11:58 UTC
