### ISSUE TITLE
Error when trying to export files - Self-service profile

### ISSUE THREAD

**Issue by wc55** [glpi-project/glpi#12359] opened 2022-08-01 14:35 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When the Self-Service profile user uses the functionality to export files from the “My requests for assistance” screen, receives the message “You don't have permission to perform this action”.

### Relevant log output

```shell
2022-08-01 09:01:47 [10@glpi]
User ID: 10 tried to access or perform an action on /front/report.dynamic.php?item_type=PluginFormcreatorIssue&start=0&criteria%5B0%5D%5Bfield%5D=4&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=notclosed&display_type=4 with insufficient rights. Additional information: The current profile does not use the standard interface
	Stack Trace:
		/var/www/html/glpi/src/Session.php:888 displayRightError()
		/var/www/html/glpi/front/report.dynamic.php:38 checkCentralAccess()
```

### Page URL

http://localhost/plugins/formcreator/front/issue.php

### Steps To reproduce

1. Acesse the self-service profile ticket page ("My requests for assistance"):

![image](https://user-images.githubusercontent.com/106084399/182165066-c9c74aff-994f-4ead-b551-e08f8dbc32d1.png)

2. Click "Export" and choose an option

![image](https://user-images.githubusercontent.com/106084399/182165617-787ac2f3-5434-45fc-a054-cc27c715a723.png)

>>>>

![image](https://user-images.githubusercontent.com/106084399/182166701-afa61d77-614c-478b-b951-b2521d64285a.png)

3. The message:

![image](https://user-images.githubusercontent.com/106084399/182166948-5b300147-a248-4469-a8cb-b1ae2ca49ef5.png)

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.2 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at localhost Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Server Software: mariadb.org binary distribution
	Server Version: 10.7.4-MariaDB-1:10.7.4+maria~focal
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_user@mariadb/glpidb
	Host info: mariadb via TCP/IP
	
PHP version (7.4.28) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.4) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.200.3.1', Port: '389', BaseDN: 'ou=people,dc=ufpr,dc=br', Connection filter: none, RootDN: none, Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.17.0     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.11.2     State: Installed / not activated               
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0-rc.2 State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.12.1     State: Enabled                                 
		Install Method: Manual
	itilcategorygroups   Name: Grupos ItilCategory            Version: 2.5.0      State: Installed / not activated               
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.9.2      State: Installed / not activated               
		Install Method: Manual

</pre></details>

### Anything else?

In the log, the standard interface is mentioned, but the self-service profile has a simplified interface. Maybe it shouldn't be available for this type of profile, but I don't know if it's configuration or bug

**Comment by cedric-anne** [comment] 2022-08-01 14:36
@btry 

Could you investigate on this, to see if it is a plugin issue or a GLPI issue ?

**Comment by wc55** [comment] 2022-08-01 14:47
I also thought about Form Creator, but decided to open the issue in GLPI first.

Thanks

**Comment by btry** [comment] 2022-08-01 22:05
URL : front/report.dynamic.php
1st executed line  after `inc/includes.php`
`Session::checkCentralAccess();`

Here we check if we ise the standard interface. This is false for self-service users.

**Comment by wc55** [comment] 2022-09-22 18:07
Hi

I still can't test version 10.0.3.

Can you validate if the problem remains?

**Comment by btry** [comment] 2022-09-22 18:08
Hi

not for now as I have some load for customers.

**Comment by wc55** [comment] 2022-09-22 18:14
OK

I believe that I will be able to test it only next week, but I will inform you here about the result.

Thanks

**Comment by wc55** [comment] 2022-09-22 18:59
I got a quick test, using the latest versions of GLPI (10.0.3) and Form Creator (2.13.1).

I confirm that the message still remains.

With the form creator disabled, the message also appeared.

**Comment by btry** [comment] 2022-09-22 19:23
Ok, then we can deduce the problem is very likely in GLPI, not Formcreator.

**Comment by PandaRoux8** [comment] 2022-12-06 11:25
Hello, is there a fix for this yet ?

**Comment by cedric-anne** [comment] 2022-12-09 08:54
Before GLPI 10.0, this export button was not available on simplified interface as it was rendered by the `Html::pintPager()` method: https://github.com/glpi-project/glpi/blob/da57a064bf9579f9e59e1238fcc1744c9e1afb0b/src/Html.php#L4328-L4335

During search page refactoring, the condition was dropped: https://github.com/glpi-project/glpi/blob/da57a064bf9579f9e59e1238fcc1744c9e1afb0b/templates/components/search/controls.html.twig#L97-L148

@orthagh Should we hide this feature or should we fix it on simplified interface ?

**Comment by orthagh** [comment] 2022-12-14 08:56
I'm not against fix it on self-service interface if it doesn't take too much time.
Otherwise, disable it again

**Closed** 2023-01-24 09:56 UTC
Labels: bug
