### ISSUE TITLE
[9.1.4] Business rule not processed on ticket when clicked on add myself button or adding the technician

### ISSUE THREAD

**Issue by lcpj** [glpi-project/glpi#2452] opened 2017-07-12 10:41 UTC
Steps to reproduce:

1 - Add a new simple business rules (add/update, does not matter)
2 - Add a criteria "Technician" is "your user"
3 - Add a new action "Assign technician group" to whatever group you need
4 - Go to a ticket and click on "assign myself" button.
5 - Nothing happens

--- old workaround start ---
If you go to the ticket but instead of clicking the assign myself button you do it manually (click on the plus sign, choose User, choose your name, click SAVE at the bottom) the rule is then processed and the desidered group is added to the ticket as well.
--- old workaround end---

the above workaround is also not working on version 9.1.4 

(same problem as https://github.com/glpi-project/glpi/issues/1915)

**Comment by orthagh** [comment] 2017-07-19 08:39
Should be fixed in 9.1.5 
Possible duplicate of #2294 

I close, feel free to comment.

**Closed by orthagh** 2017-07-19 08:39 UTC

**Comment by lcpj** [comment] 2017-07-26 16:44
Issue still persists on 9.1.5
