### ISSUE TITLE
9.5.1 global search doesnt work

### ISSUE THREAD

**Issue by kevin-m87** [glpi-project/glpi#7843] opened 2020-08-12 11:47 UTC
Hi,

Global search from tickets doesnt work.

SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'glpi_tickets``.`time_to_resolve` IS NOT NULL AND ``glpi_tickets``' at line 141 in query "SELECT DISTINCT `glpi_tickets`.`id` AS id,..................

**Comment by cristianmenghi** [comment] 2020-08-12 11:50
Hi, when debug for solve a missing column for other error on a migration, i see this.
[2020-08-12 08:38:34] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 306
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) WHERE `itemtype` = 'Monitor' AND `items_id` = '2426' AND `is_deleted` = '0'
  Error: Column 'itemtype' in where clause is ambiguous
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:857                          DBmysqlIterator->execute()
  inc/dbutils.class.php:335                          DBmysql->request()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  inc/ticket.class.php:746                           countElementsInTable()
  inc/commonglpi.class.php:339                       Ticket->getTabNameForItem()
  inc/computer.class.php:107                         CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:294                       Computer->defineTabs()
  ajax/updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()
  {"user":"8@server","mem_usage":"0.001\", 4.40Mio)"}

**Comment by cedric-anne** [comment] 2020-08-18 09:27
Hi,

@kevin-m87 Can you provide more informations ? It would be helpful to have, at least, GLPI logs related to your issue.

@cristianmenghi Your issue seems not related to global search. Please open another issue and provide all requested informations.

Regards

**Comment by kevin-m87** [comment] 2020-08-18 12:09
From page tickets : 

![image](https://user-images.githubusercontent.com/55700796/90511205-6969be80-e15c-11ea-8639-e9a4c28ed898.png)


sql-errors.log
[2020-08-18 14:04:37] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 306
  *** MySQL query error:

 Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'glpi_tickets``.`time_to_resolve` IS NOT NULL
               AND ``glpi_tickets``' at line 141

**Comment by kevin-m87** [comment] 2020-08-18 12:10
This one aswell doesnt work : 

![image](https://user-images.githubusercontent.com/55700796/90511329-98803000-e15c-11ea-8c4a-c0af9c2f0de8.png)

No result, sql error

**Comment by cedric-anne** [comment] 2020-08-18 12:36
Can you give us list of displayed columns ?

**Comment by kevin-m87** [comment] 2020-08-18 12:52
I put there the sql query error when i'm doing a global search tickets with pattern "test".

[sqlerror.txt](https://github.com/glpi-project/glpi/files/5090455/sqlerror.txt)

**Comment by cedric-anne** [comment] 2020-08-18 12:53
> I put there the sql query error when i'm doing a global search tickets with pattern "test".
> 
> [sqlerror.txt](https://github.com/glpi-project/glpi/files/5090455/sqlerror.txt)

SQL query depends on displayed columns, so having list of displayed columns into your GLPI could be really helpful.

**Comment by kevin-m87** [comment] 2020-08-18 12:56
You need columns on which table ?

**Comment by kevin-m87** [comment] 2020-08-18 12:59
You mean this ? :

![image](https://user-images.githubusercontent.com/55700796/90515801-7047ff80-e163-11ea-9469-d28b4a06f6fe.png)

**Comment by cedric-anne** [comment] 2020-08-18 13:05
Yes.

I got the problem.

Code has been refactored in GLPI 9.5, as shwon below, and `TABLE` keyword is now backquoted in search options `computation` property.
```diff
          'name'               => __('Time to resolve exceedeed'),
          'datatype'           => 'bool',
          'massiveaction'      => false,
-         'computation'        => 'IF(TABLE.`time_to_resolve` IS NOT NULL
-                                            AND TABLE.`status` <> 4
-                                            AND (TABLE.`solvedate` > TABLE.`time_to_resolve`
-                                                 OR (TABLE.`solvedate` IS NULL
-                                                      AND TABLE.`time_to_resolve` < NOW())),
-                                            1, 0)'
+         'computation'        =>
+            'IF(' . $DB->quoteName('TABLE.time_to_resolve') . ' IS NOT NULL
+               AND ' . $DB->quoteName('TABLE.status') . ' <> 4
+               AND (' . $DB->quoteName('TABLE.solvedate') . ' > ' . $DB->quoteName('TABLE.time_to_resolve') . '
+                     OR (' . $DB->quoteName('TABLE.solvedate') . ' IS NULL
+                        AND ' . $DB->quoteName('TABLE.time_to_resolve') . ' < NOW())),
+               1, 0)'
       ];
 
       $tab[] = [
```
But the `TABLE` keyword is then replaced by a backquoted table name, so the table name is surrounded by double backquotes, which is invalid.
```
      if (isset($searchopt[$ID]["computation"])) {
         $tocompute = $searchopt[$ID]["computation"];
         $tocompute = str_replace($DB->quoteName('TABLE'), 'TABLE', $tocompute);
         $tocompute = str_replace("TABLE", $DB->quoteName("$table$addtable"), $tocompute);
      }
```

We have to fix this.

**Comment by kevin-m87** [comment] 2020-08-18 13:06
Ok thanks for information.

**Comment by cedric-anne** [comment] 2020-08-18 14:24
Well, I misread the code.

This problem has been fixed prior to 9.5.0-rc by commit d76e74e48465c11e3784966fff94d5b9c11e4f4b

I still cannot reproduce.

Did you patched your GLPI code ?

**Comment by kevin-m87** [comment] 2020-08-18 14:30
I have upgraded from 9.4.6 to 9.5.1

I missed something ?

**Comment by cedric-anne** [comment] 2020-08-18 14:40
Could you try to reproduce on a fresh installation, without plugins ?

**Comment by kevin-m87** [comment] 2020-08-18 14:53
What's the point of doing this on a new installation? You can also do this.

The important thing is to do it with data. I won't have time to prepare for a new install anyway. For the moment I will stay in 9.4.6 and wait if similar cases arise in this case.

I had two plugins: fusioninventory and glpi modifications.
I disabled and deleted both, the problem still persists.

**Comment by cedric-anne** [comment] 2020-08-18 17:54
> What's the point of doing this on a new installation? You can also do this.
> 
> The important thing is to do it with data.

I tried with a GLPI installation having 20000 tickets, multiple entities, sla, ola, ... and was not able to reproduce. So the point was to check if your GLPI installation may has altered code.

**Comment by kevin-m87** [comment] 2020-08-19 06:51
Interesting, i will do a new server then and i will import the dump database.
I'll keep you informed.

**Comment by kevin-m87** [comment] 2020-08-19 09:53
After new install and import database; i facing this issue : 

[2020-08-19 11:32:53] glpiphplog.CRITICAL:   *** Uncaught Exception SodiumException: public nonce size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES bytes in /var/www/glpi/inc/toolbox.class.php at line 293
  Backtrace :
  inc/toolbox.class.php:293                          sodium_crypto_aead_xchacha20poly1305_ietf_decrypt()
  inc/authldap.class.php:2677                        Toolbox::sodiumDecrypt()
  inc/auth.class.php:225                             AuthLDAP::tryToConnectToServer()
  inc/authldap.class.php:2797                        Auth->connection_ldap()
  inc/authldap.class.php:2865                        AuthLDAP::ldapAuth()
  inc/auth.class.php:843                             AuthLDAP::tryLdapAuth()
  front/login.php:84                                 Auth->login()

When i'm trying to auth.

This fix doesnt work for me : https://github.com/glpi-project/glpi/issues/7822

root@QLIONE:/var/www/glpi# php bin/console glpi:security:change_key

In toolbox.class.php line 293:

  public nonce size should be SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES bytes


glpi:security:change_key


this issue has also happened to other people : https://forum.glpi-project.org/viewtopic.php?id=278793

**Comment by kevin-m87** [comment] 2020-08-19 12:35
Ok global search now works fresh install.

Btw i needed to grab table glpi_authldaps from database empty because mine wasnot correctly migrated.

One thing : in label field where "test" is wrote, i need to put my cursor below the box like this : 

![image](https://user-images.githubusercontent.com/55700796/90635073-01cd7500-e229-11ea-89c3-35fe2a195abd.png)

If i put my cursor in center box i can't type.
You too ?

**Comment by cedric-anne** [comment] 2020-08-20 06:40
> Ok global search now works fresh install.
> 

So, can you check if the installed code is different in your updated installation ?

> Btw i needed to grab table glpi_authldaps from database empty because mine wasnot correctly migrated.

#7782 should help to prevent password corruption during update.

> 
> One thing : in label field where "test" is wrote, i need to put my cursor below the box like this :
> 
> ![image](https://user-images.githubusercontent.com/55700796/90635073-01cd7500-e229-11ea-89c3-35fe2a195abd.png)
> 
> If i put my cursor in center box i can't type.
> You too ?

I have not this issue.

**Comment by kevin-m87** [comment] 2020-08-20 06:58
> 
> 
> > Ok global search now works fresh install.
> 
> So, can you check if the installed code is different in your updated installation ?
> 
> > Btw i needed to grab table glpi_authldaps from database empty because mine wasnot correctly migrated.
> 
> #7782 should help to prevent password corruption during update.
> 
> > One thing : in label field where "test" is wrote, i need to put my cursor below the box like this :
> > ![image](https://user-images.githubusercontent.com/55700796/90635073-01cd7500-e229-11ea-89c3-35fe2a195abd.png)
> > If i put my cursor in center box i can't type.
> > You too ?
> 
> I have not this issue.

I have this only with profile "super-admin" when the tiles are present above with statistics

**Comment by cedric-anne** [comment] 2020-08-24 06:16
Hi,

Initial bug has been resolved. I close the issue.
I created #7867 for the form issue.

Regards

**Closed by cedric-anne** 2020-08-24 06:16 UTC
Labels: Need feedback
