### ISSUE TITLE
Change pending [waiting] ticket generates a resolved email 

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#13757] opened 2023-01-07 10:39 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Good morning,
when editing a "pending" ticket, an email is sent with the status resolved to the person.
Do you have any idea how to solve this problem without touching the code?

Is:

Ticket scheduled: 1042 Scheduled the ##task.begin#

PS: I have the same problem when migrating to the 10
I looked in automatic actions and rules nothing!

I looked at the ticket code.form and notification.class I can’t find ...
In commondntm.class I have things but I do not find for now

I must prevent the sending in email in the event that a "pending" ticket is sent because it is a solved mail ticket? But do you have any idea?
It’s kind of embarrassing.

### Relevant log output

```shell
email sent resolved when it's just a change of status from outstanding to pending
```

**Comment by cedric-anne** [comment] 2023-01-09 07:24
Hi,

Could you check if you reproduce without any active plugins.

**Comment by falco2001** [comment] 2023-01-09 08:12
Hello,
I disabled all plugins and I have the same problem!
Thank you for your investigation

**Comment by falco2001** [comment] 2023-01-09 14:29
Good morning,
apparently the code uses a template number 4 is it normal to have this in the base?
![image](https://user-images.githubusercontent.com/31952346/211331423-bda30a0e-2ce9-42e9-b033-ab16514c5ba0.png)
Merci

**Comment by falco2001** [comment] 2023-01-10 09:11
Hello,
This is not a bug !
It was necessary to modify the field of the table [glpi_notificationtemplatetranslations] id4 so ##IFticket.storestatus=4 and put waiting

**Comment by cedric-anne** [comment] 2023-01-10 09:25
Glad to see you solved your problem.

I close this issue as it was not a bug.

**Closed by cedric-anne** 2023-01-10 09:25 UTC
