### ISSUE TITLE
Reset of ticket fields

### ISSUE THREAD

**Issue by Gor3pig** [glpi-project/glpi#12873] opened 2022-10-04 14:54 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When creating a ticket, the user first fills in the "Title" field, then the "Description". If the user forgets to fill in the mandatory fields, such as Location or Category, and validates the ticket with the "Add" button, an error will appear reminding him to fill in the mandatory fields before validating the ticket (which is normal).

On the other hand, there is a pure and simple reset of the entire ticket entry, which is very frustrating for users because they have to re-enter their entire ticket.

![Reset](https://user-images.githubusercontent.com/42821532/193852867-17d852ce-d6cd-4be0-8dac-8f4f5aabffb6.jpg)

**Comment by cconard96** [comment] 2022-11-04 22:31
Can you re-test on GLPI 10.0.5 to see if this is still an issue?

**Comment by LeFouineur** [comment] 2022-11-05 08:25
The problem is still present in 10.0.5

**Comment by Gor3pig** [comment] 2022-11-05 08:31
Yes, still present in 10.0.5

**Comment by cedric-anne** [comment] 2022-12-15 07:59
Fixed by #13292.

**Closed by cedric-anne** 2022-12-15 07:59 UTC
