### ISSUE TITLE
Couldn't find created ticket after upgrading to GLPI 9.2

### ISSUE THREAD

**Issue by zawaye** [glpi-project/glpi#2871] opened 2017-09-29 09:48 UTC
Dear GLPI Team,

I am using GLPI since 2 years ago. But earlier version of GLPI didn't found any error for upgrading from one version to another. Although I can upgrade from GLPI 9.1.6 to GLPI 9.2, I couldn't found any created ticket in my previous version even I search with ticket status = All. Therefore, I try to test with new ticket. But, the created new ticket also couldn't be found again. 
What happen in this complete version? 
Thanks,

**Comment by trasher** [comment] 2017-09-29 11:01
Check your logs, I guess something went wrong while upgrading your database.

**Comment by AircraftRu** [comment] 2017-09-29 12:05
I confirm it. I couldn't found all my tickets.

GLPI  9.1.4 -> GLPI 9.2

**Comment by zawaye** [comment] 2017-10-01 07:24
I haven't found any error message during my upgrade process. I just found just five warning as the following list:

1. ldap extension is not present
2. imap extension is not present
3. Zend OPcache extension is not present
4. APCu extension is not present
5. xmlrpc extension is not present

**Comment by vinz38500** [comment] 2017-10-09 09:28
Hey, I had exactly the same issue.. I can access a ticket with a direct link, but no chance to display the list of tickets.
I will redo the upgrade of the db as I may have forgotten an error message ..
Let's see

**Comment by vinz38500** [comment] 2017-10-09 12:46
Hello again
I did the upgrade from 9.1.4 tp 9.2 using cliupdate.php (to avoid timeout in the user interface)

I have the same behaviour, without any error in my log files

The only one I get is when I try to display tickets : 
`  Error: Unknown column 'glpi_tickets.time_to_resolve' in 'field list'
`
Result of my cliupdate 
`C:\LOCALDATA\website\glpi-9.2\tools>php cliupdate.php
Current GLPI version         : 9.1.4
New GLPI version             : 9.2
Current GLPI database version: 9.1.4
New GLPI database version    : 9.2
Default GLPI Language        : en_GB

========================================== Update to 9.2 ===========================================
** Api users tokens has been reset, if you use REST/XMLRPC api with personal token for authentication, please reset your user's token.
Configuration values added for login_remember_time, login_remember_default, use_notifications, notifications_mailing, notifications_ajax, notifications_ajax_check_interval, notifications_ajax_sound, notifications_ajax_icon_url, dbversion, sTask completed. (2 minutes 51 seconds)
Migration Done.`

**Comment by trasher** [comment] 2017-10-09 13:02
This is strange you get no errors during the upgrade :/
This is a field that should have been renamed; could you confirm there is a `due_date` in your `glpi_tickets` table? Same for `glpi_changes` and `glpi_problems`.

**Comment by vinz38500** [comment] 2017-10-09 13:07
Hey trasher,

Yes I confirm the field `due_date` exists in my `glpi_tickets` table.

``due_date` TIMESTAMP NULL DEFAULT NULL`
	
This field also exists in `glpi_changes` and in `glpi_problems`

**Comment by vinz38500** [comment] 2017-10-09 13:09
my colleague @tomolimo did the upgrade from 9.1.2 to 9.2 and it worked. I did a 9.1.4 to 9.2 ... in case it could help ;)

**Comment by trasher** [comment] 2017-10-09 14:00
Without any error; it's difficult to say what could goes wrong...

Just to be sure, did you check both `files/_log/php-errors.log` and `files/_log/sql-errors.log`? I was expecting to get something in the second one...

One of the lines that are not played is https://github.com/glpi-project/glpi/blob/9.2/bugfixes/install/update_91_92.php#L773

Could you tell  me if some of the following changes has been done (for example, do you have a table named `glpi_saved_searches`? What about the `*simcards*` tables?

**Comment by vinz38500** [comment] 2017-10-09 14:11
This is unbelievable ...
I've done a third migration (manually) and now it works ...
I really don't know what could have been the source of the problem as it finally works but I don't know why ...
Thks for your help @trasher and @tomolimo

**Comment by trasher** [comment] 2017-10-09 14:15
Hum... This remains me an issue @yllen get sometimes, and I've never been able to reproduce... She get the same behavior as yours: this did not work; and finally, this has worked without any changes.

Maybe should we log everything the update process does in order to find what goes wrong in such cases.

**Comment by usrqmor** [comment] 2017-10-16 13:37
Hi,
I got the same problem when I upgrade 0.90 to 9.2. I've no error when I check the log.
But I had this message "Votre version de la base de données n'est pas compatible avec la version des fichiers installés. Une mise à jour est nécessaire." and this one "Api users tokens has been reset, if you use REST/XMLRPC api with personal token for authentication, please reset your user's token." when the DB upgrade is finished.

The only bug I found is it. 
I'm using a debian 8 with php 5.6.3 and Mysql 5.7.
 
Did you have and idea about this problem ?
thank you.

**Comment by trasher** [comment] 2017-10-16 13:41
Try to:
- drop all tables in the database,
- restore your original dump
- do update

**Comment by usrqmor** [comment] 2017-10-16 13:50
Hi @trasher,
It works for me ! Thank you.
I think during my test with my plugins, I load a dump without delete the database and after I had this bug.

**Comment by trasher** [comment] 2017-10-16 13:53
This is the only way we can reproduce the issue; thanks for your feedback

**Comment by trasher** [comment] 2017-11-03 07:47
Fixed in #3041

**Closed by trasher** 2017-11-03 07:47 UTC
Labels: bug
