### ISSUE TITLE
BUG # GLPI changes the AUTHOR of the service

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#4299] opened 2018-07-05 15:33 UTC
Hello people.

When opening a service with more than one applicant, GLPI changes the AUTHOR of the service.

Example: Person X (author) requests access to Ms. Z and Y. When the service is opened, the GLPI informs that person who requested was person Y and not person X.

Has anyone ever experienced this?

version 9.2.1 through 9.2.4
![name](https://user-images.githubusercontent.com/35368369/42332823-68c68dac-804f-11e8-9e6a-c7ff31b965f1.gif)

**Comment by phamorais** [comment] 2018-07-13 16:23
Boys

In my test, it was resolved in GLPI 9.2.3, but it occurred again in 9.2.4

**Comment by trasher** [comment] 2018-07-26 05:22
Cannot reproduce, It's certainly fixed now.

**Closed by trasher** 2018-07-26 05:22 UTC
Labels: Need feedback
