### ISSUE TITLE
Glpi Version 9.5.3 Ajax browser notifications

### ISSUE THREAD

**Issue by kleverson4g** [glpi-project/glpi#8556] opened 2021-01-20 14:14 UTC
Enabled the notification via browser and works perfectly, but the notification queue is not clear like the email, is there any automatic action that corrects this?
I look forward and thank you.

**Comment by cedric-anne** [comment] 2021-03-10 14:49
Hi,

Queued notifications are cleared when they are delivered to the user. For email, delivering is done by a cron task and so their are cleared at this moment. For browser notification, delivery is done when user is connected to GLPI. If a user never connects, its notifications remains in queue.

Automatic cleaning of browser notifications is not done yet, although it is an interresting feature.

You may consider to discuss about this new feature with the community on our suggest website: https://suggest.glpi-project.org .

If you want to fund this feature, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us

I close this issue as it is not a bug.

Regards

**Closed** 2021-03-15 11:19 UTC
Labels: enhancement
