### ISSUE TITLE
WebCal Export issue in GLPI 9.1.1

### ISSUE THREAD

**Issue by Krisstof** [glpi-project/glpi#1422] opened 2016-12-11 08:32 UTC
I
Exporting GLPI WebCal planning to Apple Calendar doesn't work anymore (works in previous 0.x versions | just need to replace "webcal" with "http" in exported address).
Error in Apple Calendar : Error -1
Seems to be a syntax problem on exported file.

**Comment by Krisstof** [comment] 2017-01-11 21:54
"WebCal Export" sync correctly "Notes" but not "Ticket Tasks".

**Comment by trasher** [comment] 2017-01-27 10:46
Duplicate of #1448

**Closed by trasher** 2017-01-27 10:46 UTC
Labels: bug, duplicate
