### ISSUE TITLE
When forcing e-mail collector/receiver, attachements gets the connected user as the owner 

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi#3033] opened 2017-10-23 13:41 UTC
When user forcing a receiver (mailcollector) to fetch e-mails with the button *Get Email Tickets Now*, if found e-mails have any attachments, they will be created but with the user having clicked on the collect button as the owner instead of the user having sent the e-mail.

Steps to reproduce:
1. Alice send an e-mail to the collector e-mail address with *capture.jpg* attachment.
2. Bob click on *Get Email Tickets Now* button.

Actual result

* A new ticket is created with author = Alice
* A new document *capture.jpg* is created with owner = Bob

Excepted result

* A new ticket is created with author = Alice
* A new document *capture.jpg* is created with owner = Alice

Version: GLPI 9.1.2 (could not find any issue related to such thing)

**Comment by trasher** [comment] 2017-10-23 13:44
Several bugs has been fixed since 9.1.2. Maybe should you first try to update.

**Comment by trasher** [comment] 2017-11-03 07:45
Duplicate of https://github.com/glpi-project/glpi/issues/2875

**Comment by trasher** [comment] 2017-11-03 13:05
This is not a duplicate; this one is about manual fetching of collectors

**Closed** 2017-11-06 08:13 UTC
Labels: bug

**Comment by okvok** [comment] 2017-12-10 12:25
The BUG is still presenting in 9.2.1
