### ISSUE TITLE
global search work only with open tickets

### ISSUE THREAD

**Issue by Alex-itb** [glpi-project/glpi#716] opened 2016-06-08 14:25 UTC
My GLPI's global search work only with open tickets. It is very unusefull, because all open tickets usually shows on ticket's page and if I want to find an old ticket I can't do it. Is it BUG or a feature?

I use GLPI v.0.90.1

**Comment by yllen** [comment] 2016-06-10 11:52
You can find closed tickets from search engine by a search on ticket status.
Global search is only for active items

**Comment by Alex-itb** [comment] 2016-06-14 12:59
So, it is not a GLOBAL search...

**Comment by orthagh** [comment] 2016-06-24 12:13
I see several points to not do this :

* Performance, global search do search on a lot of objects (mainly assets and itil objects) and can be already slow. On specific instances with multiple thousands of assets and billion of tickets, il will be insanely slow to perform the queries and display the result.

* As mentioned by @yllen, it intended to retrieve active objects. Changing this behavior could be considered as regression by another users. It will confusing results.

* You have another way(s) as technicians or self-service users to retrieve closes ticket and search in their content.

I close, feel free to continue discussion on this issue if you need precisions.

**Closed by orthagh** 2016-06-24 12:13 UTC
