### ISSUE TITLE
contract display problem

### ISSUE THREAD

**Issue by falgi-dav** [glpi-project/glpi#7971] opened 2020-09-17 15:19 UTC
**error sql on contrat when display :** 

GLPI 9.5.1
```
_SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'glpi_contractcosts``.`cost`) / COUNT(``glpi_contractcosts``.`id`)) * COUNT(DISTI' at line 4 in query "SELECT DISTINCT `glpi_contracts`.`id` AS id, 'david' AS currentuser, `glpi_contracts`.`entities_id`, `glpi_contracts`.`is_recursive`, `glpi_contracts`.`name` AS `ITEM_Contract_1`, `glpi_contracts`.`id` AS `ITEM_Contract_1_id`, `glpi_entities`.`completename` AS `ITEM_Contract_80`, `glpi_contracttypes`.`name` AS `ITEM_Contract_4`, `glpi_contracts`.`num` AS `ITEM_Contract_3`, `glpi_contracts`.`begin_date` AS `ITEM_Contract_5`, `glpi_contracts`.`duration` AS `ITEM_Contract_6`, `glpi_contracts`.`notice` AS `ITEM_Contract_7`, (SUM(``glpi_contractcosts``.`cost`) / COUNT(``glpi_contractcosts``.`id`)) * COUNT(DISTINCT ``glpi_contractcosts``.`id`) AS `ITEM_Contract_11` FROM `glpi_contracts`LEFT JOIN `glpi_entities` ON (`glpi_contracts`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_contracttypes` ON (`glpi_contracts`.`contracttypes_id` = `glpi_contracttypes`.`id` ) LEFT JOIN `glpi_contractcosts` ON (`glpi_contracts`.`id` = `glpi_contractcosts`.`contracts_id` ) WHERE `glpi_contracts`.`is_deleted` = 0 AND `glpi_contracts`.`is_template` = 0 GROUP BY `glpi_contracts`.`id` ORDER BY ITEM_Contract_1 ASC LIMIT 0, 20"_
```

**Comment by falgi-dav** [comment] 2020-09-17 18:17
i think the sql syntax of line  : **(SUM(``glpi_contractcosts``.`cost`) / COUNT(``glpi_contractcosts``.`id`)) * COUNT(DISTINCT ``glpi_contractcosts``.`id`)** not correct
and the right syntax is ; 
**(SUM(`glpi_contractcosts`.`cost`) / COUNT(`glpi_contractcosts`.`id`)) * COUNT(DISTINCT `glpi_contractcosts`.`id`)**

**Comment by cedric-anne** [comment] 2020-09-18 07:18
Hi,

Same problem appeared in #7843 and was not reproduceable on a freshly installed instance.

Do you use php-fpm ? In this case, can you try to restart PHP service ? Maybe this bug comes from an unexpected behaviour in PHP cache.

Regards

**Comment by falgi-dav** [comment] 2020-09-18 17:16
on the query i have : COUNT(``glpi_contractcosts``.`id`)) * COUNT(DISTINCT ``glpi_contractcosts``.`id`)
i think it's a syntax error on the query ('' before and after glpi_)
when i take the old file (contract.class.php) on a glpi 9.4.5 , its work perfectly ...

**Comment by cedric-anne** [comment] 2020-09-21 06:16
Hi,

Do you use php-fpm ? In this case, can you try to restart PHP service ?

Regards

**Comment by falgi-dav** [comment] 2020-09-21 07:36
No i don't use php-fpm but php7.4.3

**Comment by cedric-anne** [comment] 2020-09-21 07:40
Can you paste here the content of `Server` section of `Setup >  General > System` page ?

**Comment by falgi-dav** [comment] 2020-09-21 07:45
[code]   GLPI 9.5.1 (/helpdesk => /var/www/html/helpdesk) Installation mode: TARBALL
--

Operating system: Linux ECF-Services 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 163.172.72.43 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0 Server Software: (Ubuntu) 	Server Version: 8.0.21-0ubuntu0.20.04.4 	Server SQL Mode:  	Parameters: glpi_user@localhost/GLPI 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (8.0.21) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /var/www/html/helpdesk/config has been validated. Write access to /var/www/html/helpdesk/files has been validated. Write access to /var/www/html/helpdesk/files/_dumps has been validated. Write access to /var/www/html/helpdesk/files/_sessions has been validated. Write access to /var/www/html/helpdesk/files/_cron has been validated. Write access to /var/www/html/helpdesk/files/_graphs has been validated. Write access to /var/www/html/helpdesk/files/_lock has been validated. Write access to /var/www/html/helpdesk/files/_plugins has been validated. Write access to /var/www/html/helpdesk/files/_tmp has been validated. Write access to /var/www/html/helpdesk/files/_cache has been validated. Write access to /var/www/html/helpdesk/files/_rss has been validated. Write access to /var/www/html/helpdesk/files/_uploads has been validated. Write access to /var/www/html/helpdesk/files/_pictures has been validated. Write access to /var/www/html/helpdesk/marketplace has been validated. Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

GLPI_ROOT: /var/www/html/helpdesk GLPI_CONFIG_DIR: /var/www/html/helpdesk/config GLPI_VAR_DIR: /var/www/html/helpdesk/files GLPI_MARKETPLACE_DIR: /var/www/html/helpdesk/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/helpdesk/files GLPI_CACHE_DIR: /var/www/html/helpdesk/files/_cache GLPI_CRON_DIR: /var/www/html/helpdesk/files/_cron GLPI_DUMP_DIR: /var/www/html/helpdesk/files/_dumps GLPI_GRAPH_DIR: /var/www/html/helpdesk/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/helpdesk/files/_locales GLPI_LOCK_DIR: /var/www/html/helpdesk/files/_lock GLPI_LOG_DIR: /var/www/html/helpdesk/files/_log GLPI_PICTURE_DIR: /var/www/html/helpdesk/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/helpdesk/files/_plugins GLPI_RSS_DIR: /var/www/html/helpdesk/files/_rss GLPI_SESSION_DIR: /var/www/html/helpdesk/files/_sessions GLPI_TMP_DIR: /var/www/html/helpdesk/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/helpdesk/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/helpdesk/locales GLPI_VERSION: 9.5.1 GLPI_SCHEMA_VERSION: 9.5.0 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/html/helpdesk/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/helpdesk/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.5 in (/var/www/html/helpdesk/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/helpdesk/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/helpdesk/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/helpdesk/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/helpdesk/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/helpdesk/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/helpdesk/vendor/sabre/http/lib) sabre/uri in (/var/www/html/helpdesk/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/helpdesk/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/helpdesk/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/helpdesk/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/helpdesk/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/helpdesk/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/helpdesk/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/helpdesk/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/helpdesk/vendor/symfony/console) scssphp/scssphp in (/var/www/html/helpdesk/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/helpdesk/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/helpdesk/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/helpdesk/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/helpdesk/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/helpdesk/vendor/ramsey/uuid/src) psr/log in (/var/www/html/helpdesk/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/helpdesk/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/helpdesk/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/helpdesk/vendor/guzzlehttp/guzzle/src) wapmorgan/unified-archive in (/var/www/html/helpdesk/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/helpdesk/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Server: '45.89.78.190', Port: '389', BaseDN: 'DC=ECF-SPS,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'sk2h@ECF-SPS.local', 		Use TLS: none

Not active

Way of sending emails: SMTP (informatique@ecf-sps.fr@ssl0.ovh.net)

 

advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Enabled 	news                 Name: Alertes                        Version: 1.7.0      State: Enabled 	accounts             Name: Comptes                        Version: 2.6.0      State: Enabled 	useditemsexport      Name: Export des éléments utilisés   Version: 2.4.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	gappessentials       Name: Gapp Essentials                Version: 1.2.0      State: Enabled 	geninventorynumber   Name: Génération de numéros d'invent Version: 2.5.0      State: Enabled 	order                Name: Gestion des commandes          Version: 2.6.0      State: Enabled 	tag                  Name: Gestion des tags               Version: 2.7.0      State: Enabled 	notifications        Name: Notifications                  Version: 9.4+1.0    State: Enabled 	protocolsmanager     Name: Protocols manager              Version: 1.3.0      State: Enabled 	dashboard            Name: Tableau de bord                Version: 0.9.9      State: Enabled 	yagp                 Name: yagp                           Version: 1.1.0      State: Enabled

**Comment by cedric-anne** [comment] 2020-09-21 07:47
Can you try to restart apache to see if problem persist ?

**Comment by falgi-dav** [comment] 2020-09-21 07:50
same problem after restarting apache

**Comment by falgi-dav** [comment] 2020-09-21 07:53
problem with the query invalid syntax i think in : COUNT(\`\`glpi_contractcosts\`\`.`id`)) * COUNT(DISTINCT \`\`glpi_contractcosts\`\`.`id`)
=> two \'\'
![image](https://user-images.githubusercontent.com/16518184/93743318-2635bc00-fbf0-11ea-885f-e11774e61abb.png)

**Comment by cedric-anne** [comment] 2020-09-21 07:59
As I said, same problem appeared in #7843 and was not reproduceable on a freshly installed instance.

So, I do not know how to fix this.

**Comment by cedric-anne** [comment] 2020-09-25 11:07
Hi,

Did you patched the `inc/search.class.php` file ? On #7843,  #7870 and #7997, it appears that users were using a file that was not coming from the official package, and this was causing the bug.

Regards

**Comment by cedric-anne** [comment] 2020-09-30 08:07
Hi,

I close this issue as you did not provide a feedback on latest comments and as other similar issues were due to usage of glpi-modifications plugin.

Regards

**Closed by cedric-anne** 2020-09-30 08:07 UTC
Labels: help wanted
