### ISSUE TITLE
Some notifications are not being sent

### ISSUE THREAD

**Issue by valentindragan** [glpi-project/glpi#4220] opened 2018-06-22 10:46 UTC
------------
* Steps to reproduce (which actions have you made) :
Create a new notification
Add more than one recipent

* Expected result :
All recipients should receive email
For debuging and reporting purposes, the queuednotifications table should also contain a notifications_id column. It is easy to know the notificationstemplates_if from notifications_id but very hard the other way around.

* Actual result :
Only one or sometime of the recipients receive the emails, even though entries have been generated for all of them in queued notifications

* URL of the page :

* Screenshot of the problem (if pertinent) :
http://prntscr.com/jxzsy3

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

Information about system installation and configuration
--
[code]   GLPI 9.2.3 ( => /usr/share/glpi)

Information about system installation and configuration
[code]
 
GLPI 9.2.3 ( => /usr/share/glpi)
Installation mode: GIT

Server
 
Operating system: Linux  2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64
PHP 5.6.36 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer,
	wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache (Apache Server at removed Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Server Software: MySQL Community Server (GPL) by Remi
	Server Version: 5.5.45-log
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/etc/glpi : OK
OK/var/lib/glpi/files : OK
OK/var/lib/glpi/files/_dumps : OK
OK/var/lib/glpi/files/_sessions : OK
OK/var/lib/glpi/files/_cron : OK
OK/var/lib/glpi/files/_graphs : OK
OK/var/lib/glpi/files/_lock : OK
OK/var/lib/glpi/files/_plugins : OK
OK/var/lib/glpi/files/_tmp : OK
OK/var/lib/glpi/files/_cache/ : OK
OK/var/lib/glpi/files/_rss : OK
OK/var/lib/glpi/files/_uploads : OK
OK/var/lib/glpi/files/_pictures : OK
OK/var/log/glpi : OK
OKSELinux mode is Permissive
OKSELinux boolean configuration for httpd_can_network_connect --> on
OKSELinux boolean configuration for httpd_can_network_connect_db --> on
OKSELinux boolean configuration for httpd_can_sendmail --> on

Libraries
 
htmLawed version 1.1.20 in (/usr/share/php/htmLawed)
phpCas version 1.3.5 in (/usr/share/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/usr/share/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

LDAP directories
 
Server: -

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@removed)

Mails receivers
 
Name: 'removed' Active: No
	Server: '{removed:995/imap}' Login: 'removed' Password: Yes
Name: 'removed' Active: Yes
	Server: '{removed:143/imap/notls/debug}GLPI' Login: 'removed' Password: Yes
Name: 'removed' Active: No
	Server: '{removed:995/imap/ssl}Test' Login: 'removedo' Password: Yes
Name: 'removed' Active: Yes
	Server: '{removed:143/imap/notls}GLPI' Login: 'removed' Password: Yes
Name: 'removed' Active: No
	Server: '{removed:993/imap/ssl/notls}GLPI' Login: 'removed' Password: Yes

Plugins list
 
	behaviors            Name: Comportements                  Version: 0.85       State: Not activated
	moreticket           Name: More ticket                    Version: 1.1.2      State: Not activated
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.4.3      State: Enabled
	mreporting           Name: Plus de rapports               Version: 0.85+1.0   State: Not activated
	purgelogs            Name: Purge de l'historique          Version: 0.85+1.1   State: Not activated
	reports              Name: Rapports                       Version: 1.8.0      State: Not activated

OCS Inventory NG
Host: localhost
Connection: Ok
Use the OCSNG software dictionary: No
[/code]

**Comment by trasher** [comment] 2018-06-22 11:18
Check mail logs; if only some messages are not sent, there is certainly something wrong on those adresses.

**Comment by trasher** [comment] 2018-06-22 13:04
If you do not want to provide requested informations, I can't help.

**Comment by valentindragan** [comment] 2018-06-25 05:52
Post updated

**Comment by valentindragan** [comment] 2018-06-25 08:34
I think i found the bug.
The queuednotifications automatic action was stuck on "Running" since 21st of June (5 days ago).
I have also checked another installation of glpi which had some automatic actions stuck for about two years, even though, some emails where sent right away, and any emails that were supposed to be sent by cron (cli) were not sent.
The bug would be that some cron jobs get stuck on Running. (occured on 0.85. and  9.2.3)

**Comment by trasher** [comment] 2018-06-26 11:04
When a crontask is marked as running for a while, an error has probably occurred first, and the the task get freezed. Closing this one since this is not a root cause.

**Closed by trasher** 2018-06-26 11:04 UTC

**Comment by valentindragan** [comment] 2018-07-02 12:42
I am sorry, but how cannot this be a bug?
Some cronjobs remain locked (even for years).
The watcher task should unlock the locked jobs, instead it is just setting a variable $cron_status = 1; which, from what I can see, doesn't do anything.

```

static function cronWatcher($task) {
      global $CFG_GLPI, $DB;

      $cron_status = 0;

      // Crontasks running for more than 1 hour or 2 frequency
      $query = "SELECT *
                FROM `glpi_crontasks`
                WHERE `state` = '".self::STATE_RUNNING."'
                      AND ((unix_timestamp(`lastrun`) + 2 * `frequency` < unix_timestamp(now()))
                           OR (unix_timestamp(`lastrun`) + 2*".HOUR_TIMESTAMP." < unix_timestamp(now())))";
      $crontasks = [];
      foreach ($DB->request($query) as $data) {
         $crontasks[$data['id']] = $data;
      }

      if (count($crontasks)) {
         $task = new self();
         $task->getFromDBByQuery("WHERE `itemtype` = 'Crontask' AND `name` = 'watcher'");
         if (NotificationEvent::raiseEvent("alert", $task, ['items' => $crontasks])) {
            $cron_status = 1;
            $task->addVolume(1);
         }
         QueuedNotification::forceSendFor($task->getType(), $task->fields['id']);
      }

      return 1;
   }
```

**Comment by trasher** [comment] 2018-07-02 13:51
The way crons are handled may be improved. This is not a bug, but an improvement, you can open this a a suggestion.
As of the current issue, as far as I can see; the bug has occured when cron had failed. What you describe is related to this one.
