### ISSUE TITLE
Retirement/Retierement Date - Software still counts as installed

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#6848] opened 2020-01-24 10:58 UTC
**Describe the bug**

If I set a Decommissioning/Retierement date the Installed Software is still in the List of "installed on" after this Date occurs.

**Page(s) URL**

front/computer.form.php?id=
front/software.form.php?id=

**To reproduce**

1. Go to Computer, Select one
2. Click on "Verwaltung" (Management), Set yesterday as Decommissioning/Retierement date
3. Go to Inventory->Software, select one which is installed on the computer from step 1
4. Click on installed
5. You see the software installed on retired Computer

**Expected behavior**
Software isn't shown because the Computer is retired

**Screenshots**
![1](https://user-images.githubusercontent.com/25504254/73064144-d0faac80-3ea0-11ea-9898-e9e18098bcc1.JPG)
![2](https://user-images.githubusercontent.com/25504254/73064148-d48e3380-3ea0-11ea-84a3-d820bca551ce.jpg)

**Comment by trasher** [comment] 2020-01-24 10:59
Informations requested in ticket template has not been provided.

**Comment by vollkommenIrrelevant** [comment] 2020-01-24 11:00
> 
> 
> Informations requested in ticket template has not been provided.

I think those are not nessesscarry.

**Comment by cedric-anne** [comment] 2020-01-24 13:52
Hi,

As far as I know GLPI, this retirement date is just an indicative date, so an asset having a retirement date in the past will not necessary be retired. It can, for instance, may be an administrative information that is not stricly matching the state of IT infrastructure. So, IMHO, removing softwares from installation count in this case may have unwanted side effects.

I am pretty sure that enhancements can be done to have a better handling of assets lifecycle on GLPI core. If you want to sponsor enhancemnts, feel free to contact us at contact@teclib.com .

I close this issue as this is not a bug.

Regards

**Closed by cedric-anne** 2020-01-24 13:52 UTC
Labels: invalid

**Comment by vollkommenIrrelevant** [comment] 2020-01-24 13:55
Unfortenately I have currently no Budget for this. Can you move this into a feature request?
