### ISSUE TITLE
[Glpi 9.4.4] "Requester-Writer" search filter does not work

### ISSUE THREAD

**Issue by johnartus** [glpi-project/glpi#6624] opened 2019-11-22 12:01 UTC
Nothing is displayed when I filter tickets on "Requester-Writer".

![image](https://user-images.githubusercontent.com/45217355/69423558-b2ecc080-0d26-11ea-81dd-ece697a7e000.png)

On debug mode, the query executed appears to be:

SELECT DISTINCT `glpi_tickets`.`id` AS id, 'DDupond' AS currentuser, `glpi_tickets`.`id` AS `ITEM_Ticket_2`, `glpi_tickets`.`name` AS `ITEM_Ticket_1`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`content` AS `ITEM_Ticket_1_content`, `glpi_tickets`.`status` AS `ITEM_Ticket_1_status`, `glpi_tickets`.`status` AS `ITEM_Ticket_12`, `glpi_tickets`.`date` AS `ITEM_Ticket_15`, `glpi_tickets`.`priority` AS `ITEM_Ticket_3`, GROUP_CONCAT(DISTINCT `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_4`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id`, ' ', `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_4_2`, GROUP_CONCAT(DISTINCT `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_5`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id`, ' ', `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_5_2`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_groups_1358be41ea7158319a888236ffba5355`.`completename`, '__NULL__'), '$#$',`glpi_groups_1358be41ea7158319a888236ffba5355`.`id`) 
ORDER BY `glpi_groups_1358be41ea7158319a888236ffba5355`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_8`, `glpi_itilcategories`.`completename` AS `ITEM_Ticket_7`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`items_id`, '__NULL__'), '$#$',`glpi_items_tickets`.`id`) 
ORDER BY `glpi_items_tickets`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_13`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`itemtype`, '__NULL__'), '$#$', `glpi_items_tickets`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Ticket_13_itemtype`, `glpi_users_users_id_recipient`.`name` AS `ITEM_Ticket_22`, `glpi_users_users_id_recipient`.`realname` AS `ITEM_Ticket_22_realname`, `glpi_users_users_id_recipient`.`id` AS `ITEM_Ticket_22_id`, `glpi_users_users_id_recipient`.`firstname` AS `ITEM_Ticket_22_firstname`, `glpi_tickets`.`date_mod` AS `ITEM_Ticket_19` 
FROM `glpi_tickets` 
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60` ON (`glpi_tickets`.`id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id` AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 )
LEFT JOIN `glpi_users` AS `glpi_users_a5e2026cbcb683e774f93a59e24a62a4` ON (`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id` = `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` ) 
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b` ON (`glpi_tickets`.`id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )
LEFT JOIN `glpi_users` AS `glpi_users_f201be21cd638ee780d08cba4ceff0d4` ON (`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id` = `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` ) 
LEFT JOIN `glpi_groups_tickets` AS `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b` ON (`glpi_tickets`.`id` = `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )
LEFT JOIN `glpi_groups` AS `glpi_groups_1358be41ea7158319a888236ffba5355` ON (`glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`.`groups_id` = `glpi_groups_1358be41ea7158319a888236ffba5355`.`id` )
LEFT JOIN `glpi_itilcategories` ON (`glpi_tickets`.`itilcategories_id` = `glpi_itilcategories`.`id` ) 
LEFT JOIN `glpi_items_tickets` ON (`glpi_tickets`.`id` = `glpi_items_tickets`.`tickets_id` )
LEFT JOIN `glpi_users` AS `glpi_users_users_id_recipient` ON (`glpi_tickets`.`users_id_recipient` = `glpi_users_users_id_recipient`.`id` ) 
WHERE `glpi_tickets`.`is_deleted` = 0 AND ( (`glpi_users`.`id` = '1626') ) GROUP BY `glpi_tickets`.`id` 
ORDER BY ITEM_Ticket_19 DESC 

The query gets the following error :
Error Code: 1054. Unknown column 'glpi_users.id' in 'where clause'

Problem :
'Where clause' does not use the table alias (glpi_users_a5e2026cbcb683e774f93a59e24a62a4) but its physical name (glpi_users)...

**Comment by cedric-anne** [comment] 2019-11-22 14:58
Hi,

I cannot reproduce on current 9.4 nightly build (see https://forge.glpi-project.org/tarballs/). I am pretty sure it has been fixed by #6461 .

Regards

**Comment by trasher** [comment] 2019-12-03 10:23
No feedback from a while, closing.

**Closed by trasher** 2019-12-03 10:23 UTC
