### ISSUE TITLE
Columns empty in used items of a group after migration from 9.1.2 to 9.1.3

### ISSUE THREAD

**Issue by gvetois** [glpi-project/glpi#2230] opened 2017-05-22 16:02 UTC
Dear Glpi support group,

After the upgrade to the last version 9.1.3, the column name and group/user are empty in all groups.

Please see the following picture according each environnement :  

In 9.1.2, a group and the fields "used items" look like : 
![image](https://cloud.githubusercontent.com/assets/28869478/26317381/98604bfe-3f17-11e7-895d-5a0f1c7a37b6.png)

In 9.1.3 after upgrade, the fields "used items" for same group look like :  
![image](https://cloud.githubusercontent.com/assets/28869478/26317530/121eb89a-3f18-11e7-962c-11691e95af78.png)

thanks in advance for your help,

best regards,

Gérald

**Comment by flegastelois** [comment] 2017-06-15 07:16
Related to 786eb6fa8230d91997afd8a3a3b12f7f71b0fdec

**Comment by trasher** [comment] 2018-02-28 10:12
I've just tested with 9.2/bugfixes branch (9.2.2) and I cannot reproduce. Maybe this has been fixed since?

**Comment by trasher** [comment] 2018-03-28 12:13
No feedback, closing

**Closed by trasher** 2018-03-28 12:13 UTC
Labels: Need feedback, bug
