### ISSUE TITLE
Erro to Access Marketplace before upgrade from 9.5.0 to 9.5.1

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi#7708] opened 2020-07-16 14:19 UTC
After upgrading from version 9.5.0 to 9.5.1, access to the marketplace configuration is no longer available.

![image](https://user-images.githubusercontent.com/22614882/87681598-34311180-c755-11ea-9ec3-b7b22e025dba.png)

I think it's valid to inform that I had to change my BASEURL and I don't know if the marketplace has any restrictive configuration to that.

In a new test:

![image](https://user-images.githubusercontent.com/22614882/87682057-c76a4700-c755-11ea-8763-d8a6eff1a873.png)

I repeated the installation process for a new installation and the process was released.

But it makes me lose the database and all the settings already made.

NOTE:
In many cases, customers need to change their server addresses, FQDN addresses, and if this is a limitation, it can generate a very negative experience for using GLPi

**Comment by cedric-anne** [comment] 2020-07-16 14:24
Hi,

Could you check in logs ? This blank page may be result of a fatal error.

Regards

**Comment by glpibr** [comment] 2020-07-16 14:34
unfortunately, I cannot repeat the entire testing process at this time. But, I send here the files that were in file / _log.
I hope it helps.

#
# php-errors.log
#

[2020-07-16 10:10:35] glpiphplog.WARNING: Test logger  
[2020-07-16 10:10:38] glpiphplog.WARNING: Test logger  
[2020-07-16 10:10:55] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function listTables() on null in /home/halexsandro/public_html/glpi950/inc/config.class.php at line 2915
  Backtrace :
  install/update.php:56                              Config::loadLegacyConfiguration()
  install/install.php:557                            include_once()
  install/install.php:690                            update1()
  
[2020-07-16 10:11:47] glpiphplog.DEBUG: Html::compileScss() in /home/halexsandro/public_html/glpi950/inc/html.class.php line 7394
css/styles.scss is new, loading  {"user":"@PEVTCMTNB2590"} 
[2020-07-16 10:11:47] glpiphplog.DEBUG: Html::compileScss() in /home/halexsandro/public_html/glpi950/inc/html.class.php line 7394
css/palettes/auror.scss is new, loading  {"user":"@PEVTCMTNB2590"} 
[2020-07-16 11:02:52] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:180                      GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:243                      GLPINetwork::getRegistrationInformations()
  inc/marketplace/view.class.php:149                 GLPINetwork::isRegistered()
  inc/marketplace/view.class.php:192                 Glpi\Marketplace\View::checkRegister()
  inc/marketplace/view.class.php:115                 Glpi\Marketplace\View::installed()
  inc/commonglpi.class.php:637                       Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:03:07] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:180                      GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:243                      GLPINetwork::getRegistrationInformations()
  inc/marketplace/view.class.php:149                 GLPINetwork::isRegistered()
  inc/marketplace/view.class.php:192                 Glpi\Marketplace\View::checkRegister()
  inc/marketplace/view.class.php:115                 Glpi\Marketplace\View::installed()
  inc/commonglpi.class.php:637                       Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:03:22] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:180                      GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:243                      GLPINetwork::getRegistrationInformations()
  inc/marketplace/view.class.php:149                 GLPINetwork::isRegistered()
  inc/marketplace/view.class.php:192                 Glpi\Marketplace\View::checkRegister()
  inc/marketplace/view.class.php:115                 Glpi\Marketplace\View::installed()
  inc/commonglpi.class.php:637                       Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:03:25] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:180                      GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:243                      GLPINetwork::getRegistrationInformations()
  inc/marketplace/view.class.php:149                 GLPINetwork::isRegistered()
  inc/marketplace/view.class.php:252                 Glpi\Marketplace\View::checkRegister()
  inc/marketplace/view.class.php:119                 Glpi\Marketplace\View::discover()
  inc/commonglpi.class.php:637                       Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:03:33] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:180                      GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:243                      GLPINetwork::getRegistrationInformations()
  inc/marketplace/view.class.php:149                 GLPINetwork::isRegistered()
  inc/marketplace/view.class.php:252                 Glpi\Marketplace\View::checkRegister()
  inc/marketplace/view.class.php:119                 Glpi\Marketplace\View::discover()
  inc/commonglpi.class.php:637                       Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:03:36] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:180                      GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:243                      GLPINetwork::getRegistrationInformations()
  inc/marketplace/view.class.php:149                 GLPINetwork::isRegistered()
  inc/marketplace/view.class.php:192                 Glpi\Marketplace\View::checkRegister()
  inc/marketplace/view.class.php:115                 Glpi\Marketplace\View::installed()
  inc/commonglpi.class.php:637                       Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:06:54] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:55                       GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:46                       GLPINetwork::showForConfig()
  inc/commonglpi.class.php:637                       GLPINetwork::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:06:59] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:55                       GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:46                       GLPINetwork::showForConfig()
  inc/commonglpi.class.php:637                       GLPINetwork::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:07:02] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:55                       GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:46                       GLPINetwork::showForConfig()
  inc/commonglpi.class.php:637                       GLPINetwork::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:11:58] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php at line 102
  Backtrace :
  inc/toolbox.class.php:340                          GLPIKey->get()
  inc/toolbox.class.php:283                          Toolbox::getGlpiSecKey()
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:55                       GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:46                       GLPINetwork::showForConfig()
  inc/commonglpi.class.php:637                       GLPINetwork::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-07-16 11:14:46] glpiphplog.WARNING: Test logger  
[2020-07-16 11:14:58] glpiphplog.NOTICE: GLPIKey::getLegacyKey() in /home/halexsandro/public_html/glpi950/inc/glpikey.class.php line 117
Called method is deprecated  {"user":"@PEVTCMTNB2590"} 
[2020-07-16 11:27:34] glpiphplog.ERROR: Toolbox::sodiumDecrypt() in /home/halexsandro/public_html/glpi950/inc/toolbox.class.php line 296
Unable to decrypt content. It may have been crypted with another key.  {"user":"2@PEVTCMTNB2590"} 
[2020-07-16 11:28:34] glpiphplog.ERROR: Toolbox::sodiumDecrypt() in /home/halexsandro/public_html/glpi950/inc/toolbox.class.php line 296
Unable to decrypt content. It may have been crypted with another key.  {"user":"2@PEVTCMTNB2590"} 

#
# cron.log
# 

2020-07-16 10:11:52 [@PEVTCMTNB2590]
Interno #1: Executar temp
2020-07-16 10:21:41 [2@PEVTCMTNB2590]
Interno #1: Executar mailgateerror
2020-07-16 10:33:04 [@PEVTCMTNB2590]
Interno #1: Executar contract
2020-07-16 10:54:20 [2@PEVTCMTNB2590]
Interno #1: Executar infocom
2020-07-16 11:02:45 [2@PEVTCMTNB2590]
Interno #1: Executar mailgate
2020-07-16 11:15:14 [@PEVTCMTNB2590]
Interno #1: Executar createinquest
2020-07-16 11:25:06 [2@PEVTCMTNB2590]
Interno #1: Executar watcher
2020-07-16 11:28:17 [@PEVTCMTNB2590]
Interno #1: Executar session

#
# event.log
# 

2020-07-16 10:13:13 [@PEVTCMTNB2590]
[login] 3: glpi fez login no IP 127.0.0.1
2020-07-16 10:33:12 [@PEVTCMTNB2590]
[login] 3: glpi fez login no IP 127.0.0.1
2020-07-16 11:15:10 [@PEVTCMTNB2590]
[login] 3: Login falhou para  no IP 127.0.0.1
2020-07-16 11:15:17 [@PEVTCMTNB2590]
[login] 3: glpi fez login no IP 127.0.0.1
2020-07-16 11:28:28 [@PEVTCMTNB2590]
[login] 3: glpi fez login no IP 127.0.0.1

**Comment by cedric-anne** [comment] 2020-07-21 13:13
Hi,

It looks like you used an update path that does not create the GLPI security key file.
I do not know yet how to reproduce it. Can you explain how you did excatly the update ?

Regards

**Comment by trasher** [comment] 2020-08-04 05:51
No feedback from a while, closing.

**Closed by trasher** 2020-08-04 05:51 UTC
Labels: Need feedback
