### ISSUE TITLE
Pictures Not displayed

### ISSUE THREAD

**Issue by KevinStephane** [glpi-project/glpi#5211] opened 2019-01-08 14:54 UTC
Hello,

When users send email to open new tickets with a picture, the picture is remplaced by a char sequence in the body of ticket.

We have find a stange thing : if we change language "Francais -> English" the screenshoot is displayed, We have tested any language and english is the only one that pertmit displaying pictures.
This bug appear for the user picture too.

GLPI version is 9.3.3

Thanks

**Comment by orthagh** [comment] 2019-01-08 15:14
could you paste an example of "char sequence" ?

**Comment by KevinStephane** [comment] 2019-01-08 15:30
Yes 
d9df8aa7-d9d62df8-5c344d43791cd1.15936372

**Comment by orthagh** [comment] 2019-01-09 09:10
Some additional questions so (as we don't replicate on our side).

When you says switching language solve your issue, is it when creating a new ticket or tickets created under french language now works in english language.

When the issue trigger, could you open the developper console of your browser and check about errors.
Also, we may need glpi logs (you may find them into glpi/files/_logs folder), try to only extract and paste logs corresponding to the timestamp of your tests.

Regards

**Comment by KevinStephane** [comment] 2019-01-09 10:13
[](url)

**Comment by KevinStephane** [comment] 2019-01-09 10:21
You can download logs files here  http://dl.free.fr/wpJfLbe34
Yes when switching language we can from french to english  it works event if tiket are created in french.
There is no error in debug console

**Comment by orthagh** [comment] 2019-01-10 14:06
Nothing found in your logs.
And i can't replicate at the moment.

Maybe a hint, could you go into Setup > General menu (Configuration > Générale in french) and check the param named `URL of the application` and if it's corresponding to the real url of your glpi

**Comment by Armin83** [comment] 2019-02-07 22:00
I believe that GLPI in 9.3.3 saves different paths depending on the used url.
If you use http://glpi-ticket and create a ticket copy & paste a picture. It will be saved with path http://glpi-ticket/..... and you get the an error if you use the URL of the application. http://glpi-ticket.mydomain.com which is the correct. But in this case you see the char sequence and if you open the link it goes to http://glpi-ticket and you get the error no permission but if you change the url of the picture in the extra tab to http://glpi-ticket.mydomain.com you see the picture without errors.

Can you check this case?

**Comment by cedric-anne** [comment] 2019-02-26 14:25
Hi @Armin83 ,

I cannot reproduce your issue, but I saw 2 possible explainations.
1. As you use two different domains, you use 2 different cookies. So may you are not using same user for both domains.
2. You have internal redirections or something that can affect request on server side.

To be sure that URL stored in database for images is always consitent, I have proposed a fix on 9.4 branch  (#5471). Can you test it ?

Regards

**Comment by Armin83** [comment] 2019-02-27 21:20
@cedric-anne 
to 1. I don't have double domains. In one case i only use hostname or fqdn. http://myhostname (<-- without the domain) or http://myhostname.mydomain.de but i'm not sure if i have in this case 2 differen cookies. (In my case of course it is the same user. I have only one / this user.
to 2. in http://myhostname it is no http redirect but of course i got the right answer for the internal server, from my internal dns server. (btw myhostname.mydomain.de is the fqdn for the host in my internal network.)

we only use glpi form the internal network.

at the moment i have no system with 9.4. i will try to plan a update on my test system.

**Comment by cedric-anne** [comment] 2019-02-27 22:04
@Armin83 

If your session is not live while the image is requested, then your server will serve a login page instead of the image, so your browser will not be able to display it.

When image is not correctly displayed, could you check what is displayed when opening the image URL in your browser ? If it is a login page, then the problem is that cookies are not shared accross domains. If it is an error page, you may have logs that can help us tio investigate.

Regards

**Comment by cedric-anne** [comment] 2019-03-11 15:34
@Armin83 , @KevinStephane ,

When image is not correctly displayed, could you check what is displayed when opening the image URL in your browser ? If it is a login page, then the problem is that cookies are not shared accross domains, and it may be fixed by #5471 . If it is an error page, you may have logs that can help us to investigate.

If you do not respond, I cannot help.

Regards

**Comment by Kjacremz** [comment] 2019-03-12 04:22
I'm still being harrassed and my name is this not the 83 account and I have a Samsung j7

**Comment by Kjacremz** [comment] 2019-03-12 04:24
My name is jennifer porzeinski and this is my phone that turns off constantly my email is set to TLC and I am new to all this and this is the 2nd time I have had to get a phone

**Comment by alexnar7** [comment] 2019-03-12 18:20
Did you check if you can open the image directly with URL?, if you cannot, maybe you have to check Apache's rules.
If you have a line like: RewriteRule .* – [F] in .htaccess. Comment out 

I had a similir problem in my domain, I commented out that line and now it's working.

**Comment by trasher** [comment] 2019-04-16 07:01
No feedback from a while, closing.

**Closed by trasher** 2019-04-16 07:01 UTC
Labels: Need feedback, help wanted
