### ISSUE TITLE
Solved using type N/A

### ISSUE THREAD

**Issue by sazanof** [glpi-project/glpi#7638] opened 2020-07-09 11:33 UTC
Hi! When I push self-assigned button 
![image](https://user-images.githubusercontent.com/3595562/87034606-bfa82100-c1f0-11ea-86d0-dbb87de7e69e.png)
this message will automatically adds in comments thread
![image](https://user-images.githubusercontent.com/3595562/87034499-94253680-c1f0-11ea-930c-530d11947162.png)
if this not a bug? please tell me what can i check in database or somewhere 
glpi 9.4.6 (and now glpi 9.5)

**Comment by cedric-anne** [comment] 2020-07-09 11:35
Hi,

Please provide requested informations (logs, system informations, ...).

I do not reproduce this issue. It may be due to a plugin, or to your ticket business rules. Please deactivate them and try again.

Regards

**Comment by sazanof** [comment] 2020-07-09 11:46
Thanks! 
Ticket business rules
![image](https://user-images.githubusercontent.com/3595562/87035397-f5013e80-c1f1-11ea-825e-4e1cdadf17f7.png)
Plugins - only fusion inventory (for 9.5) activated
in history tab strange action 
![image](https://user-images.githubusercontent.com/3595562/87036065-ea937480-c1f2-11ea-952d-9f95a5aab482.png)

this bus starts when i updated to 9.4.3 to 9.4.6

**Comment by cedric-anne** [comment] 2020-07-09 11:50
Can you switch to english language ? I do not understand what your "strange action" could be.

**Comment by sazanof** [comment] 2020-07-09 11:53
![image](https://user-images.githubusercontent.com/3595562/87036617-c84e2680-c1f3-11ea-87c0-853eda9235b0.png)
when i push the self-assigned button, in history "Change New to Closed"

**Comment by cedric-anne** [comment] 2020-07-09 12:00
Again, please provide requested informations (logs, system informations, ...).

Also, did you deactivate all ticket business rules ?

**Comment by sazanof** [comment] 2020-07-09 12:39
> Also, did you deactivate all ticket business rules ?
Yes. All ticket business rules are deactiveted in panel (screenshot "Активен: Нет" == "Active = No")

ok, here is a system info tab
```
[code]
 
GLPI 9.5.0 ( => /var/www/html)
Installation mode: TARBALL

Server
 
Operating system: Linux webserver 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
PHP 7.2.24-0ubuntu0.18.04.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60000" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at glpi.mosgortur.ru Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 YaBrowser/20.6.2.195 Yowser/2.5 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.30-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (5.7.30) - Perfect!Database version seems correct (5.7.30) - Perfect!
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/config has been validated.Write access to /var/www/html/config has been validated.
Write access to /var/www/html/files has been validated.Write access to /var/www/html/files has been validated.
Write access to /var/www/html/files/_dumps has been validated.Write access to /var/www/html/files/_dumps has been validated.
Write access to /var/www/html/files/_sessions has been validated.Write access to /var/www/html/files/_sessions has been validated.
Write access to /var/www/html/files/_cron has been validated.Write access to /var/www/html/files/_cron has been validated.
Write access to /var/www/html/files/_graphs has been validated.Write access to /var/www/html/files/_graphs has been validated.
Write access to /var/www/html/files/_lock has been validated.Write access to /var/www/html/files/_lock has been validated.
Write access to /var/www/html/files/_plugins has been validated.Write access to /var/www/html/files/_plugins has been validated.
Write access to /var/www/html/files/_tmp has been validated.Write access to /var/www/html/files/_tmp has been validated.
Write access to /var/www/html/files/_cache has been validated.Write access to /var/www/html/files/_cache has been validated.
Write access to /var/www/html/files/_rss has been validated.Write access to /var/www/html/files/_rss has been validated.
Write access to /var/www/html/files/_uploads has been validated.Write access to /var/www/html/files/_uploads has been validated.
Write access to /var/www/html/files/_pictures has been validated.Write access to /var/www/html/files/_pictures has been validated.
Write access to /var/www/html/marketplace has been validated.Write access to /var/www/html/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

GLPI constants
 
GLPI_ROOT: /var/www/html
GLPI_CONFIG_DIR: /var/www/html/config
GLPI_VAR_DIR: /var/www/html/files
GLPI_MARKETPLACE_DIR: /var/www/html/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_FORCE_NATIVE_SQL_TYPES: 1
GLPI_DOC_DIR: /var/www/html/files
GLPI_CACHE_DIR: /var/www/html/files/_cache
GLPI_CRON_DIR: /var/www/html/files/_cron
GLPI_DUMP_DIR: /var/www/html/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales
GLPI_LOCK_DIR: /var/www/html/files/_lock
GLPI_LOG_DIR: /var/www/html/files/_log
GLPI_PICTURE_DIR: /var/www/html/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins
GLPI_RSS_DIR: /var/www/html/files/_rss
GLPI_SESSION_DIR: /var/www/html/files/_sessions
GLPI_TMP_DIR: /var/www/html/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/locales
GLPI_VERSION: 9.5.0
GLPI_SCHEMA_VERSION: 9.5.0
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2020

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.5 in (/var/www/html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/vendor/guzzlehttp/guzzle/src)
wapmorgan/unified-archive in (/var/www/html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.3 in (/usr/share/php)

LDAP directories
 
Server: '10.-.-.-', Port: '389', BaseDN: 'DC=dc,DC=------,DC=ru', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'saz@---------.ru', Use
		TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (it@mail.-------.ru@83.---.---.---)

Mails receivers
 
Name: 'it@mail.---------.ru' Active: Yes
	Server: '{83.---.---.---:143/imap/notls}' Login: 'it@mail.-----.ru' Password: Yes
Name: 'msazanov@mosgortur.ru' Active: No
	Server: '{outlook.office365.com:143/imap}' Login: '------@-------.ru' Password: Yes

Plugins list
 
	formcreator          Name: Form Creator                   Version: 2.8.0      State: Not installed
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	mydashboard          Name: My Dashboard                   Version: 1.7.2      State: Not installed
	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Not installed
	satisfaction         Name: Больше вопросов для оценки удо Version: 1.4.0      State: Not installed
	reports              Name: Отчеты                         Version: 1.13.0     State: Not installed
	mreporting           Name: Подробные отчеты          Version: 1.6.1      State: Not installed

[/code]
```
there is no log files in /var/log/glpi

**Comment by sazanof** [comment] 2020-07-09 12:41
i find _logs folder, wait a minute please

**Comment by sazanof** [comment] 2020-07-09 12:55
https://yadi.sk/d/FmjbSUgSaku_hw
pass - glpi09072020
i didnt find any useful info in logs

**Comment by sazanof** [comment] 2020-07-09 13:13
var_dump($track->fields) on pressing self assigned button before this line https://github.com/glpi-project/glpi/blob/c312b51b007e56d2fb129e18864f51c802dd34a8/front/ticket.form.php#L182

(and if i comment this line? of course noting happens? and "Solved by using type NA not adds")

```
array(43) {
  ["id"]=>
  int(1710313155)
  ["entities_id"]=>
  int(0)
  ["name"]=>
  string(4) "test"
  ["date"]=>
  string(19) "2020-07-09 15:43:41"
  ["closedate"]=>
  NULL
  ["solvedate"]=>
  NULL
  ["date_mod"]=>
  string(19) "2020-07-09 16:07:50"
  ["users_id_lastupdater"]=>
  int(45)
  ["status"]=>
  int(1)
  ["users_id_recipient"]=>
  int(45)
  ["requesttypes_id"]=>
  int(1)
  ["content"]=>
  string(23) "<p>teet</p>"
  ["urgency"]=>
  int(3)
  ["impact"]=>
  int(3)
  ["priority"]=>
  int(3)
  ["itilcategories_id"]=>
  int(1)
  ["type"]=>
  int(1)
  ["global_validation"]=>
  int(1)
  ["slas_id_ttr"]=>
  int(0)
  ["slas_id_tto"]=>
  int(0)
  ["slalevels_id_ttr"]=>
  int(0)
  ["time_to_resolve"]=>
  NULL
  ["time_to_own"]=>
  NULL
  ["begin_waiting_date"]=>
  NULL
  ["sla_waiting_duration"]=>
  int(0)
  ["ola_waiting_duration"]=>
  int(0)
  ["olas_id_tto"]=>
  int(0)
  ["olas_id_ttr"]=>
  int(0)
  ["olalevels_id_ttr"]=>
  int(0)
  ["ola_ttr_begin_date"]=>
  NULL
  ["internal_time_to_resolve"]=>
  NULL
  ["internal_time_to_own"]=>
  NULL
  ["waiting_duration"]=>
  int(0)
  ["close_delay_stat"]=>
  int(0)
  ["solve_delay_stat"]=>
  int(0)
  ["takeintoaccount_delay_stat"]=>
  int(1)
  ["actiontime"]=>
  int(0)
  ["is_deleted"]=>
  int(0)
  ["locations_id"]=>
  int(1)
  ["validation_percent"]=>
  int(0)
  ["date_creation"]=>
  string(19) "2020-07-09 15:43:41"
  ["solutiontypes_id"]=>
  int(0)
  ["solution"]=>
  string(0) ""
}
```

**Comment by cedric-anne** [comment] 2020-07-09 13:17
Have you a `solution` and a `solutiontypes_id` in your `glpi_tickets` table ?

**Comment by sazanof** [comment] 2020-07-09 13:19
yes they are
![image](https://user-images.githubusercontent.com/3595562/87044956-efaaf080-c1ff-11ea-8637-1c2cf69e0c9d.png)

**Comment by cedric-anne** [comment] 2020-07-09 13:37
They should not. These fields should have been drop during migration from 9.2 to 9.3.

This kind of issue happens when an old database dump is restored on a top of a new database (in your case, maybe a GLPI 9.2 database dump was restored on GLPI 9.3 database). Dumps does not drop new tables (as it does not know them),  and then update process has an unexpected behaviour.

So this is not a GLPI bug, you have issues with your database.

You can check result of `bin/console glpi:database:check` and try to fix this.

I close this issue as it is not a GLPI bug. To get support, you can ask for community support on [forum](https://forum.glpi-project.org/) or [get a subscription for a professionnal support](https://glpi-project.org/subscriptions/).

Regards

**Closed by cedric-anne** 2020-07-09 13:37 UTC
Labels: Need feedback

**Comment by sazanof** [comment] 2020-07-10 05:17
> They should not. These fields should have been drop during migration from 9.2 to 9.3.
yes, you`re right. i delete this columns & its fixed the issue. thank you!
