### ISSUE TITLE
[9.2] Global statistics graph in different languages

### ISSUE THREAD

**Issue by DanielSanIT** [glpi-project/glpi#2850] opened 2017-09-28 07:02 UTC
The global statistics do not show graphs for the Russian language and some other. In English works.

![image](https://user-images.githubusercontent.com/20223013/30953105-2891c042-a433-11e7-9187-3724b6d80b8d.png)

GLPI 9.2

P.S. In GLPI 9.1.4 worked.

**Comment by trasher** [comment] 2017-10-11 09:04
I cannot reproduce the issue as you describe; but I found another more global issue: https://github.com/glpi-project/glpi/issues/2946

Could you please test the provided (temporary) solution https://github.com/glpi-project/glpi/pull/2948?

**Comment by DanielSanIT** [comment] 2017-10-11 09:43
Solution #2948 / #2946 helped. Thx.

**Comment by trasher** [comment] 2017-10-11 09:57
I mark as duplicate of #2946 because this one is more generic. Thank you very much for your feedback :)

**Closed by trasher** 2017-10-11 09:57 UTC
Labels: duplicate
