### ISSUE TITLE
[GLPI 9.1.1] Global search don't display tickets

### ISSUE THREAD

**Issue by PierreTeclib** [glpi-project/glpi#1545] opened 2017-01-06 14:49 UTC
Hello,
When we use the global search with a ticket ID it's only display Documents and not ticket. 

See attaachment.

Thks

![image001](https://cloud.githubusercontent.com/assets/6872020/21721213/a07ea66a-d427-11e6-817e-a13f1b8e4693.jpg)

**Comment by AnaelMobilia** [comment] 2017-01-06 17:54
As today, global search only search on ticket title (nor content nor id, ...)
See #1386 too

Regards

**Comment by moralillos** [comment] 2017-01-06 21:49
In my case, l lost the Licenses when I update to 9.1 version. I dont know how the solution, please help me
Any solution?

![licencias](https://cloud.githubusercontent.com/assets/24966507/21734153/840757c0-d427-11e6-8816-bf81839bfb81.png)

Thanks

**Comment by novalenik** [comment] 2017-01-09 04:05
+1 global search problems

**Comment by tomolimo** [comment] 2017-01-09 06:37
@moralillos: please open a new issue, don't mix several subjects into one. If you do so, it's impossible to help you especially when subjects seem not to be related.
Thank you,
Regards,
Tomolimo

**Comment by AnaelMobilia** [comment] 2017-01-09 06:41
for @moralillos issue => already created on #1551 (unexplicit title)
Regards

**Comment by trasher** [comment] 2017-01-16 12:54
Hum... No, global search is not limited to tickets titles only; but I'm not able to reproduce the issue on the current 9.1/bugfixes branch, searching for a specific ticket ID actually find the ticket.

Should be fixed in 9.1.2

**Closed by trasher** 2017-01-16 12:54 UTC
Labels: bug

**Comment by vinz38500** [comment] 2017-03-17 13:52
Hi ! In fact, I guess the global search is working well (id for ex) on Onpened tickets only. If the ticket is closed, then it wil not be shown in the result ... but documents of this ticket will be ... :(
