### ISSUE TITLE
Fail2Ban filter

### ISSUE THREAD

**Issue by tx7** [glpi-project/glpi#791] opened 2016-07-07 12:11 UTC
Hello,

I'm currently using GLPI v0.90.3 via Nginx.
I would like to know if there is a Fail2ban filter for this.
Thanks in advance.

Log path: `/opt/glpi/files/_log/event.log`
Here's the log:

`[login] 1: Failed login for user1 from IP ::ffff:70.33.11.00
2016-07-02 21:35:44 [@server]
[login] 3: user1 logged in from IP ::ffff:70.33.11.00
2016-07-02 21:45:23 [@server]
[login] 3: admin logged in from IP ::ffff:192.168.1.9
2016-07-02 22:13:24 [@server]
[login] 3: admin logged in from IP ::ffff:192.168.1.9
2016-07-02 22:15:00 [@server]
[login] 1: Failed login for user1 from IP ::ffff:70.33.11.00
2016-07-02 22:15:05 [@server]`

**Comment by C-Duv** [comment] 2016-07-19 14:52
To my knowledge, there is none. I've found [a post by pr_bond on OMV forum where he tried one](http://forums.openmediavault.org/index.php/Thread/7750-openmediavault-fail2ban-first-version-now-available-for-testing/?postID=117665#post117665).
The problem is that fail2ban syntax requires a timestamp on the event line where GLPI (v0.90) writes it's event on two lines:
> DATE TIME [@SERVER]
> [login] 1: Failed login for foobar from IP 1.2.3.4

`Toolbox::logInFile()` is responsible for splitting the event into two lines.

It seems some reflexion about that was done in [old Redmine issue #5352](https://forge.glpi-project.org/issues/5352) and #27

**Comment by tx7** [comment] 2016-07-19 19:21
Yes, I know he wrote, but he seems to be busy to re-write the codes.
That's why I posted here to requesting for  solutions.

**Comment by btry** [comment] 2016-08-24 12:53
Hi

Multiline support on Fail2ban seems to be implement ed since 0.9.x (0.9.0 ?) 
Source :  http://stackoverflow.com/questions/14250481/fail2ban-regex-where-ip-is-on-one-line-and-failure-message-on-another

I checked for Debian : the version match starting Squeeze (will be probably released in 2017)

It is still possible to compile it thought.

**Comment by tx7** [comment] 2017-01-16 13:52
Hello,

Please close this thread.
I no longer need this.

Thanks.

**Closed** 2017-01-17 07:47 UTC
Labels: help wanted
