### ISSUE TITLE
API : entity created but not readable

### ISSUE THREAD

**Issue by Rico29** [glpi-project/glpi#6681] opened 2019-12-06 13:03 UTC
Hello,

**Describe the bug**
I'm using API to create entities. When my API user (ex : apiuser) create an entity with :
```
        $this -> url = '/Entity/';
        $this -> method = 'POST';
        $this -> data = array("name" => $name, "comment"=>$comment, "entities_id"=>$parent_entity_id);
```
The entity seems to be correctly created in GLPI database, but it is not viewable by the api user (apiuser) in the web pannel of GLPI.

When I try to force access to that entity (https://glpi/front/entity.form.php?id=12, 12 beeing the ID of the entity previously created), Igot a "permission denied" message. 

My apiuser has full permissions in his profile, under Administration > Entities

**Expected behavior**

apiuser should have permissions on the entity he created.

**Logs**

Did not see anything in logs except cache related stuff (I guess) in php-errors.log : 

> [2019-12-06 14:01:13] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi_dev/inc/toolbox.class.php line 658
>   *** PHP Warning(2): Cannot use a scalar value as an array
>   Backtrace :
>   inc/config.class.php:2989                          
>   inc/config.php:253                                 Config::getCache()
>   inc/includes.php:48                                include_once()
>   front/entity.form.php:33                           include()
>   {"user":"115@boggs","mem_usage":"0.000\", 5.80Mio)"} 

I'm running GLPI 9.4.5

Regards

**Comment by Rico29** [comment] 2019-12-06 14:01
I just upgraded my lab glpi to 9.5/bugfixes, it seems to work correctly now. Maybe a bug in 9.4 ?

**Comment by cedric-anne** [comment] 2019-12-10 12:52
Hi,

Entity list is stored in session, so if you create an entity with the API, you have to logout/login on web UI to see it.
This logout/login is not necessary when entity is created from UI due to this hack: https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/entity.class.php#L440

Regards

**Comment by Rico29** [comment] 2019-12-10 14:27
These lines are already present in my glpi 9.4 (I'm using 9.4/bugfixes git branch). It does not solve my problem.

**Comment by Rico29** [comment] 2019-12-10 14:31
And it does not change anything to login / logout in my situation

**Comment by cedric-anne** [comment] 2019-12-12 15:17
Hi,

I am not able to reproduce. #6711 should resolve the error you mentionned about cache instanciation. Could you make a test with this fix ? Maybe your problem is related to a cache issue.

Regards

**Comment by Rico29** [comment] 2019-12-13 07:22
Hi @cedric-anne 
At first sight it seems to fix my problem. I'll make deeper tests and keep you in touch Monday.
Thanks !

**Comment by cedric-anne** [comment] 2020-01-23 09:18
Hi,

I close this issue as fix seems to work. Please free to repoen if problem persist.

Regards

**Closed by cedric-anne** 2020-01-23 09:18 UTC

**Comment by neoclust** [comment] 2023-06-07 13:43
it seems i have the same issue under glpi 10.0.7

**Comment by cedric-anne** [comment] 2023-06-07 14:20
> it seems i have the same issue under glpi 10.0.7

Please open a new issue. This one was closed 3 years ago, so it is unlikely to be the same issue.
