### ISSUE TITLE
Fix update to 9.1 and 9.11

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#1241] opened 2016-11-03 07:48 UTC
Various fix have been applied to update_0905_91.php

Some are fine (bugfix which can crash the process)

But other are schema change (license rights, new index...)
These need to be in update_91_911.php

So a glpi-9.1.1-empty.sql is also needed.

**Comment by yllen** [comment] 2016-11-17 16:59
Part of update not needed

**Comment by trasher** [comment] 2016-11-18 08:47
Which part are you talking about? The indexes stuff that cause issues on some installs?

This is needed for 9.1=>9.1.1 upgrades. It was not present in the 0.90=>9.1 update file when 9.1 has been released (see https://github.com/glpi-project/glpi/blob/9.1/install/update_0905_91.php).

Anyways, testing from a 0.90.5 database dump, and upgrades works... I wonder if ths is not a bug that would only appears upgrading on 9.1.1 when the 9.1/bugfixes branch have been used.

**Comment by orthagh** [comment] 2016-11-18 09:05
Please all, continue the thread on already opened #1296 issue.
I close this one.

**Closed by orthagh** 2016-11-18 09:05 UTC
Labels: bug
