### ISSUE TITLE
[GLPI-Sql-Error] Error: Column 'itemtype' in where clause is ambiguous

### ISSUE THREAD

**Issue by maravtdm** [glpi-project/glpi#6843] opened 2020-01-24 08:29 UTC
**Describe the bug**

I've got a lot of this error in my log
I don't really know why or what is the causeof the problem

**Logs**

Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error [2020-01-24 09:20:33] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 188
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  *** MySQL query error:
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  SQL: SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) WHERE `itemtype` = 'Ticket' AND `items_id` = '115458' AND `is_deleted` = '0'
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  Error: Column 'itemtype' in where clause is ambiguous
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  Backtrace :
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/dbmysqliterator.class.php:95
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/dbutils.class.php:329                          DBmysql->request()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/db.function.php:178                            DbUtils->countElementsInTable()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/ticket.class.php:750                           countElementsInTable()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/commonglpi.class.php:210                       Ticket->getTabNameForItem()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/ticket.class.php:873                           CommonGLPI->addStandardTab()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/commonglpi.class.php:165                       Ticket->defineTabs()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/commonglpi.class.php:707                       CommonGLPI->defineAllTabs()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  inc/commonglpi.class.php:1005                      CommonGLPI->showTabsContent()
Jan 24 09:20:37 SYDCVPITM01 GLPI-Sql-Error  front/ticket.form.php:218                          CommonGLPI->display()

**Comment by maravtdm** [comment] 2020-01-24 08:30
My setup :


[code]   GLPI 9.4.4 (/glpi => /usr/share/glpi) Installation mode: TARBALL
--

Operating system: Linux SYDCVPITM01.brake-france.fr 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 PHP 7.4.0RC5 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, imap, intl, json, 	ldap, libxml, lzf, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, 	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="15M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.4.0RC5 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.1.43-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpidb 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.1.43) - Perfect! /usr/share/glpi/files/_log : OK /usr/share/glpi/config : OK /usr/share/glpi/files : OK /usr/share/glpi/files/_dumps : OK /usr/share/glpi/files/_sessions : OK /usr/share/glpi/files/_cron : OK /usr/share/glpi/files/_graphs : OK /usr/share/glpi/files/_lock : OK /usr/share/glpi/files/_plugins : OK /usr/share/glpi/files/_tmp : OK /usr/share/glpi/files/_cache : OK /usr/share/glpi/files/_rss : OK /usr/share/glpi/files/_uploads : OK /usr/share/glpi/files/_pictures : OK Web access to files directory is protected : OK SELinux mode is Disabled

**Comment by trasher** [comment] 2020-01-24 08:31
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

**Comment by cedric-anne** [comment] 2020-01-24 13:57
Hi,

Looking at this error, the only explaination I have is that your table `glpi_tickets` has a `itemtype` field. Can you check ?

Regards

**Comment by maravtdm** [comment] 2020-01-24 14:11
Yes

MariaDB [glpidb]> select * from glpi_tickets limit 1;
+----+-------------+--------------+---------------------+---------------------+---------------------+---------------------+----------------------+--------+--------------------+-----------------+----------+----------+-----------------------------------------+---------+--------+----------+-------------------+------+-------------------+-------------+-------------+------------------+-----------------+-------------+--------------------+----------------------+----------------------+-------------+-------------+------------------+--------------------------+----------------------+------------------+------------------+------------------+----------------------------+------------+------------+--------------+--------------------+---------------+
| id | entities_id | name         | date                | closedate           | solvedate           | date_mod            | users_id_lastupdater | status | users_id_recipient | requesttypes_id | itemtype | items_id | content                                 | urgency | impact | priority | itilcategories_id | type | global_validation | slas_id_ttr | slas_id_tto | slalevels_id_ttr | time_to_resolve | time_to_own | begin_waiting_date | sla_waiting_duration | ola_waiting_duration | olas_id_tto | olas_id_ttr | olalevels_id_ttr | internal_time_to_resolve | internal_time_to_own | waiting_duration | close_delay_stat | solve_delay_stat | takeintoaccount_delay_stat | actiontime | is_deleted | locations_id | validation_percent | date_creation |
+----+-------------+--------------+---------------------+---------------------+---------------------+---------------------+----------------------+--------+--------------------+-----------------+----------+----------+-----------------------------------------+---------+--------+----------+-------------------+------+-------------------+-------------+-------------+------------------+-----------------+-------------+--------------------+----------------------+----------------------+-------------+-------------+------------------+--------------------------+----------------------+------------------+------------------+------------------+----------------------------+------------+------------+--------------+--------------------+---------------+
| 11 |           4 | Incident OPC | 2010-11-30 13:06:53 | 2011-05-18 16:30:42 | 2011-05-18 16:30:42 | 2012-09-10 17:10:33 |                 2389 |      6 |               2066 |               1 | Software |      323 | Ce ticket est un test ne pas intervenir |       3 |      3 |        3 |                 0 |    1 |                 1 |           0 |           0 |                0 | NULL            | NULL        | NULL               |                    0 |                    0 |           0 |           0 |                0 | NULL                     | NULL                 |                0 |         14610229 |         14610229 |                   16672950 |          0 |          0 |            0 |                  0 | NULL          |
+----+-------------+--------------+---------------------+---------------------+---------------------+---------------------+----------------------+--------+--------------------+-----------------+----------+----------+-----------------------------------------+---------+--------+----------+-------------------+------+-------------------+-------------+-------------+------------------+-----------------+-------------+--------------------+----------------------+----------------------+-------------+-------------+------------------+--------------------------+----------------------+------------------+------------------+------------------+----------------------------+------------+------------+--------------+--------------------+---------------+
1 row in set (0.00 sec)

**Comment by cedric-anne** [comment] 2020-01-24 14:51
Did you upgrade recently ? Did you tried to restore an old database on a new installation ?
`glpi_tickets.items_id` and `glpi_tickets.itemtype` are dropped in migration from 0.85 to 0.853.

If upgrade process has not be done correctly, it can lead to think kind of issues. Only way to fix this is to restart upgrade process as documented [here](https://glpi-install.readthedocs.io/en/latest/update.html) or to fix DB manually.

As this is not a bug from GLPI, I close the issue.

Regards

**Closed by cedric-anne** 2020-01-24 14:51 UTC
Labels: Need feedback
