### ISSUE TITLE
Change Approver does not view changes without being added manually ( V9.4.6 )

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#8004] opened 2020-09-27 20:01 UTC
Not if this is a bug or a lack of functionality with the Changes module

When I open a new Change and add an approver to it, I expected the approver to view the change automatically, just like tickets

However, it only displays if I manually enter the Change

Prints:

1 - With Change open, I added an approver to it

![image](https://user-images.githubusercontent.com/35368369/94374420-8215ae80-00e2-11eb-91ee-1f9a53962da1.png)

![image](https://user-images.githubusercontent.com/35368369/94374429-978ad880-00e2-11eb-8298-d2ae0eedc913.png)

![image](https://user-images.githubusercontent.com/35368369/94374435-a6718b00-00e2-11eb-847d-619c35377d80.png)

2 - When logging in with user "paulo.henrique" and going to the Chances module I cannot see the change for approval

![image](https://user-images.githubusercontent.com/35368369/94374477-e7699f80-00e2-11eb-9ea4-c5cece5b33e9.png)

The profile has the necessary permissions to approve the ticket changes

![image](https://user-images.githubusercontent.com/35368369/94374501-02d4aa80-00e3-11eb-98b2-7f71ee23a5f5.png)

GLPI Version 9.4.6

**Comment by phamorais** [comment] 2020-10-01 16:03
Hi guys, any help?

**Comment by cedric-anne** [comment] 2020-10-02 13:57
Hi,

I confirm that the `Validations` rights only applies for tickets (`request` and `incident`). There is actually no right on GLPI to give ability to user to see only changes they should approve.

I would say that it is not a bug, but a missing feature.

Regards

**Comment by phamorais** [comment] 2020-10-20 21:45
@cedric-anne HI

thx for u attention.
Any possibility to put in the improvement roadmap?

**Comment by cedric-anne** [comment] 2020-10-21 06:47
Hi,

This improvement is not in our roadmap for now. If you want to sponsor this feature, feel free to contact your partner manager, or submit this form: https://portal.glpi-network.com/contact-us

I close this issue as it is not a bug.

Regards

**Closed by cedric-anne** 2020-10-21 06:47 UTC
