### ISSUE TITLE
After upgrading from 0.90.5 to 9.1.1 problem with SLT.

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1740] opened 2017-01-31 10:08 UTC
Good day developers
When you attempt to log into the SLA in the SLT disappears form, more precisely on some split second flashes and then nothing. And when debug mode, the following error appears.

![slt](https://cloud.githubusercontent.com/assets/21122546/22460517/fe2e364c-e7c6-11e6-805a-1a8b8aae2c29.jpg)

and

![slt-2](https://cloud.githubusercontent.com/assets/21122546/22460519/01d2f1e8-e7c7-11e6-8a1a-54efa0cba7c0.jpg)

**Comment by trasher** [comment] 2017-01-31 10:47
Many issues have been fixed in 9.1.2; please try this version and check if you still reproduce the problem.

**Comment by trasher** [comment] 2017-04-24 10:56
Since I did not receive any update on this, I consider this is fixed.

**Closed by trasher** 2017-04-24 10:56 UTC
