### ISSUE TITLE
Slow LDAP/AD user synchronisation since 9.5.0

### ISSUE THREAD

**Issue by fralla2** [glpi-project/glpi#8819] opened 2021-03-11 13:31 UTC
**Describe the bug**

Hi, We sync all our users at night with the /bin/console glpi:ldap:synchronize_users command. 
We have about 12500 users (most of them are students only imported for listing to be able to assign computers or assets to them, they don't connect or use glpi themself).

Prior to version 9.5 (version 9.4.6 and prior), it used to take about 2 to 3 hours to sync all those users. now it takes 9 to 10 hours to sync the same amount of users. 
I've took a look at the sync today and it takes about 2 whole seconds by user.... The load on our active directory and on outr mysql server is really low, wich seems to indicate me that the process is limited somehow on the glpi script...

Can it be speeded up or be able to sync more than one user at a time in parralel?

**Page(s) URL**

/bin/console glpi:ldap:synchronize_users

Currently running GLPI 9.5.3 with bugfixes from 2 weeks ago.

Thanks
Francois

**Comment by cedric-anne** [comment] 2021-03-12 08:41
Hi,

There are some option on this command that may be used to not have to process all users each time, see https://glpi-install.readthedocs.io/en/latest/command-line.html#ldap-synchonization .

As long as it does not seems to be a bug, but a performance issue that is a problem on a large volume of users, I am not sure that someone in the community will take charge of the problem.
If you want to fund an improvement of this feature, either a performance improvement or a functionnal improvement, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us

You may also ask for community support on [forums](https://forum.glpi-project.org/)

I close this issue as it is not a bug.

Regards

**Closed** 2021-03-12 08:42 UTC

**Comment by fralla2** [comment] 2021-03-12 13:02
Thanks  @cedric-anne . I just wanted to make sure it was not an intentional delay introduced somewhere in the code between each sync request like "sleep(2)" or something similar to not overwelm the ldap/ad servers.... If so, I might have tweeked it a little on our end ;)

Have a great day
Francois
