### ISSUE TITLE
Ticket template predefined fields urgency not working

### ISSUE THREAD

**Issue by CCLGDaJul** [glpi-project/glpi#11572] opened 2022-05-12 14:14 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Create a new ticket template
Add predefied field "Urgency" to "Low"
Add predefied field "Priority" to "Low"
Save

Create a new ticket
The field "Urgency" is "Medium"
The field "Priority" is "Medium"

![image](https://user-images.githubusercontent.com/105438598/168094963-ce4d89e6-bf47-43b3-ab63-4db76be34b4e.png)
![image](https://user-images.githubusercontent.com/105438598/168095131-82097870-dd23-4c45-8f38-2da6bb760ac8.png)

In simplified interface (i'm not using it) Urgency is Low and Priority is hidden.

### Steps To reproduce

Create a new ticket template
Add predefied field "Urgency" to "Low"
Add predefied field "Priority" to "Low"
Save

Create a new ticket
The field "Urgency" is "Medium"
The field "Priority" is "Medium"

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 (/glpi => /usr/share/glpi/glpi-10.0.0)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux srv-glpi-dev 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_db@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.28) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/glpi-10.0.0/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/glpi/glpi-10.0.0
GLPI_CONFIG_DIR: /etc/glpi/
GLPI_VAR_DIR: /var/lib/glpi
GLPI_LOG_DIR: /var/log/glpi
GLPI_MARKETPLACE_DIR: /usr/share/glpi/glpi-10.0.0/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/lib/glpi
GLPI_CACHE_DIR: /var/lib/glpi/_cache
GLPI_CRON_DIR: /var/lib/glpi/_cron
GLPI_DUMP_DIR: /var/lib/glpi/_dumps
GLPI_GRAPH_DIR: /var/lib/glpi/_graphs
GLPI_LOCAL_I18N_DIR: /var/lib/glpi/_locales
GLPI_LOCK_DIR: /var/lib/glpi/_lock
GLPI_PICTURE_DIR: /var/lib/glpi/_pictures
GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/_plugins
GLPI_RSS_DIR: /var/lib/glpi/_rss
GLPI_SESSION_DIR: /var/lib/glpi/_sessions
GLPI_TMP_DIR: /var/lib/glpi/_tmp
GLPI_UPLOAD_DIR: /var/lib/glpi/_uploads
GLPI_INVENTORY_DIR: /var/lib/glpi/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/glpi/glpi-10.0.0/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/share/glpi/glpi-10.0.0/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/share/glpi/glpi-10.0.0/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/glpi-10.0.0/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/usr/share/glpi/glpi-10.0.0/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/usr/share/glpi/glpi-10.0.0/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/glpi-10.0.0/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/glpi-10.0.0/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/glpi-10.0.0/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/glpi-10.0.0/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/glpi-10.0.0/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/glpi-10.0.0/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/glpi-10.0.0/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/glpi-10.0.0/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/glpi-10.0.0/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/glpi-10.0.0/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/glpi-10.0.0/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/glpi-10.0.0/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/glpi-10.0.0/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/glpi-10.0.0/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/glpi-10.0.0/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/glpi-10.0.0/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/glpi-10.0.0/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/glpi/glpi-10.0.0/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/glpi/glpi-10.0.0/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/glpi-10.0.0/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/glpi-10.0.0/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/glpi-10.0.0/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/glpi-10.0.0/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/glpi-10.0.0/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/glpi-10.0.0/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/glpi-10.0.0/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/glpi-10.0.0/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/glpi-10.0.0/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/glpi-10.0.0/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/glpi-10.0.0/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/glpi-10.0.0/vendor/html2text/html2text/src)
symfony/dom-crawler in (/usr/share/glpi/glpi-10.0.0/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/glpi-10.0.0/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/glpi-10.0.0/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/usr/share/glpi/glpi-10.0.0/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/usr/share/glpi/glpi-10.0.0/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'reseaux.lan', Port: '389', BaseDN: 'OU=RESEAUX,DC=reseaux,DC=lan', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberOf=CN=GLPIUsers,OU=Groups,DC=reseaux,DC=lan))',
		RootDN: 'CN=glpi,OU=service,OU=z_Users,OU=RESEAUX,DC=reseaux,DC=lan', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@zimbra.le-gresivaudan.fr)

</details><details><summary>Plugins list</summary><pre> 
	servicecatalog       Name: Catalogue de service           Version: 1.6.4      State: Not installed
	fields               Name: Champs supplémentaires         Version: 1.15.0     State: Enabled
	accounts             Name: Comptes                        Version: 3.0.1      State: Enabled
	mydashboard          Name: Dashboard                      Version: 2.0.2      State: Not installed
	order                Name: Gestion des commandes          Version: 2.8.0      State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.8.0      State: Enabled

</pre></details>

### Anything else?

Kiss ;)

**Comment by cconard96** [comment] 2022-05-13 11:03
Duplicate of https://github.com/glpi-project/glpi/issues/11410.
Already fixed for 10.0.1.

The fix was done in #11421 and #11539 (in that order).

**Closed** 2022-05-13 11:03 UTC
Labels: duplicate
