### ISSUE TITLE
GLPI 10.0.0 - Category is not shown

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi#11530] opened 2022-05-09 17:20 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10.0.0

### Bug description

When adding a task and selecting the task template, the task category that is configured in the template is not shown.

![image](https://user-images.githubusercontent.com/57845086/167463315-159bff26-0747-4f97-8097-4e6f960f43c3.png)

![image](https://user-images.githubusercontent.com/57845086/167463334-443f791e-2804-4b31-846d-8d990f2b7e66.png)

This is OK on GLPI 9.5.7

![image](https://user-images.githubusercontent.com/57845086/167463729-9513ac11-9bc1-47bf-ace5-f9ef9c2c802a.png)

**Comment by cconard96** [comment] 2022-05-09 21:38
Duplicate of #11434. Fixed via #11436.
This fix will be included as part of 10.0.1.

**Closed by cconard96** 2022-05-09 21:38 UTC
Labels: duplicate
