### ISSUE TITLE
Reminder set to the wrong user

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#5298] opened 2019-01-29 08:51 UTC
Hi,

**To reproduce**

1. Create a task in a ticket
2. Add a planning to this task 
3. Add a reminder (15 minutes)
4. Change the user of the task
5. Save the task
6. Logon as the user define in the task
7. Open the task
8. The reminder is not set to 15 minutes

**Expected behavior**

The reminder should be assigned to the user set in the dropdown

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Tested in GLPI 9.3.3

**Comment by cedric-anne** [comment] 2019-03-12 12:15
Hi,

This is not a bug.

Planning recalls (called here reminders) are defined by user for itself and cannot be defined for another user.
If a technician want to set a reminder on a task that was assigned to him, he can do it by editing the task.

Regards

**Closed by cedric-anne** 2019-03-12 12:15 UTC
