### ISSUE TITLE
Member of group in watcher of ticket can't see the ticket

### ISSUE THREAD

**Issue by fgendorf** [glpi-project/glpi#6136] opened 2019-07-15 14:06 UTC
**Describe the bug**

I have a business rule that add watcher group to tickets users, a "Manager" profile can see tickets from group, but the last version 9.4.3 tickets with watcher group, the profile manager can't see the tickets with their group. 

**To reproduce**

1. create a ticket
2. add a group watcher to it
3. enter with another user with permission to see group tickets
4. the ticket will not appear

**Expected behavior**

as the olders versions, if the watcher group in ticket are present, it will be show to user that have permission profile to read ticket group

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

Information about system installation & configuration
--
[code]   GLPI 9.4.3 (/requisicao => /home/company/www/glpi) Installation mode: TARBALL

Operating system: Linux glpiocs 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 PHP 7.2.19-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, 	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="25M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at intranet.esss.co Port 80) 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.25 	Server SQL Mode:  	Parameters: glpi@mysql.fln.esss.com.br/glpi 	Host info: mysql.fln.esss.com.br via TCP/IP 	  Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in /usr/share/php/CAS/Autoload.php on line 99 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (5.7.25) - Perfect! /home/company/www/glpi/files/_log : OK /home/company/www/glpi/config : OK /home/company/www/glpi/files : OK /home/company/www/glpi/files/_dumps : OK /home/company/www/glpi/files/_sessions : OK /home/company/www/glpi/files/_cron : OK /home/company/www/glpi/files/_graphs : OK /home/company/www/glpi/files/_lock : OK /home/company/www/glpi/files/_plugins : OK /home/company/www/glpi/files/_tmp : OK /home/company/www/glpi/files/_cache : OK /home/company/www/glpi/files/_rss : OK /home/company/www/glpi/files/_uploads : OK /home/company/www/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/home/company/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/home/company/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/home/company/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/home/company/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/home/company/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/company/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/home/company/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/home/company/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/home/company/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/home/company/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/home/company/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/home/company/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/company/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/home/company/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/home/company/www/glpi/vendor/symfony/console) leafo/scssphp in (/home/company/www/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

Server: 'ldap.fln.esss.com.br', Port: '389', BaseDN: 'ou=ESSS,dc=esss,dc=com,dc=br', Connection filter: 		'(&(departmentnumber=*)(objectclass=CourierMailAccount)(!(status=*nativo)))', RootDN: none, Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@smtp.fln.esss.com.br)

Name: 'requisicaoti@esss.co' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl/novalidate-cert}requisicaoti' Login: 'servicosti@esss.co' Password: Yes Name: 'requisicaomkt@esss.co' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl/novalidate-cert}services.mkt' Login: 'servicosti@esss.co' Password: Yes Name: 'requisicaogp@esss.co' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl/novalidate-cert}requisicaogp' Login: 'servicosti@esss.co' Password: Yes Name: 'office@esss.co' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl/novalidate-cert}Office' Login: 'servicosti@esss.co' Password: Yes Name: 'requisicaobusop@esss.co' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl/novalidate-cert}BUSOP' Login: 'servicosti@esss.co' Password: Yes

fields               Name: Additionnal fields             Version: 1.10.0     State: Enabled 	addressing           Name: Endereçamento IP               Version: 2.8.0      State: Enabled 	datainjection        Name: File injection                 Version: 2.7.0      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.8.3      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled 	order                Name: Gerenciamento das ordens de co Version: 2.5.1      State: Enabled 	pdf                  Name: Imprimir em PDF                Version: 1.5.0      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.0      State: Enabled 	mreporting           Name: More Reporting                 Version: 1.6.1      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Enabled 	reports              Name: Relatórios                     Version: 1.13.1     State: Enabled 	simcard              Name: Sim cards management           Version: 1.4.2      State: Not activated

Host: mysql.fln.esss.com.brConnection: OkUse the OCSNG software dictionary: Yes
[/code]

```

**Comment by fgendorf** [comment] 2019-07-15 15:17
Looking in DEBUG tab, the SQL from list of tickets don't get nothing related to users from groups in watcher:

```
SELECT DISTINCT `glpi_tickets`.`id` AS id, 'fred' AS currentuser, `glpi_tickets`.`id` AS `ITEM_Ticket_2`, `glpi_tickets`.`name` AS `ITEM_Ticket_1`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`content` AS `ITEM_Ticket_1_content`, `glpi_tickets`.`status` AS `ITEM_Ticket_1_status`, `glpi_tickets`.`date` AS `ITEM_Ticket_15`, `glpi_tickets`.`status` AS `ITEM_Ticket_12`, GROUP_CONCAT(DISTINCT `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_4`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id`, ' ', `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_4_2`, COUNT(DISTINCT `glpi_itilfollowups`.`id`) AS `ITEM_Ticket_27`, COUNT(DISTINCT `glpi_tickettasks`.`id`) AS `ITEM_Ticket_28`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickettasks`.`actiontime`, '__NULL__'), '$#$',`glpi_tickettasks`.`id`)
ORDER BY `glpi_tickettasks`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_96`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_fields_centrodecustofielddropdowns_78fc1437c7b4fd068ac8e998028e5efe`.`completename`, '__NULL__'), '$#$',`glpi_plugin_fields_centrodecustofielddropdowns_78fc1437c7b4fd068ac8e998028e5efe`.`id`)
ORDER BY `glpi_plugin_fields_centrodecustofielddropdowns_78fc1437c7b4fd068ac8e998028e5efe`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_76665`, `glpi_tickets`.`time_to_resolve` AS `ITEM_Ticket_18`, `glpi_tickets`.`status` AS `ITEM_Ticket_18_status`, `glpi_tickets`.`actiontime` AS `ITEM_Ticket_45`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_groups_c4fd3c0e88c6dca4af1d451af9d747fb`.`completename`, '__NULL__'), '$#$',`glpi_groups_c4fd3c0e88c6dca4af1d451af9d747fb`.`id`)
ORDER BY `glpi_groups_c4fd3c0e88c6dca4af1d451af9d747fb`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_65`, 
GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_taskcategories_e5ca2f53018fdc28a31faf534186b3a2`.`name`, '__NULL__'), '$#$',`glpi_taskcategories_e5ca2f53018fdc28a31faf534186b3a2`.`id`)
ORDER BY `glpi_taskcategories_e5ca2f53018fdc28a31faf534186b3a2`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_20`, GROUP_CONCAT(DISTINCT `glpi_users_users_id_tech_e5ca2f53018fdc28a31faf534186b3a2`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_95`, GROUP_CONCAT(DISTINCT `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_5`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id`, ' ', `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_5_2`, `glpi_tickets`.`date_mod` AS `ITEM_Ticket_19`
FROM `glpi_tickets`
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60` ON (`glpi_tickets`.`id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id` AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 )
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8` ON (`glpi_tickets`.`id` = `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id` AND `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 )
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b` ON (`glpi_tickets`.`id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )
LEFT JOIN `glpi_ticketvalidations` ON (`glpi_tickets`.`id` = `glpi_ticketvalidations`.`tickets_id` )
LEFT JOIN `glpi_users` AS `glpi_users_a5e2026cbcb683e774f93a59e24a62a4` ON (`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id` = `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` )
LEFT JOIN `glpi_itilfollowups` ON (`glpi_tickets`.`id` = `glpi_itilfollowups`.`items_id` AND `glpi_itilfollowups`.`itemtype` = 'Ticket' )
LEFT JOIN `glpi_tickettasks` ON (`glpi_tickets`.`id` = `glpi_tickettasks`.`tickets_id` )
LEFT JOIN `glpi_plugin_fields_ticketinfoadicionals` ON (`glpi_tickets`.`id` = `glpi_plugin_fields_ticketinfoadicionals`.`items_id` AND `glpi_plugin_fields_ticketinfoadicionals`.`itemtype` = 'Ticket' )
LEFT JOIN `glpi_plugin_fields_centrodecustofielddropdowns` AS `glpi_plugin_fields_centrodecustofielddropdowns_78fc1437c7b4fd068ac8e998028e5efe` ON (`glpi_plugin_fields_ticketinfoadicionals`.`plugin_fields_centrodecustofielddropdowns_id` = `glpi_plugin_fields_centrodecustofielddropdowns_78fc1437c7b4fd068ac8e998028e5efe`.`id` )
LEFT JOIN `glpi_groups_tickets` AS `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8` ON (`glpi_tickets`.`id` = `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id` AND `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 )
LEFT JOIN `glpi_groups` AS `glpi_groups_c4fd3c0e88c6dca4af1d451af9d747fb` ON (`glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`groups_id` = `glpi_groups_c4fd3c0e88c6dca4af1d451af9d747fb`.`id` )
LEFT JOIN glpi.glpi_groups_users ON (glpi_groups_c4fd3c0e88c6dca4af1d451af9d747fb.id=glpi_groups_users.groups_id)
LEFT JOIN `glpi_taskcategories` AS `glpi_taskcategories_e5ca2f53018fdc28a31faf534186b3a2` ON (`glpi_tickettasks`.`taskcategories_id` = `glpi_taskcategories_e5ca2f53018fdc28a31faf534186b3a2`.`id` )
LEFT JOIN `glpi_users` AS `glpi_users_users_id_tech_e5ca2f53018fdc28a31faf534186b3a2` ON (`glpi_tickettasks`.`users_id_tech` = `glpi_users_users_id_tech_e5ca2f53018fdc28a31faf534186b3a2`.`id` )
LEFT JOIN `glpi_users` AS `glpi_users_f201be21cd638ee780d08cba4ceff0d4` ON (`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id` = `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` )
WHERE ( `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.users_id = '6' OR `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.users_id = '6' 
OR `glpi_tickets`.`users_id_recipient` = '6' OR `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id` = '6' 
OR `glpi_ticketvalidations`.`users_id_validate` = '6') AND `glpi_tickets`.`is_deleted` = 0 
AND ( `glpi_tickets`.`entities_id` IN ('1') ) AND ( `glpi_tickets`.`status` IN ('1','2','3','4') 
AND (`glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` = '6') ) 
GROUP BY `glpi_tickets`.`id`
ORDER BY ITEM_Ticket_19 DESC 
```

**Comment by cedric-anne** [comment] 2019-07-16 09:37
Hi @fgendorf ,

Can you try to apply https://github.com/glpi-project/glpi/pull/6130 ?

Regards

**Comment by fgendorf** [comment] 2019-07-16 10:35
Hi @cedric-anne, I applied and doesn't work, but it don't sound the same issue, all my Groups are in root entity and the profile with "See Group Ticket" can't see tickets with the group in watcher of it.

The SQL from list tickets still the same.
I think is missing something like:
LEFT JOIN **glpi.glpi_groups_users** ON (glpi_groups_c4fd3c0e88c6dca4af1d451af9d747fb.id=glpi_groups_users.groups_id)

**Comment by cedric-anne** [comment] 2019-07-16 13:36
On current 9.4/buxfixes branch, I cannot reproduce.

1. I create a profile with `See my ticket` and `See group ticket`.
2. I created a user having this profile.
3. I added it as a manager of a new group.
4. I created a ticket and assign this new group as observer. -> User can see the ticket.
5. I remove observer group. -> User cannot see anymore the ticket.

Have you try to logout/login ? Is is possible that your user has multiple profiles and does not use the good one ?

Regards

**Comment by fgendorf** [comment] 2019-07-16 14:05
Ok, thanks for your check point, I will do a test with branch 9.4/bugfixes,
that have 29 commits more than 9.4.3.

"Have you try to logout/login ? Is is possible that your user has multiple
profiles and does not use the good one ?"
A: Yes we have some profiles, for different reason, but the profile
selected is just to see the tickets from group, so I sure using the right
profile.




_________________________
Frederico Gendorf

**Comment by fgendorf** [comment] 2019-07-16 16:09
Hi @cedric-anne, I installed the GLPI from scratch, version latest branch 9.4-bugfix, changed the profile Self-service to "see group ticket", created another user, with profile self-service, and the group test to post-only user and the new user.

Created a new ticket with post-only user and switch to another user, in same group and same profile "Self-service", and the other user can view the ticket...

Returned to my production database and created a new Profile and changed to "see group ticket", confirmed the groups, and I can't see the ticket with group observer again :-(

How can I debug where is the issue?

**Comment by fgendorf** [comment] 2019-07-16 16:43
I found where is the issue... the ticket is in sub-entity... I transferred it to root entity, and it works, other user from the same group com view it!

**Comment by fgendorf** [comment] 2019-07-16 18:02
Maybe it related to #6130, I found a lot of $_SESSION['glpiactiveentities'] and $_SESSION['glpiactive_entity'] in code

**Comment by cedric-anne** [comment] 2019-07-18 08:35
Hi,

I cannot reproduce on current state of 9.4/bugfixes branch.

If you are able to reproduce on your test server, can you give us a dump of the database to help us investigate on this issue ?

Regards

**Comment by fgendorf** [comment] 2019-07-18 16:38
Sure, I prepared a database with the issue, you can get it at https://sftp.esss.co/~fred/dump.sql
there are 3 users, **user1** pass: user1, **user2** pass: user2, both are in group "Information Tecnology" and **glpi** pass: glpi

the user2 have two profiles: post-only and Manager, the profile Manager have the option "See group ticket" enabled

each user opened a ticket, user1 can see the ticket GLPI35371  and user2 com see the GLPI35372 at profile Post-only.

With user2 with profile Manager should be able to see both tickets, but doesn't.

In other test database https://sftp.esss.co/~fred/dump2.sql, I moved the tickets to ROOT entity and put access to user1 and user2, after that, user2 with profile Manager com see both tickets from group "Information Technology"

So I sure the problem is on Sub-entity

**Comment by cedric-anne** [comment] 2019-07-19 08:21
Hi,

#6151 should fix your problem.

Regards

**Closed** 2019-07-19 09:32 UTC
Labels: bug
