### ISSUE TITLE
When creating a computer using a template - the management tab is not included even if it is filled in the template

### ISSUE THREAD

**Issue by PuchadesC-Antibes** [glpi-project/glpi#8544] opened 2021-01-19 13:57 UTC
When creating a computer using a template - the management tab is not included even if it is filled in the template

1 - add a computer
2 - choose a template with financial informations
3 - Save the new computer created
4 - the management tab of computer is empty.

**Comment by novakl1** [comment] 2021-02-18 12:35
Hello... I have absolutelly same problem. Does anyone else encountered such strange behaviour? Any Idea how to solve it. (It was working cca on the end of 2020 year. No GLPI update done.

**Comment by mirda123** [comment] 2021-04-08 12:34
same here in glpi 9.5.3   is it ok in 9.5.4 ?

**Comment by mirda123** [comment] 2021-04-08 12:57
not OK in 9.5.4

**Comment by novakl1** [comment] 2021-04-08 13:35
So what now? Who can,  please help! Using templates in such situation has limited use. I belive that much more users has similar problem and must edit management tab for each asset during insertion:(

**Comment by mirda123** [comment] 2021-04-08 14:07
i tried to edit manually financial data during insertion, you can't for most of them ...

**Comment by mirda123** [comment] 2021-04-12 10:25
hi,please trasher, can you confirm it's a bug ? because it's not labbeled as it ? thanks !

**Comment by cedric-anne** [comment] 2021-04-12 11:05
Hi,

I cannot reproduce on current state of 9.5/bugfixes branch. Either bug has been solved, either a plugin prevents this to work.

I close this issue, feel free to reopen if the problem persist without any active plugin. In this case, please provide detailed informations (steps to reproduce, GLPI installation details, logs, ...).

Regards

**Comment by mirda123** [comment] 2021-04-13 13:22
Hi novakl1 ! I found the bug !

problem occurs only when general setup is: default active financial data = YES
if you change to NO , financial data are OK when creating a computer...
if i go back to NO , financial data disapper when creating...

can you try ?

**Comment by novakl1** [comment] 2021-04-28 08:59
Hello mirda123. 
Many many thanks. Thats it. Tested and it is working now like a charm:). thanks and děkuju moc:) It save me a lot of additional manual work. Thanks

**Comment by mirda123** [comment] 2021-04-28 10:02
Není zač !!
 you're welcome ! : )

**Comment by mirda123** [comment] 2021-04-28 10:03
Please can someone label it as a bug ?

**Comment by mirda123** [comment] 2021-09-20 16:23
Hi, 
problem is still there

need fix, thank you !

**Comment by mirda123** [comment] 2021-11-20 08:45
Hi,
problem is still there

need fix, thank you !

**Comment by cconard96** [comment] 2022-01-13 15:36
@mirda123 Please indicate which version you are using.
I am not able to recreate the issue.

If the template has management info, the created Computer has the same info regardless of the "Enable the financial and administrative information by default" option.

**Comment by mirda123** [comment] 2022-01-23 10:51
Hi, i just upgraded 9.5.6, problem is still there (so pb is in  9.5.3, 9.5.4, 9.5.6)

step to reproduce :

1. set general setup : default active financial data = YES
![p1](https://user-images.githubusercontent.com/78594318/150674832-0b4dbe3f-86ab-493b-b76e-5e9573bace09.jpg)

2. Go to computer, open a  computer gabarit (model) , just check there are financial data
![p2](https://user-images.githubusercontent.com/78594318/150674866-dd70cb2c-4962-4dd6-a9e8-4c5d20748252.jpg)

3. Create a new computer , and choose the former gabarit (modele)
4. before saving, try for example to add a financial data  and change a value in financia data : you can't ..
![p3](https://user-images.githubusercontent.com/78594318/150674919-30a94fc3-e52f-4d0a-bb8c-55fccdf40e81.jpg)

5.  Save you  computer, example "atest111"
6. Open you computer atest111, go to financial data.. nothing there...
![p4](https://user-images.githubusercontent.com/78594318/150674946-a11d8773-8373-45c9-b9c6-19f47af5dc84.jpg)

Problem only occurs when general setup / default active financial data = YES . Switch to NO , it works perfectly ! Other people confirmed the same issue.

Hope you can recreate the issue !
thank you for helping us

**Comment by cconard96** [comment] 2022-01-23 17:56
May be fixed by #10406

**Closed** 2022-02-23 10:04 UTC
Labels: bug
