### ISSUE TITLE
Can't select category inherited from root entity on ticket after upgrade to 10.0.17

### ISSUE THREAD

**Issue by raultak** [glpi-project/glpi#18279] opened 2024-11-08 16:13 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

While creating a ticket, if the selected entity is different from the root and selected Category is inherited from root, the Category field gets blank.
This behavoring was observed in a installation upgraded from 10.0.16 to 10.0.17 and in a new brand 10.0.17 installation. 

### Relevant log output

```shell
No log related.
```

### Page URL

https://{glpi}/front/ticket.form.php

### Steps To reproduce

1. Create a category in the root entity and allow it to child entities.
2. Go to ticket creation, select a child entity for the ticket and select the inherited category.

![Image](https://github.com/user-attachments/assets/034efb9a-28d2-48b0-a720-c191b1439a8a)

3. After the screen reload the category field get blank.

![Image](https://github.com/user-attachments/assets/32c16c9e-bbef-4370-827a-903289bcf3f8)

4. If the selected category is from the child entity it works fine.

![Image](https://github.com/user-attachments/assets/33577955-e77d-4489-b599-90481b6be1e6)

5. If the root entity is selected to the ticket it works fine too.
![Image](https://github.com/user-attachments/assets/caa61f67-362b-4ce4-bfc0-72de2d9645cb)

### Your GLPI setup information

Information about system installation and configuration

GLPI 10.0.17 ( => /var/www/glpi.lab.internal)
Installation mode: TARBALL
Current language:en_GB

---

Server

Operating system: Linux tsr-csv-011 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64
PHP 8.1.2-1ubuntu2.19 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl,
	json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.11.9-MariaDB-ubu2204
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: laboratory@tsr-csv-010.lab.internal:3306/lab_glpi
	Host info: tsr-csv-010.lab.internal via TCP/IP
	
PHP version (8.1.2-1ubuntu2.19) is supported.PHP version (8.1.2-1ubuntu2.19) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.9) is supported.Database engine version (10.11.9) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi.lab.internal/files/_cache has been validated. Write access to /var/www/glpi.lab.internal/files/_cron has been validated. Write access to /var/www/glpi.lab.internal/files has been validated. Write access to /var/www/glpi.lab.internal/files/_dumps has been validated. Write access to /var/www/glpi.lab.internal/files/_graphs has been validated. Write access to /var/www/glpi.lab.internal/files/_lock has been validated. Write access to /var/www/glpi.lab.internal/files/_pictures has been validated. Write access to /var/www/glpi.lab.internal/files/_plugins has been validated. Write access to /var/www/glpi.lab.internal/files/_rss has been validated. Write access to /var/www/glpi.lab.internal/files/_sessions has been validated. Write access to /var/www/glpi.lab.internal/files/_tmp has been validated. Write access to /var/www/glpi.lab.internal/files/_uploads has been validated.Write access to /var/www/glpi.lab.internal/files/_cache has been validated.
Write access to /var/www/glpi.lab.internal/files/_cron has been validated.
Write access to /var/www/glpi.lab.internal/files has been validated.
Write access to /var/www/glpi.lab.internal/files/_dumps has been validated.
Write access to /var/www/glpi.lab.internal/files/_graphs has been validated.
Write access to /var/www/glpi.lab.internal/files/_lock has been validated.
Write access to /var/www/glpi.lab.internal/files/_pictures has been validated.
Write access to /var/www/glpi.lab.internal/files/_plugins has been validated.
Write access to /var/www/glpi.lab.internal/files/_rss has been validated.
Write access to /var/www/glpi.lab.internal/files/_sessions has been validated.
Write access to /var/www/glpi.lab.internal/files/_tmp has been validated.
Write access to /var/www/glpi.lab.internal/files/_uploads has been validated.

Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi.lab.internal/marketplace has been validated.Write access to /var/www/glpi.lab.internal/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

---

GLPI constants

GLPI_ROOT: "/var/www/glpi.lab.internal"
GLPI_CONFIG_DIR: "/var/www/glpi.lab.internal/config"
GLPI_VAR_DIR: "/var/www/glpi.lab.internal/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi.lab.internal/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/glpi.lab.internal/files"
GLPI_CACHE_DIR: "/var/www/glpi.lab.internal/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi.lab.internal/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi.lab.internal/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi.lab.internal/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi.lab.internal/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi.lab.internal/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi.lab.internal/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi.lab.internal/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi.lab.internal/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi.lab.internal/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi.lab.internal/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi.lab.internal/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi.lab.internal/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi.lab.internal/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi.lab.internal/locales"
GLPI_VERSION: "10.0.17"
GLPI_SCHEMA_VERSION: "10.0.17@bde16719fbd4112f59a9a7d34c66c959bce73434"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

---

Libraries

htmlawed/htmlawed version 1.2.14 in (/var/www/glpi.lab.internal/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi.lab.internal/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi.lab.internal/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/var/www/glpi.lab.internal/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi.lab.internal/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi.lab.internal/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi.lab.internal/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi.lab.internal/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi.lab.internal/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi.lab.internal/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi.lab.internal/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi.lab.internal/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi.lab.internal/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi.lab.internal/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi.lab.internal/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi.lab.internal/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi.lab.internal/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi.lab.internal/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi.lab.internal/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi.lab.internal/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi.lab.internal/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi.lab.internal/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi.lab.internal/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi.lab.internal/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi.lab.internal/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi.lab.internal/vendor/psr/cache/src)
league/csv in (/var/www/glpi.lab.internal/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi.lab.internal/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi.lab.internal/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi.lab.internal/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi.lab.internal/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi.lab.internal/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi.lab.internal/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi.lab.internal/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi.lab.internal/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi.lab.internal/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi.lab.internal/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi.lab.internal/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi.lab.internal/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi.lab.internal/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi.lab.internal/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi.lab.internal/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi.lab.internal/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

---

SQL replicas

Not active

---

Notifications

Way of sending emails: SMTP (anonymous@tsr-csv-010.lab.internal)

---

Plugins list

fields               Name: Additional fields              Version: 1.21.15    State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.9     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.4.0      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.10    State: Enabled                                 
		Install Method: Marketplace

**Comment by RobertoMarcelino** [comment] 2024-11-08 19:55
The same problem occurs in version 11.0.0-alpha.

**Comment by stonebuzz** [comment] 2024-11-09 18:09
Seems like a duplicate of #18240

**Closed** 2024-11-12 08:58 UTC
