### ISSUE TITLE
[inventory] Duplicate entry 'Computer-' for key 'unicity' - and error 500 from the agent for updated Cisco Anyconnect

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#14169] opened 2023-02-24 10:51 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

We are using GLPI Agent 1.4 and after a update of the Cisco AnyConnect client via the VPN Server we have the following error for nearly all computer:
`[2023-02-24 11:30:00] glpiphplog.ERROR:   *** PHP User Error (256): Duplicate entry 'Computer-101-108695' for key 'unicity' in /var/www/glpi/src/DBmysql.php at line 1969
  Backtrace :
  src/DBmysql.php:1969                               trigger_error()
  src/Inventory/Asset/Software.php:874               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:446               Glpi\Inventory\Asset\Software->storeAssetLink()
  src/Inventory/Asset/MainAsset.php:871              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:791              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1522                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1626                        Rule->process()
  src/Inventory/Asset/MainAsset.php:571              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()`

After the Cisco AnyConnect update there are two software entries in the inventory file of the GLPI Agent, that result in the dublicate.

    <SOFTWARES>
      <ARCH>i586</ARCH>
      <COMMENTS>A SmartNET contract is required for support - Cisco AnyConnect Secure Mobility Client.</COMMENTS>
      <FROM>registry</FROM>
      <GUID>{F4BACC43-70D3-4CCF-A0C6-89512F64CBB4}</GUID>
      <HELPLINK>http://www.cisco.com/TAC/</HELPLINK>
      <INSTALLDATE>14/02/2023</INSTALLDATE>
      <NAME>Cisco AnyConnect Secure Mobility Client</NAME>
      <PUBLISHER>Cisco Systems, Inc.</PUBLISHER>
      <SYSTEM_CATEGORY>system_component</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>MsiExec.exe /X{F4BACC43-70D3-4CCF-A0C6-89512F64CBB4}</UNINSTALL_STRING>
      <URL_INFO_ABOUT>http://www.cisco.com</URL_INFO_ABOUT>
      <VERSION>4.10.06079</VERSION>
    </SOFTWARES>

and

    <SOFTWARES>
      <ARCH>i586</ARCH>
      <COMMENTS>A SmartNET contract is required for support - Cisco AnyConnect Secure Mobility Client.</COMMENTS>
      <FROM>registry</FROM>
      <GUID>Cisco AnyConnect Secure Mobility Client</GUID>
      <HELPLINK>http://www.cisco.com/TAC/</HELPLINK>
      <INSTALLDATE>14/02/2023</INSTALLDATE>
      <NAME>Cisco AnyConnect Secure Mobility Client </NAME>
      <PUBLISHER>Cisco Systems, Inc.</PUBLISHER>
      <SYSTEM_CATEGORY>application</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\Uninstall.exe -remove</UNINSTALL_STRING>
      <URL_INFO_ABOUT>http://www.cisco.com</URL_INFO_ABOUT>
      <VERSION>4.10.06079</VERSION>
    </SOFTWARES>

Perhaps this is an GLPI Agent issue?

In difference to #14088 there are no hidden symbols.

**Comment by trasher** [comment] 2023-02-24 10:52
Please try with latest nightly, several fixes has already been done.

**Comment by AndiMb** [comment] 2023-03-06 15:19
The Problem still exists in the nightly build 10.0-807b01d and also in a fresh installation of 10.0.6.

**Comment by stonebuzz** [comment] 2023-03-06 15:56
Can you post here related inventory file ?

**Comment by AndiMb** [comment] 2023-03-06 15:58
I'm not allowed to post the related inventory file in public. Is it possible to send a mail or pm?

**Comment by stonebuzz** [comment] 2023-03-06 15:59
yep

**Comment by stonebuzz** [comment] 2023-03-07 06:53
Hi @AndiMb 

I reproduce with your recommendations =) 
injecting the XXX.json as starting point, with the old Cisco AnyConnect-Version and then injecting a new on I’m getting the error.

I'll take a look

Best regards

**Comment by trasher** [comment] 2023-03-07 07:16
I also can reproduce, and it seems to be an Agent issue at the first time; I see no reason for that same software to be present twice in the files.
ANyways, since this is a stable agent release, I guess we could try to do something.

**Comment by AndiMb** [comment] 2023-03-07 08:09
From the GLPI users perspective it is not obvious, what's the difference between, the to cases:

1. injecting the first inventory file (with one entry of the old software version) and then the new inventory file (with two entries of the new software version) to an fresh server -> error
2. injecting only the new inventory file (with two entries of the new software version) to a fresh server -> no error.

In the second case the inventory file seems to be correct and in the first scenario the same file is handled differently.

**Comment by trasher** [comment] 2023-03-07 08:55
Update is not exactly the same as creation. Your case is fixed with https://github.com/glpi-project/glpi/pull/14253

**Closed** 2023-03-07 09:25 UTC
Labels: bug
