### ISSUE TITLE
10.0 : unmanaged equipement  the function action recycle bin doesnt exist

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#11560] opened 2022-05-11 08:21 UTC
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0 fix 20220510

### Bug description

I wanted to delete old equipment not managed but the action function recycle bin doesnt exist
To solve the problem I convert in a computer or network equipment for example and I can delete

![image](https://user-images.githubusercontent.com/68054991/167802488-bf55282b-b4af-4c23-bc37-73b63a915303.png)

### Relevant log output

```shell
no log
```

### Page URL

/glpi/front/unmanaged.php

### Steps To reproduce

1. unmanaged equipement  
2. Try delete the unmanaged equipement

**Comment by cconard96** [comment] 2022-05-13 11:12
Confirmed bug. Issue seems to be that the unmanaged devices use the "config" right (General Setup) which doesn't have any delete permissions and doesn't really fit with the use case here.

**Comment by trasher** [comment] 2022-05-24 07:26
Fixed by #11661

**Closed by trasher** 2022-05-24 07:26 UTC
Labels: bug
