### ISSUE TITLE
GLPI 10.0.03 - Creation of a ticket -> Business rule of a ticket replace group of technician at ticket's creation

### ISSUE THREAD

**Issue by tristangallet** [glpi-project/glpi#12810] opened 2022-09-29 13:36 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.3

### Bug description

Have a few business's rules to ADD or UPDATE the group of technician based on the category.

So, if a cateogry is changed in a ticket, a group of technicien is ADDED.

When we create a new ticket, we choose a category wich have a business rule to add the groupe of technicians.
EX  : Category=HELPDESK, business rule : ADD or UPDATE group of technicien : GROUP_HELPDESK.
Before we click on ADD, we want to add one or several group of technicians for "Assigned To" (ex : GROUP_NETWORK)

On GLPI version 9.5, it was ok, ticket was created, based on business's rule -> group of technicien : GROUP_HELPDESK was added and group of technicians GROUP_NETWORK was here.

With version 10.0.03, only the group from the business's rule is attached, GROUP_NETWORK is removed.
It's only at the **creation** of the ticket, when the ticket is created, all is ok, business's rules are adding groups without removing  
the groups already in the ticket.

**Comment by cedric-anne** [comment] 2022-09-29 13:47
Hi,

If you want to append an actor without replacing those that have just been defined, you have to use the `Add` action. Indeed, `Assign` will erase value defined in submitted form or defined by previous rules, while `Add` will append the value.

Before GLPI 9.5.6, groups were not handfled the same way as users. See #6906.

I close this issue as it is an intended behaviour.

**Closed by cedric-anne** 2022-09-29 13:47 UTC
