### ISSUE TITLE
[9.2] An error in notifications

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#2991] opened 2017-10-17 08:49 UTC
Hello.
In the group notification is this error.

![glpi - groups - error](https://user-images.githubusercontent.com/17082164/31654756-92da90c2-b32f-11e7-8040-91240d58fe56.png)

![glpi](https://user-images.githubusercontent.com/17082164/31660282-a0f212f6-b33f-11e7-8340-6eb780313c3d.png)

And there is grammar mistake: "occurRed".

Error log:
`[Tue Oct 17 11:43:51.100294 2017] [:error] [pid 2025] [client 10.1.3.169:54322] PHP Fatal error:  Uncaught Error: Call to undefined method Notification::getMode() in /var/www/glpi92/inc/notificationtarget.class.php:1328\nStack trace:\n#0 /var/www/glpi92/inc/notificationtarget.class.php(1347): NotificationTarget::showForGroup(Object(Group))\n#1 /var/www/glpi92/inc/commonglpi.class.php(482): NotificationTarget::displayTabContentForItem(Object(Group), '1', '')\n#2 /var/www/glpi92/ajax/common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Group), 'NotificationTar...', '', Array)\n#3 {main}\n  thrown in /var/www/glpi92/inc/notificationtarget.class.php on line 1328, referer: http://glpi.domain.ru/glpi-test/front/group.form.php?id=1`

**Comment by trasher** [comment] 2017-10-19 06:45
Duplicate of https://github.com/glpi-project/glpi/issues/2953

**Closed by trasher** 2017-10-19 06:45 UTC
Labels: duplicate
