### ISSUE TITLE
Pictures - Knowledge base

### ISSUE THREAD

**Issue by matheuslwcardoso** [glpi-project/glpi#2992] opened 2017-10-17 12:35 UTC
Hi,

I'm use the version 9.2 and my pictures of itens of knowledge base doesn't show in browser.
![image](https://user-images.githubusercontent.com/18727391/31665208-db662cec-b326-11e7-91be-4d8b28d7345c.png)

I made test in Chrome, IE, Firefox and Edge but no sucess.

**Comment by trasher** [comment] 2017-11-03 07:32
I wonder if this is not a duplicate of https://github.com/glpi-project/glpi/issues/2980

Please test patch provided for this one.

**Comment by trasher** [comment] 2018-02-02 07:33
No feedback; closing.

**Closed by trasher** 2018-02-02 07:33 UTC

**Comment by ralporto** [comment] 2018-02-08 19:01
Hi trasher!
I have this same issue here and i already tried to apply the mencioned fix and it does not work.
Some times if i edit the knowled again the image appear but only in edition mode. When i back to the main knowledge page the document are not show. When i click at documents tab the image is there too and when i click at it the image open normally. I'm loged with super admin.
Take a look:
![image](https://user-images.githubusercontent.com/33453857/35992469-78610606-0cf1-11e8-9c2f-bf9f5ca83a90.png)

![image](https://user-images.githubusercontent.com/33453857/35992523-9ef7dc18-0cf1-11e8-9a16-d1052373830c.png)

![image](https://user-images.githubusercontent.com/33453857/35992548-ae6201ba-0cf1-11e8-92c8-a1f68f560efe.png)

**Comment by ralporto** [comment] 2018-02-08 20:01
Making some tests i could see something strange. Sometimes the pictures just appears att the body of knowlead base but sometimens they dont. So i observe that when the picture does not appears theres a document created, but when the picture appears no document are create. So I tryed to see de source code of the knowled that i'm edditing and i saw that the code of the picture that are showed is completely diferent.
Take a look:
<p>  </p>
<p> <a href="http://server:8001/glpi/front/document.send.php?docid=1025" target="_blank"><img src="http://server:8001/glpi/front/document.send.php?docid=1025" alt="d3818d46-d782c752-5a7ca693a8ac12.49285975" width="500" height="500" /></a></p>
<p> </p>
<p> <img id="d3818d46-d782c752-5a7ca6b2c2a612.98642095" src="blob:http://server:8001/39e3be51-26e8-47d0-9c0d-4c17d80b9f3b" width="500" height="500" /></p>
<p> </p>
<p> <img id="d3818d46-d782c752-5a7ca6c3bfd111.13891161" src="blob:http://server:8001/94a246d1-718d-42c8-9465-46fc637ceb46" width="500" height="500" /></p>
<p> </p>
<p> <img id="d3818d46-d782c752-5a7ca6e0148710.14970762" src="blob:http://server:8001/9f94ea6e-c861-4aec-96c2-42d916fd23e4" width="500" height="500" /></p>
<p> </p>

The first picture on this code are showed as you can see:

![image](https://user-images.githubusercontent.com/33453857/35995030-5945cd08-0cf9-11e8-97c2-2aacbfb04346.png)

But there's 4 images and only one are showed but at documents only 3 are showed cause the embed image are not at the documents tab:

![image](https://user-images.githubusercontent.com/33453857/35995294-09595e76-0cfa-11e8-977e-001e155a5157.png)
