### ISSUE TITLE
Can't load Images, wrong URL

### ISSUE THREAD

**Issue by oscargomez87** [glpi-project/glpi#6017] opened 2019-06-12 13:19 UTC
When tickets are created using mail import, the images can't be visualized. When I click on them the URL is cut, the hostname is cut, this is an exmaple:

`https://front/document.send.php?docid=62&tickets_id=1190`

An the attachments documents give a "file not found" error this is a URL to an attached file

`https://hostname/front/document.send.php?docid=1300&tickets_id=1232`

There are no errors in php-error.log or nginx error log.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
Information about system installation & configuration
[code]
 
GLPI 9.4.2 ( => /var/www/.com/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux glpi 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64
PHP 7.1.8 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="256M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: nginx/1.14.0
	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.10-MariaDB
	Server SQL Mode: 
	Parameters: mercadeo@localhost/mercadeo
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (10.3.10) - Perfect!Database version seems correct (10.3.10) - Perfect!
OK/var/www/.com/glpi/files/_log : OK
OK/var/www/.com/glpi/config : OK
OK/var/www/.com/glpi/files : OK
OK/var/www/.com/glpi/files/_dumps : OK
OK/var/www/.com/glpi/files/_sessions : OK
OK/var/www/.com/glpi/files/_cron : OK
OK/var/www/.com/glpi/files/_graphs : OK
OK/var/www/.com/glpi/files/_lock : OK
OK/var/www/.com/glpi/files/_plugins : OK
OK/var/www/.com/glpi/files/_tmp : OK
OK/var/www/.com/glpi/files/_cache : OK
OK/var/www/.com/glpi/files/_rss : OK
OK/var/www/.com/glpi/files/_uploads : OK
OK/var/www/.com/glpi/files/_pictures : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.OKSELinux mode is Permissive
OKSELinux boolean configuration for httpd_can_network_connect --> on
OKSELinux boolean configuration for httpd_can_network_connect_db --> on
OKSELinux boolean configuration for httpd_can_sendmail --> on

Libraries
 
htmLawed version 1.2.4 in (/var/www/.com/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/.com/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/.com/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/.com/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/.com/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/.com/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/.com/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/.com/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/.com/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/.com/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/.com/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/.com/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/.com/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/.com/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/.com/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/.com/glpi/vendor/leafo/scssphp/src)

LDAP directories
 
Server: '', Port: ', BaseDN: 'dc=,dc=', Connection filter: none, RootDN:
		'uid=,cn=,cn=', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+TLS ()

Mails receivers
 
Name: '' Active: Yes
	Server: '{imap/ssl/validate-cert}INBOX' Login: 'mercadeo' Password: Yes

Plugins list
 
	dashboard            Name: Dashboard                      Version: 0.9.7      State: Enabled
	mod                  Name: GLPI Modifications             Version: 1.3.2      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.0      State: Enabled

```

**Comment by trasher** [comment] 2019-06-13 06:08
> There are no errors in php-error.log or nginx error log.

What about glpi logs?

**Comment by oscargomez87** [comment] 2019-06-13 11:54
This is the list of files I have in files/_log

```
-rw-r--r--. 1 nginx nginx    36028 jun 13 06:36 cron.log
-rw-r--r--. 1 nginx nginx      193 jun 12 07:53 event.log
-rw-r--r--. 1 nginx nginx    98059 jun 12 18:24 mail.log
-rw-r--r--. 1 nginx nginx     9321 jun 13 01:28 php-errors.log
-rw-rw-r--. 1 nginx nginx       80 abr 11 05:19 remove.txt
```
nothing came up in any of those files while accesing attached files or images.

updated glpi to 9.4.2 (forgot to mention i was on 9.4.1 before this post) and now the new tickets show images and attached files correctly, but the old tickets still give me the same result. Is there any way i can confirm the files exist?

**Comment by cedric-anne** [comment] 2019-06-14 08:41
Hi,

Looks like a duplicate of #5619.

Migration from 9.4.1 to 9.4.2 may have removed trailing slash of defined base URL in your configuration. Wrong URL contained in DB will not be fixed automatically. Wrong URL looks like `//front/document.send.php?` (relative to protocol) instead of `/front/document.send.php?` (relative to domain).

Regards

**Comment by oscargomez87** [comment] 2019-06-14 12:48
There is no traling `/` in `URL of the application ` global configuration. 

![image](https://user-images.githubusercontent.com/45802292/59510233-d0188b80-8e78-11e9-9820-b894cdd3a482.png)

**Comment by oscargomez87** [comment] 2019-06-14 12:51
So there is a wrong URL saved in DB?, i dont have a trailing `/` in `URL of application` global configuration.

![image](https://user-images.githubusercontent.com/45802292/59510375-2685ca00-8e79-11e9-9f85-4858c339c6a2.png)

**Comment by cedric-anne** [comment] 2019-06-14 12:56
If you had a trailing slahs, it has been removed during migration to 9.4.2, but data stored in DB has not been fixed in this case.

**Comment by oscargomez87** [comment] 2019-06-14 13:00
Is there a table I can check to confirm?

**Comment by cedric-anne** [comment] 2019-06-14 13:08
Table for tickets is `glpi_tickets`.

**Comment by oscargomez87** [comment] 2019-06-14 13:12
I just checked and have to correct myself. On new tickets, images found in the message body are showing correctly, but attached files like `PDF` still give me `file not found` error.

**Comment by cedric-anne** [comment] 2019-06-14 13:16
> but attached files like `PDF` still give me `file not found` error.

Where is this `file not found` error shown ? In your browser, in logs, ... ? If it is a link, what is the URL ?

**Comment by oscargomez87** [comment] 2019-06-14 13:18
this is the URL
`https://mercadeo.lan.cdo-sa.com/front/document.send.php?docid=1176&tickets_id=1295`
The error is shown in a new browser page.

**Comment by oscargomez87** [comment] 2019-06-14 13:36
This is the path to the file I'm checking

`PDF/4b/9ef0758f95d15cf9991ad3ee70db647debc32f.PDF`

But the file does not exist, using find to check if any file has been created, I can see files created yesterday and the amount of documents created is consistent with the number of tickets created that day.

**Comment by cedric-anne** [comment] 2019-06-14 13:44
Have you something in your logs ?

Is your cron running using a user that has rights to write on the directory `files` and its subdirectories ? Are all `files` directory and subdirectories rights correct ? If you launch cron with another user than the one used by the webserver, it may have create directories with a not expected owner/group .

**Comment by oscargomez87** [comment] 2019-06-14 13:48
You are right, the URL to the files have something wrong in the older tickets. And the problem with the PDF file was that something went wrong with the copies made of the files folder during migration.

I assume is neccesary to replace the URL from the tickets. Is there a script or something along those lines you can point me to?

Thanks for all the help.

**Comment by cedric-anne** [comment] 2019-06-14 13:58
Sorry, there is no script to fix this.

**Closed** 2019-06-15 06:13 UTC
Labels: Need feedback

**Comment by smarcos-starxpert** [comment] 2021-04-13 14:23
Hi all,

I would like to reopen this issue if possible.

I have just made a migration from a GLPI 9.3.3 on IIS to a GLPI 9.5.4 on Linux.
Everything is good at all levels, glpi and plugins.
However I have the same problem. The images integrated in the body of the follow-up of ticket or at the opening of a ticket point towards a URL of this kind:

http://FQDN/glpi/front/document.send.php?docid=XXXX
but the correct URL should be 
http://FQDN/front/document.send.php?docid=XXXX

The error is not present in the logs but only on the WEB interface, telling me that the config_db.php file is not present.
This is wrong, because without this file, it is impossible to connect to the database.

Here is what the logs give me:
==> /var/log/apache2/access.log <==
172.31.26.18 - - [13/Apr/2021:16:17:57 +0200] "GET /glpi/front/document.send.php?docid=4139&tickets_id=14312 HTTP/1.1" 401 742

==> /var/log/apache2/referer.log <==
http://srv-glpi/front/ticket.form.php?id=14312 -> /glpi/front/document.send.php

==> /var/log/apache2/access.log <==
172.31.26.18 - *********************** [13/Apr/2021:16:17:57 +0200]"GET /glpi/front/document.send.php?docid=4139&tickets_id=14312 HTTP/1.1" 200 2498

==> /var/log/apache2/referer.log <==
http://srv-glpi/front/ticket.form.php?id=14312 -> /glpi/front/document.send.php

Translated with www.DeepL.com/Translator (free version)
