### ISSUE TITLE
[9.2] Bug with image in ticket description

### ISSUE THREAD

**Issue by usrqmor** [glpi-project/glpi#3235] opened 2017-12-01 14:38 UTC
Hello,

I search on github same issue and the issue #2869 was the most useful for me.
I apply the corrections to solve the problem but I still have an issue with the pictures in the ticket description.
In fact, the picture that are more a certain height and width appears like this in the ticket : 
![image](https://user-images.githubusercontent.com/17316903/33487439-7aa25a34-d6ad-11e7-972e-89ae1e027197.png)

Like ou can see, the picture is set as a document but I have a blank image and some "n".

Can you help me with this bug ? 
Thank you.

**Comment by trasher** [comment] 2017-12-01 14:45
Most of those issues are fixed in 9.2.1; consider updating your instance. 

Picking random patches will probably not work... or will completely break.

**Closed by trasher** 2017-12-01 14:45 UTC

**Comment by cvscg** [comment] 2017-12-01 14:48
It is not fixed in version 9.2.1, I have this version and I also have this problem. 👎

**Comment by trasher** [comment] 2017-12-01 14:51
This is reported as fixed on the original issue; but not for existing images. "n" issue is something else.

If you think there is a bug in 9.2.1, please open a ticket with required informations and steps to reproduce. Current ticket is about issues on 9.2.

**Comment by usrqmor** [comment] 2017-12-01 14:55
I'll try upgrade my test glpi and if the bug is still here, i'll open an another issue with the 9.2.1 version.

**Comment by trasher** [comment] 2017-12-01 14:56
Thank you

**Comment by ciadch** [comment] 2017-12-18 13:48
Works fine with 9.2.1. Thanks

**Comment by usrqmor** [comment] 2017-12-20 08:07
Not for me and some people :/ 
Even after a clean install of 9.2.1. I'll wait for the 9.2.2 to see if it's better.

**Comment by ciadch** [comment] 2017-12-20 09:24
Sorry I mistaken issue... Effectively the problem seems to be already present. Event after a clean install
