### ISSUE TITLE
Bug in migration to 9.1

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1079] opened 2016-09-28 11:12 UTC
http://forum.glpi-project.org/viewtopic.php?id=155451

**Comment by trasher** [comment] 2016-09-28 11:42
@yllen you're waiting for a confirmation to close this one?

We'll have to backport this fix in thee master aswell, lemme know if you do or if I would ;)

**Comment by remicollet** [comment] 2016-09-28 11:47
I think the commit only fix the warning when migration is played several time.

Not the missing right after migration.

**Comment by trasher** [comment] 2016-09-28 11:50
Oh, OK, I misunderstood :)

**Comment by remicollet** [comment] 2016-09-28 11:51
I think the issue is there:

```
   $new = $migration->addField("glpi_softwarelicenses", "is_deleted", "bool");

   if ($new) {
      //new right for software license
```

IIRC these fields where at some point in the 0.90 branch (by mistake)

**Comment by remicollet** [comment] 2016-09-28 11:53
Indeed in 0.90.3
See https://github.com/glpi-project/glpi/blob/60519387f63bed3f76d1c0354be605a149a4f2ba/install/update_0901_0902.php#L95

**Comment by trasher** [comment] 2016-09-28 11:58
Thanks for the hint!

**Comment by yllen** [comment] 2016-09-28 12:07
@remicollet I think all OK now. Can you test and close if OK for you?

**Comment by yllen** [comment] 2016-09-28 12:09
I'll backport these modifications in master after your test

**Comment by remicollet** [comment] 2016-09-28 12:15
@yllen I think the fix is OK (cannot test now, have to reinstall a 0.90.3 to ensure everything is ok)

**Comment by yllen** [comment] 2016-09-28 12:21
@trasher done also for master

**Closed** 2016-09-28 12:20 UTC
Labels: bug

**Comment by trasher** [comment] 2016-09-28 12:51
Super, thank you very much :)
