### ISSUE TITLE
MySQL query warning - Truncated incorrect DOUBLE value for networkports

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#13522] opened 2022-12-05 11:07 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

Hi.
My sql-errors.log file is spammed with entries:

[2022-12-05 10:32:01] glpisqllog.WARNING: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 404
  *** MySQL query warnings:
  SQL: SELECT `glpi_peripherals`.`id`, `glpi_networkports`.`id` AS `portid` FROM `glpi_peripherals` LEFT JOIN `glpi_networkports` ON (`glpi_peripherals`.`id` = `glpi_networkports`.`items_id` AND `glpi_networ
kports`.`itemtype` = 'Peripheral') WHERE (`glpi_networkports`.`mac` IN ('xx:xx:xx:xx:xx:xx')) AND (`glpi_networkports`.`logical_number` = 'port2')
  Warnings:
1292: Truncated incorrect DOUBLE value: 'port2'
  Backtrace :
  src/DBmysqlIterator.php:112
  src/DBmysql.php:1056                               DBmysqlIterator->execute()
  src/RuleImportAsset.php:538                        DBmysql->request()
  src/Rule.php:1649                                  RuleImportAsset->findWithGlobalCriteria()
  src/Rule.php:1507                                  Rule->checkCriterias()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/NetworkPort.php:251            RuleCollection->processAllRules()
  src/Inventory/Asset/NetworkPort.php:514            Glpi\Inventory\Asset\NetworkPort->handleLLDPConnection()
  src/Inventory/Asset/NetworkPort.php:538            Glpi\Inventory\Asset\NetworkPort->handleConnections()
  src/Inventory/Asset/NetworkPort.php:528            Glpi\Inventory\Asset\NetworkPort->portChanged()
  src/Inventory/Asset/InventoryNetworkPort.php:499   Glpi\Inventory\Asset\NetworkPort->portUpdated()
  src/Inventory/Asset/InventoryNetworkPort.php:119   Glpi\Inventory\Asset\NetworkPort->handleUpdates()
  src/Inventory/Asset/NetworkPort.php:690            Glpi\Inventory\Asset\NetworkPort->handlePortsTrait()
  src/Inventory/Asset/NetworkPort.php:523            Glpi\Inventory\Asset\NetworkPort->handlePorts()
  src/Inventory/Asset/MainAsset.php:862              Glpi\Inventory\Asset\NetworkPort->handle()
  src/Inventory/Asset/MainAsset.php:782              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/Inventory/Asset/NetworkEquipment.php:222       Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/RuleImportAsset.php:950                        Glpi\Inventory\Asset\NetworkEquipment->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:564              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:702                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:337                    Glpi\Inventory\Inventory->handleItem()
  ...inc/communicationnetworkinventory.class.php:156 Glpi\Inventory\Inventory->doInventory()
  marketplace/glpiinventory/hook.php:1096            PluginGlpiinventoryCommunicationNetworkInventory->import()
  src/Plugin.php:1521                                plugin_glpiinventory_network_inventory()
  src/Inventory/Request.php:278                      Plugin::doHookFunction()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
{"user":"inventory@glpi","mem_usage":"0.001\", 9.64Mio)"}

### Anything else?

[https://forum.glpi-project.org/viewtopic.php?id=285503](https://forum.glpi-project.org/viewtopic.php?id=285503)

**Comment by cedric-anne** [comment] 2022-12-05 11:17
Hi,

We made many changes on inventory since last release. Could you try to reproduce on a test server using the latest [nightly build](https://nightly.glpi-project.org/glpi/) ?

**Comment by WebGregGit** [comment] 2022-12-12 11:35
Hi @cedric-anne 
It seems to have actually OK with 10.0.6-dev. Thank You

**Comment by WebGregGit** [comment] 2022-12-14 10:14
Hi @cedric-anne 

Sorry, I didn't notice that I didn't enable the inventory plugin. After launching it, the same error appears.
Maybe I should report it in the glpi-inventory section?

**Comment by stonebuzz** [comment] 2022-12-14 10:18
Hi @WebGregGit  Can you provide related XML inventory file ?

**Comment by WebGregGit** [comment] 2022-12-14 12:27
Hi @stonebuzz 

I don't even know what device it is. I searched the mac address shown in log but it didn't return anything.
I also don't know if a log is really required. I think @cconard96 knows what's up:

"SQL warnings were enabled for 10.0 so in cases where we are accidentally trying to search for a text value in numeric columns there is now this warning shown. It is a bug. Please open an issue on the GitHub. I'm working on another project/feature so I may accidentally forget to look into this when I have a chance to switch tasks."

**Comment by cedric-anne** [comment] 2022-12-14 12:41
@WebGregGit 

When a developer asks for information, it is usually because it is one of the best ways to identify the source of a problem. 

We provide free support here, but we are under no obligation to issue a fix for every request we receive. It is not uncommon for a developer to overlook a reported problem and not provide an answer if he does not think he can easily identify the cause of it. There is indeed a lot to do and we generally choose to deal with the issues we are able to reproduce.

**Comment by WebGregGit** [comment] 2022-12-14 13:00
@cedric-anne yes I know it. My intention was only to signal that someone may already associate the topic. 
In addition, I mentioned that I don't even know what kind of device it is - as a result, I don't know where to get the inventory file.

By the way, I'm not only looking for support here, but I also provide free tests.

**Comment by trasher** [comment] 2022-12-15 08:17
Please provide steps/files to reproduce your issue on a fresh 10.0/bugfixes install.

**Comment by WebGregGit** [comment] 2022-12-30 09:45
Hi @trasher 

Sorry it took so long but I was sick. In addition, the taskscheduler action jammed - and from that moment the logs were clean. I restarted the jobs and I have sql-errors entries again.

Unfortunately, I don't understand what I can give you (where to get it). I just run the discovery task and see the mentioned errors in the log file.


[2022-12-30 10:12:57] glpisqllog.WARNING: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 404
  *** MySQL query warnings:
  SQL: SELECT `glpi_phones`.`id`, `glpi_networkports`.`id` AS `portid` FROM `glpi_phones` LEFT JOIN `glpi_networkports` ON (`glpi_phones`.`id` = `glpi_networkports`.`items_id` AND `glpi_networkports`.`itemtype` = 'Phone') WHERE (`glpi_networkports`.`mac` IN ('d4:x6:ax:xx:xd:20')) AND (`glpi_networkports`.`logical_number` = 'port2')
  Warnings:
1292: Truncated incorrect DOUBLE value: 'port2'

[2022-12-30 10:12:57] glpisqllog.WARNING: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 404
  *** MySQL query warnings:
  SQL: SELECT `glpi_printers`.`id`, `glpi_networkports`.`id` AS `portid` FROM `glpi_printers` LEFT JOIN `glpi_networkports` ON (`glpi_printers`.`id` = `glpi_networkports`.`items_id` AND `glpi_networkports`.`itemtype` = 'Printer') WHERE (`glpi_networkports`.`mac` IN ('d4:x6:ax:xx:xd:20')) AND (`glpi_networkports`.`logical_number` = 'port2')
  Warnings:
1292: Truncated incorrect DOUBLE value: 'port2'

**Comment by cedric-anne** [comment] 2023-01-30 08:07
Hi,

I close this issue as many fixes that may have a positive impact on this were done in GLPI 10.0.6 / glpiinventory 1.10.0.
If issue persist, feel free to reopen the issue if you can give inventory files to reproduce it.

**Closed by cedric-anne** 2023-01-30 08:07 UTC

**Comment by EC2311** [comment] 2023-10-25 14:48
Hello

On 10.0.10 I have this warning 

By using global search
![image](https://github.com/glpi-project/glpi/assets/42341169/2baa4173-eded-4603-876d-6481a12b987e)
put whatever as input

the warning appears in sql-errors.log

**Comment by cedric-anne** [comment] 2023-10-25 14:49
> Hello
> 
> On 10.0.10 I have this warning
> 
> By using global search ![image](https://user-images.githubusercontent.com/42341169/278051996-2baa4173-eded-4603-876d-6481a12b987e.png) put whatever as input
> 
> the warning appears in sql-errors.log

Hi,

Please create a new issue for this, and give all requested information.
