### ISSUE TITLE
error when upgrading from version 9.5.5 to 9.5.5 (downloaded today)

### ISSUE THREAD

**Issue by felipepimentel08** [glpi-project/glpi#9312] opened 2021-07-21 18:29 UTC
When downloading a new version 9.5.5 for test base, I did the restore of a database in version 9.5.5 and asked for an update.

I did not get it but it's OK.

I performed the update procedure, but stopped at this error screen (attachment)

![image](https://user-images.githubusercontent.com/47112555/126540851-2a9ac431-2b4c-4ef6-8427-401a291b4286.png)

**Comment by cedric-anne** [comment] 2021-07-22 09:43
Hi,

Update process is launched because you did not copied your DB configuration file. It just replays the latest migration, ignoring already migrated elements. This is a totally intended feature required by GLPI developpers during development phase.

To bypass you issue, just copy and update manually your configuration files (all the `/path/to/glpi/config/` directory).

I was not able to reproduce using the current state of 9.5/bugfixes branch. I just removed my configuration files, run the update process, and all was OK. I close this issue as it seems to be already fixed.

Regards

**Closed by cedric-anne** 2021-07-22 09:43 UTC
