### ISSUE TITLE
 Errors when updating from 9.1 to 9.4 : migration of the data of the plugin "Racks"

### ISSUE THREAD

**Issue by castorsenior** [glpi-project/glpi#7019] opened 2020-03-05 11:08 UTC
Hello,
I'm getting 680 messages like these ones when I execute "racks_plugin.php" in order to migrate the data from the plugin inside the core of GLPI :
   * PluginRacksOtherModel (2): Not found
   * PluginRacksOtherModel (6): Not found
   * PluginRacksOtherModel (7): Not found
   * PluginRacksOtherModel (9): Not found
   * PluginRacksOtherModel (10): Not found
   * NetworkEquipmentModel (159): Not found
   * NetworkEquipmentModel (275): Not found
   * NetworkEquipmentModel (276): Not found
   * ComputerModel (2096): Not found
   * ComputerModel (2103): Not found
   * NetworkEquipmentModel (297): Not found
   * PluginRacksOtherModel (13): Not found
   * PluginRacksOtherModel (14): Not found
   * PluginRacksOtherModel (15): Not found
   * PluginRacksOtherModel (16): Not found
   * PluginRacksOtherModel (17): Not found
   * PluginRacksOtherModel (18): Not found
   * PluginRacksOtherModel (19): Not found
   * PluginRacksOtherModel (20): Not found
   * PluginRacksOtherModel (21): Not found
   * PluginRacksOtherModel (22): Not found
   * PluginRacksOtherModel (3): Not found
   * PluginRacksOtherModel (23): Not found
   * PluginRacksOtherModel (24): Not found
   * PluginRacksOtherModel (25): Not found
   * PluginRacksOtherModel (26): Not found
   * PluginRacksOtherModel (27): Not found
   * PluginRacksOtherModel (28): Not found
   * PluginRacksOtherModel (29): Not found
   * Pdu (1): Not found
   * PluginRacksOther (3): Type not found
   * PluginRacksOther (4): Type not found
   * Pdu (3): Not found
   * PluginRacksOther (6): Type not found
   * Pdu (1): Not found
   * Pdu (4): Not found
   * Pdu (5): Not found
   * Pdu (6): Not found
   * Pdu (7): Not found
   * Pdu (2): Not found
   * Computer (19870): Not found
   * Computer (20721): Not found
   * Computer (21083): Not found

Some elements are missing in fact in my bays.
What mean the numbers above ?
Thank you for your help, 
with best regards

**Comment by trasher** [comment] 2020-03-05 11:23
All listed erros seems to be missing references in your plugin tables. First part is the item type, and the number into parenthesis the id of the missing reference. For exampl, a PluginRacksOtherModel with the id 2 is referenced but does not exists.

From provided informations, this is not a bug; migration command cannot fix data issues. You can try to see what is missing and get your data fixed in the plugin before doing migration.

**Closed by trasher** 2020-03-05 11:23 UTC

**Comment by castorsenior** [comment] 2020-03-09 12:19
Thank you very much @trasher for your answer :-)
For the other followers, when you erase an item from the core of GLPI, it still stays registered in the plugin, even if it is not displayed in the rack. For example, I have deleted the item number 22737 :  
![image](https://user-images.githubusercontent.com/12443836/76212347-8c389400-6208-11ea-81dd-2ca1ab8f00ae.png)
