### ISSUE TITLE
[9.5.3] Cannot add a ticket via REST API 

### ISSUE THREAD

**Issue by StefanSa** [glpi-project/glpi#8866] opened 2021-03-23 15:13 UTC
**Describe the bug**
Hi there,
i come from here: https://github.com/wandrey66/Zabbix-WebHook-GLPI/issues/1
Although the api user has enough user rights, super-admin, he cannot create a ticket.
`Response: 400, ERROR_GLPI_ADD You don't have permission to perform this action`

**Page(s) URL**
`/apirest.php/Ticket/`

**To reproduce**
get a valide session token:
```
JavaScript Object Notation: application/json
    Object
        Member Key: session_token
            String value: 0mbpqpttvm6e0a9veqagk5627k
            Key: session_token
```
send api message to create the ticket:
```
JavaScript Object Notation: application/json
    Object
        Member Key: input
            Object
                Member Key: name
                    String value: Problem: "Spooler" (Druckwarteschlange) is not running (startup type automatic)
                    Key: name
                Member Key: content
                    String value [truncated]: Problem started at 10:02:42 on 2021.03.23\r\nProblem name: "Spooler" (Druckwarteschlange) is not running (startup type automatic)\r\nHost: XXX\r\nSeverity: Average\r\nOperational data: Stopped (6)\r\nOriginal p
                    Key: content
                Member Key: itilcategories_id
                    String value: 1
                    Key: itilcategories_id
                Member Key: entities_id
                    String value: 1
                    Key: entities_id
                Member Key: urgency
                    String value: 3
                    Key: urgency
                Member Key: impact
                    String value: 3
                    Key: impact
                Member Key: priority
                    String value: 3
                    Key: priority
                Member Key: _users_id_assign
                    String value: 8
                    Key: _users_id_assign
            Key: input

```
get this api error message return:
```
JavaScript Object Notation: application/json
    Array
        String value: ERROR_GLPI_ADD
        String value: You don't have permission to perform this action.
```
was tested on different users, each with maximum user rights, but always the same api error message.

**Expected behavior**

A new ticket is added and a response with HTTP status code 200 is returned.

**Logs**

```
no clear indications even in debug mode.
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
Operating system: Linux ****** 5.3.18-lp152.66-default #1 SMP Tue Mar 2 13:18:19 UTC 2021 (73933a3) x86_64
PHP 7.4.6 apache2handler (Core, PDO, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, ctype, curl, date, dom,
	exif, fileinfo, filter, gd, hash, iconv, imagick, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
	pdo_sqlite, session, soap, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0
Server Software: MariaDB package
	Server Version: 10.4.17-MariaDB
	Server SQL Mode: 
	Parameters: ************
	Host info: ******** via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is not presentapcu extension is not present
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is not presentCAS extension is not present
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.4.17) - Perfect!Database version seems correct (10.4.17) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /srv/www/htdocs/glpi/config has been validated.Write access to /srv/www/htdocs/glpi/config has been validated.
Write access to /srv/www/htdocs/glpi/files has been validated.Write access to /srv/www/htdocs/glpi/files has been validated.
Write access to /srv/www/htdocs/glpi/files/_dumps has been validated.Write access to /srv/www/htdocs/glpi/files/_dumps has been validated.
Write access to /srv/www/htdocs/glpi/files/_sessions has been validated.Write access to /srv/www/htdocs/glpi/files/_sessions has been validated.
Write access to /srv/www/htdocs/glpi/files/_cron has been validated.Write access to /srv/www/htdocs/glpi/files/_cron has been validated.
Write access to /srv/www/htdocs/glpi/files/_graphs has been validated.Write access to /srv/www/htdocs/glpi/files/_graphs has been validated.
Write access to /srv/www/htdocs/glpi/files/_lock has been validated.Write access to /srv/www/htdocs/glpi/files/_lock has been validated.
Write access to /srv/www/htdocs/glpi/files/_plugins has been validated.Write access to /srv/www/htdocs/glpi/files/_plugins has been validated.
Write access to /srv/www/htdocs/glpi/files/_tmp has been validated.Write access to /srv/www/htdocs/glpi/files/_tmp has been validated.
Write access to /srv/www/htdocs/glpi/files/_cache has been validated.Write access to /srv/www/htdocs/glpi/files/_cache has been validated.
Write access to /srv/www/htdocs/glpi/files/_rss has been validated.Write access to /srv/www/htdocs/glpi/files/_rss has been validated.
Write access to /srv/www/htdocs/glpi/files/_uploads has been validated.Write access to /srv/www/htdocs/glpi/files/_uploads has been validated.
Write access to /srv/www/htdocs/glpi/files/_pictures has been validated.Write access to /srv/www/htdocs/glpi/files/_pictures has been validated.
Write access to /srv/www/htdocs/glpi/marketplace has been validated.Write access to /srv/www/htdocs/glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

Libraries

htmlawed/htmlawed version 1.2.5 in (/srv/www/htdocs/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/srv/www/htdocs/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/srv/www/htdocs/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/srv/www/htdocs/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/srv/www/htdocs/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/srv/www/htdocs/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/srv/www/htdocs/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/srv/www/htdocs/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/srv/www/htdocs/glpi/vendor/sabre/http/lib)
sabre/uri in (/srv/www/htdocs/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/srv/www/htdocs/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/srv/www/htdocs/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/srv/www/htdocs/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/srv/www/htdocs/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/srv/www/htdocs/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/srv/www/htdocs/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/srv/www/htdocs/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/srv/www/htdocs/glpi/vendor/symfony/console)
scssphp/scssphp in (/srv/www/htdocs/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/srv/www/htdocs/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/srv/www/htdocs/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/srv/www/htdocs/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/srv/www/htdocs/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/srv/www/htdocs/glpi/vendor/ramsey/uuid/src)
psr/log in (/srv/www/htdocs/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/srv/www/htdocs/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/srv/www/htdocs/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/srv/www/htdocs/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/srv/www/htdocs/glpi/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/srv/www/htdocs/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/srv/www/htdocs/glpi/vendor/paragonie/sodium_compat/src)
```

**Comment by StefanSa** [comment] 2021-03-24 07:51
The interesting thing is, i can add a computer object, but not a ticket.
Access rights ?

**Comment by cedric-anne** [comment] 2021-03-24 07:55
Hi,

If your user have many profiles, the API will use the default profile of your user, or the first found if the default one is not set. So maybe the profile used by the API has no rights for this.

Regards

**Comment by StefanSa** [comment] 2021-03-24 07:59
Bonjour Cedric,
I have just created a new user zabbix with admin authorization, who can also add computer objects but not tickets. How can i change this ? Or where do i have to look?

**Comment by cedric-anne** [comment] 2021-03-24 08:05
To get support, you can ask for community support on [forum](https://forum.glpi-project.org/) or [get a subscription for a professionnal support](https://glpi-project.org/subscriptions/).

I close this issue as it is not a bug, but a configuration issue.

**Closed by cedric-anne** 2021-03-24 08:05 UTC
