### ISSUE TITLE
 Error in associated elements in ticket list - wrong object

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4107] opened 2018-05-31 09:46 UTC
* Steps to reproduce (which actions have you made) :
I have exactly #3367

* Expected result :
Display the correct associted element in ticket list.

* Actual result :
wrong objects on different tickets

* URL of the page :

* Screenshot of the problem (if pertinent) :
if you need a new you get it.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
9.2.3 ubuntu 16.04 ltsb
I deactivated all plugins. I don't have installed unsupported plugins i cleaned up.

**Comment by trasher** [comment] 2018-06-06 11:01
Still can't reproduce:
![screenshot-2018-6-6 glpi - tickets](https://user-images.githubusercontent.com/224733/41034322-82096924-6989-11e8-9bf2-6f564b573a2e.png)

So, please provide detailled use case to reproduce.

**Comment by Armin83** [comment] 2018-06-06 13:34
first i uninstall forms plugin and not disable because your last forum answer to different topic.
ciadch descriped the problem (link) in his environment correct there is some dependency on a valid id i think.

I have 4 items in my ticket. 2 computer (internal id i  see from link in itmes section 4 and 5 2 monitors with id 1 and 2). In this case i see in the list view only 2 times the computers with id 1 and 2 of course this wrong.

![2018-06-06 15_33_13-window](https://user-images.githubusercontent.com/19192087/41041340-0f7b3124-699f-11e8-9be2-34041cd8d116.png)
![2018-06-06 15_33_32-window](https://user-images.githubusercontent.com/19192087/41041341-0f98ff7e-699f-11e8-809b-b3627a139ff5.png)

tested on 9.3bugfix from this night

**Comment by trasher** [comment] 2018-06-06 13:43
The only think that differs in my example is I had only one monitor. I just add another one ; and I still cannot reproduce.
2 ways to go: either reproduce on the demo (will be reset this sunday), or provide us INSERT queries of the data to reproduce.

It may also be something in the configuration; but I got absolutely no idea what :/

**Comment by trasher** [comment] 2018-06-06 13:50
Rather than a few inserts, a complete dump would be probably better (this will include the whole configuration - among others), but only if you do not have sensitive data. You can send it by mail if you prefer on glpi AT teclib.com

**Comment by Armin83** [comment] 2018-06-06 13:58
Could it be a acpu problem ?
My test system don't run in strict mode should i change this ?

> [2018-06-06 15:54:23] glpiphplog.DEBUG: Config::getCache() in /usr/share/glpi/inc/config.class.php line 2929
CACHE cache_trans Zend\Cache\Storage\Adapter\Apcu  {"user":"2@lalaland","mem_usage":"0.005\", 1.30Mio)"}
[2018-06-06 15:54:23] glpiphplog.DEBUG: Config::getCache() in /usr/share/glpi/inc/config.class.php line 2929
CACHE cache_db Zend\Cache\Storage\Adapter\Apcu  {"user":"2@lalaland"}
[2018-06-06 15:54:23] glpiphplog.DEBUG: Config::getCache() in /usr/share/glpi/inc/config.class.php line 2929
CACHE cache_trans Zend\Cache\Storage\Adapter\Apcu  {"user":"2@lalaland","mem_usage":"0.004\", 1.29Mio)"}

**Comment by trasher** [comment] 2018-06-06 14:03
No, I do not think cache is used here. To be sure, just restart your PHP.
What stric_mode are you talking about? mysql one? this ie not necessary (in facts, that would probably cause other issues...).

**Comment by Armin83** [comment] 2018-06-06 14:32
System

> Information about system installation and configuration
> --
>    GLPI 9.3-dev (/glpi => /usr/share/glpi) Installation mode: TARBALL
> 
> Operating system: Linux lalaland 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 PHP 7.0.30-0ubuntu0.16.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, libxml, 	mbstring, mcrypt, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, recode, session, 	shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, 	zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at 192.168.1.106 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 Server Software: (Ubuntu) 	Server Version: 5.7.22-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: Glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed ldap extension is not present CAS extension is not present Database version seems correct (5.7.22) - Perfect! /usr/share/glpi/config : OK /usr/share/glpi/files : OK /usr/share/glpi/files/_dumps : OK /usr/share/glpi/files/_sessions : OK /usr/share/glpi/files/_cron : OK /usr/share/glpi/files/_graphs : OK /usr/share/glpi/files/_lock : OK /usr/share/glpi/files/_plugins : OK /usr/share/glpi/files/_tmp : OK /usr/share/glpi/files/_cache : OK /usr/share/glpi/files/_rss : OK /usr/share/glpi/files/_uploads : OK /usr/share/glpi/files/_pictures : OK /usr/share/glpi/files/_log : OK Web access to files directory is protected : OK
> 
> htmLawed version 1.2.4 in (/usr/share/glpi/lib/htmlawed) SimplePie version 1.5.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
> 
> Not active
> 
> Way of sending emails: PHP
> 
>  
> 
>  
> 
> 
>

**Comment by trasher** [comment] 2018-06-06 16:33
Well, using the dump you send me, all seems OK:
![screenshot-2018-6-6 glpi - tickets](https://user-images.githubusercontent.com/224733/41051954-d56104dc-69b7-11e8-8785-135d7f6e04c2.png)

Links with "monitor" are linked to monitor.form.php, all othrs to computer.form.php.

**Comment by trasher** [comment] 2018-06-06 16:37
Tested with php 7.0.30, 7.1.18 and 7.2.6 (can't test on 5.6, but since you're on 7.0, this should not be the problem).

**Comment by Armin83** [comment] 2018-06-06 22:31
I don't unterstand new server 18.04 ltsb ubuntu restore db. same problem ??
> 
> Information about system installation and configuration
> --
> [code]   GLPI 9.3-dev ( => /var/www/glpi) Installation mode: TARBALL
> 
> Operating system: Linux glpidev 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 PHP 7.2.5-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, recode, session, 	shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, 	xsl, zlib) Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at 192.168.1.108 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 Server Software: (Ubuntu) 	Server Version: 5.7.22-0ubuntu18.04.1 	Server SQL Mode:  	Parameters: glpidbuser@localhost/glpidb 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (5.7.22) - Perfect! /etc/glpi/ : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK /var/www/glpi/files/_log : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.
> 
> htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
> 
> Not active
> 
> Way of sending emails: PHP
> 
>  
> 
>  
> [/code]
> 
>

**Comment by trasher** [comment] 2018-06-11 05:11
So this is a MySQL issue. Are you sure you didi not get any errors in the sql-errors log?
Sounds like a duplicate of https://github.com/glpi-project/glpi/issues/627.

GLPI is not known to be compatible with MySQL 5.7 (cannot install it, and don't really want to waste time on that). Use MariaDB or MySQL <= 5.6.

**Comment by Armin83** [comment] 2018-06-11 09:33
Maybe you should make a note there https://glpi-install.readthedocs.io/en/latest/prerequisites.html#database "GLPI is not known to be compatible with MySQL 5.7"

I tried to work with /etc/glpi/local_define.php. I looked in the wrong directory for the logs...

> root@glpidev:/var/www/glpi/files/_log# cat sql-errors.log
> [2018-06-11 11:27:16] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 181
>   *** MySQL query error:
>   SQL: SELECT * FROM `SELECT @@sql_mode` AS `mode`
>   Error: Table 'glpidb.SELECT @@sql_mode' doesn't exist
>   Backtrace :
>   inc/dbmysqliterator.class.php:78
>   inc/dbmysql.class.php:587                          DBmysqlIterator->execute()
>   inc/dbmysql.class.php:694                          DBmysql->request()
>   inc/central.class.php:177                          DBmysql::isMySQLStrictMode()
>   inc/central.class.php:80                           Central::showMyView()
>   inc/commonglpi.class.php:478                       Central::displayTabContentForItem()
>   ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
>   {"user":"2@glpidev","mem_usage":"0.155\", 2.17Mio)"}

(There a no other errors in sql-errors.log)

**Comment by trasher** [comment] 2018-06-26 11:09
I won't add this in the documentation, since I'm not sure. Main issue regarding MySQL 5.7 has been kind of fixed (with more a hack than a fix). Since the only difference here is this version, this is certainly the issue, but as I do not have MySQL, I can't test myself.
If there are no errors in any logs, maybe check server's ones.

**Comment by trasher** [comment] 2018-07-02 08:51
Hi @Armin83 ; anything in system's mysql logs?

**Comment by Armin83** [comment] 2018-07-02 20:52
No, i can't see errors in errors.log

**Comment by cedric-anne** [comment] 2019-03-05 19:20
Hi,

Is it possible that #5529 fixes this problem?

Regards

**Comment by cedric-anne** [comment] 2021-01-07 19:57
Hi @Armin83 ,

Does #8504 fixes your issue ?

Regards

**Comment by Armin83** [comment] 2021-01-08 16:03
maybe @flo1994 can test it.
I don't use glpi anymore.

Regards

**Closed** 2021-02-16 10:19 UTC
Labels: bug
