### ISSUE TITLE
About data center 40x39 grid squares 

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#10529] opened 2022-02-03 17:09 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

HI, 
While discovering Data Centers features of GLPI, I found some abnormal behavior: grid squares are defined at 40x39 pixels. I think it should be 40x40 in order to exactly map background image files. In particular in:

/usr/share/glpi/css/styles.scss:
```< @@ -6076,7 +6076,7 @@ ul.indexes {
    .racks_add {
       border: 1px solid #EEEEEE;
       border-width: 0 1px 1px 0;
-      background-size: 40px 39px;
+      background-size: 40px 40px;
       background-image: linear-gradient(to right, #EEEEEE 1px, transparent 1px), linear-gradient(to bottom, #EEEEEE 1px, transparent 1px);
    }

@@ -6160,7 +6160,7 @@ ul.indexes {

          li {
             width: 10px;
-            height: 39px;
+            height: 40px;
             line-height: 40px;
          }
       }
@@ -6175,7 +6175,7 @@ ul.indexes {
    margin-left: 15px;

    .cell_add {
-      height: 39px;
+      height: 40px;
       width: 40px;
       float: left;
 ```

 /usr/share/glpi/inc/rack.class.php: 

```@@ -621,7 +621,7 @@ class Rack extends CommonDBTM {
       $cols     = (int) $room->fields['vis_cols'];
       $w_prct   = 100 / $cols;
       $grid_w   = 40 * $cols;
-      $grid_h   = (39 * $rows) + 16;
+      $grid_h   = (40 * $rows) + 16;
       $ajax_url = $CFG_GLPI['root_doc']."/ajax/rack.php";
```

The next modification is a little bit more complex, in particular it works for small background images (like 320x280), but not for ones like 1500x950, have to check a little bit more. I needed it, because with 320x280 png files, there is a vertical distortion of the image.

```@@ -683,7 +683,7 @@ class Rack extends CommonDBTM {
          $blueprint = "
             <div class='blueprint'
                  style='background: url({$blueprint_url}) no-repeat top left/100% 100%;
-                        height: ".$grid_h."px;></div>";
+                        height: ".($grid_h - 16)."px;></div>";
          $blueprint_ctrl = "<span class='mini_toggle active'
                                   id='toggle_blueprint'>".__('Blueprint')."</span>";
       }

@@ -756,7 +756,7 @@ class Rack extends CommonDBTM {
          $('.grid-room .grid-stack').gridstack({
             column: $cols,
             maxRow: ($rows + 1),
-            cellHeight: 39,
+            cellHeight: 40,
             verticalMargin: 0,
             float: true,
             disableOneColumnMode: true,
```

What do you think?
Thanks.

**Comment by cedric-anne** [comment] 2022-02-04 07:33
Hi,

Such a change will not be made in 9.5 branch, but feel free to open a PR on master branch if this behaviour is still present in GLPI 10.0.

Regards

**Comment by kabassanov** [comment] 2022-02-04 08:28
Hi, 

I can understand... I'll first find a way to make it work correctly in 9.5.7 and after that, I'll test as soon as possible with master branch code.

**Comment by kabassanov** [comment] 2022-02-04 17:28
Hi,
Despite of the not symetric dimensions of squares, there are these html errors in the code:

In /usr/share/glpi/inc/rack.class.php  2022-02-04 16:17:57.073021768 +0100:

```
@@ -683,13 +683,13 @@ class Rack extends CommonDBTM {
          $blueprint = "
             <div class='blueprint'
                  style='background: url({$blueprint_url}) no-repeat top left/100% 100%;
-                        height: ".$grid_h."px;></div>";
+                        height: ".$grid_h."px;'></div>";
          $blueprint_ctrl = "<span class='mini_toggle active'
                                   id='toggle_blueprint'>".__('Blueprint')."</span>";
       }
```
```
@@ -723,9 +723,9 @@ class Rack extends CommonDBTM {

       echo "</div>"; //.grid-stack
       echo $blueprint;
-      echo "</div>"; //.grid-room
       echo "<div class='sep'></div>";
       echo "<div id='grid-dialog'></div>";
+      echo "</div>"; //.grid-room
       echo "</div>"; // #viewgraph

       $rack_add_tip = __s('Insert a rack here');
```

**Comment by orthagh** [comment] 2022-03-23 10:37
Hello @kabassanov .

I resume this issue.
For the 40-39px, this is due to a strange margin management of the gridstack library (wich serve to display the block in the grid under the rack_add control). The lib until recently permitted to management vertical spacing easily but not horizontal one.
We must align gridstack cells with above rack_add controls.
It changes recently in gridstack but the proposed change may impact some other positioning so i'm not sure i want to do it now.

Now, could you explain the issue with background positioning (and maybe provide a file for trying myself) with some screenshots ?
Also, please, can you test with 10.0.0-rc3 to see if the issue is still present ?

**Comment by orthagh** [comment] 2022-03-24 08:17
You're right, but i already checked and if i'm not wrong, they are already fixed on master branch (glpi 10)

**Closed** 2022-03-28 07:08 UTC
