### ISSUE TITLE
Users elements don't show when creating the ticket after adding requester

### ISSUE THREAD

**Issue by mrajema** [glpi-project/glpi#12333] opened 2022-07-29 10:48 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.2

### Bug description

Requesters'elements don't show when adding a ticket at his name as requester. 

### Steps To reproduce

Add New Ticket
Add Requester
A new menu should be shown on Element : My Element after adding the requester, so we had to search manually his elements

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.2 (/glpi10 => /var/www/html/glpi10)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux pvtprod0100 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at it.pivotworks.org Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.3-MariaDB-1:10.7.3+maria~bullseye
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi10@localhost/glpi10
	Host info: Localhost via UNIX socket
	
PHP version (7.4.28) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.3) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi10/files/_cache has been validated.
Write access to /var/www/html/glpi10/config has been validated.
Write access to /var/www/html/glpi10/files/_cron has been validated.
Write access to /var/www/html/glpi10/files has been validated.
Write access to /var/www/html/glpi10/files/_dumps has been validated.
Write access to /var/www/html/glpi10/files/_graphs has been validated.
Write access to /var/www/html/glpi10/files/_lock has been validated.
Write access to /var/www/html/glpi10/files/_pictures has been validated.
Write access to /var/www/html/glpi10/files/_plugins has been validated.
Write access to /var/www/html/glpi10/files/_rss has been validated.
Write access to /var/www/html/glpi10/files/_sessions has been validated.
Write access to /var/www/html/glpi10/files/_tmp has been validated.
Write access to /var/www/html/glpi10/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi10/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi10
GLPI_CONFIG_DIR: /var/www/html/glpi10/config
GLPI_VAR_DIR: /var/www/html/glpi10/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi10/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi10/files
GLPI_CACHE_DIR: /var/www/html/glpi10/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi10/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi10/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi10/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi10/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi10/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi10/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi10/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi10/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi10/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi10/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi10/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi10/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi10/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi10/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi10/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi10/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi10/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi10/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi10/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi10/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi10/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi10/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi10/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi10/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi10/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi10/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi10/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi10/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi10/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi10/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi10/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi10/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi10/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi10/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi10/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi10/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi10/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi10/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi10/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi10/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi10/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi10/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi10/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi10/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi10/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi10/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi10/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi10/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi10/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi10/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi10/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi10/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi10/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi10/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi10/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi10/vendor/symfony/polyfill-php81)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (noreply.it@pivotworks.org@smtp.gmail.com)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.16.0     State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.0.4      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Gestion d'objets               Version: 2.12.1     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.3      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.0      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

### Anything else?

The problem : 
![ticket1](https://user-images.githubusercontent.com/54265953/181743167-18954c6e-6fef-4789-9347-4d2e22ed7028.png)

The menu is showing after creating ticket 

![ticket2](https://user-images.githubusercontent.com/54265953/181743339-04c97df1-5117-428f-b922-1ae867b988c9.png)

**Comment by cconard96** [comment] 2022-07-29 10:52
Duplicate of #11646

**Closed by cconard96** 2022-07-29 10:52 UTC
