### ISSUE TITLE
Re-size image when attaching Document to Tickets

### ISSUE THREAD

**Issue by gromka** [glpi-project/glpi#7248] opened 2020-05-08 20:25 UTC
Dear developers

Please draw your attention to the problem. glpi ver 9.4.6

The attached photo (screenshot) of the ticket, when sent by e-mail to the task director, observer and all other ticket participants, is compressed to a size of 400x300 pixels, which is extremely small.

Here is the original screenshot that I (as a technician) put in a comment ticket https://yadi.sk/i/SDT0fQHnw-rouw

And here is the picture that eventually came in a letter to the creator of the application https://yadi.sk/d/Bm8QAEscWoSX6g

As you can see, it is impossible to read anything.

At the same time, the original picture is stored in the ticket on the glpi portal, but our glpi is configured to accept applications through the mail receiver and users on the glpi portal are not registered and do not track tickets, all discussion is conducted only through the mail receiver and comments.

Such compression creates great difficulties for embedding images.

We found that the resolution to which the attachments are compressed is encoded in the file /inc/document.class.php on line 1606 and 1607

```
$ mwidth = 400;
$ mheight = 300;
```

Dear developers. Please enable disabling compression of embedded images from the settings menu of the portal glpi or at least change these values ​​without interfering with your source codes.

Thank!

**Comment by cedric-anne** [comment] 2020-06-18 13:54
Hi,

Although it may be interesting for many usages, such an improvement is not in our roadmap for now. If you want to sponsor this feature, feel free to contact us at contact@teclib.com.

I close this issue as it is not a bug. You can open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).

Duplicates #6739.

Regards

**Closed by cedric-anne** 2020-06-18 13:54 UTC

**Comment by RAurelian** [comment] 2020-12-07 08:34
Hello,

We`ve just started using GLPI and were flabbergasted by this issue. I am sorry, but this NOT a feature or normal behavior - the normal behavior would be to no do anything with the images. We do not really use the GLPI web interface - for most tickets email is sufficient, but in GLPI all images are compressed beyond recognition - it`s impossible to read anything on them.

We have used several other Helpdesk solutions and none had this issue. We get in the mail exactly what the user attached.

Please reconsider and disable this compressing of images and then you can add it as a toggle-able features for those that want it.

**Comment by berils** [comment] 2024-06-21 06:48
Facing simillar issue. If i want to deliver information through attachment, it criples image and its not possible. There should be an general option for not compressing attachments at all.
