### ISSUE TITLE
Problems with Notifications by e-mail | Can't get DB lock

### ISSUE THREAD

**Issue by ajjmoraes** [glpi-project/glpi#15046] opened 2023-06-29 21:18 UTC
Hi,

I'm facing this problem when sending email alerts in GLPI version 10.0.7. I have already carried out all possible checks, the environment is properly configured, however the emails are not sent.

When opening the Cron log, I see these messages occurring all the time:

Could you give me a tip on how to solve this problem, please?

Could not acquire DB lock
2023-06-29 18:05:02 [@LPI-SRV-GLPI]
External #1: Execute contract
2023-06-29 18:05:51 [2@LPI-SRV-GLPI]
Internal #1: Run temp
2023-06-29 18:06:01 [@LPI-SRV-GLPI]
Could not acquire DB lock
2023-06-29 18:06:01 [@LPI-SRV-GLPI]
Could not acquire DB lock
2023-06-29 18:06:01 [@LPI-SRV-GLPI]
External #1: Run mailgate
2023-06-29 18:06:01 [@LPI-SRV-GLPI]
Could not acquire DB lock
2023-06-29 18:07:01 [@LPI-SRV-GLPI]
External #1: Run mailgate
2023-06-29 18:07:01 [@LPI-SRV-GLPI]
Could not acquire DB lock
2023-06-29 18:07:01 [@LPI-SRV-GLPI]
Could not acquire DB lock
2023-06-29 18:07:01 [@LPI-SRV-GLPI]
External #1: Execute contract

_Originally posted by @cedric-anne in https://github.com/glpi-project/glpi/issues/7327#issuecomment-638888448_

**Comment by cedric-anne** [comment] 2023-06-30 06:07
Hi,

`Could not acquire DB lock` probably means that there is already another instance of GLPI `cron.php` script that is processing automatic actions. As you can see, once lock is released, next tasks are executed.

I close this issue as it is not a bug.

**Closed** 2023-06-30 06:08 UTC
Labels: support

**Comment by ajjmoraes** [comment] 2023-06-30 13:49
Hello,
I don't understand why the case was closed, see that the same problem has already been reported as a bug in a previous case, which did not have a solution, so I believe it could be a system bug and not a configuration failure. Can you help me?

https://github.com/glpi-project/glpi/issues/7327#issuecomment-638888448

**Comment by cedric-anne** [comment] 2023-06-30 14:14
All the following entries correspond to a cron task execution, so the GLPI cron system seems to works.

```
2023-06-29 18:05:02 [@LPI-SRV-GLPI]
External #1: Execute contract
2023-06-29 18:05:51 [2@LPI-SRV-GLPI]
Internal #1: Run temp
2023-06-29 18:06:01 [@LPI-SRV-GLPI]
External #1: Run mailgate
2023-06-29 18:07:01 [@LPI-SRV-GLPI]
External #1: Run mailgate
2023-06-29 18:07:01 [@LPI-SRV-GLPI]
External #1: Execute contract
```

`Could not acquire DB lock` just indicates that one of the `front/cron.php` execution was skipped because another concurrent execution was detected. This is not a bug.

**Comment by cedric-anne** [comment] 2023-06-30 14:16
Also, you did not provide most of requested information in the [bug report form](https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&projects=&template=bug_report.yml), so with the only few information we have, we consider that there is no proof of any bug.
