### ISSUE TITLE
GLPI 10.0.8 - Images are not added in templates

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi#15170] opened 2023-07-08 15:04 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.8

### Bug description

I created templates for solution and follow up in 9.x versions, adding texts and images.

When I add the solution or follow up to the ticket, the image appears.

![image](https://github.com/glpi-project/glpi/assets/57845086/1b3a217b-47b5-415b-9767-da0f6254e0d7)

Now, in versions 10.x, when I go to edit the follow up record, the image is not visible, even in the source code there is no link related to the image.

![image](https://github.com/glpi-project/glpi/assets/57845086/4234308d-f944-41dc-8777-3639d1bf8425)

I can no longer paste images.

**Comment by cedric-anne** [comment] 2023-07-10 06:43
Hi,

This feature was not supposed to be enabled, see #14137.

Explaination is simple. When there are images in templates, they are not copied in the new item context. People with rights to see all documents will be able to see them, but images will not be attached in notifications and will not be viewable by people that have limited rights.

I will close this issue as this is not a bug, but a missing feature.

**Closed** 2023-07-10 07:01 UTC
Labels: feature suggestion
