### ISSUE TITLE
License Budget

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1357] opened 2016-11-28 13:17 UTC
Hello 

Is it possible to add a column in license view (licenses users) with Group, allowing to separate license by group

Thank you

**Comment by AnaelMobilia** [comment] 2016-12-30 16:41
@satyan01 
Hi,
Isn't this issue a duplicate of #1397  ?

If yes, could you, please, close it ?
Else, give more details on the differences ;-)

**Comment by trasher** [comment] 2017-01-10 08:02
See #1397

**Closed by trasher** 2017-01-10 08:02 UTC
