### ISSUE TITLE
[9.5] Impact analysis

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#6677] opened 2019-12-05 13:37 UTC
I begin to test Impact analysis with multiples plugins : 
But i have 2 problems : 

I cannot add 2 (or more) plugins to $CFG_GLPI["impact_asset_types"].

For test : I add into my setup.php : 
$CFG_GLPI['impact_asset_types']['PluginDatabasesDatabase'] = "plugins/databases/databases.png";
$CFG_GLPI['impact_asset_types']['PluginWebapplicationsWebapplication'] = "plugins/webapplications/webapplications.png";

For resolve it temporarily i add into inc/define.php

```
$CFG_GLPI["impact_asset_types"]  = [
   'Computer'         => "pics/impact/computer.png",
   'Monitor'          => "pics/impact/monitor.png",
   'NetworkEquipment' => "pics/impact/networkequipment.png",
   'Peripheral'       => "pics/impact/peripheral.png",
   'Phone'            => "pics/impact/phone.png",
   'Printer'          => "pics/impact/printer.png",
   'Software'         => "pics/impact/software.png",
   'DCRoom'           => "pics/impact/dcroom.png",
   'Rack'             => "pics/impact/rack.png",
   'Enclosure'        => "pics/impact/enclosure.png",
   'PluginWebapplicationsWebapplication'        => "plugins/webapplications/webapplications.png",

];
```

Second problem : 
On display : 

![image](https://user-images.githubusercontent.com/13178158/70239987-ab88d680-176c-11ea-87e1-c88e9ec8f88d.png)

The name of plugins are not loaded

**Comment by AdrienClairembault** [comment] 2019-12-05 14:46
Thanks for your feedback.

1\) What is the exact issue when you enable these two classes ?
I guess the second one (WebApplication) doesn't work so that's why you had to put it in define.php ?
I just tried with your two plugins, adding Database and WebApplication to the impact config in their setup and it works fine.
Could it be that you forgot to declare the global $CFG_GLPI in the setup of WebApplication ?


2\) Will be fixed by https://github.com/glpi-project/glpi/pull/6664/commits/7caf30484903b51bcd17a8bf263d2f84b5bd67c7 in pull request #6664.

**Comment by tsmr** [comment] 2019-12-05 18:38
You're right. All is corrected.

Another problem found : 

![image](https://user-images.githubusercontent.com/13178158/70263449-a93b7200-1796-11ea-9563-8c3bc72b904e.png)


![image](https://user-images.githubusercontent.com/13178158/70263432-9cb71980-1796-11ea-80d2-480145301ced.png)


To correct : 
```
@@ -816,7 +816,7 @@ class Impact extends CommonGLPI {
             $icon = "pics/impact/default.png";
          }
 
-         echo '<h4><img class="impact-side-icon" src="/../' . $icon . '" title="' . $itemtype::getTypeName() . '" data-itemtype="' . $itemtype . '">';
+         echo '<h4><img class="impact-side-icon" src="'.$CFG_GLPI["root_doc"].'/' . $icon . '" title="' . $itemtype::getTypeName() . '" data-itemtype="' . $itemtype . '">';
          echo "<span>" . $itemtype::getTypeName() . "</span></h4>";
          echo '</div>'; // impact-side-filter-itemtypes-item
       }
```

**Comment by AdrienClairembault** [comment] 2019-12-06 13:53
Thanks, will be fixed in the same PR.

**Comment by tsmr** [comment] 2020-03-17 14:59
> You're right. All is corrected.
> 
> Another problem found :
> 
> ![image](https://user-images.githubusercontent.com/13178158/70263449-a93b7200-1796-11ea-9563-8c3bc72b904e.png)
> 
> ![image](https://user-images.githubusercontent.com/13178158/70263432-9cb71980-1796-11ea-80d2-480145301ced.png)
> 
> To correct :
> 
> ```
> @@ -816,7 +816,7 @@ class Impact extends CommonGLPI {
>              $icon = "pics/impact/default.png";
>           }
>  
> -         echo '<h4><img class="impact-side-icon" src="/../' . $icon . '" title="' . $itemtype::getTypeName() . '" data-itemtype="' . $itemtype . '">';
> +         echo '<h4><img class="impact-side-icon" src="'.$CFG_GLPI["root_doc"].'/' . $icon . '" title="' . $itemtype::getTypeName() . '" data-itemtype="' . $itemtype . '">';
>           echo "<span>" . $itemtype::getTypeName() . "</span></h4>";
>           echo '</div>'; // impact-side-filter-itemtypes-item
>        }
> ```

I still have the worry

> Thanks, will be fixed in the same PR.

I still have the worry

**Comment by AdrienClairembault** [comment] 2020-03-19 08:08
You mean this is still broken on your side ? I'm not able to reproduce it on my end.

**Comment by tsmr** [comment] 2020-03-19 08:20
Yes. My github is up to date & i still modify with :

```
@@ -816,7 +816,7 @@ class Impact extends CommonGLPI {
             $icon = "pics/impact/default.png";
          }
 
-         echo '<h4><img class="impact-side-icon" src="/../' . $icon . '" title="' . $itemtype::getTypeName() . '" data-itemtype="' . $itemtype . '">';
+         echo '<h4><img class="impact-side-icon" src="'.$CFG_GLPI["root_doc"].'/' . $icon . '" title="' . $itemtype::getTypeName() . '" data-itemtype="' . $itemtype . '">';
          echo "<span>" . $itemtype::getTypeName() . "</span></h4>";
          echo '</div>'; // impact-side-filter-itemtypes-item
       }
```

**Comment by AdrienClairembault** [comment] 2020-03-23 08:16
The line
```php
echo '<h4><img class="impact-side-icon" src="/../' . $icon . '" title="' . $itemtype::getTypeName() . '" data-itemtype="' . $itemtype . '">';
``` 
has already been modified, maybe some cache issue on your side ?
If not can you paste here a copy of one img's src tag in the generated HTML code ?

**Comment by tsmr** [comment] 2020-03-23 13:21
Hum

https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/impact.class.php#L934

You must add root_doc, no ?
src="'.$CFG_GLPI["root_doc"].'/' . $icon . '

**Comment by AdrienClairembault** [comment] 2020-03-23 15:22
Unless I'm missing something, this would not change anything (../ is the root doc in this context).
What URL are you on and what is the generated src tag ?

**Comment by tsmr** [comment] 2020-03-23 18:12
In fact. I use impact Tab on my plugin : 
And the errors are here because it search icons on my plugin

![image](https://user-images.githubusercontent.com/13178158/77348553-f2a9d000-6d39-11ea-91a4-403372c434fb.png)

**Closed** 2020-03-24 08:08 UTC
