### ISSUE TITLE
GLPI Update 9.3.0 to 9.4.0 failed - update base de données bloqué à mise à jour en 9.4

### ISSUE THREAD

**Issue by GuillaumeBie** [glpi-project/glpi#5731] opened 2019-04-02 14:35 UTC
bonjour, 

je ne parviens pas à mettre à jour mon installation de GLPI actuellement en 9.3.3 vers la 9.4 ni vers la 9.4.1.

le processus de mise à jour de la base GLPI reste comme figé sur traitement en cours ...

dans les logs, je peux voir :
```
##certificate.url##
 ##ENDFOREACHcertificates##','&lt;p&gt;
##lang.certificate.entity## : ##certificate.entity##&lt;br /&gt;
##FOREACHcertificates##
&lt;br /&gt;##lang.certificate.name## : ##certificate.name##&lt;br /&gt;

  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''&lt;p&gt;
##lang.certificate.entity## : ##certificate.entity##&lt;br /&gt;
##FO' at line 1
  Backtrace :
  front/backup.php:259                               
  front/backup.php:536                               restoreMySqlDump()
  {"user":"2@server","mem_usage":"0.000\", 2.09Mio)"} 
[2019-04-02 13:53:49] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: INSERT INTO `glpi_notificationtemplatetranslations` VALUES ('25','25','','##certificate.action##  ##certificate.entity##','##lang.certificate.entity## : ##certificate.entity##

##FOREACHcertificates##

##lang.certificate.serial## : ##certificate.serial##

##lang.certificate.expirationdate## : ##certificate.expirationdate##

##certificate.url##
 ##ENDFOREACHcertificates##','&lt;p&gt;
##lang.certificate.entity## : ##certificate.entity##&lt;br /&gt;
##FOREACHcertificates##
&lt;br /&gt;##lang.certificate.name## : ##certificate.name##&lt;br /&gt;
##lang.certificate.serial## : ##certificate.serial##&lt;br /&gt;

  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''&lt;p&gt;
##lang.certificate.entity## : ##certificate.entity##&lt;br /&gt;
##FO' at line 1
  Backtrace :
  front/backup.php:259                               
  front/backup.php:536                               restoreMySqlDump()
  {"user":"2@server","mem_usage":"0.000\", 2.09Mio)"} 

```
avez-vous une idée?
j'ai oublié, je suis en ubuntu 18.04.2.

cordialement,
![Capture](https://user-images.githubusercontent.com/49200632/55411072-40478e80-5565-11e9-9b8b-f151a8e42408.PNG)

**Comment by cedric-anne** [comment] 2019-04-04 07:41
Hi,

In your logs, error is not related to the update process but to the backup process (`front/backup.php:536                               restoreMySqlDump()`).

Can you try to update using the CLI tool in verbose mode (i.e. `php bin/console db:update -vvv`) ? 

Regards

**Comment by GuillaumeBie** [comment] 2019-04-04 07:58
Hi,

Thanks for your help.
I try your solution, but it don't works.
In atachement, the result of php bin/console db:update -vvv.

Regards,

sorry for my english ^^

**Comment by cedric-anne** [comment] 2019-04-04 08:16
I think the problem is that you restore a 9.3.x backup on a 9.4.x database. Doing this, you have a mix of 9.3.x and 9.4.x schema in your database that makes update process not working.

If you have a mysql dump of tyour database prior to update: remove all tables from your db, restore your dump, and launch the update command.

If you do not have a mysql dump, try to delete `glpi_itils_projects` and `glpi_itilfollowups` tables and run the command again, but as I do not know how the backup tool works, I am not sure it will work as excpected.

**Comment by trasher** [comment] 2019-04-04 08:19
Embed GLPI backup is very poor and is not a way to get a safe backup of an instance, use mysqldump.

**Comment by GuillaumeBie** [comment] 2019-04-04 10:05
Hi,

Thanks for your help.

@cedric-anne your solution is good, my glpi instance is now in version 9.4.0.
the delete of glpi_itils_projects and glpi_itilfollowups tables allowed the migration.

@trasher i note your recommandation for use mysqldump for the futur.

regards,

**Comment by trasher** [comment] 2019-04-04 10:15
Please note that several secirity issues has been fixed in 9.4.1.1, you should update quicjly. 9.4.2 will be out soon also to fix several quite big issues.

**Closed by trasher** 2019-04-04 10:15 UTC
Labels: Need feedback

**Comment by h3ct0rjs** [comment] 2019-04-09 01:47
Hi @trasher, I was checking multiple issues on the project, I was wondering if the verbose flag is enable in 9.3.3 glpi currently I'm in version GLPI 9.1.1, I don't know if is it possible to update to 9.4 using the latest version. 

Thank you very much if you can answer my question. 
Sincerely, 
_**H**_

**Comment by eckorion** [comment] 2021-06-08 07:18
Bonjour,
Pour information j'ai rencontré le même problème en passant de 9.3.3 en 9.5.5
J'ai procédé comme indiqué et ça a parfaitement fonctionné.
Je suis parti d'une base de test qui refusait de migrer. Chaque essai je suis reparti d'une restauration et non pas d'une migration échouée.
J'ai également été confronté à des souci sur la table (nombreuses erreurs sql) où j'ai de supprimer des colonnes comme indiqué sur l'issue #5359:
GLPI Update 9.3.0 to 9.4.0 failed - Incorrect key file for table'glpi_itils_projects' #5359
Tout fonctionne parfaitement à présent
