### ISSUE TITLE
MySQL "fetch_assoc() on a non-object" error

### ISSUE THREAD

**Issue by vanomel** [glpi-project/glpi#658] opened 2016-05-18 17:05 UTC
Ticket form freezes at loading. 

Web server log:
`PHP Fatal error:  Call to a member function fetch_assoc() on a non-object in /var/www/html/glpi/inc/dbmysql.class.php on line 280, referer: http://{serverIP}/glpi/front/ticket.form.php?id=5`
Server configuration
```
GLPI 0.90.3 (/glpi => /var/www/html/glpi)

Server
 
Operating system: Linux host.name 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, json, ldap, libxml, mbstring, mhash, mysql, mysqli,
	openssl, pcre, pdo_mysql, pdo_sqlite, session, shmop, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlwriter,
	xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/5.4.16 ()
	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.12
	Server SQL Mode: ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.
OKSELinux mode is Permissive
OKSELinux boolean configuration for httpd_can_network_connect --> on
OKSELinux boolean configuration for httpd_can_network_connect_db --> on
Some features may require this to be onSELinux boolean configuration for httpd_can_sendmail --> off (Some features may require this to be on)

Libraries
 
htmLawed version 1.1.21 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/html/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/html/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/html/glpi/lib/Zend)
SimplePie version 1.3.1 in (/var/www/html/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/html/glpi/lib/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi/lib/password_compat). Compatitility: Ok

Mysql replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	fusioninventory      Name: FusionInventory                Version: 0.90+1.2   State: Enabled
```

**Comment by remicollet** [comment] 2016-05-18 17:47
MySQL is not yet supported, 
Duplicate of #627

**Closed by remicollet** 2016-05-18 17:47 UTC

**Comment by remicollet** [comment] 2016-05-18 17:58
Notice: as you are using RHEL or CentOS 7, MariaDB 5.5 provided in the distribution repositories works perfectly with GLPI.
