### ISSUE TITLE
[GLPI 10] calendar picker idle

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#10437] opened 2022-01-25 19:12 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master (25.01.2022)

### Bug description

In all categories the calendar picker is out of order.
Nothing happens when you click the calendar icon or the date field. 
![grafik](https://user-images.githubusercontent.com/8606735/151043366-f2a85275-4085-4a80-b9ff-b978c6e4f6b1.png)

### Your GLPI setup information
Arch Linux
PHP 8.0 or 8.1
Apache/2.4.52 & 10.6.5-MariaDB

**Comment by cconard96** [comment] 2022-01-25 19:35
Please include more details about the issue. Are you saying that the picker doesn't work anywhere in GLPI?

Do you have any errors in your browser's console (F12 key and then the console tab)?

**Comment by husisusi** [comment] 2022-01-25 19:49
Yes, picker doesn't work anywhere in GLPI.
Yes, a lot of errors in your browser's console.
![grafik](https://user-images.githubusercontent.com/8606735/151048800-990fc58a-bfa8-44ad-b0b4-a929f23e87fe.png)

**Comment by husisusi** [comment] 2022-01-28 21:52
The problem is "bin/console dependencies install" (npm update)
If I replace "public/lib/base.js" with the old one, everything works.

**Comment by cedric-anne** [comment] 2022-01-31 07:37
> The problem is "bin/console dependencies install" (npm update) If I replace "public/lib/base.js" with the old one, everything works.

The old one works only because the code that bugs was not existing in your previous version, but it does not mean that the `bin/console dependencies install` is the problem.

**Comment by cconard96** [comment] 2022-02-02 00:27
I cannot recreate the issue with the latest master commit. When running `bin/console dependencies install` or `npm run build` are there any warnings/errors shown?

**Comment by trasher** [comment] 2022-02-02 08:03
Like Curtis, I cannot reproduce - and I run the dependencies command quite often.

The dependencies install command is part of the development process, for testing, it's better to rely on nightly builds, with pre-built files like in the official release archive. It seems to me the easier way to go.

I close this one for now, please try with latest master branch (or switch to nightlies) - and feel free to reopen if you still have an issue.

**Closed by trasher** 2022-02-02 08:03 UTC
Labels: beta

**Comment by husisusi** [comment] 2022-02-02 08:30
The latest master branch has now no issue.
Calendar picker works.
