### ISSUE TITLE
[9.3.1] "Notifications for my changes" overriden by mail follow-up

### ISSUE THREAD

**Issue by openseatecnologia** [glpi-project/glpi#4643] opened 2018-09-14 16:43 UTC
* Steps to reproduce (which actions have you made) :
Select "No" in "Notifications for my changes"

* Expected result :
Expect to not be notified about your own follow-ups in a ticket

* Actual result :
If the follow-up is done by mail, you do receive the notification

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
 Operating system: Linux glpi 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
PHP 5.6.35 cgi-fcgi (Core, PDO, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, cgi-fcgi, ctype, curl, date, dom, ereg,
	fileinfo, filter, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mysql, mysqli, mysqlnd, pcre, pdo_pgsql,
	pgsql, posix, readline, session, snmp, soap, standard, tokenizer, xml, xmlrpc, xmlwriter, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: lighttpd/1.4.48
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.92 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.1.32-MariaDB
```

**Comment by cedric-anne** [comment] 2018-09-14 17:13
Seems duplicate of https://github.com/glpi-project/glpi/issues/4366.

**Comment by openseasite** [comment] 2018-09-14 18:57
> Seems duplicate of #4366.

I don't know if I should consider duplicate, as I haven't activated "Anonymous ticket creation" and the result is correct if the follow-up is done in the web [I'm not notified about my own follow-up].

**Comment by arthurrschaefer** [comment] 2018-09-17 01:14
Likewise here.
Every time I insert a followup via Web Interface, I don't receive the notification.
If I insert a followup via email (mail collector), I receive an email warning of the insertion.

I don't use **"Anonymous ticket creation"**. The option **"Notifications for My Changes"** is set for **"No"**
The notifications recipients are ok as well.

**Comment by cedric-anne** [comment] 2018-10-11 19:19
The "notification to myself" preference is not working in cron mode due to 2 elements:
 - `$notify_me` is forced to true in cron mode (https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/notificationevent.class.php#L142),
 - check to determines if modification is done by user is comparing values of `users_id` of the targetted user, and the current session id (https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/notificationtarget.class.php#L189).

**Comment by openseatecnologia** [comment] 2018-10-15 14:50
> The "notification to myself" preference is not working in cron mode due to 2 elements:
> 
> * `$notify_me` is forced to true in cron mode (https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/notificationevent.class.php#L142),
> * check to determines if modification is done by user is comparing values of `users_id` of the targetted user, and the current session id (https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/notificationtarget.class.php#L189).

So, hipothetically speaking, if I do set "mailgate" to "Run Mode GLPI", the problem would be solved?

**Comment by cedric-anne** [comment] 2018-10-16 07:42
Hi,

Hypothetically, it will not change anything, as tasks runned in "Mode GLPI" should be considered as runned by "cron".

Regards

**Comment by levifranzen** [comment] 2018-11-26 10:37
Hello,

The bug stills occurs in 9.3.2 and I'ven't deleted the op account, just turned it into organization.

**Comment by Cristian9828** [comment] 2019-06-05 12:26
Same problem here.
I use 9.3.4 version. When I send an email like a requester, i receive back my own followup notify!
Is there a solution right now? I really need it!

**Comment by Armin83** [comment] 2019-06-06 05:00
@cedric-anne with my old version 9.3.3 the bug occurse in both modes cli and glpi

**Comment by cedric-anne** [comment] 2019-06-06 07:19
Hi,

Bug is a bit hard to fix and requires a lot of rework on technical part of notification system. I did not find  time to work on this bug and I will probably not before some months.

Regards

**Comment by levifranzen** [comment] 2019-09-18 13:41
Is there something we can do to help this get solve? This is like a killer feature for those who work with third-party tickets, like opening a ticket in a partner who uses Zendesk.

**Comment by crewer** [comment] 2020-03-31 15:42
Same issue in version 9.4.5, please work on it, thank you very much!

**Comment by cedric-anne** [comment] 2020-06-04 07:47
Hi,

#7360 should fix your problem.

Can you confirm ?

Regards

**Comment by levifranzen** [comment] 2020-06-04 12:12
Confirmed, the commit [#7360](https://github.com/glpi-project/glpi/pull/7360) fix this.
Thank you!

**Closed** 2020-06-04 12:25 UTC
Labels: bug
