### ISSUE TITLE
[9.1.2] Business rule not processed on ticket when clicked on add myself button

### ISSUE THREAD

**Issue by lcpj** [glpi-project/glpi#1915] opened 2017-03-08 10:38 UTC
Steps to reproduce:

1 - Add a new simple business rules (add/update, does not matter)
2 - Add a criteria "Technician" is "your user"
3 - Add a new action "Assign technician group" to whatever group you need
4 - Go to a ticket and click on "assign myself" button.
5 - Nothing happens

If you go to the ticket but instead of clicking the  assign myself button you do it manually (click on the plus sign, choose User, choose your name, click SAVE at the bottom) the rule is then processed and the desidered group is added to the ticket as well.

**Comment by trasher** [comment] 2017-04-24 06:45
I guess the issue is the same as #2047 ; it has been recently fixed in 9.1/bugfixes branch and will be part of 9.1.3 release.

**Closed by trasher** 2017-04-24 06:45 UTC

**Comment by lcpj** [comment] 2017-07-12 10:37
Not working again in 9.1.4
