### ISSUE TITLE
Content protection issue during import through email collector

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#1862] opened 2017-02-23 15:48 UTC
Hello,

Some ticket replies by email are rejected by GLPI with this SQL error:

*** MySQL query error:
SQL: INSERT
 INTO `glpi_ticketfollowups` (`content`,`tickets_id`,`users_id`,`requesttypes_id`,`is_private`,`date`,`date_creation`,`date_mod`) VALUES (\'Merci, xxxxx plage d\'adresses xxx
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'adresses xxx

Backtrace :
   inc/commondbtm.class.php:436
   inc/commondbtm.class.php:852                       CommonDBTM->addToDB()
   inc/mailcollector.class.php:555                    CommonDBTM->add()
   inc/mailcollector.class.php:1615                   MailCollector->collect()
   :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:88                                  CronTask::launch()

With additional debugging in mailcollector.class.php line 550 :

` // Is a mail responding of an already existing ticket ?`
`                     if (isset($tkt['tickets_id']) ) {`
`                        $fup = new TicketFollowup();`
`                                toolbox::logdebug("Ajout followup", $tkt);`
`                        if ($fup->add($tkt)) {`

Ticket object debug displays:
`[content] => Merci, xxxxx plage d&#39;adresses xxx`

So I think that there is some mess with message encoding. 
In addition, bouncing the rejected mail through MS Outlook, changes it somehow, so it is not rejected anymore.

Thanks.

**Comment by orthagh** [comment] 2017-07-13 07:54
Maybe duplicate of #1264 

I close, feel free to comment anyway.

**Closed by orthagh** 2017-07-13 07:54 UTC
Labels: bug
