### ISSUE TITLE
Acces to user when column number of assigned tickets is VERY slow

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6456] opened 2019-10-10 15:10 UTC
**Describe the bug**
In user (glpi/front/user.php)
When activate the showing of more than 1 column counting number, the time to wait is exponential and the mysqld process is 100% between this time (more than 30 seconds).
When just one column among (Nombre de tickets assignés | nombre de tickets créés | nombre de tickets en tant que demandeur) is immediate .

**To reproduce**
Go to user tab, add those columns (I just have approx 650 users), mysqld is at 100%, querying ...

**Expected behavior**
If one column between among 3 is immediate, why 2 or 3 columns is so long (more than a minute !). 

**Logs**
No errors in logs, just very slow

Context GLPI 9.4.4/Ubuntu

**Comment by mab18** [comment] 2019-10-10 15:26
I think columns "Nombre de tickets assignés" and "Nombre de tickets en tant que demandeur" are quite fast, even together.

**Comment by cedric-anne** [comment] 2019-12-13 14:19
Hi,

Sorry for the late reply.

I just looked at the query made to display these fields and I do not know what can be easilly done on application side to optimize this query as most of relevant fields are already indexed.

Query responsiveness also depends greatly on the aount of data you have on each used tables and how you configured your database.

As this is not a bug, I close this issue. Feel free to ask for support on [community forums](https://forum.glpi-project.org/).

Regards

**Closed by cedric-anne** 2019-12-13 14:19 UTC
