### ISSUE TITLE
All automatic tasks that are part of a plugin show "Disabled Plugin"

### ISSUE THREAD

**Issue by raregtp** [glpi-project/glpi#5710] opened 2019-03-29 05:10 UTC
**Describe the bug**

Any automatic task that is part of a plugin shows "Disabled Plugin" directly above the Status dropdown.

**Page(s) URL**

https://glpi.rei.local/front/crontask.php

**To reproduce**

Open Automatic Actions and select an action from a built in plugin.

**Expected behavior**

Automatic actions should not show the action as "Disabled Plugin" when the associated plugin is in fact enabled.

**Logs**

No errors in logs

**Screenshots**

![image](https://user-images.githubusercontent.com/16689744/55210595-2baa7580-51b6-11e9-85ed-5ba80182a1cc.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

Information about system installation & configuration
--
[code]   GLPI 9.4.2 ( => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux jinx.rei.local 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 PHP 7.3.3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session, shmop, sockets, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.3 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.1.38-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.1.38) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Disabled

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.6 in (/usr/share/pear)

Server: 'ldaps://dc2.rei.local', Port: '636', BaseDN: 'DC=rei,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(memberOf=CN=grpGLPI,OU=GLPI,OU=Groups,OU=Omaha,OU=REI,DC=rei,DC=local)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 		RootDN: 'CN=svc-ldapauth,OU=Service Accounts,OU=*Global,OU=REI,DC=rei,DC=local', Use TLS: none

Not active

Way of sending emails: PHP

 

accounts             Name: Accounts                       Version: 2.5.0      State: Enabled 	fields               Name: Additionnal fields             Version: 1.9.1      State: Enabled 	news                 Name: Alerts                         Version: 1.5.1      State: Enabled 	dashboard            Name: Dashboard                      Version: 0.9.6      State: Enabled 	domains              Name: Domains                        Version: 2.1.0      State: Enabled 	datainjection        Name: File injection                 Version: 2.7.0      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.8.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled 	addressing           Name: IP Adressing                   Version: 2.8.0      State: Enabled 	services             Name: ITIL Services                  Version: 1.0.6      State: Not installed 	mydashboard          Name: My Dashboard                   Version: 1.7.1      State: Enabled 	notifications        Name: Notifications                  Version: 9.4+1.0    State: Enabled 	order                Name: Orders management              Version: 2.4.0      State: Enabled 	physicalinv          Name: Physical inventory             Version: 9.1+1.1    State: Enabled 	pdf                  Name: Print to pdf                   Version: 1.4.0      State: Enabled 	reservation          Name: Reservation                    Version: 2.1.2      State: Enabled 	tasklists            Name: Tasks list                     Version: 1.5.0      State: Enabled 	timelineticket       Name: Timeline of tickets            Version: 9.4+1.0    State: Enabled 	typology             Name: Typologies                     Version: 2.6.0      State: Enabled 	useditemsexport      Name: Used items export              Version: 2.2.0      State: Enabled 	webapplications      Name: Web applications               Version: 2.6.0      State: Enabled
[/code]



```

**Additional context**

This was not happening on 9.4, but started after upgrading to 9.4.1.1.  The nightly tarball was applied in an attempt to resolve.  Also, cron tasks and automatic actions that use CLI mode, including automatic actions from plugins, are actually running as expected, even though they show "Disabled Plugin" and the next run says Disabled.

**Comment by trasher** [comment] 2019-03-29 06:57
Certainly a duplicate of https://github.com/glpi-project/glpi/issues/5637

**Closed by trasher** 2019-03-29 06:57 UTC

**Comment by cedric-anne** [comment] 2019-03-29 11:36
Hi,

I confirm that #5694 should solve this problem.

Regards
