### ISSUE TITLE
[9.4.4] Dicctionary - Software does no changes

### ISSUE THREAD

**Issue by DGermany** [glpi-project/glpi#7470] opened 2020-06-22 10:43 UTC
There's no action if you want to change Softwarecategorie by Softwarename and Manufactuer

Exg.: 
Criteria:  
- Software regular expression matches  /00001Test/
![grafik](https://user-images.githubusercontent.com/30858247/85278608-74b6ab80-b485-11ea-9345-e17c29e76c93.png)

Action: 
-Category ASSIGN app
![grafik](https://user-images.githubusercontent.com/30858247/85278658-84ce8b00-b485-11ea-8795-b0dede0d4542.png)

Result: No changes on Softwareobject. :/ 
![grafik](https://user-images.githubusercontent.com/30858247/85278993-06beb400-b486-11ea-8a70-9dec6ab166c5.png)

**Comment by cedric-anne** [comment] 2020-06-22 11:43
Hi,

I just tried with this rule and it works when I manually add a software.

1. Check that your rule is active.
2. You have a leading space in your criteria value. If software name does not contains this leading space, it will not match.
3. If it still does not work, maybe you should try to upgrade to GLPI 9.4.6 and/or check with plugins disabled.

I close this ticket as I cannot reproduce. If you need communitiy support, please use [forums](https://forum.glpi-project.org/).

If you consider reopening this issue, please fill all informations requested in issue form (i.e. logs, system informations, installed plugins, steps to reproduce the issue, ...).

Regards

**Closed by cedric-anne** 2020-06-22 11:43 UTC
