### ISSUE TITLE
PHP Notice:  Constant GLPI_ROOT already defined

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#226] opened 2015-11-05 09:05 UTC
in .../inc/includes.php on line 38
When opening index.php

https://github.com/glpi-project/glpi/commit/bd76e2426ce5d9ccf40104bdf938d0f3a079c0e1#diff-d0a743c66d90c74b4c7fe9667b7df844R35

we need to review top of index.php or revert this code in includes
```
 if (!defined('GLPI_ROOT')) {
```

**Comment by tsmr** [comment] 2015-11-05 09:07
Same problem on logout & central.php

**Comment by ladenree76000** [comment] 2015-11-05 22:48
same problem on webservices : see :http://forum.glpi-project.org/viewtopic.php?id=130320

**Comment by tsmr** [comment] 2015-11-06 08:05
Same problem
[06-Nov-2015 09:04:14 Europe/Paris] PHP Notice:  Constant GLPI_ROOT already defined in C:\wamp\www\glpi90\inc\includes.php on line 38

**Comment by remicollet** [comment] 2015-11-06 08:15
Full backtrace ?
Line 38 is the fixed one.
Check your git clone.

**Comment by tsmr** [comment] 2015-11-06 08:23
No full backtrace it's on error_log of apache
My master is updated before

**Comment by remicollet** [comment] 2015-11-06 08:24
Can't reproduce, someone else ?

**Comment by tsmr** [comment] 2015-11-06 08:26
Sorry my fault effectivly

**Closed by tsmr** 2015-11-06 08:26 UTC
Labels: task
