### ISSUE TITLE
Undefined array key in logs

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#14754] opened 2023-05-23 07:25 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

We're having lots of the following warnings in the logs but don't know how to address them.
```
[2023-05-23 07:39:17] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "0f1a371ef526b694bc0a05a1f8f90347" in /var/www/glpi/src/Inventory/Asset/InventoryAsset.php at line 442
  Backtrace :
  src/Inventory/Asset/MainAsset.php:851              Glpi\Inventory\Asset\InventoryAsset->handleInput()
  src/Inventory/Asset/NetworkEquipment.php:228       Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\NetworkEquipment->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:575              RuleCollection->processAllRules()
  src/Inventory/Asset/Printer.php:201                Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:710                    Glpi\Inventory\Asset\Printer->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  ...inc/communicationnetworkinventory.class.php:156 Glpi\Inventory\Inventory->doInventory()
  marketplace/glpiinventory/hook.php:1095            PluginGlpiinventoryCommunicationNetworkInventory->import()
  src/Plugin.php:1663                                plugin_glpiinventory_network_inventory()
  src/Inventory/Request.php:278                      Plugin::doHookFunction()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
```

### Steps To reproduce

We don't know.

**Comment by trasher** [comment] 2023-05-23 07:40
Last errors of this kind were due to something "wrong" in inventory files (like unbrakable spaces in soft/manufavcturers names).
You may try with current 10.0/bugfixes nightly build to see if you reproduce.

**Comment by trasher** [comment] 2023-05-30 07:53
No feedback, closing.

**Closed by trasher** 2023-05-30 07:53 UTC
Labels: Need feedback
