### ISSUE TITLE
[9.1.2] global bookmark error 

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1861] opened 2017-02-23 15:02 UTC
I crated a global bookmark on 9.1.2.
I want to load this bookmark and get and error. "translated" it could not be all loaded.

> 2017-02-23 15:58:54 [6@myhostname01]
  *** PHP Notice(8): Undefined offset: -1
  Backtrace :
  inc/search.class.php:5461
  inc/search.class.php:5188                          Search::getOptions()
  inc/bookmark.class.php:402                         Search::getCleanedOptions()
  inc/bookmark.class.php:495                         Bookmark->prepareQueryToUse()
  inc/bookmark.class.php:467                         Bookmark->getParameters()
  front/bookmark.php:97                              Bookmark->load()
2017-02-23 15:58:54 [6@myhostname01]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc/search.class.php:5461
  inc/search.class.php:5188                          Search::getOptions()
  inc/bookmark.class.php:402                         Search::getCleanedOptions()
  inc/bookmark.class.php:495                         Bookmark->prepareQueryToUse()
  inc/bookmark.class.php:467                         Bookmark->getParameters()
  front/bookmark.php:97                              Bookmark->load()
2017-02-23 15:59:06 [6@myhostname01]
  *** PHP Notice(8): Undefined offset: -1
  Backtrace :
  inc/search.class.php:5461
  inc/search.class.php:5188                          Search::getOptions()
  inc/bookmark.class.php:402                         Search::getCleanedOptions()
  inc/bookmark.class.php:495                         Bookmark->prepareQueryToUse()
  inc/bookmark.class.php:467                         Bookmark->getParameters()
  front/bookmark.php:97                              Bookmark->load()
2017-02-23 15:59:06 [6@myhostname01]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc/search.class.php:5461
  inc/search.class.php:5188                          Search::getOptions()
  inc/bookmark.class.php:402                         Search::getCleanedOptions()
  inc/bookmark.class.php:495                         Bookmark->prepareQueryToUse()
  inc/bookmark.class.php:467                         Bookmark->getParameters()
  front/bookmark.php:97                              Bookmark->load()

**Comment by trasher** [comment] 2017-03-31 10:16
I cannot reproduce with the actual 9.1/bugfixes. Could you take a try with this branch and see if your issue was solved?

I'm closing for now, feel free to reopen if issue persists.

**Closed by trasher** 2017-03-31 10:16 UTC
Labels: bug
