### ISSUE TITLE
legacy API, partial content queries return 200 instead of 206

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#17940] opened 2024-09-26 08:37 UTC
Due to the public router and `ApiRestController` returning a ` StreamedResponse`  with default return code
While I found quickly a way to dirty fix that, I may want to ask why the current set of web tests are not detecting that. we have return code checking in our suite.

**Comment by cedric-anne** [comment] 2024-09-26 13:32
I am not able to reproduce the issue on an Apache+mod_php env. If I change the expected status code in tests, they are correctly failing.
Maybe the issue appears with a different configuration due to a different behaviour when 2 distincts http code are sent. Maybe with Apache+mod_php only the first one is accepted and with nginx+php-fpm the last value overrides the previous values.

**Comment by Pierstoval** [comment] 2024-10-02 13:12
I'm not sure how to reproduce the issue either, but there is indeed a general problem in the sense that now the sending of HTTP headers and HTTP response are separate from each other.

The solution is to enforce using the `http_response_code(...)` PHP function **before** sending ANY content.

That's the main problem with GLPI: sending headers and content are intertwined in PHP files, code and classes, and it's hard to untangle. Wrapping it in the Kernel definitely showed the issue 😅

Do you have a particular method to reproduce the error @orthagh?

**Comment by orthagh** [comment] 2024-10-02 13:13
nginx+php-fpm I guess

**Comment by cedric-anne** [comment] 2024-10-03 12:45
It is a known bug. We have to find how to handle this on our side.

https://bugs.php.net/bug.php?id=81451
https://stackoverflow.com/a/69213593

**Comment by cedric-anne** [comment] 2024-10-08 09:32
Fixed by #18014.

**Closed by cedric-anne** 2024-10-08 09:32 UTC
Labels: beta, api

**Comment by gdespres-solocal** [comment] 2024-11-14 13:43
Is it really a patch version ? Since 10.0.17, all partial content return 206 instead of 200 in the "Get sub items" api.
The semver is not respected and it's not compatible with several api client like python-glpi-api (https://github.com/unistra/python-glpi-api).

The API documentation is not up-to-date (https://<glpi>/apirest.php#get-sub-items)

**Comment by trasher** [comment] 2024-11-14 13:55
Issue was about GLPI 11, not GLPI 10. Please do not comment on closed issues; and open tickets only for bugs.
