### ISSUE TITLE
10.0.x - no info about object name

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#11959] opened 2022-06-21 12:21 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

I'm not sure if it's a bug or the design idea, but it does limit functionality.

In version 9, all tabs showed the name of the object. In version 10 - only the primary. 
I can change objects using the navigation buttons, but I don't know what object I am browsing at the moment. So I have to click on the primary tab every time and come back to the one I am checking.

For example "Operating systems" tab for Computer (9.x version):
![image](https://user-images.githubusercontent.com/68922721/174780009-e490cbf6-1517-4f47-ac5c-a04ccd87dcc4.png)

The same tab for 10.x version:"
![image](https://user-images.githubusercontent.com/68922721/174779701-a8174034-2018-4c0b-aca5-6b71205c3341.png)

This problem occurs everywhere. For example: marketplace/glpiinventory/front/iprange.php  "Associated SNMP credentials" tab too.

### Page URL

front/computer.form.php?id=1

### Steps To reproduce

1. Open the computer asset
2. Change the tab e.g.  -  "Documents"
3. There is no computer name.

**Comment by cconard96** [comment] 2022-06-21 13:09
Duplicate of #11493.

**Closed by cconard96** 2022-06-21 13:09 UTC
