### ISSUE TITLE
display licence in search engine

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2643] opened 2017-08-24 15:43 UTC
http://forum.glpi-project.org/viewtopic.php?id=158682

I don't understand why licence name is added for serial, otherserial and comment of a licence and not for all fields.
If you want the licence's name you can add it in search request

**Comment by yllen** [comment] 2017-08-24 18:05
http://forum.glpi-project.org/viewtopic.php?id=158695

**Comment by AnaelMobilia** [comment] 2017-11-26 23:50
Duplicate of #426
Fix on PR #3208

**Closed** 2017-11-27 07:12 UTC
Labels: duplicate
