### ISSUE TITLE
Change the size of an image in email

### ISSUE THREAD

**Issue by bltsv** [glpi-project/glpi#6739] opened 2019-12-27 14:11 UTC
Hi. Is it possible to change the size of an image which i received via email? In the web i can see the image in FullHD, but in email the image in low resolution and quality.

**Comment by cedric-anne** [comment] 2020-01-23 15:58
Hi,

As images are embedded in email, it is intentionnal to keep them small, in order to not send huge emails. For now, max image size is 400x300. Maybe it can be changed to something less small, but sending them in full HD seems not a good idea.

Regards

**Comment by bltsv** [comment] 2020-01-24 08:04
> Hi,
> 
> As images are embedded in email, it is intentionnal to keep them small, in order to not send huge emails. For now, max image size is 400x300. Maybe it can be changed to something less small, but sending them in full HD seems not a good idea.
> 
> Regards

Hi, thanks for reply.
Is it possible to create a setting to control possible image sizes?
For example, the default value will be 400x300, but if necessary, you can change to the required size.

**Comment by bltsv** [comment] 2020-01-31 07:25
For example, in our organization, all departments except IT don't use the GLPI web interface and all communication goes through the mail, when someone writes and applies an image to us, it is so compressed that it is impossible to understand the essence of the picture, it also turns out the other way round when we respond to the employee and attach the image, the employee cannot see the text in the picture.

**Comment by cedric-anne** [comment] 2020-01-31 08:17
Hi,

Although it may be interesting for many usages, such an improvement is not in our roadmap for now. If you want to sponsor this feature, feel free to contact us at contact@teclib.com.

I close this issue as it is not a bug. You can open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).

Regards

**Closed by cedric-anne** 2020-01-31 08:17 UTC

**Comment by RAurelian** [comment] 2020-12-07 08:33
Hello,

We`ve just started using GLPI and were flabbergasted by this issue. I am sorry, but this NOT a feature or normal behavior - the normal behavior would be to no do anything with the images. We do not really use the GLPI web interface - for most tickets email is sufficient, but in GLPI all images are compressed beyond recognition - it`s impossible to read anything on them.

We have used several other Helpdesk solutions and none had this issue. We get in the mail exactly what the user attached.

Please reconsider and disable this compressing of images and then you can add it as a toggle-able features for those that want it.

**Comment by bltsv** [comment] 2020-12-07 08:43
> Hello,
> 
> We've just started using GLPI and were flabbergasted by this issue. I am sorry, but this NOT a feature or normal behavior - the normal behavior would be to no do anything with the images. We do not really use the GLPI web interface - for most tickets email is sufficient, but in GLPI all images are compressed beyond recognition - it's impossible to read anything on them.
> 
> We have used several other Helpdesk solutions and none had this issue. We get in the mail exactly what the user attached.
> 
> Please reconsider and disable this compressing of images and then you can add it as a toggle-able features for those that want it.

My ticket in GLPi feature request service:
https://glpi.userecho.com/ru/communities/1/topics/1784-change-the-size-of-an-image-in-email
