### ISSUE TITLE
Computer Search tab buggy when filtering Antivirus

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#16246] opened 2023-12-27 11:39 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

I'm trying to find Windows 10 computers that **don't have** Bitdefender Antivirus:

![image](https://github.com/glpi-project/glpi/assets/8606735/e07dee1e-1d63-43f7-94f2-4b538d78ced5)

![image](https://github.com/glpi-project/glpi/assets/8606735/655b48cc-5a01-4469-9f0e-1a052f5e8416)

But the filter doesn't work, many machines with Bitdefender are listed.

### Steps To reproduce

See screenshots

**Comment by cconard96** [comment] 2023-12-27 11:44
Probably not a bug; just how the search engine works. Try with "AND NOT" instead of "AND" and switch "not contains" to "contains".
"AND Antivirus - Name not contains Bitdefender": Computers that have and antivirus that doesn't contain "Bitdefender"
"AND NOT Antivirus - Name contains Bitdefender": Computers that have no antivirus containing "Bitdefender"

**Comment by husisusi** [comment] 2023-12-27 14:43
Thank you @cconard96
I tried it before too, but same thing:
![image](https://github.com/glpi-project/glpi/assets/8606735/607eb35d-98bf-495c-87d9-32ae7137808c)

**Comment by husisusi** [comment] 2023-12-28 07:32
#16252 works for me.
 Thanks You @cconard96

**Comment by trasher** [comment] 2024-01-08 09:05
Fixed in #16252

**Closed by trasher** 2024-01-08 09:05 UTC
