### ISSUE TITLE
[9.5] Impact analysis - Display object criticity / linked tickets / KnowLedgeBase Article

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#6680] opened 2019-12-05 18:51 UTC
Ideas : 

I think it's will be interesting to display on Impact analysis : 
- the crititicy field of objects diplayed 
- linked tickets ?
- Use KnowLedgeBase Article as an object

And in tickets / problems / changes
- Display a tab that displays the impact analysis when the ticket (problem / change) is linked to an object on which the impact analysis was configured

We do this in our plugin : 

![screen](https://user-images.githubusercontent.com/13178158/70263993-d63c5480-1797-11ea-8f6e-10ad143bc0f0.png)

**Comment by tsmr** [comment] 2020-05-20 16:57
All is done except tooltips - good job 👍

**Comment by cedric-anne** [comment] 2020-06-23 11:55
Hi,

Features are now freezed for GLPI 9.5.

I close this issue as this is not a bug. Do not hesitate to open a topic on [suggestion website](https://glpi.userecho.com/).

Regards

**Closed by cedric-anne** 2020-06-23 11:55 UTC
Labels: feature suggestion
