### ISSUE TITLE
Web server root directory configuration is not safe as it permits access to non-public files.

### ISSUE THREAD

**Issue by Ridha-DEBBAR** [glpi-project/glpi#14683] opened 2023-05-09 15:58 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

We updated GLPI 10.0.6 to 10.0.7 on Linux
We follow the installation steps according to the GLPi documentation
define('GLPI_VAR_DIR', '/var/lib/glpi');
define('GLPI_LOG_DIR', '/var/log/glpi');
define('GLPI_CONFIG_DIR', '/etc/glpi/');
We modify the GLPi config for Apache : 
<Directory /var/www/glpi/public>
        Require all granted
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php [QSA,L]
    </Directory>
</VirtualHost>

the upgrade works fine and GLPI is accessible
When we access GLPI Portal, we always got the message:
Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.

**Comment by cedric-anne** [comment] 2023-05-15 12:21
Hi,

You probably forgot to update the `DocumentRoot` directive.

Anyway, this is not a bug, so I will close the issue.

**Closed** 2023-05-15 12:22 UTC
Labels: support
