### ISSUE TITLE
Dictionaries Manufacturers  

### ISSUE THREAD

**Issue by dwtz** [glpi-project/glpi#12807] opened 2022-09-29 12:32 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3 + #12670 (with or without)

### Bug description

when i import a macos client, i get an error 500 in the glpi agent log. 
On the glpi server there are the following entries in the log.

but this only happens when an import rule is active.
XML from agent:

```
    <BIOS>
      <BVERSION />  <SMANUFACTURER>Apple Inc.</SMANUFACTURER>
      <SMODEL>iMac21,1</SMODEL>
      <SSN>H12G3HX6Q6X2</SSN>
    </BIOS>
```

![grafik](https://user-images.githubusercontent.com/21999928/193031126-b24d66d8-0e22-4b91-98e4-d43758992126.png)
![grafik](https://user-images.githubusercontent.com/21999928/193031328-02efb07c-5a13-4102-aeaf-877364e43500.png)

if I turn off the import rule, everything works.

[sql-errors.log](https://github.com/glpi-project/glpi/files/9674618/sql-errors.log)

**Comment by trasher** [comment] 2022-09-29 14:15
duplicate of #12811

**Closed by trasher** 2022-09-29 14:15 UTC
