### ISSUE TITLE
GLPI native inventory does not handle SNMP communication errors forwarded by glpi-agent on network inventory

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#14943] opened 2023-06-16 14:45 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8-dev

### Bug description

After the detection of a several number of Apache Errors 500, I was able to trace back and discover that it happens during communications with glpi-agent. In particular,the issue is observed when glpi-agent sends error records related to unreacheable printers through SNMP:
```(
      [content] => Array
          (
              [device] => Array
                  (
                      [error] => Array
                          (
                              [id] => 210
                              [message] => SNMP communication error: no response from host 13.22.7.57
                              [type] => PRINTER
                          )

                  )

              [moduleversion] => 5.1
              [processnumber] => 5618276
          )

      [deviceid] => hotline-xxxxx-2023-05-12-18-48-55
      [action] => netinventory
  )
```

It seems that convertNetworkInventory  does not handle this kind of error messages and throws a RuntimeException('Key ' . $key . ' is not handled in network devices conversion'), leading later to Error 500

**Comment by trasher** [comment] 2023-06-16 14:57
Please provide error stacktrace. It may be a glpiinventory plugin issue, not a GLPI core one.

**Comment by kabassanov** [comment] 2023-06-19 13:05
I'm able to put debug messages in front/inventory.php and that's there that I caught the previous message in the Glpi\Inventory\Request Object...

**Comment by cedric-anne** [comment] 2023-08-03 08:40
@g-bougard 

Could you provide the XML/JSON contents that is supposed to be sent to GLPI when a SNMP inventory tasks fails due to network issue?
It could help to reproduce the issue.

**Comment by g-bougard** [comment] 2023-08-03 09:01
Here is the exact content that should have been sent in that case:
```
<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <ERROR>
        <ID>210</ID>
        <MESSAGE>SNMP communication error: no response from host 13.22.7.57</MESSAGE>
        <TYPE>Printer</TYPE>
      </ERROR>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>5618276</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>hotline-xxxxx-2023-05-12-18-48-55</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
```

**Comment by cedric-anne** [comment] 2023-08-03 09:05
Here is the GLPI error stack trace:
```
glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Key error is not handled in network devices conversion in /var/www/glpi/vendor/glpi-project/inventory_format/lib/php/Converter.php at line 1529
  Backtrace :
  ...ject/inventory_format/lib/php/Converter.php:380 Glpi\Inventory\Converter->convertNetworkInventory()
  ...ject/inventory_format/lib/php/Converter.php:323 Glpi\Inventory\Converter->convertTo01()
  src/Inventory/Inventory.php:141                    Glpi\Inventory\Converter->convert()
  src/Inventory/Request.php:265                      Glpi\Inventory\Inventory->setData()
  src/Inventory/Request.php:250                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:242                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:187                         Glpi\Inventory\Conf->importContentFile()
  src/Inventory/Conf.php:287                         Glpi\Inventory\Conf->importFiles()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->displayImportFiles()
  public/index.php:82                                require()
```

**Comment by trasher** [comment] 2023-08-07 07:47
Huh.. This XML should only passed to inventory plugin, which handle it and prevent it being considered as an inventory file. SNMP queries XML files are not ment to be handled in native inventory.

**Comment by trasher** [comment] 2023-08-07 07:47
I still think this is an plugin or a configuration, issue rather than a GLPI one.

**Comment by trasher** [comment] 2023-09-07 06:51
Closing in favor of https://github.com/glpi-project/glpi-inventory-plugin/issues/400

**Closed by trasher** 2023-09-07 06:51 UTC
Labels: bug

**Comment by stonebuzz** [comment] 2023-09-08 07:15
@kabassanov  can you check my last comment
 
https://github.com/glpi-project/glpi-inventory-plugin/issues/400

Best regards

**Comment by kabassanov** [comment] 2023-09-08 07:31
@stonebuzz , 
Yes, I will try what you propose. Will try to do it today, but not sure to have time.

**Comment by kabassanov** [comment] 2023-09-11 10:09
Hmmm, is it the expected reply? 

```[Mon Sep 11 11:33:59 2023][error] [thread 7] #60, [thread 7] SNMP communication error: no response from host 132.17.12.207
[Mon Sep 11 11:33:59 2023][debug2] [thread 7] #60, [http client] sending message:
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <ERROR>
        <ID>262</ID>
        <MESSAGE>SNMP communication error: no response from host 132.17.12.207</MESSAGE>
        <TYPE>PRINTER</TYPE>
      </ERROR>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>5664926</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>hotline-test.test.fr-2023-05-12-18-48-55</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>
[Mon Sep 11 11:33:59 2023][debug2] [thread 7] #60, format: Zlib
[Mon Sep 11 11:33:59 2023][debug2] [thread 7] #60, [http client] receiving message:
<?xml version="1.0"?>
<REPLY/>
```

**Comment by stonebuzz** [comment] 2023-09-11 10:15
Nop (maybe a bad copy / past from pull request)

All PR should prevent this

```
glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Key error is not handled in network devices conversion in /var/www/glpi/vendor/glpi-project/inventory_format/lib/php/Converter.php at line 1529
```

Have you "correctly" apply : 

https://github.com/glpi-project/inventory_format/pull/121

https://github.com/glpi-project/glpi-inventory-plugin/pull/402



Best regards

**Comment by stonebuzz** [comment] 2023-09-11 10:15
If allis OK you should see this in task job log

https://github.com/glpi-project/glpi-inventory-plugin/pull/402#issuecomment-1711299205

**Comment by kabassanov** [comment] 2023-09-11 10:53
I think I have applied files correctly (the ones from glpi were retreived from bugfixes commits.
The plugin file was copied/pasted. 

I do see the relevant message in the task job log, even if I think that the status should be 'in error' and not "Successful" ...

My question was about:
```<?xml version="1.0"?>
<REPLY/>
```
That is what you are talking about also? It could just be a wrong logging of the packet?

**Comment by kabassanov** [comment] 2023-09-11 11:02
And I have no more the following message in the agent log:

``` 
[Mon Sep 11 09:34:35 2023][error] [thread 9] #60, [http client] communication error: 500 Internal Server Error
```
