### ISSUE TITLE
Priority in New Ticket is always set on High

### ISSUE THREAD

**Issue by Corrano** [glpi-project/glpi#4026] opened 2018-05-17 11:13 UTC
* Steps to reproduce (which actions have you made) :
Create New ticket in GLPI and set **Urgency, Impact and Priority** on **Very Low** or any other value beyond **High**

* Expected result :
Priority still is set on **Very Low**

* Actual result :
Priority is set on **High**

* URL of the page :
Any ticket

* Screenshot of the problem (if pertinent) :
Before Creating
![image](https://user-images.githubusercontent.com/39371670/40173882-96845f32-59d3-11e8-9fbe-6e1c903b032f.png)

After
![image](https://user-images.githubusercontent.com/39371670/40173966-d670e228-59d3-11e8-9a24-1960eeeb5f5c.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.2
php 7.0.25
Ubuntu 16.04.1
Apache 2.4.18
MySQL 5.7.21

**Comment by cedric-anne** [comment] 2018-05-18 08:16
Hi,

I tried on GLPI 9.2.3 and did not reproduce this problem. Can you try to update and check if it fixes your issue ?

Thanks

**Comment by Corrano** [comment] 2018-05-18 09:10
I updated GLPI to 9.2.3 and problem still occurs

**Comment by cedric-anne** [comment] 2018-05-18 09:20
Can you check if you have a business rule (`/front/ruleticket.php`) that could explain this behavior ?

Thanks

**Comment by Corrano** [comment] 2018-05-18 10:20
Below all content of file `(/front/ruleticket.php)`


```
/** @file
* @brief
*/
include ('../inc/includes.php');
$rulecollection = new RuleTicketCollection($_SESSION['glpiactive_entity']);
include (GLPI_ROOT . "/front/rule.common.php");
```

I also check in **Administration > Rule** and i don't see any automatic action which can change Priority

**Comment by flegastelois** [comment] 2018-05-18 15:39
Can you check your "Matrix of calculus for priority" ? (Setup > General > Assistance).

![image](https://user-images.githubusercontent.com/470612/40244121-484f5962-5ac2-11e8-9e24-c7f4d6436025.png)

**Comment by trasher** [comment] 2018-05-29 10:10
Does not seems to be a bug; closing

**Closed by trasher** 2018-05-29 10:10 UTC
