### ISSUE TITLE
SLA and Pause time

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#15605] opened 2023-09-19 12:43 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

We have a ticket escalated to a group, with a High priority for example, that with the business rules, an SLA is assigned according to the priority.

If the priority is changed and the SLA is updated by business rules, the new SLA does not take into account the pause time that was initially accumulating, and is calculated from the opening,

### Steps To reproduce

"Create the incident with an SLA, let it run for a while, put it on hold for days, and change the applied SLA to another one. The new SLA will start from the opening date without taking into account the time it was on hold."

### Your GLPI setup information

10.0.9

**Comment by cconard96** [comment] 2023-10-02 22:34
Can you test this with 10.0.10? There were fixes in that version related to SLA/waiting times.

**Comment by trasher** [comment] 2023-10-13 06:19
Ne feedback from a while, closing

**Closed by trasher** 2023-10-13 06:19 UTC
Labels: Need feedback

**Comment by josimarsant** [comment] 2024-07-10 18:42
I'm using 10.0.10 version and the problem is still there.

**Comment by cedric-anne** [comment] 2024-07-11 06:32
@josimarsant 

Could you try with GLPI 10.0.16 ?
