### ISSUE TITLE
Mail collector: Encoding issue with emails in GB2312 containing special characters

### ISSUE THREAD

**Issue by MarcSamD** [glpi-project/glpi#8986] opened 2021-04-23 08:40 UTC
**Describe the bug**

When the mail collector collect an email encoded in GB2312 (simplified chinese) which is also including some other special characters, all the chinese characters in the content of the ticket will be displayed as garbage.

**To reproduce**

1. Send an email encoded in GB2312 containing any chinese characters (like "我爱中国") AND a special character like "–" (to not mistake with the standard dash "-")
2. The mail collector will create the ticket, no problem with the Title of the ticket, but in the Description all the chinese characters will be displayed as garbage (like "ÕâÁ½ÌìÓÃµçÄÔ£¬"). The latin letters will still be displayed normally.

**GLPI setup**

```
GLPI 9.5.5 - PHP 7.4.3 - Apache/2.4.41 - Server Version: 10.3.25-MariaDB-0ubuntu0.20.04.1
```

**Comment by cedric-anne** [comment] 2021-04-23 12:15
Hi,

Could you please export corresponding email to an eml file and attach it to this issue ? It would help a lot to be able to reproduce and test a fix.

Regards

**Comment by MarcSamD** [comment] 2021-04-25 03:46
File attached. No display issue when opened in Outlook. But displayed as below in GLPI:
```
Title: =?gb2312?B?1eLKx7rcu7W1xE1pbnVzIKhDIEJsYWJsYQ==?
Description: ÕâÊÇºÜ»µµÄMinus ¨C Blabla
```
[这是很坏的Minus – Blabla.txt](https://github.com/glpi-project/glpi/files/6371187/Minus.Blabla.txt)

**Comment by cedric-anne** [comment] 2021-04-27 10:48
Hi,

I am not sure about that, but it looks like your email is malformed.

Indeed, for the subject, when trying to decode it using `iconv_mime_decode("=?gb2312?B?1eLKx7rcu7W1xE1pbnVzIKhDIEJsYWJsYQ==?=")`, in strict mode following notice appears: `Notice: iconv_mime_decode(): Detected an illegal character in input string`. This `iconv_mime_decode` is used by `laminas/laminas-mail` library (the library we use to collect emails) to decode subject.

So the problem is either on the mail client used to send this email, either on `laminas/laminas-mail` library, either on `libiconv` system component.

I close this issue as we cannot do anything on GLPI side.

Regards

**Closed** 2021-04-27 10:48 UTC

**Comment by cedric-anne** [comment] 2021-04-27 13:22
After looking around for a bit, I think the problem is with the handling of the character `–` by the client sending the email. I found a solution to almost fix the ticket description (see #9001 ).

I have no solution to propose for the subject conversion. It is done on `laminas/laminas-mail` library, and, as it seems to be due to a char probelm in the original email, I doubt they will accept any patch proposal to fix it.

**Comment by tomolimo** [comment] 2021-04-30 07:47
Hello @MarcSamD 
Just to add a small piece of info about the same issue we've got, and the solution we've applied:
1. we are using Outlook and MSExchange,
2. some of our user are in China, and they are using Windows 10 as client OS with Outlook
3. Outlook was configured to "automatically select encoding for outgoing messages",
4. And Outlook was sending emails with GB2312 as the encoding charset, but those emails were also containing GB18030 chars!!! And of course that conbinaison was giving strange ticket contents...
5. the solution is either to force Outlook to encode Chinese emails into GB18030 (but some of our users in China are French or German based users, so to force GB18030 would deprive them from European chars), or either to force Outlook to use UTF-8 encoding, like below screen copy: 
![image](https://user-images.githubusercontent.com/7569958/116664513-dfcfe900-a998-11eb-918c-2705e461cc40.png)

This is the only viable solution, to force Outlook to use UTF-8 to encode the outgoing messages...
We have done that via a GPO.

Thank you
Regards,
Tomolimo

**Comment by MarcSamD** [comment] 2021-05-07 09:42
Thanks for the detailed explanation @tomolimo 
Shame on us, we tried to setup Outlook to UTF-8 but missed to uncheck the box "automatically select encoding for outgoing messages"...
I confirm that it is working now, and [deployment by GPO](https://www.codetwo.com/kb/global-encoding-of-outgoing-messages-at-exchange/) too 👍
