### ISSUE TITLE
[9.3] Computer -> Connections ignore is_deleted flag

### ISSUE THREAD

**Issue by lufik** [glpi-project/glpi#4705] opened 2018-09-25 11:14 UTC
* Steps to reproduce (which actions have you made) :
1) Create dynamic connection between computer and monitor (e.g. fusioninventory or update the db record to is_dynamic = 1).
2) Disconnect (manually or use uninstall plugin)

After those steps the glpi_computers_items.is_deleted is set to 1 and nothing can be done
with it anymore (disconnect, add, ...). You have to remove it manually in DB using SQL.

* Expected result :
The connection is not listed (and coutned) in Computer -> Connections

* Actual result :
The connection is counted and listed in Computer -> Connections but does not show in Monitor -> Connections.

* URL of the page :
https://glpi.devel.invasys.org/front/computer.form.php?id=8
https://glpi.devel.invasys.org/ajax/common.tabs.php?_target=/front/computer.form.php&_itemtype=Computer&_glpi_tab=Computer_Item$1&id=8&withtemplate=

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
Same as in #4682 

* How to fix it?

1. IMHO it's better to remove the is_deleted column from glpi_computers_items table as there is no way to purge records with is_deleted = 1 from GUI (only SQL in DB). I'm not sure if is_dynamic make sense without is_deleted.
1. However there is also way (I currently use this) to add support for is_deleted flag into computer_items class.

I can prepare pull request for both ways. I have no clue which one is better.

**Comment by lufik** [comment] 2018-09-25 13:06
Ok, so is_deleted is used as a Lock so only the how to fix number 2. (fix display for computer) is the right way.

**Comment by trasher** [comment] 2018-09-26 08:43
>  The connection is counted and listed in Computer -> Connections but does not show in Monitor -> Connections.

It should be displayed on monitors side as well.

Solution is probably to add the action that seems to be missing in the massive actions (I did not check this point).

**Comment by lufik** [comment] 2018-09-26 08:47
The problem is, that Monitor -> Connections take care of is_deleted flag but the Computer -> Connections doesn't.

So both sides shows the active connection. But then the dynamic connection is disconnected the Computer -> Connections still shows it (even the deleted one) but Monitor -> Connections do not show it.

**Comment by trasher** [comment] 2018-09-26 08:50
Both sides should display all connections: monitor side is (surprisingly) currently wrong.

**Comment by lufik** [comment] 2018-09-26 08:55
Ok, I'm going to change the pull request. I'm not sure with the different background colour for deleted items. I'll check.

**Comment by trasher** [comment] 2018-09-26 08:59
See https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/computer_item.class.php#L427 and https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/computer_item.class.php#L574.

Indeed, on the "not compter" side, the query is not good; we had to remmove https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/computer_item.class.php#L489

**Comment by lufik** [comment] 2018-09-26 09:12
I see the code lines you mentioned but I don't see different bg color for the name and definitely it's not even in the HTML code generated.

I'm not sure it's enough to remove just the line. I'll investigate.

**Comment by trasher** [comment] 2018-09-26 09:31
Hum indeed. So can't say, have to spend time to understand the exact issue; standard behavior seems to work as expected.

**Comment by lufik** [comment] 2018-09-26 09:43
Ok, take your time. Do not hesitate to contact me if I can help with something.
Just a side note. The Connections are not ready to show deleted/locked connections (as massive actions shows only disconnect - even for locked connections which makes no change = is only confusing).

**Comment by cedric-anne** [comment] 2018-09-27 09:38
If the linked asset is marked as `is_deleted`, it is displayed in red (if it does not work somewhere, it is an oversight).

The problem is that it is the link between two assets that has been marked as `is_deleted`, not one of the assets, and there is nothing to handle that in the code. The function that retrieves links does not even retrieves this information (request made in https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/commondbrelation.class.php#L1642).
To retrieve this information, something like that should be done:
```diff
diff --git a/inc/commondbrelation.class.php b/inc/commondbrelation.class.php
index 27653cdda3..7ee25f8897 100644
--- a/inc/commondbrelation.class.php
+++ b/inc/commondbrelation.class.php
@@ -1675,6 +1675,11 @@ abstract class CommonDBRelation extends CommonDBConnexity {
          'ORDER'     => $item->getTable() . '.' . $order_col
       ];
 
+      $relation_item = new static();
+      if ($relation_item->maybeDeleted()) {
+         $params['SELECT'][] = static::getTable() . '.is_deleted AS link_is_deleted';
+      }
+
       if ($DB->fieldExists(static::getTable(), 'itemtype')) {
          $params['WHERE'][static::getTable() . '.itemtype'] = $itemtype;
       }
```

But functionnaly, I do not know how to handle this case.

Not sure that displaying in red is enought, but it can be achieve like that:
```diff
diff --git a/inc/computer_item.class.php b/inc/computer_item.class.php
index 45d128a204..d78ce7da1b 100644
--- a/inc/computer_item.class.php
+++ b/inc/computer_item.class.php
@@ -416,7 +416,9 @@ class Computer_Item extends CommonDBRelation{
             $link = $itemtype::getFormURLWithID($data["id"]);
             $name = "<a href=\"".$link."\">".$linkname."</a>";
 
-            echo "<tr class='tab_bg_1'>";
+            echo "<tr class='"
+               . ((isset($data['link_is_deleted']) && $data['link_is_deleted'])?"tab_bg_2_2":"tab_bg_1")
+               . "'>";
 
             if ($canedit) {
                echo "<td width='10'>";
```

**Comment by lufik** [comment] 2018-10-01 13:15
Yeah, there are more ways to solve it. The main goal is now on your (glpi devels) side to decide what is the right way. As I wrote I can help with the patch (till end of November) but I don't want to invest my time into something what can be dropped because it does not fit glpi ideas.

**Comment by orthagh** [comment] 2018-10-01 13:49
Explanation for a (little) more old developer:
- Deleting dynamic connections set them as locked and hidden in the connections tab (you can retrieve them into lock tab of the computer). I'm not sure we want to remove this feature.
- On other side item, we could improve the display to warn the user about the lock.
- There may be some issues with counters we can fix also

**Comment by lufik** [comment] 2018-10-01 14:54
To keep previous behaviour (as described by orthagh) is the best suitable my pull request (stop showing **locked**) connections from Computer -> Connections (as they're not showed in e.g. Monitor -> Connections).

Definitely I'm sorry that I confuse several people with the very first description (as I didn't catch correctly the behaviour).

**Comment by sdvroot** [comment] 2018-11-13 17:07
Hi, do you have updates concerning this issue ?

I open a computer with monitor connected. In massive action i choose disconnect..
I have a message for successful action but the monitor is still present in connected items of the computer. A lock is put on the monitor.

I delete the lock.
Go on the monitor and disconnect the computer.
The monitor disappears from connected items list.

I go back to the computer form and the monitor is still present.
In database, relation is still present with is_deleted set to 1

**Comment by trasher** [comment] 2019-06-11 06:18
Fixed in https://github.com/glpi-project/glpi/pull/6003

**Closed by trasher** 2019-06-11 06:18 UTC
Labels: bug
