### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by KevinStephane** [glpi-project/glpi#5290] opened 2019-01-22 14:52 UTC
Hello, 
On my production glpi server, i have a problem with images.  
The images are not diyplayed in tickets and they are remplaced by sequence number.
After some research i can't find any solution , so i decided to install a new server and restore my prod database and files folder in this new installation.
And it works for my new tickets but for the older tickets i see a sequence number instead of image.
I noticed one strange thinks. 
For the order tickets the images links is :  http://172.16.160.59/front/document.send.php?docid=518&tickets_id=4961 
and for the new tickets the iamge link is : http://172.16.160.59/**glpi**/front/document.send.php?docid=112&tickets_id=5013.

You can see that the difference in url is "GLPI" 

Can you help me please ?

**Comment by AnaelMobilia** [comment] 2019-01-29 09:13
Hello @KevinStephane ,

We need more informations on your configurations (as wrote on the Template for issues ;-)).

Could you, please, submit them ?

Regards,
Anael

**Comment by cedric-anne** [comment] 2019-02-28 20:47
Hi,

The problem is that images are stored using the configured base URL if ticket is created by mail collector, or using the current URL if ticket is created in web UI.

So, you can basically have this problem if you misconfigured the base URL of GLPI or if you moved your GLPI inside directory structure of your domain (i.e. from `/` to `/glpi/`).

To fix this, we would have to sore relative URLs and rebuild full path on display, but it requires some work. Not sure it will be done soon, at least by me.

Regards

**Comment by trasher** [comment] 2019-03-01 07:01
I guess this kind of "issue" will be fixed when collector will be reworked since we'll change almost everything and add unit tests.
This is not planned for now.

**Closed by trasher** 2019-03-01 07:01 UTC
