### ISSUE TITLE
Location import from OCS-Inventory when "As child of" used in GLPI 

### ISSUE THREAD

**Issue by freestorm** [glpi-project/glpi#11058] opened 2022-03-21 10:48 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Hi,

I have some locations in GLPI linked as "Parent-Child" as for example:

[BAT-NORD] > [NORD-1] > [N100]
[BAT-NORD] > [NORD-2] > [N201]
[BAT-SUD] > [SUD-4] > [S400]

In OCS I created the rooms N100,N201,S400 in a SELECT field type of "Administrative Data" (field_6)

When I synchronize or import computers from OCSInventory-NG, the plugin do not match the location defined in GLPI, and create new location

On attached file, you can see the ID 9 of glpi_locations that was created by ocs-plugin, It should match id 5 and not create a new location entry

When I create a location in GLPI without "As child of" option, the synchronization works between OCS and GLPI

The issue do no seams coming from the plugin "OCS Inventory NG", I have opened a bug issue on the plugin github:
https://github.com/pluginsGLPI/ocsinventoryng/issues/315

As the plugin maintainer said, he use a GLPI function to import location:
```

inc/ocsadmininfoslink.class.php
$var = Dropdown::importExternal("Location", $var, $entities_id);
```
I have checked the function "Dropdown::importExternal" 
and is use  "findID($input));" to return the location ID form the location name
`
 }
 return ($add ? $this->import($input) : $this->findID($input));
 }
 `

When looking  at the function "findID" 
```
else if (isset($input['name']) && !empty($input['name'])) {
  $fk = $this->getForeignKeyField();
```
the variable $fk is set to "locations_id" by getForeignKeyField();

and then 
```
$criteria = [
            'SELECT' => 'id',
            'FROM'   => $this->getTable(),
            'WHERE'  => [
               'name'   => $input['name'],
               $fk      => (isset($input[$fk]) ? $input[$fk] : 0)
            ]
         ];
```
The debug of $criteria return:

```
SELECT:"id"
FROM:"glpi_locations"
WHERE:array(2)
name:"N100"
locations_id:0
```

You can see the value "locations_id:0" is added to the criteria variable.

The SQL Query returned by 
`
       // Check twin :
         $iterator = $DB->request($criteria);
         if (count($iterator)) {
            $result = $iterator->next();
            return $result['id'];
         }
      }
`

`sql:"SELECT `id` FROM `glpi_locations` WHERE `name` = 'N100' AND `locations_id` = '0' AND (`glpi_locations`.`entities_id` = '0')"`

You can see the criteria  "`locations_id` = '0'  on the query " but the locations_id  for location "N100" is "3" because of "As child of" used on the location 

So the location "N100" is not found ans a new location "N100" is created on the database.

When I comment the line $fk..
```
         $criteria = [
            'SELECT' => 'id',
            'FROM'   => $this->getTable(),
            'WHERE'  => [
               'name'   => $input['name'],
               // $fk      => (isset($input[$fk]) ? $input[$fk] : 0)
            ]
         ];

The import form OCS_Inventory work, it find the location and do not create a new one

```

### Your GLPI setup information

```
GLPI 9.5.7 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB
```
### Server
```
Operating system: Linux sie-lx001 5.10.0-12-amd64 #1 SMP Debian 5.10.103-1 (2022-03-07) x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Debian) (Apache/2.4.52 (Debian) Server at 10.228.146.105 Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
Server Software: Debian 11
	Server Version: 10.5.12-MariaDB-0+deb11u1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.5.12) - Perfect!Database version seems correct (10.5.12) - Perfect!

The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
```
### GLPI constants

```
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 9.5.7
GLPI_SCHEMA_VERSION: 9.5.7
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022
```
### Libraries

```
htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
```
### SQL replicas
`Not active`

### Notifications
`Way of sending emails: PHP`

### Mails receivers
`N/A`

### Plugins list
`ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Enabled`

### OCS Inventory NG
```
Host: localhost
Connection: Ok
Use the OCSNG software dictionary: No
```

**Comment by cedric-anne** [comment] 2022-03-21 11:09
Hi,

This is not a bug. A same location name can be used at multiple places in the location tree. This check on `locations_id` ensure that GLPI is acting on the correct item in tree.

**Comment by cedric-anne** [comment] 2022-03-21 12:10
Sorry, I misread the code. Actually, the `Dropdown::importExternal()` method is not using the completename. see #11062

**Comment by cconard96** [comment] 2022-03-23 10:00
Issue was fixed on the GLPI side for GLPI v10 RC3.
The plugin will need updated to pass the required information as right now it looks like they only pass the name and entity, and nothing in the extra_params array.

**Closed by cconard96** 2022-03-23 10:00 UTC
Labels: bug

**Comment by freestorm** [comment] 2022-03-24 08:11
Thank you for the bug correction
