### ISSUE TITLE
Planning rights

### ISSUE THREAD

**Issue by intersedev** [glpi-project/glpi#1785] opened 2017-02-07 16:17 UTC
Hello,

There is no rights management for planning updates.
Everyone can change the tasks of everyone.
Can you add rights to updates for tasks on schedules? Or use the option "Edit All" in Task for Profile?

Thanks.

**Comment by jgobet** [comment] 2017-06-13 14:09
Hello,

This problem is not fixed in version 9.1.3.
Can you add this control in the next version ?

The problem is that everyone can resize and drag the tasks of everyone in the planning.
Everyone can delete permanently the tasks of everyone too.

Thanks.

**Comment by jgobet** [comment] 2017-06-20 15:06
Same in GLPI 9.1.4...

**Comment by jgobet** [comment] 2017-08-29 14:00
Hello,

This problem is always present in GLPI 9.1.6.
Can you correct it please?

**Closed** 2021-09-13 21:05 UTC
