### ISSUE TITLE
How to set smtp from e-mail?

### ISSUE THREAD

**Issue by Sogl** [glpi-project/glpi#458] opened 2016-02-15 07:34 UTC
Hi!

My notification settings:
![image](https://cloud.githubusercontent.com/assets/7556290/13042181/e2ed6492-d409-11e5-9e09-df07afdf883d.png)

I want to set `From` e-mail other than `Reply-to` e-mail. 
Now I did this only with set in `class.phpmailer.php`, line 1199:

``` php
protected function smtpSend($header, $body)
    {
        $bad_rcpt = array();

        if (!$this->smtpConnect()) {
            throw new phpmailerException($this->lang('smtp_connect_failed'), self::STOP_CRITICAL);
        }
//        $smtp_from = ($this->Sender == '') ? $this->From : $this->Sender;
        $smtp_from = 'support@domain.com';
        if (!$this->smtp->mail($smtp_from)) {
            $this->setError($this->lang('from_failed') . $smtp_from . ' : ' . implode(',', $this->smtp->getError()));
            throw new phpmailerException($this->ErrorInfo, self::STOP_CRITICAL);
        }
```

`support@domain.com` is our mailgate e-mail, `admin@domain.com` is administrator e-mail.

Maybe I missed this option somewhere  in the web interface?

**Comment by tomolimo** [comment] 2016-02-15 07:42
Hello,

That’s the way to do it:
[cid:image001.png@01D167CC.BB10E150]

You don’t need to change source code for that!

Regards,

Olivier MORON

**Comment by Sogl** [comment] 2016-02-15 07:44
@tomolimo I can't see your attached image... something broken

**Comment by tomolimo** [comment] 2016-02-15 07:47
![image](https://cloud.githubusercontent.com/assets/7569958/13042487/c5ac4c7a-d3c0-11e5-807f-f20d45ea1b22.png)

**Comment by Sogl** [comment] 2016-02-15 07:57
With this setting GLPI sends me recursive e-mails: 1 mail to sender/user and 1 mail to `support@domain.com`...support is my mailgate.

But with my code change:
1. User send e-mail to `support@domain.com`
2. 1 mail confirmation to user from `support@domain.com` (tickets mailgate)
3. 1 mail confirmation to `admin@domain.com` (IT department)
4. If user wants to reply - message comes to `admin@domain.com` (IT)

How can I do it without code change?

**Comment by Sogl** [comment] 2016-02-15 23:27
@tomolimo Any ideas?

**Comment by tomolimo** [comment] 2016-02-16 06:07
Hello
As I can't reproduce the same behavior, could you please try to narrow down the problem and get basic steps to reproduce? 
Thank you 
Regards 
Tomolimo

**Comment by Sogl** [comment] 2016-02-16 07:00
@tomolimo 

Steps:
1. Set `support@domain.com` mail to mailgate:
![image](https://cloud.githubusercontent.com/assets/7556290/13068596/9fa9a38e-d4c8-11e5-85e3-e08a25675243.png)
2. Set `support@domain.com` as administrator e-mail and `admin@domain.com` as reply-ro email:
![image](https://cloud.githubusercontent.com/assets/7556290/13068727/1576a9ee-d4ca-11e5-9a7b-e0163198adf3.png)
3. Test mail comes to `support@domain.com` correctly. I delete it quickly because mailgate mail.
4. I create ticket from `user@domain.com` and receive 2 notifications: 1 mail notification to `user@domain.com`, 1 mail notification to `support@domain.com`:
![image](https://cloud.githubusercontent.com/assets/7556290/13068939/d6ac69fe-d4cb-11e5-9666-2fd5f32e25f6.png)

But I want admin notifications to `admin@domain.com`, just because `support@domain.com` creates new tickets every 5 minutes (mailgate). `user@domain.com` see `support@domain.com` as email sender, but if he want to answer, letter comes to `admin@domain.com` because reply-to.

My `class.phpmailer.php` change let me send test mail to `admin@domain.com` (not mailgate by default) , I set it as Admin email and send all ticket notifications to `admin@domain.com`. How it looks with change:
![image](https://cloud.githubusercontent.com/assets/7556290/13069252/a825a502-d4ce-11e5-917e-c9e3adaf941d.png)


Clear? =)

**Comment by tomolimo** [comment] 2016-02-17 10:17
Hello,

Could you clarify the point 4?

> I create ticket from user@domain.com and receive 2 notifications: 1 mail notification to `user@domain.com`, 1 mail notification to `support@domain.com`

Do you mean that for each ticket creation an email is sent to `support@domain.com`?
If it's the case, then you may have a wrong notification 'Recipients' settings in the 'Setup' > 'Notifications' > 'Notifications' see the one that is applied for ticket creation.

**Comment by Sogl** [comment] 2016-02-18 00:36
>Do you mean that for each ticket creation an email is sent to support@domain.com?

Yes.

>f it's the case, then you may have a wrong notification 'Recipients' settings in the 'Setup' > 'Notifications' > 'Notifications' see the one that is applied for ticket creation.

You mean `New Ticket` notification recipients?
![image](https://cloud.githubusercontent.com/assets/7556290/13129836/50e3f1fa-d62b-11e5-909b-9297b0373d8e.png)

Where I can find this list to edit e-mails?

**Comment by tomolimo** [comment] 2016-02-18 06:09
Hello 
In the screen capture you sent, there is the answer to your problem: delete the first recipient named 'Administrator'.
Regards 
Tomolimo

**Comment by Sogl** [comment] 2016-02-18 06:42
I can't send emails: `550 5.7.1 Client does not have permissions to send as this sender` More info:
https://support.desk.com/customer/portal/articles/1104707-client-does-not-have-permissions-to-send-as-this-sender-error

My `admin@domain.com` is alias on Exchange. I can't give my `support@domain.com` rights to the aliases (this is not possible).

**Comment by Sogl** [comment] 2016-02-18 06:58
>In the screen capture you sent, there is the answer to your problem: delete the first recipient named 'Administrator'.

After deleting `Administrator` new tickets notifications sends only to `user@domain.com`, but I need IT department `admin@domain.com` too.

**Comment by tomolimo** [comment] 2016-02-18 07:30
I don't understand this

> I can't send emails: 550 5.7.1 Client does not have permissions to send as this sender More info:
https://support.desk.com/customer/portal/articles/1104707-client-does-not-have-permissions-to-send-as-this-sender-error
>
> My admin@domain.com is alias on Exchange. I can't give my support@domain.com rights to the aliases (this is not possible).


But regarding this I understand the need

> After deleting Administrator new tickets notifications sends only to user@domain.com, but I need IT department admin@domain.com too.

IT department is NOT Administrator: you must define another user/group with another email (<> support@domain.com) for that. And you may set the new group in the 'new ticket' recipient list.

**Comment by Sogl** [comment] 2016-02-19 05:04
Finally I solved my problem in this way:

1. Set organization email to `support@domain.com` (Administration -> Entities). 
After that change all new tickets sender in MySQL table `glpi_queuedmails` (column `sender`) becomes `support@domain.com`. It was `admin@domain.com` earlier. If fix permissions problem.
More info:
http://forum.glpi-project.org/viewtopic.php?pid=164227#p164227
2. Set admin and replyto mails to `admin@domain.com` in Notifications:
![image](https://cloud.githubusercontent.com/assets/7556290/13166439/a0bcd6e0-d713-11e5-8c9e-ce2a29d7d202.png)

That's all! User creates ticket and notifications sends to admin and user.

Small problems remain:
1. I don't know why, but after deleting Administrator and adding IT group in `New Ticket` recipitents, emails sending stop to `Requester`. No `Requester` row in `glpi_queuedmails`. Screen:
![image](https://cloud.githubusercontent.com/assets/7556290/13166581/2840f32a-d715-11e5-9126-08ae3ed980b5.png)
Maybe it's because requester email equals one of IT-department's mails? (I used my email for tests)
2. `class.phpmailer.php` can't connect to Exchange server with default 272 line:
```
public $AuthType = '';
```
Output:
```
2016-02-19 04:42:33     SERVER -> CLIENT: 220 exchange.domain.com Microsoft ESMTP MAIL Service ready at Fri, 19 Feb 2016 14:                                                                                                              42:32 +1000
2016-02-19 04:42:33     CLIENT -> SERVER: EHLO inventory.domain.com
2016-02-19 04:42:33     SERVER -> CLIENT: 250-exchange.domain.com Hello [192.168.1.240]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH GSSAPI NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
250 XSHADOW
2016-02-19 04:42:33     CLIENT -> SERVER: STARTTLS
2016-02-19 04:42:33     SERVER -> CLIENT: 220 2.0.0 SMTP server ready
2016-02-19 04:42:33     CLIENT -> SERVER: EHLO inventory.domain.com
2016-02-19 04:42:33     SERVER -> CLIENT: 250-exchange.domain.com Hello [192.168.1.240]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH GSSAPI NTLM LOGIN
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
250 XSHADOW
2016-02-19 04:42:33     CLIENT -> SERVER: AUTH PLAIN
2016-02-19 04:42:38     SERVER -> CLIENT: 504 5.7.4 Unrecognized authentication type
2016-02-19 04:42:38     SMTP ERROR: AUTH command failed: 504 5.7.4 Unrecognized authentication type
2016-02-19 04:42:38     CLIENT -> SERVER: QUIT
2016-02-19 04:42:38     SERVER -> CLIENT: 221 2.0.0 Service closing transmission channel
SMTP connect() failed.
2016-02-19 04:42:38     SERVER -> CLIENT: 220 exchange.domain.com Microsoft ESMTP MAIL Service ready at Fri, 19 Feb 2016 14:                                                                                                              42:37 +1000
2016-02-19 04:42:38     CLIENT -> SERVER: EHLO inventory.domain.com
2016-02-19 04:42:38     SERVER -> CLIENT: 250-exchange.domain.com Hello [192.168.1.240]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-X-ANONYMOUSTLS
250-AUTH GSSAPI NTLM
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
250 XSHADOW
2016-02-19 04:42:38     CLIENT -> SERVER: STARTTLS
2016-02-19 04:42:38     SERVER -> CLIENT: 220 2.0.0 SMTP server ready
2016-02-19 04:42:38     CLIENT -> SERVER: EHLO inventory.domain.com
2016-02-19 04:42:38     SERVER -> CLIENT: 250-exchange.domain.com Hello [192.168.1.240]
250-SIZE 20971520
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH GSSAPI NTLM LOGIN
250-X-EXPS GSSAPI NTLM
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250-XEXCH50
250-XRDST
250 XSHADOW
2016-02-19 04:42:38     CLIENT -> SERVER: AUTH PLAIN
2016-02-19 04:42:43     SERVER -> CLIENT: 504 5.7.4 Unrecognized authentication type
2016-02-19 04:42:43     SMTP ERROR: AUTH command failed: 504 5.7.4 Unrecognized authentication type
2016-02-19 04:42:43     CLIENT -> SERVER: QUIT
2016-02-19 04:42:43     SERVER -> CLIENT: 221 2.0.0 Service closing transmission channel
SMTP connect() failed.
``` 
And no errors in GLPI logs at all! Only with `public $SMTPDebug = 2;` I saw errors in console.

So... after this change:
```
public $AuthType = 'LOGIN';
```
All my mails works fine. Where I can find auth type in GLPI web-interface?

My SMTP settings:
![image](https://cloud.githubusercontent.com/assets/7556290/13166870/b2102ec4-d718-11e5-8b79-e1f74baaf444.png)

>IT department is NOT Administrator: you must define another user/group with another email

It doesn't matter in our company because only IT deapartment uses GLPI.

**Comment by tomolimo** [comment] 2016-02-19 08:11
Hello,

1)
>> Maybe it's because requester email equals one of IT-department's mails? (I used my email for tests)

> What is your setting for 
![image](https://cloud.githubusercontent.com/assets/7569958/13169857/72e7a5a4-d6e8-11e5-8392-052bd1f619e5.png)?

2)
Exchange doesn't support TLS, but only BASIC

**Comment by Sogl** [comment] 2016-02-20 00:52
>What is your setting for ... ?

Enabled.

>Exchange doesn't support TLS, but only BASIC

TLS is encryption type/protocol. BASIC is auth type. This is different things.

**Comment by tomolimo** [comment] 2016-02-22 07:26
Hello,

You are right about TLS and BASIC, but you should look at this in the traces:

> 2016-02-19 04:42:33     CLIENT -> SERVER: AUTH PLAIN
2016-02-19 04:42:38     SERVER -> CLIENT: 504 5.7.4 Unrecognized authentication type
2016-02-19 04:42:38     SMTP ERROR: AUTH command failed: 504 5.7.4 Unrecognized authentication type

So do some googling to find how to configure the connection.

**Comment by Sogl** [comment] 2016-02-24 00:13
>You are right about TLS and BASIC, but you should look at this in the traces:

If I leave it empty by default, my connection uses `PLAIN`. But I need `LOGIN`.
Where I can set it in GLPI?

**Comment by trasher** [comment] 2017-07-05 09:27
Set "Way of sending email" to "SMTP", and not "SMTP+TLS".

Closing; this is more a user support than a bug; and that seems solved anyways.

**Closed by trasher** 2017-07-05 09:27 UTC
