### ISSUE TITLE
Permission denied when deleting more than 250 software items

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#14941] opened 2023-06-16 13:03 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When putting software items in trash, there seems to be a limit of max 1000 items at a time. Selecting more than 1000 just results in the first 1000 to be put in trash. The max_input_vars is set at 1000 in php.ini, so that can explain this.
When trying to permantly delete trashed software items, the limit seems to be 250. If I select more than 250 items, I get an error "The action you have requested is not allowed. ". Setting max_input_vars to 20000 solves this, but it might be something to set dynamically (or configurable) in glpi.
More: since it seems that the permanently delete needs more post variables than the "put in trash", it might be worth looking at the reason for that.

**Comment by MarcSamD** [comment] 2023-06-20 04:05
Duplicate of https://github.com/glpi-project/glpi/issues/14863, should be solved in [10.1.0](https://github.com/glpi-project/glpi/milestone/49)

**Comment by trasher** [comment] 2023-06-20 05:21
This can be solved updating temporary related PHP configuration value

**Closed by trasher** 2023-06-20 05:21 UTC
Labels: duplicate
