### ISSUE TITLE
Bug in the searching list of changes

### ISSUE THREAD

**Issue by marios1984** [glpi-project/glpi#4154] opened 2018-06-08 14:33 UTC
* Steps to reproduce (which actions have you made) :
Remove 'See all' right from profile in Changes: 
Administration -> Profiles -> Assistance -> unselect 'See all' in Changes table.
Create one change and add more watchers.

* Expected result :
See only one line for the last change created (with several watchers) in the searching list interface.

* Actual result :
If in the change we have 4 watchers, then in the list we will have 4 line for this change (same id).

* URL of the page :
glpi/front/change.php

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/4922280/41163520-2a20fdba-6b39-11e8-8ebe-9579cc8fdca0.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.2.3 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux lxglpiprod 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64
PHP 7.2.5-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at lxglpiprod Port 80)
	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.22-0ubuntu18.04.1
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/var/www/html/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/var/www/html/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)

**Comment by cedric-anne** [comment] 2018-06-12 11:52
Hi,

The problem is also present for tickets.

To reproduce:
1. Have a user without `See all` rights for item.
2. Create an item and add multiple watchers.
3. Display list without displaying any column related to users/groups (requester, assign to, watcher, ...).

Now we have to find how to fix it.

Regards

**Comment by trasher** [comment] 2018-06-22 06:49
@cedric-anne on which version have you tested? I've tried with 9.3/bf, and I'm not able to reproduce

**Comment by cedric-anne** [comment] 2018-06-22 07:58
I just reproduced on GLPI 9.3. I had to remove all groups from user to reproduce.

**Closed** 2018-06-29 06:09 UTC
Labels: bug
