### ISSUE TITLE
[GLPI 9.5.0] Dashboard : Provider::formatMonthyearDates() must be of the type string

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#7689] opened 2020-07-15 11:55 UTC
In the dasboard [glpi9.5], i have errors in the php-errors.log
If I refresh the page dashboard (central or parc or assistance), the error is generated in the file (php-errors.log). 
In use, it works correctly but maybe it can cause another bug? I dont know

[2020-07-15 13:44:56] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Glpi\Dashboard\Provider::formatMonthyearDates() must be of the type string, null given, called in /var/www/html/glpi/inc/dashboard/provider.class.php on line 754 in /var/www/html/glpi/inc/dashboard/provider.class.php at line 983
  Backtrace :
  inc/dashboard/provider.class.php:754               Glpi\Dashboard\Provider::formatMonthyearDates()
  :                                                  Glpi\Dashboard\Provider::getTicketsStatus()
  inc/dashboard/grid.class.php:945                   call_user_func_array()
  ajax/dashboard.php:108                             Glpi\Dashboard\Grid->getCardHtml()
  
[2020-07-15 13:45:36] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Glpi\Dashboard\Provider::formatMonthyearDates() must be of the type string, null given, called in /var/www/html/glpi/inc/dashboard/provider.class.php on line 754 in /var/www/html/glpi/inc/dashboard/provider.class.php at line 983
  Backtrace :
  inc/dashboard/provider.class.php:754               Glpi\Dashboard\Provider::formatMonthyearDates()
  :                                                  Glpi\Dashboard\Provider::getTicketsStatus()
  inc/dashboard/grid.class.php:945                   call_user_func_array()
  ajax/dashboard.php:108                             Glpi\Dashboard\Grid->getCardHtml()

**Comment by steph461** [comment] 2020-07-15 11:57
Operating system: Linux srv-glpi 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64
PHP 7.4.8 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session, shmop, snmp, sockets, sodium,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="5M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.6 (CentOS) PHP/7.4.8 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Server Software: MariaDB Server

**Comment by trasher** [comment] 2020-07-15 12:38
It seems your have a missing creation date in your tickets; we are able to reproduce only if we set the date value to null in the database directly (did not find a way to achieve that from the UI).

You should check you `glpi_tickets` table for rows missing a `date` value (if you did a migration from an old version, check your in your backup as well). Since this is not an expected behavior, we need more information on how to reproduce (it can be an issue in GLPI, or in a plugin).

**Comment by steph461** [comment] 2020-07-15 13:19
Check glpi_ticket :
Ticket_ID: 956 with Colonne date (open date) value is NULL, it was the only ticket, the value was zero
I do Update date 2020-03-06 15:10:16 in my requete
I check , The issue is resolve

thank you :)

**Comment by trasher** [comment] 2020-07-15 13:25
Okay, I close this issue then; if problem happens again, you'll have to focus on this missing date issue (and open an issue against bogus component) :)

**Closed by trasher** 2020-07-15 13:25 UTC
Labels: Need feedback
