### ISSUE TITLE
Associate item to ticket

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi#8635] opened 2021-02-07 16:42 UTC
I configured it in "Business rules for tickets" so that a ticket containing "SERVER-01" has associated the computer with the corresponding MAC address.

```
Rule:
Child entities: Yes
Active: Yes
Logical operator: AND
Use rule to: Add / Update

Criteria:
description
contains
SERVER-01

Actions:
Associated elements
Assign: equipment by MAC address
00:00:00:00:00:00 (SERVER-01 MAC)
```

Working!

I created another rule to associate a Device (USB drive).

In "Assets", "Devices", I selected the device and in "Network port", I added an "Alias port".

I generated a MAC address based on the manufacturer (Seagate = 00:04:CF:00:00:00 to 00: 04:CF:FF:FF:FF).

I configured in "Business rules for tickets" so that a ticket with the unit "BKP" has associated the device with the corresponding MAC address.

```
Rule:
Child entities: Yes
Active: Yes
Logical operator: AND
Use rule to: Add

Criteria:
Title
contains
SERVER-01 - BKP

Actions:
Associated elements
Assign: equipment by MAC address
00:00:00:00:00:00 (BKP device MAC)
```

It worked more or less!

In calls without the device rule, SERVER-01 is correctly associated. When the rule for the device was added, SERVER-01 no longer appears, leaving only the BKP device.

Comment:

I have already changed the rules in several ways together and separately.

```
Rule:
Child entities: Yes
Active: Yes
Logical operator: AND and also OR
Use rule to: Add, Update, Add / Update
```

Either add the server when the subject is only SERVER-01 or add BKP when the subject is BKP.

Do not add the 2 items to the ticket.

They are different items: one is a computer and the other is a device.

I've tried the same rule to add the 2 through MAC address but only add one.

I added this question to the forum and received the following answer: "Processing ends at the first rule that fires."

I have 202 rules that are applied correctly, in sequence.

Example:

```
Rule:
Service level - incidents (disk)
Child entities: Yes
Active: Yes
Logical operator: AND
Use rule to: Add / Update

Criteria:
Title
contains
Disk space is (from Zabbix)

Actions:
Assign - Incident SLA - First call
Assign - SLA Incident - Solution
Assign - OLA Incident - First call
Assign - OLA Incident - Solution
Assign - Type - Incident
Assign - Category - Storage> USB drive> Out of space
Assign - Urgency - High
Assign - Priority - High
Assign - Impact - High


Rule:
Child entities: Yes
Active: Yes
Logical operator: AND
Use rule to: Add / Update

Criteria:
description
contains
SERVER-01

Actions:
Associated elements
Assign: equipment by MAC address
00:00:00:00:00:00 (SERVER MAC-01)


Rule:
Child entities: Yes
Active: Yes
Logical operator: e
Use rule to: Add

Criteria:
Title
contains
SERVER-01 - BKP

Actions:
Associated elements
Assign: equipment by MAC address
00:00:00:00:00:00 (BKP device MAC)
```

When Zabbix sends an alert to GLPI, a ticket is opened with all the correct settings based on "Business rules for tickets", filling in the fields correctly, including the server etc.

This applies to other existing rules.

However, when there is a question about the USB drive, the ticket is filled in correctly, except for Items, where only the rule for the USB drive appears.

So, it is not that the GLPI only applies the first rule. He will check all the rules that apply to that ticket and make the settings.

The problem is that GLPI is not adding another component to Items, just one.

I did an experiment, putting 2 servers in the server rule and disabled the USB drive rule. Only the second server was added to the ticket, although there are 2 pieces of equipment in the rule.

**Comment by cedric-anne** [comment] 2021-03-08 12:00
Hi,

Unless I am wrong, this is not a bug, but a missing feature.

In rules, at least for ticket actor fields, `assign` keywork is used to redefine the value of a field, and `add` keyword is used to add result to existing items. In case of `Associated elements`, there is no `add` action, only assign.

Changing the way these assignment rules works would have an impact on existing rules, so the correct solution to handle this problem is to create new `add` actions, to be able to choose between adding a new item or completely replace items list.

I close this issue as it is not a bug.

If you want to discuss about this enhancement with community, you can do it on our suggest website: https://suggest.glpi-project.org .

If you want to fund this feature, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us .

Regards

**Closed by cedric-anne** 2021-03-08 12:00 UTC

**Comment by RobertoMarcelino** [comment] 2021-03-08 21:54
Hi Cedric.

 

I would like to be able to help by contributing to this feature, however I am concerned if I will be able to afford it.

 

Would you have a sense of what these costs would represent?

 

Big hugs,

 

Roberto Marcelino

21 9 7288 3373

 

De: Cédric Anne <notifications@github.com> 
Enviada em: segunda-feira, 8 de março de 2021 09:01
Para: glpi-project/glpi <glpi@noreply.github.com>
Cc: Roberto Marcelino Machado <souteimoso@gmail.com>; Author <author@noreply.github.com>
Assunto: Re: [glpi-project/glpi] Associate item to ticket (#8635)

 

Hi,

Unless I am wrong, this is not a bug, but a missing feature.

In rules, at least for ticket actor fields, assign keywork is used to redefine the value of a field, and add keyword is used to add result to existing items. In case of Associated elements, there is no add action, only assign.

Changing the way these assignment rules works would have an impact on existing rules, so the correct solution to handle this problem is to create new add actions, to be able to choose between adding a new item or completely replace items list.

I close this issue as it is not a bug.

If you want to discuss about this enhancement with community, you can do it on our suggest website: https://suggest.glpi-project.org .

If you want to fund this feature, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us .

Regards

**Comment by cedric-anne** [comment] 2021-03-09 08:36
> Would you have a sense of what these costs would represent?

Hi,

To be honest, adding this feature is not a big deal and the most complicated part will be to add automatic test case on it. If you subscribe to a [Basic support subscription](https://glpi-project.org/subscriptions/), we will offer you this development free of charge.
If you are interrested, fill [this form](https://portal.glpi-network.com/contact-us) and our commercial service will send you a quotation mentioning both the subscription and this free of charge feature.

Regards.
