### ISSUE TITLE
[9.5.2] Can't update ticket via API if ticket has Follow-up/Task

### ISSUE THREAD

**Issue by Faoran** [glpi-project/glpi#8780] opened 2021-03-08 12:47 UTC
**Describe the bug**

While trying to update a ticket with at least one follow-up or task via the REST API, I always receive the following error message:

["ERROR_GLPI_UPDATE","You don't have permission to perform this action."]

The user used for the REST API calls has UPDATE rights and is able to update the ticket in the Helpdesk without any problems.

**To reproduce**

1. Create Ticket
2. Add follow-up
3. Try to update e.g. the status of the ticket via REST API

**Comment by Faoran** [comment] 2021-03-10 09:03
Hi,

thanks for your input, the multiple profiles were the culprit. The user had a second profile without the UPDATE right, which was apparently selected as the default one. I've tried using a different user with only one profile with the appropriate rights and it's working now.

Regards

**Comment by cedric-anne** [comment] 2021-03-10 09:11
Thanks for the feedback.

I close this issue as fix would be the same as #8657 .

As fixing the issue is not so simple and as a workaround exists, this issue is not on top of our TODO list.
If you want to speed up its resolution, you may consider subscribe to [professionnal support](https://glpi-project.org/subscriptions/).

Regards

**Closed by cedric-anne** 2021-03-10 09:11 UTC
Labels: Need feedback
