### ISSUE TITLE
Root entity can't change default ticket type

### ISSUE THREAD

**Issue by amatteo78** [glpi-project/glpi#10977] opened 2022-03-15 10:22 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0-rc2

### Bug description

Root entity can't change default ticket type, when open new ticket by email it open like Incident, same on web.

**Comment by cedric-anne** [comment] 2022-03-31 07:14
Hi,

I cannot reproduce. Indeed, when I change the root entity configuration, the `Type` field in new ticket form has the correct default value, whenever I am opening the form in the root entity or in a sub entity.
![image](https://user-images.githubusercontent.com/33253653/160998748-acc6ea15-b919-4784-aa0c-319c34146eaa.png)

Can you try to reproduce on [latest master nightly build](https://nightly.glpi-project.org/glpi/), and provide more details about the way to reproduce ?

**Comment by trasher** [comment] 2022-04-19 06:40
No feedback from a while, closing.

**Closed by trasher** 2022-04-19 06:40 UTC
Labels: beta, Need feedback
