### ISSUE TITLE
[glpi 10.0 beta] Reminders not showing html content on dashboard view

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#10351] opened 2022-01-17 17:50 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

[glpi 10.0 beta]

### Bug description

Inside the reminder menu list, the html content do show.

However when the reminder is shown on the dashboard then the html content shows as source code.
Reminder list with html showing properly :
(Editable markdown cards do show html properly on the dashboard
![Screenshot 2022-01-17 at 18-39-23 GLPI - Reminders](https://user-images.githubusercontent.com/63743077/149817265-7baa87b9-e058-4e4e-8496-7aa6476db75e.png)

dashboard view:(note that the html show properly for the markdown cards)
![Screenshot 2022-01-17 at 18-40-45 GLPI - Interface standard](https://user-images.githubusercontent.com/63743077/149817300-e910e66a-6105-461b-a85b-9c630ff7266e.png)
)

### Your GLPI setup information

GLPI 10 beta 
Debian 4.19.208-1 (2021-09-29) x86_64
PHP version (7.4.27) 

### Anything else?

the html show properly for the markdown cards on the dashboard

**Comment by cconard96** [comment] 2022-01-23 18:49
![Screenshot from 2022-01-23 13-47-34](https://user-images.githubusercontent.com/17678637/150693266-52e0eaea-55af-4243-a77d-329827476b80.png)

Seems OK for me. Was this reminder created in an older version of GLPI?

**Comment by joomlafun** [comment] 2022-01-23 19:44
Hi,

No and to make sure I just recreated the note ; do you put special tags in your html? It's like some tags are being stripped
![image](https://user-images.githubusercontent.com/63743077/150695048-07fd0424-62c4-47c1-ad95-83a7b686ed86.png)
I don't know if those JS errors have anything to do
![image](https://user-images.githubusercontent.com/63743077/150695124-96ed2202-c2c5-48f1-bea0-2141015cf48c.png)

I think I may have an issue with Tinymce as its header does not show fully.
![image](https://user-images.githubusercontent.com/63743077/150695294-171afaea-d2ea-44ca-90e7-f9651f237727.png)

![image](https://user-images.githubusercontent.com/63743077/150695318-e0402c70-ea91-4ab8-94c1-cd0ea210ca79.png)

**Comment by cconard96** [comment] 2022-01-23 20:06
Iframes are not allowed in rich text by default because they are not considered safe and shouldn't work anywhere unless the relevant option is set in the `config/local_define.php` file.

For my test, all I did was drag and drop an image from my PC into the content of a new reminder and set the visibility period so that it was currently visible.

**Comment by joomlafun** [comment] 2022-01-23 20:15
For your information Iframe do work with the "editable markdown card" ; I'm pretty sure I have an issue with tinyMCE as it does not show the "view source" code button as on another demo site.

**Comment by cedric-anne** [comment] 2022-01-25 07:51
Hi,

Maybe you still have a mix between GLPI 9.5 files and GLPI 10.0 files.
Please, backup your `config` and `files` directory, empty your GLPI directory, extract the GLPI 10.0 archive and restore the backuped `config` and `files` directory. This will ensure your GLPI is not using old files.

Regards

**Comment by cedric-anne** [comment] 2022-03-23 08:04
Hi,

Can you reproduce the issue using GLPI 10.0.0-rc3 ?

**Comment by trasher** [comment] 2022-04-19 06:43
No feedback from a while, closing.

**Closed by trasher** 2022-04-19 06:43 UTC
Labels: beta, Need feedback
