### ISSUE TITLE
satisfaction survey missing

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1371] opened 2016-11-30 09:09 UTC
GLPI 9.2

Hello

some users are not able to fill the satisfaction suvey, it is strange because they receive the mail but they don't have the approval for satisfaction survey.

Do you have an idea to fix this issue.

just in self service profile it does not work anymore

I have disabled all plugins but same behavior

**Comment by arthurrschaefer** [comment] 2017-01-04 18:44
Using GLPI 9.1.1 and we also can't see the satisfaction tab under simplified interface.

The notification comes to my requesters, but they don't have the permission to see or even answer the survey!

Any idea of what's going on?

**Comment by adrianeladeira** [comment] 2017-01-04 18:48
I have the problem here! GLPI 9.1.1.

**Comment by diulius** [comment] 2017-01-09 12:18
I have the same problem here! GLPI 9.1

**Comment by adrianeladeira** [comment] 2017-01-09 13:23
Does someone have any clue about when it will be solved?

**Comment by tomolimo** [comment] 2017-01-09 15:43
I confirm, this a bug, I reproduce this behavior

**Comment by tomolimo** [comment] 2017-01-09 16:13
The problem is that a 'post-only' user ('helpdesk' interface) must also have the `Approve solution/Reply survey (my ticket)` right to be able to answer satisfaction survey, but this right is only available for 'normal' users ('central' interface).

**Comment by remicollet** [comment] 2017-01-10 08:49
My thoughts.

The right is "Ticket::SURVEY" so
-  translation should be fixed to reflect only "survey"
- removed from Ticket::canApprove()

The code for TicketSatisfaction is no consistent
- should be managed in canUpdate method (not only about checked "before" display)

And this should be added in "helpdesk" (simplified interface) right.

(as this is a new right, it should probably be granted by default)

**Comment by tomolimo** [comment] 2017-01-10 10:56
So at the end we may have requesters with no rights to 'approve solution/reply survey', is it what we want?
And should we keep 'approve solution' and 'reply survey' in the same right? If not, we must add a new right?

**Closed** 2017-01-11 13:48 UTC
Labels: bug, wip

**Comment by ashish091994** [comment] 2018-08-28 12:56
Hi,
Try this for satisfaction survey , it's working 

Automatic action - createinquest 
Run frequency = Daily
Status = scheduled
Run mode = GLPI
Run period = 0 -24

https://ibb.co/jfz5Hp
https://ibb.co/fnybOU
https://ibb.co/fgYXxp
