### ISSUE TITLE
[9.2 & 9.1.7] Rights problem to assign a ticket without the update right

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#3547] opened 2018-02-13 17:02 UTC
GLPI 9.2 & 9.1.7

Profile of the user:
![right](https://user-images.githubusercontent.com/15138371/36162619-d62e6062-10de-11e8-8c8d-bc7290f38838.png)
so he's not allowed to update the ticket, but assign on the ticket.

Ticket interface with this profile: 
![ticketupdate](https://user-images.githubusercontent.com/15138371/36162692-0af9b882-10df-11e8-99ac-e37bcc7b6769.png)

It can assign a technician or group but it can't save the ticket.

**Comment by Armin83** [comment] 2018-03-02 12:07
I don't know why but if you give the right "see group ticket" it could work but don't will change the status of ticket see  #3655. It must work because the other bug could not exists.

**Comment by trasher** [comment] 2018-03-05 12:28
Should be fixed as of https://github.com/glpi-project/glpi/pull/3615

**Closed by trasher** 2018-03-05 12:28 UTC

**Comment by glpi123** [comment] 2022-01-18 13:23
hello,
i have exactly the same problem describe above with glpi 9.5.5 
i check #3615, nothing work
please help

**Comment by cedric-anne** [comment] 2022-01-18 13:28
> hello, i have exactly the same problem describe above with glpi 9.5.5 i check #3615, nothing work please help

This issue has been closed 4 years ago and is related to GLPI 9.2.x.

Please, try with latest version (9.5.6 or 9.5 nightly build) and, if you can reproduce, create a new issue and provide all requested information.

Regards

**Comment by glpi123** [comment] 2022-01-18 13:44
thank u for your quick response. 
I will try with 9.5.6
