### ISSUE TITLE
after successful use of scripts/cliinstall.php on web interface move to install/install.php

### ISSUE THREAD

**Issue by a11g0rhythm** [glpi-project/glpi#4312] opened 2018-07-08 08:26 UTC
V 9.2.4 clean install
* Steps to reproduce (which actions have you made) :
use  php scripts/cliinstall.php to install

* Expected result :
ready to login glpi window in web browser

* Actual result :
 web browser move to install/install.php

**Comment by trasher** [comment] 2018-07-09 04:06
Cannot reproduce. There will be no new 9.2 releases, closing this one.

**Closed by trasher** 2018-07-09 04:06 UTC
