### ISSUE TITLE
Users' dropdown list in Administration->Groups->Users tab

### ISSUE THREAD

**Issue by apires02** [glpi-project/glpi#1268] opened 2016-11-09 09:43 UTC
Hi,

I'd like to submit a behavior that may be a bug in GLPI version 9.1.
When I want to add a user in a group througth Administration->Groups->Users the dropdown list only contains Root Entity users instead of all the users of the entity in wich the group is.

Note that I don't have this problem with another server using GLPI 0.85.4

**Comment by fgendorf** [comment] 2016-11-09 12:27
Is the same issue https://github.com/glpi-project/glpi/issues/1242, I already fix in my server.

**Comment by apires02** [comment] 2016-11-10 08:29
It works fine thank you

**Comment by orthagh** [comment] 2016-11-10 08:37
duplicate of #1242, i close this one

**Closed by orthagh** 2016-11-10 08:37 UTC
Labels: duplicate
