### ISSUE TITLE
API : upload document : Invoke-RestMethod : ["ERROR_UPLOAD_FILE_TOO_BIG_POST_MAX_SIZE","The file seems too big"]

### ISSUE THREAD

**Issue by Dead-Red** [glpi-project/glpi#8967] opened 2021-04-17 12:11 UTC
**Describe the bug**

We are unable to upload file to glpi from invoke-ResMetod. Upload to Ticket/ID/Document and too : /Document

The same file is successfully uploaded successfuly in curl

**To reproduce**

# GLPI REST API CONFIG :
$AppURL =     "https://glpi.xxxxxxxxxxxx.fr/apirest.php"
$UserToken = "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
$AppToken =   "XXXXXXXXXXX"

$ID = 161
$ItemType = "Ticket"
$SubItemType = "Document"
$manifest = @{}

$SessionToken = Invoke-RestMethod "$AppURL/initSession" -Method Get -Headers @{"Content-Type" = "application/json";"Authorization" = "user_token $UserToken";"App-Token"=$AppToken}

$FileContent = [System.IO.File]::ReadAllBytes("C:\temp1\clear.png")

$input = New-Object System.Collections.ArrayList
$type =New-Object System.Collections.ArrayList
$filename =New-Object System.Collections.ArrayList

$input = @{input=@{"name"="titre";"_filename"="clear.png";"tickets_id"="161"}}
$type = @{"type"="application/json"}
$filename =@{"filename[0]"="C:\temp1\clear.png"}

$manifest.Add("uploadManifest",$input)
$manifest.Add("type=","application/json")
$manifest.Add("filename[0]=",@("C:\temp1\clear.png"))

$json = @($manifest | ConvertTo-Json)
#Display Convert to JSON
#$json

Invoke-RestMethod "$AppURL/$($ItemType)/$($ID)/$($SubItemType)" -Method Post -Headers @{"session-token"=$SessionToken.session_token; "App-Token" = $AppToken} -Body ([System.Text.Encoding]::UTF8.GetBytes($json)) -ContentType 'multipart/data'
      
## Test autre ContentType  

Invoke-RestMethod "$AppURL/$($ItemType)/$($ID)/$($SubItemType)" -Method Post -Headers @{"session-token"=$SessionToken.session_token; "App-Token" = $AppToken} -Body ([System.Text.Encoding]::UTF8.GetBytes($json)) -ContentType 'multipart/form-data'

#Kill session
Invoke-RestMethod "$AppURL/killSession" -Headers @{"session-token"=$SessionToken.session_token; "App-Token" = "$AppToken"}

**Expected behavior**
File uploaded to Document attached to ID or uploaded to Document

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.3
```

where is the problem ?

Thank's by advance

**Comment by trasher** [comment] 2021-04-19 06:03
You have to try with latest stable release

**Comment by Dead-Red** [comment] 2021-04-20 08:02
Hello,

I have update my glpi to 9.5.5 and the problem still present. And if i try to upload same file from Postman all is good, and if i get the Powershell command from postman the problem still the same.

thank's for your help.

**Comment by cedric-anne** [comment] 2021-04-20 08:09
Hi,

If it works using Postman, then there is no bug on GLPI side.

To get support, you can ask for community support on [forum](https://forum.glpi-project.org/) or [get a subscription for a professionnal support](https://glpi-project.org/subscriptions/).

I close this issue as it is not a bug.

Regards

**Closed by cedric-anne** 2021-04-20 08:09 UTC
Labels: Need feedback

**Comment by J-C-P** [comment] 2021-04-20 09:02
Yeah, right... "If it works using Postman, then there is no bug on GLPI side."

Honestly, I use GLPI for more than 10 years (since 0.72). I signed the first partnership in Luxembourg (we still are the only one, I think), I developed a powershell module to interact with GLPI (you know, Powershell, the script language nobody never use in modern IT), I think I can say I know the product.

The goal here is to make your product more open, more accessible, to make integration easier (the API is the best way to do that).

I really don't know what is wrong with you people... Having a considerate look at someone question might look the right thing to do.

I will open a ticket using our partnership subscription to, at least, have some technical answer.

Thanks a lot for making things so easy for your community (which is the heart of your success, do not forget that ! )...

**Comment by cedric-anne** [comment] 2021-04-20 09:41
I closed this issue because it is not strictly speaking a bug in GLPI but a problem in the interaction between a third party application and GLPI.

Because the query was reported to work using Postman, I considered the source of the problem to be only in the third-party application, and therefore a Github issue was not the best place to get help on this issue. Indeed, the forum is the best place to get help from the community, and we strive to centralize all community support there, in particular by redirecting to the forum any support request not relating to a GLPI bug.

Feel free to reopen if you consider it is a bug.

**Comment by Dead-Red** [comment] 2021-04-20 11:26
Hello,

Thank's for your second answer.

Maybe a developper could be retry my script and "monitor" the result in GLPI. I think you have more skills to know what is wrong with the expected data.

The problem is same with powershell 7.2.

And before open a bug here we have open a post in Forum, stackoverflow, ...

Forum :  You can look the thread
https://forum.glpi-project.org/viewtopic.php?pid=484272#p484272

stackoverflow :
https://stackoverflow.com/questions/67075197/curl-powershell-invoke-restmethod-to-glpi-api-upload-document

And we are not alone with this problem (look at google).

Thank's for your contribution J-C-P

**Comment by cedric-anne** [comment] 2021-04-20 11:59
As far as I know, most active community contributors that have skills on Powershell are active on the forum, so forum is still the best place to get support for your problem.

As I do not have any skills on Powershell, and as I do not even have the required environment to run your script, I cannot even help.

**Comment by lobamo** [comment] 2021-08-19 13:48
`public function createTicket(string $path, string $name, string $date, string $content)
    {
         $ch = curl_init();

         // configuration des options
         curl_setopt($ch, CURLOPT_URL, $this->host . '/' . $path);
         curl_setopt($ch,CURLOPT_POST, 1);                //0 for a get request
         curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
         curl_setopt($ch,CURLOPT_RETURNTRANSFER, true);
         curl_setopt($ch, CURLOPT_HTTPHEADER, array(
             'App-Token:' . $_SERVER["APP_TOKEN"],
             'Session-token:' . $this->session_token['session_token'],
         ));
         $arguments = array(
            'name' => $name,
            'date' => $date,
            'content' => $content
         );
         curl_setopt($ch, CURLOPT_POSTFIELDS,
            $arguments);
         // exécution de la session
         if( ! $results = curl_exec($ch))
         {
             trigger_error(curl_error($ch));
         }
         curl_close($ch);
         return $results;

    }`

`public function testRequest()
        {
                        // given 
            $host = 'http://dev-glpi/apirest.php';

            $credentials = array(
                            'username' => 'glpi',
                            'password' => 'glpi'
                        );
            
            $service = new GlpiBase($host, $credentials);
            
            $service->connexion();
            $results = $service->createTicket('Ticket', 'groot', date('l jS \of F Y h:i:s A'), 'hello worl');
            dump($results);

        }`

This script without any file when performing post request return me the error ["ERROR_UPLOAD_FILE_TOO_BIG_POST_MAX_SIZE","The file seems too big"] too

**Comment by alekyxander** [comment] 2023-10-02 20:54
> Olá,
> 
> Atualizei meu glpi para 9.5.5 e o problema ainda está presente. E se eu tentar fazer upload do mesmo arquivo do Postman, tudo estará bem, e se eu receber o comando Powershell do postman, o problema continuará o mesmo.
> 
> Obrigado pela ajuda.

Olá irmão pode passar o que vc usou no postamn para envio
