### ISSUE TITLE
Database schema is not up to date after migration from 9.x to 10.0.7

### ISSUE THREAD

**Issue by AldarisPale** [glpi-project/glpi#14788] opened 2023-05-29 11:43 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When debugging https://github.com/glpi-project/glpi/issues/14735 I noticed the following row in file files/_log/warning_during_migration_to_10.0.7.log:

```
The database schema is not consistent with the current GLPI version.
It is recommended to run the "php bin/console database:check_schema_integrity" command to see the difference.
```
When running `php bin/console database:check_schema_integrity` the resulting output is more 3145 lines. It's mostly column type text -> mediumtext.

When running php bin/console database:update it tells that GLPI version is 10.0.7 and GLPI database version is 10.0.7. No migration needed.

**Comment by cconard96** [comment] 2023-05-29 11:48
This warning doesn't necessarily mean the upgrade to 10.0.7 from the previous version failed. At some point though, an update didn't finish as expected. The reason you see this now is because the schema checker was added in a recent update.

The best solution is to manually make the adjustments needed in the database to ensure it is consistent with what GLPI expects.

**Comment by AldarisPale** [comment] 2023-05-29 13:33
Thanks, @cconard96.
It looks like the problem is introduced when migration to utf8mb4 is done, as there is unit test which at least in text asks to ignore `mediumtext` instead of expected `text` at https://github.com/glpi-project/glpi/blob/52224e88f365c48f425264bbe09c3062abe8b1e6/tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php#L416
and it looks like this check is not ignored in `php bin/console database:check_schema_integrity`

DB is running on AWS RDS: https://aws.amazon.com/rds/mysql/

**Comment by AldarisPale** [comment] 2023-05-29 13:46
Update: after going over the diff manually, in all reported cases the issue was that field type is `mediumtext` in database while GLPI expects `text`. So, probably a non-issue in reality, just false alarms in the diff tool.

**Comment by AldarisPale** [comment] 2023-05-30 08:57
@cedric-anne 
> What is the exact command you are executing? What is the content of your `config/config_db.php` file (you can redact user/pass)?

1. Command being run: `php bin/console database:check_schema_integrity`
2. Contents of `config/config_db.php`
```
<?php

define("MYSQL_DB_HOST", getenv('MYSQL_DB_HOST'));
define("MYSQL_DB_USER", getenv('MYSQL_DB_USER'));
define("MYSQL_DB_PASSWORD", getenv('MYSQL_DB_PASSWORD'));
define("MYSQL_DB_NAME", getenv('MYSQL_DB_NAME'));

class DB extends DBmysql {
   public $dbhost = MYSQL_DB_HOST;
   public $dbuser = MYSQL_DB_USER;
   public $dbpassword = MYSQL_DB_PASSWORD;
   public $dbdefault = MYSQL_DB_NAME;
}
```
3. Since config is read in from env (since it's running in kubernetes), the relevant env variables are:
```
MYSQL_DB_HOST=xxxxxxxxxx.rds.amazonaws.com
MYSQL_DB_NAME=glpi
MYSQL_DB_USER=yyyyyyyyyy
MYSQL_DB_PASSWORD=zzzzzzzzzzzz
```

**Comment by cedric-anne** [comment] 2023-05-30 09:05
It seems that you overrided the `config/config_db.php` file.

Migration tokens are considered as differences because GLPI is not aware that migrations were done. You config file should probably contain following lines:
```php
<?php
class DB extends DBmysql {
   ...
   public $use_utf8mb4 = true;
   public $allow_myisam = false;
   public $allow_datetime = false;
   public $use_timezones = true;
   public $allow_signed_keys = false;
}
```

I close this issue as it is not a bug.

**Closed by cedric-anne** 2023-05-30 09:05 UTC
Labels: Need feedback

**Comment by AldarisPale** [comment] 2023-06-01 08:23
Thanks, @cedric-anne !
Quilty as charged for overwriting config file.
However after thinking about it for some time, perhaps it would make sense to move db booleans to separate file to keep connection parameters in a separate file as future feature as I believe this would help with deployments in containerized environments / CI/CD auto deploy environments.

After thinking about it a bit more - is there any reason to store those booleans at all, since GLPI already has autodiscovery feature: https://github.com/glpi-project/glpi/blob/f8650dc32554100534cc88066f12faf11968bdd2/src/DBmysql.php#L2051 ?

**Comment by cedric-anne** [comment] 2023-06-02 11:24
Maybe this can be improved, indeed.
