### ISSUE TITLE
Need to click 2 times to fill a field

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#487] opened 2016-02-24 13:27 UTC
Example (the issue has been tested on firefox and chrome):

- I create a new dropdown value
- I'm redirected to a the same to insert a new dropdown value
- I need to click 2 times on the name field (for example) in order to fill the form. The first time, I lost the focus

**Comment by orthagh** [comment] 2016-02-25 14:35
Duplicate of #487

**Closed by orthagh** 2016-02-25 14:35 UTC
Labels: bug
