### ISSUE TITLE
locked ticket after itself update

### ISSUE THREAD

**Issue by EugeneSE79** [glpi-project/glpi#5803] opened 2019-04-16 06:51 UTC
We using "Item Locks" for blocking tickets while somebody is working with tickets. Tickets is blocking by author of update.
In version 9.3 all work fine. 
After update to version 9.4.1.1 and than 9.4.2 beginning problem.
When ticket is updated and pressed button "Save" splashing message "Locked by you!	Unlock Ticket #....".
----------------------------------------------------------------

Information about system installation & configuration
--
[code]   GLPI 9.4.2 ( => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux servicedesk 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64 PHP 5.6.40 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, 	libxml, mbstring, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, 	sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, 	zlib) Setup: max_execution_time="180" memory_limit="156M" post_max_size="10M" safe_mode="" session.save_handler="files" 	upload_max_filesize="15M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.40 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.6.43 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (5.6.43) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to files directory is protected : OK SELinux mode is Disabled

**Comment by trasher** [comment] 2019-04-16 06:53
Possible duplicate of https://github.com/glpi-project/glpi/issues/5799

**Closed** 2019-04-16 06:55 UTC
Labels: duplicate
