### ISSUE TITLE
display memory size

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4918] opened 2018-11-15 11:12 UTC
https://forum.glpi-project.org/viewtopic.php?id=165949

Can someone reproduce this issue?

**Comment by trasher** [comment] 2018-11-22 08:10
I'm not able to reproduce on 9.3/bf branch.

As far as I understand, the notice the user give on the forum talks about a "non numeric value"; so after that, this may be wrong. In that case, there is certainly something wrong in his database, but he do not provide enough informations.

Guess current issue is not the initial problem, closing for now.

**Closed by trasher** 2018-11-22 08:10 UTC
