### ISSUE TITLE
Slow query in dashboard in this function nbItemByFk

### ISSUE THREAD

**Issue by calidadcarm** [glpi-project/glpi#13879] opened 2023-01-25 20:13 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.12

### Bug description

**GROUP BY `glpi_itilcategories`.`completename` is very slow.   7.266 sec / 0.000 sec**

SELECT `glpi_itilcategories`.`completename` AS `fk_name`, `glpi_itilcategories`.`id` AS `fk_id`, COUNT(DISTINCT(`glpi_tickets`.`id`)) AS `cpt` FROM `glpi_tickets` LEFT JOIN `glpi_itilcategories` ON (`glpi_itilcategories`.`id` = `glpi_tickets`.`itilcategories_id`) WHERE `glpi_tickets`.`is_deleted` = '0' AND (`glpi_tickets`.`entities_id` IN ('1')) GROUP BY `glpi_itilcategories`.`completename` ORDER BY `cpt` DESC LIMIT 50

**Is better GROUP BY `fk_id` 3.125 sec / 0.000 sec**

SELECT `glpi_itilcategories`.`completename` AS `fk_name`, `glpi_itilcategories`.`id` AS `fk_id`, COUNT(DISTINCT(`glpi_tickets`.`id`)) AS `cpt` FROM `glpi_tickets` LEFT JOIN `glpi_itilcategories` ON (`glpi_itilcategories`.`id` = `glpi_tickets`.`itilcategories_id`) WHERE `glpi_tickets`.`is_deleted` = '0' AND (`glpi_tickets`.`entities_id` IN ('1')) GROUP BY `fk_id` ORDER BY `cpt` DESC LIMIT 50

### Relevant log output

```shell
[2023-01-19 09:16:57] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 402
  *** MySQL query error:
  SQL: SELECT `glpi_itilcategories`.`completename` AS `fk_name`, `glpi_itilcategories`.`id` AS `fk_id`, COUNT(DISTINCT(`glpi_tickets`.`id`)) AS `cpt` FROM `glpi_tickets` LEFT JOIN `glpi_itilcategories` ON (`glpi_itilcategories`.`id` = `glpi_tickets`.`itilcategories_id`) WHERE `glpi_tickets`.`is_deleted` = '0' AND (`glpi_tickets`.`entities_id` IN ('1')) GROUP BY `glpi_itilcategories`.`completename` ORDER BY `cpt` DESC LIMIT 50
  Error: Error writing file '/tmp/MYfd=801' (OS errno 28 - No space left on device)
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:969                          DBmysqlIterator->execute()
  inc/dashboard/provider.class.php:529               DBmysql->request()
  inc/dashboard/provider.class.php:182               Glpi\Dashboard\Provider::nbItemByFk()
  :                                                  Glpi\Dashboard\Provider::__callStatic()
  inc/dashboard/grid.class.php:1007                  call_user_func_array()
  ajax/dashboard.php:124                             Glpi\Dashboard\Grid->getCardHtml()
  {"user":"13468@glpi-pru-sa2"}
```

### Page URL

glpi/front/central.php

### Steps To reproduce

start glpi
central dashboard 

### Your GLPI setup information

\inc\dashboard\provider.class.php

### Anything else?

         //'GROUPBY'   => "$fk_table.$name",
            'GROUPBY'   => "fk_id",
            'ORDERBY'   => "cpt DESC",
            'LIMIT'     => $params['limit'],

**Comment by cedric-anne** [comment] 2023-01-26 06:35
Hi,

MySQL error says:
> `Error: Error writing file '/tmp/MYfd=801' (OS errno 28 - No space left on device)`

You probably have to do some cleaning on your server filesystem.

I close this issue as it it not a bug.

**Closed by cedric-anne** 2023-01-26 06:35 UTC
