### ISSUE TITLE
[9.1.3] Bug: you can see the open tickets in the tab of the tickets associated with the item

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#2151] opened 2017-05-04 06:48 UTC
If you go to an item and select the tickets tab you can see the last 6 tickets opened + the number of tickets associated.

**Comment by trasher** [comment] 2017-05-04 08:00
Could you please precise? I do not understand what the problem is.

Is it related to #1916 or #2078?

**Comment by jsamaniegog** [comment] 2017-05-04 08:56
Ok, sorry, i try again:

1. Go to an asset.
2. Click on tickets tab.
3. You will see open tickets that are not associated with the asset.

**Comment by ArriMa** [comment] 2017-05-04 09:56
Me too, after upgrade to 9.1.3 the counter of linked ticket (showed in the TAB) are correct, but the list showed contains tickets that do not contain that object.

**Comment by ArriMa** [comment] 2017-05-04 10:05
TEMPORARY WORKAROUND: click on "Show All" link, the list of ticket with that associated item is correct.

**Comment by yllen** [comment] 2017-05-10 16:03
Not agree with the purpose of correction

`// in list of ticket linked to the object, i also display incoming ticket if i have correct right`
            `if (Session::haveRightsAnd(self::$rightname, [self::READASSIGN, self::ASSIGN])) {`
              ` $restrict .= " AND glpi_tickets.status = ".self::INCOMING;`
            `}`
           `$restrict .= ")";`

**Comment by tyronewyatt** [comment] 2017-05-17 03:53
Is this another duplicate of https://github.com/glpi-project/glpi/issues/2135 ?

**Comment by trasher** [comment] 2017-05-17 06:20
@tyronewyatt no; this is something else.

**Comment by yllen** [comment] 2017-05-22 14:36
another post in forum: http://forum.glpi-project.org/viewtopic.php?id=157693

**Comment by trasher** [comment] 2017-06-02 08:45
Original commit that cause the issue has just been reverted. This solves current issue.

**Closed by trasher** 2017-06-02 08:45 UTC
Labels: bug
