### ISSUE TITLE
Change storage engine to innodb

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#644] opened 2016-05-12 05:11 UTC
Pros:
- better locking mechanism (performance)
- transaction (first needed by test suite, can be later used in the app)
- foreign keys for db integrity (need a lot of change in the schema, and probably a rewrite of backup / restore)

Cons:
- can be missing in some shared hosting env.

**Comment by tomolimo** [comment] 2016-05-12 06:19
Hello,

My proposal is to permit both myIsam and innodb engines.
Or better: to use postgresql, as it seems that postgresql can optimize itself☺!
Could it be done using PDO? One interesting link on the performances of PDO is: http://archive.jnrbsn.com/2010/06/mysqli-vs-pdo-benchmarks


Olivier MORON
GLPI Development

RAYNET SAS
Tel : +33 476 33 4952
Fax: +33 4 76 70 56 63

**Comment by ddurieux** [comment] 2016-05-12 06:25
If we decide to change to PDO, need to remove the very big queries with many joins and made only simple queries (anhance performances), I think about search engine but not only.

So yes it's a very big work, but if need modify all queries, perhaps do with the best way ;)

**Comment by tomolimo** [comment] 2016-05-12 06:53
Currently on my test server, I’ve been using innodb instead of myisam for 1 year without any problem.
The main advantages I can see for this are:

1)      Better optimization of server memory use (cache, and so on)

2)      And with recent mysql versions (> 5.6.27), when an optimization of the db is done (via cron task dboptimize), the tables are not locked, and such will not block any GLPi use.


Olivier MORON
GLPI Development

RAYNET SAS
Tel : +33 476 33 4952
Fax: +33 4 76 70 56 63

**Comment by trasher** [comment] 2016-09-08 14:07
Does some hosting providers have a so old MySQL version that does not provide innodb? :)

As for using PDO... I'm affraid it would be a very huge work; maybe you could open another ticket for that.

**Comment by tomolimo** [comment] 2016-09-08 14:34
I have been using innoDB on my test server for 2 years without any troubles...
And I plan to use it for next 9.1 on production server too. As far as I can see there are only some troubles with the fulltext indexes when there are two (or more fields) in the fulltext index: innoDB doesn't mange to have two fields in fulltext indexes (this can be done via two fulltext indexes). So it concerns `glpi_knowbaseitems` and `glpi_knowbaseitemtranslations` for which it's possible to declare two indexes instead of only one.

**Comment by trasher** [comment] 2016-09-08 14:59
Also, fulltext index are only available in MySQL 5.6+ I do not know wich database versions we plan to suppport, but actual tests on travis are run against mariadb 5.5 for php 5.4 and 5.5.

I did not read about the index limitations you pointed out; have you got any reference?

I guess using 2 indexes should be ok, wa can also keep some tables using myisam.

**Comment by tomolimo** [comment] 2016-09-08 16:02
See #771

**Comment by tomolimo** [comment] 2016-09-08 16:06
I believe I have mixed some information about these indexes. The real problem is that innodb doesn't handle the indexes the same way myisam does. 
Sorry for that. 
Regards 
Tomolimo

**Comment by tomolimo** [comment] 2016-09-09 06:16
Hello,
To explain my wrong sentence 

> As far as I can see there are only some troubles with the fulltext indexes when there are two (or more fields) in the fulltext index: innoDB doesn't manage to have two fields in one fulltext index (this can be done via two fulltext indexes).

Yes, InnoDB supports multi-columns in fulltext indexes, but the way it is managed is not the same way than MyISAM does. To quote the info in mysql documentation (http://dev.mysql.com/doc/refman/5.7/en/fulltext-restrictions.html): 

> The MATCH() column list must match exactly the column list in some FULLTEXT index definition for the table, unless this MATCH() is IN BOOLEAN MODE on a MyISAM table. For MyISAM tables, boolean-mode searches can be done on nonindexed columns, although they are likely to be slow.

regards,
Tomolimo

**Comment by trasher** [comment] 2016-09-09 06:40
@tomolimo thank you for the clarifications; even if I must admint I do not understand all the implications ;-)

Well, from my point of view, the problem is still the MySQL version requirement (5.6.4).

On EL-6, there is only 5.1 available; EL-7 comes with mariadb 5.5; but 10.0.5 would be required (see https://mariadb.com/kb/en/mariadb/fulltext-index-overview/). On Fedora, it would be OK.

Maybe newer versions are available from SCLs, I did not check. I guess the issue would be the same on some other distros, and I do not speak of existing systems that should also run a quite older release :/

**Comment by ddurieux** [comment] 2016-09-09 06:44
Perhaps the question is not the right, because _glpi_knowbaseitems_ and _glpi_knowbaseitemtranslations_ in most cases not have thousand and thousands lines in the tables, so the search will be a little more slow but not long, so not have fulltext indexes can be dropped

**Comment by tomolimo** [comment] 2016-09-09 06:45
EL?
SCL?
:smiley: 

For me it's not a problem as if we just add the missing fulltext indexes as mentioned above, then our DB is compliant with both engines. Let' say version 5.6.4+ when using innodb and 5.x when using myisam

**Comment by ddurieux** [comment] 2016-09-09 06:47
For DB, I have begin a POC with _phinx_, and manage migration (and rollback), compatible sqllite3, mysql, postgresql, mssql (so for a nearly issues I will open for that :p), you can see the files here: https://github.com/ddurieux/glpi/tree/master%2Blessql/db/migrations

**Comment by remicollet** [comment] 2016-09-09 06:48
* EL = Enterprise Linux (RHEL, CentOS and other clones)
* SCL = Software Collections, the current way Red Hat provides newer versions (e.g. PHP 5.6, MariaDB 10.1, MySQL 5.6...)

**Comment by tomolimo** [comment] 2016-09-09 06:50
thank you, I'm still a newbie in the Linux world :smile:

**Comment by trasher** [comment] 2016-09-09 06:50
@tomolimo sorry.
EL stands for "Enterprise Linux" - Red Hat and derivates (centos, scientific linux, ...)
SCL stands for software collections; a way to install different versions of some softs on the same server (PHP, MariaBD, and some other). SCL is a good way to get some recent PHP versions for example on systems that ships old ones.

**Comment by tomolimo** [comment] 2016-09-09 06:51
thank you

**Comment by trasher** [comment] 2016-09-09 06:55
(@remicollet was once again faster than me!)

I do not really agree to keep myisam for < 5.6.4 users; for one or two tables in the whole schema it would be a shame.

@ddurieux proposition should be a solution, I do not know GLPI nor this specific part enough to have a point of view...

**Comment by ddurieux** [comment] 2016-09-09 06:56
I'm not enough explicit, for MySQL it's for innodb :p

**Comment by tomolimo** [comment] 2017-10-12 14:07
Hello,
To give an input on this topic regarding InnoDB: we are running GLPI 9.1.2 on our production server with InnoDB tables.
We have been running InnoDB since March 11th 2017, date of the migration.
Regards,
Tomolimo

**Comment by orthagh** [comment] 2018-01-25 14:56
done in #3439 (merged)

**Closed by orthagh** 2018-01-25 14:56 UTC
Labels: enhancement
