### ISSUE TITLE
Notification ticket.solution.description

### ISSUE THREAD

**Issue by Hellden** [glpi-project/glpi#4309] opened 2018-07-07 16:39 UTC
Hi,

GLPI 9.3

There is a problem with the balise notification ticket.solution.description. The mail received shows N / A and not the solution.

Do you have a workaround ?

Thx

**Comment by roshanroche** [comment] 2018-07-07 17:29
Duplicate of #4266

**Comment by Hellden** [comment] 2018-07-07 17:29
Bonjour,

Cette adresse de messagerie n'est plus valide. Merci d'utiliser ma nouvelle adresse: rchapotin@gepy89.fr

Cordialement,

**Closed** 2018-07-08 06:40 UTC
Labels: duplicate
