### ISSUE TITLE
Card count its different from filter results

### ISSUE THREAD

**Issue by detruxdeveloper** [glpi-project/glpi#7957] opened 2020-09-15 19:38 UTC
**Describe the bug**

Example:

I have 3 technician groups in a Entity, and none can see the tickets of others.

In assistance >, If I add a card "Assigned Tickets", it will show the quantity of Assigned tickets in the whole entity, including others technician groups tickets even if i dont have access. 

**To reproduce**

1. Create 3 tech group with 1 tech users in each;
2. Set the profile of the tech users to see only his group tickets;
3. assign 1 ticket por tech group;
4. In assitance > Assigned tickets, it will show 3 tickets, but when the tech user click on it, it will show only one tickets because thats his permission.

**Expected behavior**

Edit or add an option called "Number of new tickets OF MY GROUP";

**Screenshots**

This is the card count. This number includes all groups assigned tickets:
![image](https://user-images.githubusercontent.com/49076842/93256142-4806ed00-f771-11ea-91eb-39b6d378eda6.png)

But the result shows only the tickets he have access, in that his tech group tickets.
![image](https://user-images.githubusercontent.com/49076842/93256282-82708a00-f771-11ea-9c00-6ac8dab47480.png)

**Comment by orthagh** [comment] 2020-09-24 09:16
Hello @detruxdeveloper 

I work on some dashboard improvements (see #7793), and i fixed the issue in that pr.
The issue is the miss of application of profile rights in the sql queries of assistance queries.

I don't know if the fix will be in the incoming 9.5.2 but i hope to be ready for it (otherwise it will be in 9.5.3)

**Closed** 2020-09-29 06:18 UTC
