### ISSUE TITLE
Global asset not displayed

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1953] opened 2017-03-14 14:34 UTC
Error: Unknown column 'glpi_softwarelicenses.contact' in 'field list'
  Backtrace :
  inc/search.class.php:921                           
  inc/search.class.php:97                            Search::constructDatas()
  inc/search.class.php:80                            Search::showList()
  front/allassets.php:46                             Search::show()

**Comment by trasher** [comment] 2017-03-14 14:59
Is not that one already fixed in the 9.1/bugfixes branch?

**Comment by trasher** [comment] 2017-03-31 09:23
Sounds like fixed in 9.1/bugfixes; cannot reproduce

**Closed by trasher** 2017-03-31 09:23 UTC
Labels: bug

**Comment by orthagh** [comment] 2017-04-28 09:32
duplicate #1329
