### ISSUE TITLE
Bug in rules when authorization a new user

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1705] opened 2017-01-25 18:01 UTC
When authorization a new user with email finished by @sub.domain.ru (example), is not assigned to the desired entity.
GLPI 9.1.2
Not working at all on really. Assigned "root entity" always.
This is critical problem.

Example:
![glpi_rules_bug](https://cloud.githubusercontent.com/assets/17082164/22302554/54c29128-e340-11e6-9943-4b13a9cc2da3.png)

![glpi_rules_bug_1](https://cloud.githubusercontent.com/assets/17082164/22302601/7c6d3340-e340-11e6-83ea-c8ef45c61be2.png)

![glpi_rules_bug_2](https://cloud.githubusercontent.com/assets/17082164/22302559/59c21a36-e340-11e6-9c9f-f971f1e0076b.png)

**Comment by AircraftRu** [comment] 2017-01-27 09:39
Please, help me with this problem!
This is the big problem on working GLPI.

I explane, the problem with the distribution of organizations, not to the test. This description above is an example!

**Comment by AircraftRu** [comment] 2017-01-28 17:19
Give feedback. Maybe something is not clear. This is a bug.

**Comment by Danyt83** [comment] 2017-04-05 08:48
Bonjour,
nous avons le même problème,
172 entités, 11 800 utilisateurs, connexion au travers d'un portail sso.
Nous avons une règle d'affectation (entité+profil) sur le critère : ENTPersonFonctions (commence par) issus de notre sso.
![image](https://cloud.githubusercontent.com/assets/15905496/24697334/11a5194a-19ed-11e7-8bc9-6f91acfa01d8.png)

Aucun problème lors du test des règles.
Lors de la connexion d'un nouvel utilisateur, il est affecté à l'entité racine.
Dans les logs de l'utilisateur nous avons ça : 
![image](https://cloud.githubusercontent.com/assets/15905496/24697001/d2b58446-19eb-11e7-822f-fb38123a050b.png)
Pouvez vous nous aidez ?
nous avons fait la mise à jour en 9.1.2 il y a 2 semaines, déjà 8 000 utilisateurs avec le problème.

**Comment by orthagh** [comment] 2017-04-21 12:23
@AircraftRu, I think i got the bug.
In case of ldap users, email criteria is never set in input for rules, it seems dedicated to others sync methods (SSO, IMAP, etc). I'm currently working on a fix for that.
Could you confirm the users you try to match are imported from ldap ?

@Danyt83 Could you also confirm the type of sync of the user ? 
You'll find the information into the user form  in authentication field: 
![image](https://cloud.githubusercontent.com/assets/418844/25277231/1584f6bc-269e-11e7-8e28-60b154f0790a.png)

**Comment by Danyt83** [comment] 2017-04-21 12:41
@orthagh : 
![image](https://cloud.githubusercontent.com/assets/15905496/25277842/a1edae62-26a0-11e7-8da8-6509ffb749c0.png)

**Comment by orthagh** [comment] 2017-04-21 13:08
@Danyt83, in Synchronisation tab, you could force ldap auth, and force the synchronisation.
In that case, you rule criteria will match

**Comment by Danyt83** [comment] 2017-04-21 13:22
Exactly, but in the case of connecting a new user it does not work. Thanks for the tip.

**Comment by orthagh** [comment] 2017-04-21 13:33
In case of the connection of a new user, you shouldn't have "Not yet authenticated" mode

**Comment by AircraftRu** [comment] 2017-04-21 20:05
@orthagh 
> Could you confirm the users you try to match are imported from ldap ?

Yes, I import from LDAP

**Comment by trasher** [comment] 2017-04-24 06:25
Hi,

Could you try the fix proposed in #2083 and confirm it solves your issues?

**Comment by Danyt83** [comment] 2017-04-24 08:25
Hello,
I modified the 2 files and tested the connection of a new user. The user is assigned to the root entity.
![image](https://cloud.githubusercontent.com/assets/15905496/25328487/53a237f2-28d8-11e7-8f72-3d36c9d0d7fd.png)

So it's not resolved. I can carry out other tests if necessary.
thank you.

**Comment by orthagh** [comment] 2017-04-24 15:39
hello @Danyt83 

As i said previously, your issue is currently that your user is set to "Not yet authentified".
It's not normal, and i think its another issue.

Could you precise the workflow for importing yours users ?
- As the picture mention DN, i think you imported user from LDAP, no ?
- Did the user was previously present in GLPI (imported so) ?
- Is the login still successful (with bad entity/profile) ?
- what's the auth part (like your screenshot) after the login ?

**Comment by orthagh** [comment] 2017-04-24 15:48
Anyway, it seems that we have a regression since #1670 
Currently testing it

**Comment by Danyt83** [comment] 2017-04-25 11:37
Hello,

I'm sorry if I misunderstood the problem.

We connect through a SSO portal : 
![image](https://cloud.githubusercontent.com/assets/15905496/25382990/421ee984-29ba-11e7-9c90-ae7934d805b2.png)

The first time you log in, the user is imported from the following LDAP settings:
![image](https://cloud.githubusercontent.com/assets/15905496/25383226/71813ece-29bb-11e7-8797-c47fe75b23f1.jpg)

Users are not imported manually.

The user is successfully logged on but is assigned to the root entity with the default profile.

Thank you for your help

**Comment by orthagh** [comment] 2017-04-25 11:40
Ok so CAS SSO, more difficult to test :)

Could you confirm the auth type after import (and before any connection) ?

**Comment by Danyt83** [comment] 2017-04-25 11:46
How can I do that?

**Comment by orthagh** [comment] 2017-04-25 11:48
in user form, like in your https://github.com/glpi-project/glpi/issues/1705#issuecomment-296573868 ,please, could you give me the sentence defined in "Authentication".

No need for a full capture.

**Comment by Danyt83** [comment] 2017-04-25 11:54
If the user connects through the portal sso, and it is not created previously we have this:
![image](https://cloud.githubusercontent.com/assets/15905496/25383950/8e03b1f0-29be-11e7-94ec-f431ed533ed0.png)

If the user is imported from the LDAP:
![image](https://cloud.githubusercontent.com/assets/15905496/25383989/b94ec066-29be-11e7-9139-925e87f929c2.png)

**Comment by orthagh** [comment] 2017-04-25 11:57
to be sure, if the user imported from ldap connects for the first time, credentials are correctly applied ?

**Comment by Danyt83** [comment] 2017-04-25 11:57
yes.

**Comment by orthagh** [comment] 2017-04-25 11:59
ok, i think i got the issue.
Will do a fix this afternoon

**Comment by Danyt83** [comment] 2017-04-25 12:00
Thank you so much !

**Comment by orthagh** [comment] 2017-04-25 12:09
@Danyt83, could you test the following change: https://github.com/glpi-project/glpi/pull/2083/commits/fe57152db27c5003225765aa41df1a2214edcd2b ?

**Comment by Danyt83** [comment] 2017-04-25 12:15
Yes it works !
![image](https://cloud.githubusercontent.com/assets/15905496/25384685/8b949fa8-29c1-11e7-8ff2-cb90cdfe3d7c.png)

a big thank-you !

**Closed** 2017-04-25 12:40 UTC
Labels: bug
