### ISSUE TITLE
GLPI 9.4.5 - 9.5.5 upgrading results error mysqlnd driver required

### ISSUE THREAD

**Issue by itprotj** [glpi-project/glpi#9167] opened 2021-06-11 12:17 UTC
**Describe the bug**

Installation of GLPI 9.5.5 causes message "Use of mysqlnd driver is required for exchanges with the MySQL Server".
mysqlnd driver is installed and active.

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

Main index page when all 9.5.5 files have been uploaded.

**To reproduce**

N/A

**Expected behavior**

Upgrade page instead of error

**Screenshots**

![2021-06-11_21-56-52](https://user-images.githubusercontent.com/7754695/121684862-9d0a4080-cb02-11eb-8a87-a0b3268d5a65.jpg)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Prior to upgrade (currently on 9.4.5) this is what I see:
```
Server
 
Operating system: Linux hostingplatform.net.au 3.10.0-962.3.2.lve1.5.44.3.el7.x86_64 #1 SMP Mon Feb 22 04:35:33 EST
	2021 x86_64
PHP 7.2.34 litespeed (Core, PDFlib, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, geoip, gettext, gmp, hash, iconv, imagick, ionCube Loader, json, libxml, litespeed, mbstring,
	mysqli, mysqlnd, openssl, pcntl, pcre, readline, session, shmop, sockets, sqlite3, standard, tokenizer, xml, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: LiteSpeed
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.177
Server Software: MariaDB Server
	Server Version: 10.3.29-MariaDB
	Server SQL Mode: 
	Parameters: atech@localhost/atech
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
Zend OPcache extension is installed
exif extension is installed
ldap extension is not present
imap extension is not present
APCu extension is not present
xmlrpc extension is not present
CAS extension is not present
Database version seems correct (10.3.29) - Perfect!Database version seems correct (10.3.29) - Perfect!
OK/home/mywebsite/it/files/_log : OK
OK/home/mywebsite/it/config : OK
OK/home/mywebsite/it/files : OK
OK/home/mywebsite/it/files/_dumps : OK
OK/home/mywebsite/it/files/_sessions : OK
OK/home/mywebsite/it/files/_cron : OK
OK/home/mywebsite/it/files/_graphs : OK
OK/home/mywebsite/it/files/_lock : OK
OK/home/mywebsite/it/files/_plugins : OK
OK/home/mywebsite/it/files/_tmp : OK
OK/home/mywebsite/it/files/_cache : OK
OK/home/mywebsite/it/files/_rss : OK
OK/home/mywebsite/it/files/_uploads : OK
OK/home/mywebsite/it/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

```

**Additional context**

Upgrading from 9.4.5, presents mysqlnd error when hosting currently has this already. Unsure what is causing the problem and if this check can be bypassed somehow.

**Comment by cedric-anne** [comment] 2021-06-14 07:25
Hi,

You have this error because the `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` is not defined in your PHP installation. This constant is defined when mysqli extension uses the mysqlnd driver. If it is not defined, then it should means that the mysqli extension of your PHP installation is using libmysql.

Bypassing this check is not an option, as it would result in unexpected variables types in MySQL results; which can cause many bugs in GLPI.

Regards

**Comment by itprotj** [comment] 2021-06-15 03:55
> Hi,
> 
> You have this error because the `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` is not defined in your PHP installation. This constant is defined when mysqli extension uses the mysqlnd driver. If it is not defined, then it should means that the mysqli extension of your PHP installation is using libmysql.
> 
> Bypassing this check is not an option, as it would result in unexpected variables types in MySQL results; which can cause many bugs in GLPI.
> 
> Regards

Thankyou for the reply. I am confused - Did GLPI change extensions as it was working up to that version.. If it has indeed then I think that would break alot of people using it on shared hosting servers where libmysql is very much in common use.

what options do I have?

**Comment by cedric-anne** [comment] 2021-06-15 06:25
Hi,

In GLPI 9.5, we choose to use an option that is only available with `mysqlnd` driver. `mysqlnd` is the default and recommended MySQL driver used by PHP since PHP 5.4, so I am not sure that usage of the `libmysql` driver is a common use, even on shared hosting.

We cannot make usage of this driver optionnal, as it has an huge impact on how data is returned by database. Unfortunately, in GLPI, there is nothing to handle DB results casting on PHP side, and it would take years to add it in core and plugins. Having diffference on this would be a pain for developpers and would be really hard to handle in automated tests, and would surely result in tons of bugs.

Sometimes, shared hosting services are providing a way to configure PHP installation. You should check that.

I close this issue as this is not a bug. If you need more support, you can ask on [forums](https://forum.glpi-project.org/) for community support.

Regards

**Closed by cedric-anne** 2021-06-15 06:25 UTC
