### ISSUE TITLE
 customization: assign call to yourself on the "processing call" screen

### ISSUE THREAD

**Issue by diogodc** [glpi-project/glpi#6361] opened 2019-09-26 13:33 UTC
my customization: assign call to yourself on the "processing call" screen.

**Directory: \glpi\inc\commonitilobject.clss.php**

line 6194

     if ($canadd_solution) {
         echo "<li class='solution' onclick='".
              "javascript:viewAddSubitem".$this->fields['id']."$rand(\"Solution\");'>"
              ."<i class='fa fa-check'></i>".__("Solution")."</li>";
      }
      Plugin::doHook('timeline_actions', ['item' => $this, 'rand' => $rand]);

// Begin Diogo: 
      $can_assigntome = $this->canAssignToMe();
      if (      
          //$ID  // old
          $can_assigntome
          && !in_array($this->fields['status'], $this->getClosedStatusArray())
          && !$is_hidden['_users_id_assign']
          && !$this->isUser(CommonITILActor::ASSIGN, Session::getLoginUserID())
          && $this->isAllowedStatus($this->fields['status'], CommonITILObject::ASSIGNED
      )) {
         Html::showSimpleForm($this->getFormURL(), 'addme_assign', __('Associate myself'),
                              array($this->getForeignKeyField() => $this->fields['id']),
                              $CFG_GLPI["root_doc"]."/pics/addme.png");
      }                              
      // End Diogo.

      echo "</ul>"; // timeline_choices
      echo "<div class='clear'>&nbsp;</div>";

      echo "</div>"; //end timeline_form

      echo "<div class='ajax_box' id='viewitem" . $this->fields['id'] . "$rand'></div>\n";
   }
line 6225

Example:

![image](https://user-images.githubusercontent.com/17382148/65692409-deb23980-e048-11e9-94ea-9bd03cbdfa66.png)

**Comment by cedric-anne** [comment] 2019-09-26 13:37
Hi,

You can easilly do a plugin for it, using the `timeline_actions` hook.

If you want, you can open a pull request to propose your change, but I close this issue as this is not a bug.

Regards

**Closed by cedric-anne** 2019-09-26 13:37 UTC
