### ISSUE TITLE
Mentions unavailable for followup templates

### ISSUE THREAD

**Issue by AldarisPale** [glpi-project/glpi#15230] opened 2023-07-17 09:18 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Mentions are not available when creating Followup Template

### Steps To reproduce

1. Open a ticket
2. Click on "Answer"
3. Choose "+" next to "reply icon"
4. Give random name to followup templae
5. In "Content" box, type in some text, try to mention someone via @username
6. Notice that now popup appears for choosing the user to be mentioned
7. Save the template hoping that when template is being used, it would still trigger the mention functionality
8. Notice that the mentioning functionality does not work when a template is used where person already has been tagged via @username

### Anything else?

The mentions functionality is awesome otherwise. Kudos!

**Comment by cedric-anne** [comment] 2023-08-02 12:31
Hi,

Enabling user mentions in templates is not so simple, as it may result in mentioning users that should not be visible in ticket entity. Indeed, the template may be accessible in a child entity that is accessible by the mentioned user.

I will close this issue as it is not a bug.

**Closed** 2023-08-02 12:31 UTC
Labels: feature suggestion
