### ISSUE TITLE
It does not show me the whole list of phone lines.

### ISSUE THREAD

**Issue by laurixia** [glpi-project/glpi#17135] opened 2024-05-16 10:41 UTC
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.14

### Bug description

I have all my phone lines registered in the management/phone lines section but it does not show me the list of all the lines and when I search it only shows me the first result.

Search that should show me all:

![lineas1vacia](https://github.com/glpi-project/glpi/assets/26741776/89283ac0-a682-4335-a5e0-a140d97d9994)

Search that should show me items containing a 6 and only shows me one line:

![image](https://github.com/glpi-project/glpi/assets/26741776/7da352c5-d08f-4638-b076-a88d644ed6b3)

**Comment by cconard96** [comment] 2024-05-16 10:45
Please provide the GLPI setup information and logs requested and also test with plugins disabled to rule them out as the cause of the issue. It looks like you have at least one plugin enabled (Camera Input).

**Comment by laurixia** [comment] 2024-05-16 13:43
I have deactivated the plugins as recommended, but I still have the same problem.
<img width="435" alt="image" src="https://github.com/glpi-project/glpi/assets/26741776/5f46b4a1-b394-4c6e-b698-c700e32dcd45">

**Comment by trasher** [comment] 2024-05-16 13:45
It has also been asked to provide all required information.

**Comment by trasher** [comment] 2024-05-16 13:51
And also, please try with latest stable release.

**Comment by stonebuzz** [comment] 2024-05-17 06:29
And try again with debug mode enabled, a missing result table seems to indicate an error (PHP or SQL).
Check GLPI logs when this page was displayed (files/_log/php-error.log / sql-error.log)

**Comment by laurixia** [comment] 2024-05-17 07:26
I have found a way that shows me all the lines and is sorted by name. The bug occurs when sorting by user in the search.

![image](https://github.com/glpi-project/glpi/assets/26741776/9313e719-86a0-4705-a2a0-c406d57c9607)

That would be enough for me

**Comment by trasher** [comment] 2024-05-17 11:44
Requested information are not provided, closing.

**Closed by trasher** 2024-05-17 11:44 UTC
Labels: invalid

**Comment by stonebuzz** [comment] 2024-05-17 12:36
Should be fixed by -> https://github.com/glpi-project/glpi/pull/16872

Please update GLPI to the latest version to benefit from the fix
