### ISSUE TITLE
Email follow-up on tickets does not work

### ISSUE THREAD

**Issue by TestOrganigrammeBA** [glpi-project/glpi#14596] opened 2023-04-26 14:22 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When a ticket is created by one of our collaborators, the ticket is created, follow-up by email is activated on the requester, but when you click on the bell 
![image](https://user-images.githubusercontent.com/91662361/234604254-17dbd48f-82ba-4ba7-913e-3f2dc20d80cd.png)

To see to which email address the follow-up is sent, you realizes that the field is empty.
![image](https://user-images.githubusercontent.com/91662361/234604458-436489e7-cc25-4b86-9ec9-827902c3133a.png)

While the applicant has an email address entered on his user file (the email field is automatically retrieved from AD).
![image](https://user-images.githubusercontent.com/91662361/234604689-23592fdd-5434-47e6-a7fc-a328402d0141.png)
![image](https://user-images.githubusercontent.com/91662361/234604937-333fe89e-5850-4c1d-8095-1a89d1cd59d8.png)

I would therefore like the field to be completed with the applicant's email address. Otherwise, it does not receive notifications

### Steps To reproduce

1. Create a ticket from the Self-Service UI
2. Viewing the ticket from an Admin profile

### Your GLPI setup information

<html>
<body>

Informations sur le système, l'installation et la configuration
--
 
GLPI 10.0.7 (/glpi => /var/www/html/glpi) 
Installation mode: TARBALL 
Current language:fr_FR

SERVER
--

Operating system: Linux srvweb 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 PHP 8.0.25 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, snmp, sockets, sodium, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at srvweb Port 443 ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Server Software: Debian 10 	Server Version: 10.3.36-MariaDB-0+deb10u2 	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: glpiuser@localhost/glpidb 	Host info: Localhost via UNIX socket 	 PHP version (8.0.25) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (10.3.36) is supported. No files from previous GLPI version detected. The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.  Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details. The following directories should be placed outside "/var/www/html/glpi": ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public". Sessions configuration is secured. OS and PHP are relying on 64 bits integers. exif extension is installed. ldap extension is installed. openssl extension is installed. Following extensions are installed: bz2, Phar, zip. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/html/glpi/marketplace has been validated. Timezones seems loaded in database.

GLPI constants
--

GLPI_ROOT: "/var/www/html/glpi" GLPI_CONFIG_DIR: "/var/www/html/glpi/config" GLPI_VAR_DIR: "/var/www/html/glpi/files" GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace" GLPI_USE_CSRF_CHECK: "1" GLPI_CSRF_EXPIRES: "7200" GLPI_CSRF_MAX_TOKENS: "100" GLPI_USE_IDOR_CHECK: "1" GLPI_IDOR_EXPIRES: "7200" GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?\|feed):\\/\\/[^@:]+(\\/.*)?$/"] GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org" GLPI_INSTALL_MODE: "TARBALL" GLPI_NETWORK_MAIL: "glpi@teclib.com" GLPI_NETWORK_SERVICES: "https://services.glpi-network.com" GLPI_MARKETPLACE_ALLOW_OVERRIDE: true GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true GLPI_USER_AGENT_EXTRA_COMMENTS: "" GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1" GLPI_AJAX_DASHBOARD: "1" GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: "0" GLPI_CENTRAL_WARNINGS: "1" GLPI_DOC_DIR: "/var/www/html/glpi/files" GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache" GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron" GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps" GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs" GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales" GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock" GLPI_LOG_DIR: "/var/www/html/glpi/files/_log" GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures" GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins" GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss" GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions" GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp" GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads" GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories" GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/" GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/" GLPI_I18N_DIR: "/var/www/html/glpi/locales" GLPI_VERSION: "10.0.7" GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6" GLPI_MARKETPLACE_PRERELEASES: false GLPI_MIN_PHP: "7.4.0" GLPI_MAX_PHP: "8.3.0" GLPI_YEAR: "2023"

Libraries
--

htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/marketplace/pdf/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) psr/cache in (/var/www/html/glpi/vendor/psr/cache/src) league/csv in (/var/www/html/glpi/vendor/league/csv/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) symfony/cache in (/var/www/html/glpi/vendor/symfony/cache) html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src) symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector) symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler) twig/twig in (/var/www/html/glpi/vendor/twig/twig/src) twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81) symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82) league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider) league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider) thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

Plugins list
--

addressing           Name: Adressage IP                   Version: 3.0.1      State: Enabled                                  		Install Method: Marketplace 	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                  		Install Method: Marketplace 	news                 Name: Alertes                        Version: 1.10.6     State: Enabled                                  		Install Method: Marketplace 	treeview             Name: Arborescence                   Version: 1.10.0     State: Enabled                                  		Install Method: Manual 	financialreports     Name: Arrêtés du parc                Version: 3.0.0      State: Enabled                                  		Install Method: Marketplace 	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                  		Install Method: Marketplace 	camerainput          Name: Camera Input                   Version: 2.0.2      State: Enabled                                  		Install Method: Marketplace 	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Enabled                                  		Install Method: Marketplace 	fields               Name: Champs supplémentaires         Version: 1.20.5     State: Enabled                                  		Install Method: Marketplace 	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace 	costs                Name: Costs                          Version: 3.0.1      State: Enabled                                  		Install Method: Manual 	mydashboard          Name: Dashboard                      Version: 2.1.4      State: Enabled                                  		Install Method: Marketplace 	datainjection        Name: Data Injection                 Version: 2.13.0     State: Enabled                                  		Install Method: Marketplace 	consumables          Name: Demande de consommables        Version: 2.0.0      State: Enabled                                  		Install Method: Manual 	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                 		 Install Method: Marketplace 	formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                  		Install Method: Marketplace 	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                  		Install Method: Marketplace 	gdrive               Name: GDrive                         Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace 	geninventorynumber   Name: Génération de numéros d'invent Version: 2.8.3      State: Enabled                                 		 Install Method: Marketplace 	genericobject        Name: Gestion d'objets               Version: 2.14.2     State: Enabled                                  		Install Method: Marketplace 	order                Name: Gestion des commandes          Version: 2.10.3     State: Enabled                                  		Install Method: Marketplace 	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                  		Install Method: Marketplace 	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.5.1      State: Enabled                                  		Install Method: Marketplace 	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                  		Install Method: Marketplace 	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                  		Install Method: Marketplace 	jsaddons             Name: JS Addons                      Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace 	metabase             Name: Metabase                       Version: 1.3.3      State: Enabled                                  		Install Method: Marketplace 	onetimesecret        Name: OneTimeSecret                  Version: 2.0.0      State: Enabled                                  		Install Method: Manual 	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                  		Install Method: Marketplace 	reports              Name: Rapports                       Version: 1.16.0     State: Enabled                                  		Install Method: Manual 	archisw              Name: Structures d'Applications      Version: 3.0.3      State: Installed / not activated                		Install Method: Marketplace 	rgpdtools            Name: Utilitaires RGPD               Version: 1.0.0      State: Enabled                                  		Install Method: Manual 	webhook              Name: Webhooks                       Version: 1.0.12     State: Enabled                                  		Install Method: Marketplace 	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                  		Install Method: Marketplace

</body>
</html>

**Comment by cedric-anne** [comment] 2023-05-03 09:42
Hi,

> I would therefore like the field to be completed with the applicant's email address. Otherwise, it does not receive notifications

This assertion is incorrect. Indeed, this field can be used to define an alternative email address. If no value is defined here, then  notifications will be sent to the primary e-mail address of the user. I just made a test and confirm that it works as expected.

In GLPI 9.5, this field was always defined, but result was that a user that has changed its primary e-mail address was still receiving notification on the previous address for tickets that was already existing before this address change.

Anyway, UX could probably be improved by adding a placeholder containing the primary e-mail address of the actor. I do not know if this enhancement is complex to implement, but I think it could be really valuable as many users are thinking that lack of value here is the cause of their notification problems.

**Comment by cedric-anne** [comment] 2023-06-14 16:18
Fixed by #14913

**Closed by cedric-anne** 2023-06-14 16:18 UTC
Labels: enhancement, ux
