### ISSUE TITLE
Broken search regexp

### ISSUE THREAD

**Issue by Krakozaber** [glpi-project/glpi#1168] opened 2016-10-17 04:29 UTC
GLPI 9.1 not work search whith ^ or $ regexp

**Comment by flegastelois** [comment] 2016-10-17 05:57
Hi,
Have you got an error in your files/_log/sql-errors.log or in files/_log/php-errors.log ?
You can also see these errors in debug mode.

**Comment by Krakozaber** [comment] 2016-10-17 07:00
No, there are no errors

**Comment by flegastelois** [comment] 2016-10-17 08:23
Ok, we need a step by step (fully example) to reproduce your issue.

**Comment by Krakozaber** [comment] 2016-10-17 08:44
1) Assets -> Computers
2) Items seen -> Contains -> $PC
there are no results

If you look for just PC, the results are shown

**Comment by flegastelois** [comment] 2016-10-17 09:17
It's not a bug.

**^** and **$** chars are specific characters to perform an advanced search.

- Name -> Contains -> **^PC** : search records where name started by **PC**
- Name -> Contains -> **PC$** : search records where name ended by **PC**
- Name -> Contains -> **^PC$** : search records where name is exactly **PC**

If you want to search an item contains special char **$** you can use : 

- Name -> Contains -> **%$%** : search records where name contains **$**

 Regards,

**Comment by Krakozaber** [comment] 2016-10-17 09:29
Thank you for the clarification.

And correct here -> http://wiki.glpi-project.org/doku.php?id=ru:doc:start:start an opportunity ?

**Comment by flegastelois** [comment] 2016-10-17 09:43
This wiki is very outdated (but partially ok for advanced search as I can see).

As stated in the announcement of the 9.1 ([link](http://glpi-project.org/spip.php?page=annonce&id_breve=366&lang=en)) : 
GLPi’s documentation is outdated or missing.
We are aware of this issue and would like to address it.
If you want to help, please [contact us](mailto:glpi@teclib.com) (the documentation’s main language is English).

I close this issue.

Best regards,

**Closed by flegastelois** 2016-10-17 09:43 UTC
Labels: help wanted
