### ISSUE TITLE
[9.2.3] KB item content is erased after save

### ISSUE THREAD

**Issue by gitdevmod** [glpi-project/glpi#3949] opened 2018-05-02 08:29 UTC
* Steps to reproduce (which actions have you made) :
Create a new KB item with random text (www.faux-texte.com/lorem-ipsum-3.htm)
Add a small picture (from windows 7 capture tool)
Add a full screen picture (from windows 7 capture tool)
Save

* Expected result :
Content saved

* Actual result :
Content erased

* URL of the page :

http://demo.glpi-project.org/front/knowbaseitem.form.php?id=2674

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

I can reproduce issue on 9.2.3 and 9.2.2 (from demo glpi)
It was working on 9.2.1

**Comment by trasher** [comment] 2018-05-03 05:00
I cannot reproduce the issue.
Check if this is not related to the browser/system you use; also double check logs and test all that with debug mode on.

**Comment by gitdevmod** [comment] 2018-05-03 10:09
I can reproduce issue on
Windows 7 with Firefox 60 and 61
Ubuntu 18.4 Firefox 59

No error in apache error.log or access.log and glpi php-errors.log sql-errors.log
No error in browser console
[Video](http://djdomics.free.fr/pub/2018-05-02%2011-06-10.mp4)

**Comment by cedric-anne** [comment] 2018-06-08 09:52
Hi,

I reproduce once this problem, but I did not found the 100% reproductible scenario. I tried to update TinyMCE, assuming that it is a TinyMCE bug.

Could you try if using the 9.3 version with TinyMCE update (PR https://github.com/glpi-project/glpi/pull/4148) is fixing your problem ?

Regards

**Comment by gitdevmod** [comment] 2018-06-08 21:43
I installed 9.3R2 and it produces a different bug, the first image is ok but the second is displayed in base64
![image](https://user-images.githubusercontent.com/2040775/41182377-a2c75f0c-6b75-11e8-9de5-639258bbda72.png)

**Comment by cedric-anne** [comment] 2018-06-11 11:06
Hi,

I opened another issue for the base64 problem: https://github.com/glpi-project/glpi/issues/4157.
It happens when you paste an image which content is exactly the same as any image that GLPI already stored.
Can you try using each time a different image ?

Regards

**Comment by gitdevmod** [comment] 2018-06-11 17:08
Pasted images are not the same, each image is unique. I capture different selection of screen each time I created a new kb for testing.

**Comment by cedric-anne** [comment] 2018-06-12 10:05
Hi,

Sorry, I was testing on 9.2 branch, so I wasnot able to reproduce. The base64 issue you describe has been introduced in 9.3 in commit https://github.com/glpi-project/glpi/commit/5bdbeeab8954059838944a60769eb4ae5dd61f34 .

When the first image is pasted, `uploaded` value is `false`, so it is handled correctly. When the second image is paste, `uploaded` has previous image tag as value, so it does not trigger upload behaviour.

We have to fix this.

Regards

**Comment by trasher** [comment] 2018-06-20 08:37
Closing, as initial issue seems solved; and there is another ticket for the other issue.

**Comment by cedric-anne** [comment] 2018-06-25 10:50
Hi,

I just reproduced while testing another fix, so I was able to find source and made a fix (#4228).

Regards

**Closed** 2018-06-26 10:28 UTC
Labels: bug
