### ISSUE TITLE
no menu after migration from 9.2.1 to 9.3.2

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#4948] opened 2018-11-21 09:27 UTC
Hello,

I have migrated today, after migration I don't have menu anymore, except in debug mode in superadmin profile.

Thx for your help
normal mode
![image](https://user-images.githubusercontent.com/30655170/48831797-e85b7880-ed77-11e8-990a-c5bfd8c93c90.png)

debugmode

![image](https://user-images.githubusercontent.com/30655170/48831817-f4473a80-ed77-11e8-882a-e271b76a603f.png)

**Comment by Armin83** [comment] 2018-11-21 20:17
Did you already clear the browser cache ?

**Comment by trasher** [comment] 2018-11-22 06:41
did you restart php/apache on the server after the upgrade?

**Comment by yalgva** [comment] 2018-11-22 06:59
yes php / iis

**Comment by yalgva** [comment] 2018-11-22 07:02
![image](https://user-images.githubusercontent.com/30655170/48886636-fa4b2300-ee2c-11e8-9eb1-c66744006804.png)

**Comment by yalgva** [comment] 2018-11-22 07:03
you are able to see that interface is without css

**Comment by trasher** [comment] 2018-11-22 07:03
Sounds like a missing/bad CSS. You probably missed something during your udpate, try to remove .min.* files in `css` and `js` directories.

**Comment by yalgva** [comment] 2018-11-22 07:38
Do I have to remove and copy them from source again ?

**Comment by yalgva** [comment] 2018-11-22 07:40
I did it but same behavior.
log out / ctrl + f5

**Comment by tomolimo** [comment] 2018-11-22 07:45
Hello,
I get the same kind of issue trying to install 9.3.2 from scratch.
I get the following screen copies:
![image](https://user-images.githubusercontent.com/7569958/48888356-bb1fd080-ee32-11e8-9f9e-7ececd261ad6.png)
And in Chrome debug view, I got:
![image](https://user-images.githubusercontent.com/7569958/48888382-cf63cd80-ee32-11e8-9adf-f478b0a52413.png)
The root cause is the URL to get the libraries...

thank you,
Regards,
Tomolimo

**Comment by trasher** [comment] 2018-11-22 07:49
Can't reproduce, windows only issue?

**Comment by trasher** [comment] 2018-11-22 07:50
(note that I'm testing on current 9.3/bf, maybe something has been fixed already)

**Comment by tomolimo** [comment] 2018-11-22 07:53
The root cause is the path used in install.php on the lines Html::script().
For 9.1 (and below), it was a relative path '../lib/and_so_on' and since 9.2 it is 'lib/and_so_on'

> (note that I'm testing on current 9.3/bf, maybe something has been fixed already)

Seems not, as I looked already into the install.php file on the 9.3/bf

**Comment by tomolimo** [comment] 2018-11-22 07:56
Something is wrong somewhere: I got the same when trying to do a fresh install of 9.2.4

**Comment by tomolimo** [comment] 2018-11-22 07:57
Migration from 9.1 to 9.2 is ok for me, but fresh install of 9.2 gives same screen copies and same http 404 in Chrome debug tools.

**Comment by tomolimo** [comment] 2018-11-22 07:58
I'm using PHP 7.2.12

**Comment by trasher** [comment] 2018-11-22 07:59
Since 9.2 are out form more than a year, I guess this issue is not new and maybe relies on some configuration on the server part.
Well, since I can't reproduce, I can't get fixed... (and I'm not going to reproduce your setup :D )

**Comment by tomolimo** [comment] 2018-11-22 08:00
> Well, since I can't reproduce, I can't get fixed... (and I'm not going to reproduce your setup :D )
:)

But could it be that the new version relies on some specific PHP settings?

**Comment by tomolimo** [comment] 2018-11-22 08:01
I mean like `doc_root`?

**Comment by trasher** [comment] 2018-11-22 08:02
Which new version? 9.2.4? 9.3? I do not have in mind anything that would explain the issue right now. Can't tell more on my side without reproducing unfortunately.

**Comment by tomolimo** [comment] 2018-11-22 08:04
> Which new version? 9.2.4? 9.3?
Both, as the modification of the install.php file is the same for both versions
I'm going to debug this, and keep you informed
:smiley:

**Comment by tomolimo** [comment] 2018-11-22 08:08
First clue: as soon as I set the `doc_root` in the PHP.ini file, then tada, there is no more troubles with the install.php file
This means that somewhere in the code something is relying on this settings, which of course is not good, as we may have several web sites on the same server. so the paths in the install.php file must be relative to the script (or absolut for the web site), but not relative to a PHP setting.

**Comment by tomolimo** [comment] 2018-11-22 15:05
I made two new tests on my Test server:
with PHP 7.2.12 x64 (and `doc_root ` is empty)
1. new 9.2.4: is OK
1. new 9.3.2: is OK

So I don't know why on my machine I got the `root_doc` issue...

**Comment by tomolimo** [comment] 2018-11-22 16:11
Hello,
I found my problems root cause: it's a mix between lower cases and upper cases in the paths given in IIS server for the web application definition and the real paths on the disk.
the function Config::detectRootDoc() doesn't support mix of cases.
Regards,
Tomolimo

**Comment by trasher** [comment] 2018-11-23 06:44
Sounds like an IIS configuration issue then, closing.

**Closed by trasher** 2018-11-23 06:44 UTC

**Comment by yalgva** [comment] 2018-11-23 06:48
Do you have the solution ?

**Comment by yalgva** [comment] 2018-11-23 06:49
May I have to start migration again ?

**Comment by trasher** [comment] 2018-11-23 07:46
As I've said, it's an IIS configuration issue; not a GLPI bug. 
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by orthagh** [comment] 2018-11-23 09:52
Also maybe @tomolimo can share its changes in IIS configuration

**Comment by yalgva** [comment] 2018-11-23 10:30
after completely delete glpi folder, copy glpi 9.2.1, export database, copy glpi9.3.2 folder, migrate, OK

**Comment by tomolimo** [comment] 2018-11-23 13:14
> Also maybe @tomolimo can share its changes in IIS configuration

As requested by @orthagh, here are the explanations:

1. my folders:
![image](https://user-images.githubusercontent.com/7569958/48945094-627f2f00-ef29-11e8-8dd2-04b08c92be67.png)

1. the configuration on my IIS and the wrongly set path:
![image](https://user-images.githubusercontent.com/7569958/48945208-c86bb680-ef29-11e8-9c40-ea5bec4da590.png)

1. As soon as I changed the path to be: `C:\Projects\GLPI\9.3` and restarted IIS, then the installation goes well

Regards
Tomolimo

**Comment by yalgva** [comment] 2018-11-26 07:19
I understand, but with 9.2.1 I have no problem, could you explain that ?

**Comment by tomolimo** [comment] 2018-11-26 07:21
> I understand, but with 9.2.1 I have no problem, could you explain that ?

Sorry, but I can't :smiley: I've got no clues about your configuration...

**Comment by yalgva** [comment] 2018-11-26 07:32
Ok, I will create my iis from scracth, do you have a procedure to follow ? I will do the same as you.

Thx for your help

**Comment by tomolimo** [comment] 2018-11-26 07:51
you should go to the GLPI forum to get this kind of help, thank you,
https://forum.glpi-project.org
