### ISSUE TITLE
[GLPI 10 Bugfixes] On new ticket cannot link items of user

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#11646] opened 2022-05-20 11:12 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

On ticket creation form, after select the requester, the user items dropdown is not available : 

![image](https://user-images.githubusercontent.com/13178158/169516007-7ddd7ff9-5ace-43e3-8b55-bb84a48f70da.png)

When update ticket you have : 

![image](https://user-images.githubusercontent.com/13178158/169516127-9f64ff78-d1aa-487a-a792-0077dade8306.png)

**Comment by cconard96** [comment] 2022-05-24 16:02
Confirmed. The field only seems to take into account the requestor that was initially set. If you have the option set to pre-select yourself as the requestor, then it always shows your devices during the ticket creation. Otherwise, nothing is ever shown for "My devices" during the ticket creation.

**Comment by tsmr** [comment] 2022-05-25 14:31
The problem is that you can have now multiple requesters. So you can display the field if only one requester is posted ?

```
diff --git a/src/Item_Ticket.php b/src/Item_Ticket.php
index 236e002394..b9bce69e8a 100644
--- a/src/Item_Ticket.php
+++ b/src/Item_Ticket.php
@@ -276,6 +276,21 @@ class Item_Ticket extends CommonItilObject_Item
                 'rand'       => $rand,
                 'tickets_id' => $params['id']
             ];
+            if (isset($params['_actors'])) {
+               if (isset($params['_actors']['requester']) && count($params['_actors']['requester']) > 0) {
+                  $requesters = $params['_actors']['requester'];
+                  $user_requester = [];
+                  foreach ($requesters as $requester) {
+                     if ($requester['itemtype'] == 'User') {
+                        $user_requester[] = $requester;
+                     }
+                  }
+                  if (count($user_requester) == 1) {
+                     $params['_users_id_requester'] = $user_requester[0]['items_id'];
+                  }
+               }
+            }
+
            // My items
             if ($params['_users_id_requester'] > 0) {
                 ob_start();
```

**Comment by cconard96** [comment] 2022-05-25 15:05
No, I think the problem is that there are different properties containing actor information. When you change actors in the form, "actors" is used instead of the original properties that were for each type of actor.

**Comment by OlegusPF** [comment] 2022-06-03 10:57
ok, thanks, i was revert it. waiting for resolve )

**Comment by angelavit** [comment] 2022-06-14 14:19
Hello,
is it possible that the problem is due to the version of the agent? I noticed that the list is empty with the GLPI 1.2 agent, instead it is set with the 1.1 agent

**Comment by tsmr** [comment] 2022-06-29 06:35
Closed by error

**Comment by cconard96** [comment] 2022-09-01 00:51
This seems to be working now. The dropdown is showing again and will show the devices of the ticket writer.

**Comment by cedric-anne** [comment] 2022-12-07 17:27
I close the issue as it seems to be fixed. Feel free to reopen.

**Closed by cedric-anne** 2022-12-07 17:27 UTC
Labels: bug
