### ISSUE TITLE
GLPI 9.5.2 - Ticket import from collector without attachment - wrong encoding

### ISSUE THREAD

**Issue by weah35** [glpi-project/glpi#8160] opened 2020-10-22 10:12 UTC
Hi,

Just upgrade from GLPI 9.4.4 to GLPI 9.5.2.

We use GLPI with collector.

In my company we add HTML emails signatures automatically when users send emails.

When users send email without attachment or inline screen capture, GLPI make ticket but ticket signature is not correctly displayed. 

**Example :**

```html
<p><br /><br /><br /></p>
<div class="WordSection1"><br />
<p class="MsoNormal">Test without attachment.</p>
<br />
<p class="MsoNormal"> </p>
</div>
<p> </p>
<p> </p>
<div style="font-family: Arial, Helvetica, sans-serif; margin-top: 10px;"><br />
<div style="font-size: 12pt; font-weight: bold; color: #4e3241;">User</div>
<br />
<div style="font-size: 11pt; color: #4e3241;">Technicien<br /><br /></div>
<br />
<div style="font-size: 9pt; margin-top: 10px; font-weight: bold; color: #4e3241;"><br /></div>
<br />
<div style="font-size: 9pt; margin-top: 5px; color: #4e3241;">/<br /><br />Tél. 1</div>
</div>
<p> </p>
```

With emails with attachment (PDF) or inline print screen, ticket signature is OK.

**Example :**

```html
<div class="WordSection1">
<p class="MsoNormal">Test image inline..</p>
<p class="MsoNormal"> </p>
<p class="MsoNormal"> </p>
<p><a href="https://support.fr/front/document.send.php?docid=4831&amp;tickets_id=18103" target="_blank" rel="noopener"><img src="https://support.fr/front/document.send.php?docid=4831&amp;tickets_id=18103" alt="7d9d010c-d9d62df8-5f8efa81e850c6.57488767" width="843" /></a></p>
<p class="MsoNormal"> </p>
<p class="MsoNormal"> </p>
<p class="MsoNormal"> </p>
<p class="MsoNormal"> </p>
<p class="MsoNormal">test</p>
</div>
<table style="border-spacing: 0px;">
<tbody>
<tr>
<td valign="middle">
<div style="font-family: Arial, Helvetica, sans-serif; margin-top: 10px;">
<div style="font-size: 12pt; font-weight: bold; color: #4e3241;">User</div>
<div style="font-size: 11pt; color: #4e3241;">Technicien</div>
<div style="font-size: 9pt; margin-top: 10px; font-weight: bold; color: #4e3241;"></div>
<div style="font-size: 9pt; margin-top: 5px; color: #4e3241;"> / <br />Tél. 1</div>
</div>
</td>
</tr>
</tbody>
</table>
```

Do you have any idea ?

What's change between 9.4.4 and 9.5.2 about ticket encoding with collector ?

In 9.4.4 everything work fine.

Best regards.

**Comment by cedric-anne** [comment] 2020-10-22 10:17
Hi,

Please provide emails sources in eml format to help us investigate.

Also, please provide requested informations (logs, GLPI version, plugins list, ...).

Regards

**Comment by weah35** [comment] 2020-10-22 15:46
Hi,

Plugins : OCS Inventory 1.7.0

GLPI version :

Operating system: Linux  webapp 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64
PHP 7.3.14-5+0~20200202.52+debian9~1.gbpa71879 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl,
	json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, pdo_sqlsrv, posix, readline, session,
	shmop, sockets, sodium, sqlite3, sqlsrv, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at support.fr Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36 Edg/86.0.622.48
Server Software: Debian 9.9
	Server Version: 10.1.41-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: thomas@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.1.41) - Perfect!Database version seems correct (10.1.41) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/config has been validated.Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files has been validated.Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_cache has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

Logs from file : php-error.log 

[2020-10-22 17:01:01] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7926
Missing type for Ticket template!  {"user":"@webapp01"}
[2020-10-22 17:01:01] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7926
Missing type for Ticket template!  {"user":"@webapp01","mem_usage":"0.085\", 24.04Mio)"}
[2020-10-22 17:01:01] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7926
Missing type for Ticket template!  {"user":"@webapp01","mem_usage":"0.018\", 24.04Mio)"}
[2020-10-22 17:01:01] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7926
Missing type for Ticket template!  {"user":"@webapp01","mem_usage":"0.013\", 24.04Mio)"}
[2020-10-22 17:17:04] glpiphplog.ERROR: CommonITILObject::getTemplateFieldName() in /var/www/html/glpi/inc/commonitilobject.class.php line 7926
Missing type for Ticket template!  {"user":"247@webapp01"}


Only basic HTML emails from Outlook 2010 to 2019..

Don't you reproduce it on 9.5.2 ?

Thanks.

**Comment by cedric-anne** [comment] 2020-10-22 18:21
> Only basic HTML emails from Outlook 2010 to 2019..
> 
> Don't you reproduce it on 9.5.2 ?

I do not have Outlook, so no, I do not reproduce.

We fixed a lot of bug recently on the mail receiver feature, but we did it only when we was able to add the source email in our test suite.

Regards

**Comment by cedric-anne** [comment] 2020-10-23 09:45
Hi,

First, please do not send direct emails on my personnal email adress.

Second, I do not understand what is your issue.

I converted your msg files into eml (to be able to import them), and I get these two tickets created:
![image](https://user-images.githubusercontent.com/33253653/96988773-1548d500-1525-11eb-8618-a8a4ca72e75d.png)
![image](https://user-images.githubusercontent.com/33253653/96988800-1ed23d00-1525-11eb-9ed4-a075f9650296.png)

What is the expected result ?

Regards

**Comment by weah35** [comment] 2020-10-23 12:21
Hi,

Signature email is add when mail is sending so i can't give you EML.

Without images inline or PDF attachment , ticket look like : 

![image](https://user-images.githubusercontent.com/20817044/97002291-133d4100-153a-11eb-882c-6614932efa38.png)


Here HTML code :

```
<p><br /><br /><br /></p>
<div class="WordSection1"><br />
<p class="MsoNormal">Test.</p>
<br />
<p class="MsoNormal"> </p>
</div>
<p> </p>
<p> </p>
<div style="font-family: Arial, Helvetica, sans-serif; margin-top: 10px;"><br />
<div style="font-size: 12pt; font-weight: bold; color: #4e3241;">test info</div>
<br />
<div style="font-size: 11pt; color: #4e3241;">Technicien<br /><br /></div>
<br />
<div style="font-size: 9pt; margin-top: 10px; font-weight: bold; color: #4e3241;"><br /><br /></div>
<br />
<div style="font-size: 9pt; margin-top: 5px; color: #4e3241;">/ DSIT<br /><br />Tél.  </div>
</div>
<p> </p>
```

Expect result is here and i obtain it when sending email with inline image or PDF attachments :

![image](https://user-images.githubusercontent.com/20817044/97002160-e0934880-1539-11eb-9f8b-4c916ae36b30.png)

HTML Code :

```
<div class="WordSection1">
<p class="MsoPlainText">Test</p>
<p class="MsoPlainText"> </p>
</div>
<table style="border-spacing: 0px;">
<tbody>
<tr>
<td valign="middle">
<div style="font-family: Arial, Helvetica, sans-serif; margin-top: 10px;">
<div style="font-size: 12pt; font-weight: bold; color: #4e3241;">test info</div>
<div style="font-size: 11pt; color: #4e3241;">Technicien</div>
<div style="font-size: 9pt; margin-top: 10px; font-weight: bold; color: #4e3241;">Company</div>
<div style="font-size: 9pt; margin-top: 5px; color: #4e3241;">/ DSIT<br />Tél.</div>
</div>
</td>
</tr>
</tbody>
</table>
```

Thanks.

**Comment by cedric-anne** [comment] 2020-10-26 07:21
Hi,

On the exemple you send me by mail, the email source is:
```html
<div class=WordSection1>
  <p class=MsoPlainText>Test.<o:p></o:p></p>
  <p class=MsoPlainText><o:p>&nbsp;</o:p></p>
  <p class=MsoPlainText><span style='mso-fareast-language:FR'><img width=572 height=490 style='width:5.9583in;height:5.1041in' id="Image_x0020_1" src="cid:image001.jpg@01D6A79A.ABC40200"></span><o:p></o:p></p>
  <p class=MsoPlainText><o:p>&nbsp;</o:p></p>
  <p class=MsoPlainText><o:p>&nbsp;</o:p></p>
  <p class=MsoPlainText>Merci.<o:p></o:p></p>
</div>
```

Resulting ticket html is:
```html
<div class="WordSection1">
  <p class="MsoPlainText">Test.</p>
  <p class="MsoPlainText">&nbsp;</p>
  <p class="MsoPlainText"><span style="mso-fareast-language:FR"></span></p>
  // image gallery code
  <p class="MsoPlainText">&nbsp;</p>
  <p class="MsoPlainText">&nbsp;</p>
  <p class="MsoPlainText">Merci.</p>
</div>
```

Ticket HTML corresponds to email HTML, so there is no bug on this example.
It contains empty paragraphs (paragraphs that contains only `&nbsp;`). These paragraphs may not be rendered in Outlook, but they are in GLPI.

If you can give us an export of an email that is not rendered accordingly to email HTML source, we could investigate, but without it, we cannot do nothing.

Regards

**Comment by weah35** [comment] 2020-10-26 09:19
Hi,

Here 2 mails, one only with text and signature and second with image and signature.

[test_with_inline_images.zip](https://github.com/glpi-project/glpi/files/5437893/test_with_inline_images.zip)

Regards

**Comment by cedric-anne** [comment] 2020-10-26 10:14
Hi,

Here is the result I have when importing your 2 emails.

![image](https://user-images.githubusercontent.com/33253653/97159519-4b7f9200-177b-11eb-9e92-d8350c2e6b8d.png)
![image](https://user-images.githubusercontent.com/33253653/97159632-74a02280-177b-11eb-93a4-ca2f44addd71.png)

So, as I still have a result that is consistent with email source, I close the issue, as it does not seems there is a bug. Feel free to reopen if you can provide the source of an email that cause a bug.

You can ask for [community support on forums](https://forum.glpi-project.org/), or you can consider subscribing to [professional support](https://services.glpi-network.com/).

Regards

**Comment by weah35** [comment] 2020-10-26 12:39
OK for EML i understand.

Can't import ".MSG" into GLPI without converting ?

We use Outlook and email are encoding in MSG so we are not in the same case...

Regards

**Comment by cedric-anne** [comment] 2020-10-26 13:16
> We use Outlook and email are encoding in MSG so we are not in the same case...

GLPI does not read MSG files. It reads mails using IMAP or POP3 protocol. Many tools can be used to export a mail in EML format. In your case, the easier way to do it to configure a tool like Thunderbird to connect through IMAP to the same adress as the GLPI mail receiver, and export the email that cause your issue. And please, do not alter email source (even line breaks) by editing it, as it may explain why I cannot reproduce your issue.

**Comment by husisusi** [comment] 2020-10-26 21:22
I have exactly the same issue, I confirm it!
GLPI 9.5.2

**Comment by cedric-anne** [comment] 2020-10-27 08:06
> I have exactly the same issue, I confirm it!
> GLPI 9.5.2

Please, provide the source of an email that can be used to reproduce this issue. We cannot fix anything if we cannot reproduce it, and most of GLPI contributors works on Linux, with no access to Outlook application.

**Comment by cedric-anne** [comment] 2020-11-13 15:02
Hi,

Maybe #8267 fixes this issue.

I close this issue as no reproducible case was provided.

Regards

**Closed by cedric-anne** 2020-11-13 15:02 UTC
Labels: Need feedback

**Comment by husisusi** [comment] 2020-11-13 16:50
Yes, #8267 fixes this issue.
