### ISSUE TITLE
Notification alerts for expired and inactive certificates

### ISSUE THREAD

**Issue by sbruneauBVS** [glpi-project/glpi#14986] opened 2023-06-22 12:20 UTC
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Good morning,

I configured the certificates module as well as the notifications.

I entered my certificates, some of which I made inactive because they expired.

I receive emails for certificates that will expire, however I also receive notifications for expired and inactive certificates.

Is it normal?

**Comment by cedric-anne** [comment] 2023-06-22 12:42
Hi,

Indeed, you will receive notifications for expired certificates too, even if expiration date was years ago. You can prevent these to be include in alerts by removing their expiration date value. Unless you set a reminder frequency, you should receive only one alert for each expired certificate.

This could probably be enhanced. You can open a topic on [the suggestion website](https://glpi.userecho.com/) to propose some enhancements on this part.

I close this issue as it is not a bug.

**Closed** 2023-06-22 12:42 UTC
Labels: feature suggestion
